### ISSUE TITLE
aws_cognito_pool ignores provider

### ISSUE THREAD

**Issue by rlc4** [terraform-providers/terraform-provider-aws#4112] opened 2018-04-07 16:30 UTC
### Terraform Version
$ terraform -v
Terraform v0.11.6
+ provider.aws v1.12.0

### Affected Resource(s)
- aws_cognito_pool
Untested with other resources

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "us-east-1"
}

provider "aws" {
  alias  = "oregon"
  region = "us-west-2"
}

resource "aws_cognito_user_pool" "test_user_pool" {
  provider = "aws.oregon"
  name     = "testingUsers"
}
```

CMD: `TF_LOG=DEBUG AWS_PROFILE=terraform.readonly terraform import aws_cognito_user_pool.test_user_pool  us-west-2_GF2f5Jd0G`

### Relevant debug output from command
>2018-04-07T09:22:00.548-0700 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: POST / HTTP/1.1
>2018-04-07T09:22:00.548-0700 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: Host: cognito-idp.us-east-1.amazonaws.com
>2018-04-07T09:22:00.548-0700 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: User-Agent: aws-sdk-go/1.13.28 (go1.9.2; darwin; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.11.4
>2018-04-07T09:22:00.548-0700 [DEBUG] plugin.terraform-provider-aws_v1.14.0_x4: Content-Length: 36

### Actual Behavior
Import failed, with the message: 

>2018/04/07 09:22:00 [DEBUG] plugin: waiting for all plugin processes to complete...
>Error: aws_cognito_user_pool.test_user_pool (import id: us-west-2_GF2f5Jd0G): 1 error(s) occurred:
>
>* import aws_cognito_user_pool.test_user_pool result: us-west-2_GF2f5Jd0G: import aws_cognito_user_pool.test_user_pool (id: us-west-2_GF2f5Jd0G): Terraform detected a resource with this ID doesn't
exist. Please verify the ID is correct. You cannot import non-existent
resources using Terraform import.

### Expected Behavior
It should have queried the us-west-2 endpoint for cognito-idp.  If aws.region (for the default provider) is changed to us-west-2, then the import succeeds.

### Steps to Reproduce
Create a cognito userpool in the us-west-2 region
Perform the command above with the pool ID for your newly created pool

**Comment by rlc4** [comment] 2018-04-10 03:50
Hi Clint, thanks for the detailed response!

I have no AWS_REGION or AWS_DEFAULT_REGION settings in my profile (checked with `env | fgrep AWS` which gave no results.

I also checked ~/.aws/config and I do see a region but it's under a completely profile.

Unfortunately, my own testing doesn't match yours.  With no AWS_* settings in my env (checked as above), here are the results of the states I think needed testing:

 vvv Env vvv / -> Config -> | region=us-east-1 | region=us-west-2 |
------------|------|-------
AWS_DEFAULT_REGION=us-west-2  | fails | works |
AWS_DEFAULT_REGION=us-east-1   | fails | works |
AWS_REGION=us-west-2                   | fails | works |
AWS_REGION=us-east-1                    | fails | works |
NO REGION SETTING                         | fails | works |

To make sure I didn't fat-finger any commands:

> AWS_DEFAULT_REGION=us-east-1 AWS_PROFILE=terraform.readonly terraform import aws_cognito_user_pool.test_user_pool us-west-2_GF2f5Jd0G

> AWS_REGION=us-east-1 AWS_PROFILE=terraform.readonly terraform import aws_cognito_user_pool.test_user_pool us-west-2_GF2f5Jd0G

> AWS_PROFILE=terraform.readonly terraform import aws_cognito_user_pool.test_user_pool us-west-2_GF2f5Jd0G

Let me know if there's something else I should be including or testing let me know.

**Comment by rlc4** [comment] 2018-04-10 21:26
I'm hoping that in my own details I might find something that will point me at having done something myself to have caused this, so far I haven't discovered anything.

terraform.readonly (and its counterpart terraform.privileged) only contains key id and secret information. 

Having looked at ~/.aws/config previously, the only region information in that file is in a different profile block.  Is there anything else that might be something to consider that I should look for in the config or profiles?

**Comment by bflad** [comment] 2018-04-10 22:05
Whenever I personally run into trouble with multiple providers and importing, I usually wind up setting the [`-provider` flag to `terraform import`](https://www.terraform.io/docs/commands/import.html#provider-provider) to workaround any oddities with the import process and configuration.

> -provider=provider - Specified provider to use for import. The value should be a provider alias in the form TYPE.ALIAS, such as "aws.eu". This defaults to the normal provider based on the prefix of the resource being imported. You usually don't need to specify this.

e.g. potentially in your case
```
terraform import -provider=aws.oregon aws_cognito_user_pool.test_user_pool us-west-2_GF2f5Jd0G
```

I know its not ideal, but I thought it was worth mentioning as something potentially helpful.

It might be related to the sentence in the middle: `This defaults to the normal provider based on the prefix of the resource being imported.` At least to me, this seems to imply that the import process will default to the hardcoded region in your original "default" AWS provider configuration (the one with no alias), assuming it follows the same ordering as credentials as defined in the [provider documentation](https://www.terraform.io/docs/providers/aws/index.html). We define the credentials ordering there, but not the region configuration ordering. As a note to myself, its probably worth explicitly mentioning the region configuration ordering in the documentation (rather than hiding under the guise of `Authentication` and `Static Credentials`).

**Comment by rlc4** [comment] 2018-04-10 22:36
@bflad Good suggestion,  but it only works for the situation of wanting to use a single provider to perform an action.  The reason I was setting things up with multiple providers was to be able to have modules take actions in different regions by referencing the alias.  The example I provided is the simplest example that demonstrates the flaw.

[The example in Multiple Provider Instances](https://www.terraform.io/docs/configuration/providers.html) appears to match exactly what I have, am I missing something?

**Comment by bflad** [comment] 2018-04-10 22:50
You're not doing anything wrong or missing anything. 😄  Currently, the import functionality of Terraform does not take provider configuration into consideration automatically: https://github.com/hashicorp/terraform/issues/17139

**Comment by rlc4** [comment] 2018-04-11 05:33
@bflad I have finally had some time to do some more testing.

I was certain that I'd gotten to the import failure as my sample case after trying to use terraform to create resources and having failures.  However, that seems not to be the case.

My test config looks like:
```
provider "aws" {
  region = "us-east-1"
  # region = "us-west-2"
}

provider "aws" {
  alias  = "oregon"
  region = "us-west-2"
}

resource "aws_cognito_user_pool" "test_user_pool" {
  provider = "aws.oregon"
  name     = "testingUsers-apply"
}
```

My commands are now:

> AWS_DEFAULT_REGION=us-east-1 AWS_PROFILE=terraform.privileged terraform apply

> AWS_REGION=us-east-1 AWS_PROFILE=terraform.privileged terraform apply

> AWS_PROFILE=terraform.privileged terraform apply

In all cases, the cognito pool "testingUsers-apply" is created in us-west-2 region. 

I'm presuming this is expected and desired behavior which reduces this issue to a duplicate (or provider specific example) of [hashicorp/terraform#17139](https://github.com/hashicorp/terraform/issues/17139)

**Comment by bflad** [comment] 2018-09-25 20:48
Closing as this appears to be a duplicate of https://github.com/hashicorp/terraform/issues/17139 as noted above.

**Closed by bflad** 2018-09-25 20:48 UTC
Labels: bug, waiting-response
