### ISSUE TITLE
cannot destroy and recreate VPC with gateways

### ISSUE THREAD

**Issue by dmrzzz** [terraform-providers/terraform-provider-aws#1248] opened 2017-07-26 16:49 UTC
Terraform fails to destroy and recreate an aws_vpc which contains an aws_internet_gateway and aws_vpn_gateway.

My hypothesis: TF doesn't destroy the existing gateway resources because it plans to reuse them for the new VPC, but in order for that to work it needs to call DetachInternetGateway and DetachVpnGateway (prior to deleting the old VPC), and then call the corresponding Attach methods after creating the new VPC.  It doesn't seem to be calling the Detach methods.

### Terraform Version
Terraform v0.9.11

### Affected Resource(s)
- aws_vpc
- aws_internet_gateway
- aws_vpn_gateway

### Terraform Configuration Files
main.tf:
```hcl
provider "aws" {
  region = "us-east-2"
}

# create VPC with Internet Gateway and VPN Gateway

resource "aws_vpc" "vpc" {
  cidr_block = "192.168.1.0/24"
  #cidr_block = "192.168.2.0/24"
}

resource "aws_internet_gateway" "igw" {
  vpc_id = "${aws_vpc.vpc.id}"
}

resource "aws_vpn_gateway" "vgw" {
  vpc_id = "${aws_vpc.vpc.id}"
}

# display IDs

output "vpc_id" {
  value = "${aws_vpc.vpc.id}"
}

output "igw_id" {
  value = "${aws_internet_gateway.igw.id}"
}

output "vgw_id" {
  value = "${aws_vpn_gateway.vgw.id}"
}
```

### Steps to Reproduce

1. terraform apply

    ```
    Apply complete! Resources: 3 added, 0 changed, 0 destroyed.
    ...
    Outputs:

    igw_id = igw-0d7cef64
    vgw_id = vgw-0bce423b
    vpc_id = vpc-057d3a6c
    ```

2. Edit main.tf and change cidr_block from 192.168.1.0/24 to 192.168.2.0/24 (thus forcing the VPC to be recreated)

3. terraform plan

    ```
    ~ aws_internet_gateway.igw
        vpc_id: "vpc-057d3a6c" => "${aws_vpc.vpc.id}"

    -/+ aws_vpc.vpc
        assign_generated_ipv6_cidr_block: "false" => "false"
        cidr_block:                       "192.168.1.0/24" => "192.168.2.0/24" (forces new resource)
        default_network_acl_id:           "acl-246b214d" => "<computed>"
        default_route_table_id:           "rtb-6767340e" => "<computed>"
        default_security_group_id:        "sg-8415f5ec" => "<computed>"
        dhcp_options_id:                  "dopt-2b17f942" => "<computed>"
        enable_classiclink:               "" => "<computed>"
        enable_dns_hostnames:             "false" => "<computed>"
        enable_dns_support:               "true" => "true"
        instance_tenancy:                 "default" => "<computed>"
        ipv6_association_id:              "" => "<computed>"
        ipv6_cidr_block:                  "" => "<computed>"
        main_route_table_id:              "rtb-6767340e" => "<computed>"

    ~ aws_vpn_gateway.vgw
        vpc_id: "vpc-057d3a6c" => "${aws_vpc.vpc.id}"

    Plan: 1 to add, 2 to change, 1 to destroy.
    ```

4. terraform apply

   Expected behavior: as shown in the plan above (successfully end up with a new VPC that contains the two gateways)

   Actual behavior:

    ```
    aws_vpc.vpc: Refreshing state... (ID: vpc-057d3a6c)
    aws_vpn_gateway.vgw: Refreshing state... (ID: vgw-0bce423b)
    aws_internet_gateway.igw: Refreshing state... (ID: igw-0d7cef64)
    aws_vpc.vpc: Destroying... (ID: vpc-057d3a6c)
    aws_vpc.vpc: Still destroying... (ID: vpc-057d3a6c, 10s elapsed)
    aws_vpc.vpc: Still destroying... (ID: vpc-057d3a6c, 20s elapsed)
    ...snip...
    aws_vpc.vpc: Still destroying... (ID: vpc-057d3a6c, 4m40s elapsed)
    aws_vpc.vpc: Still destroying... (ID: vpc-057d3a6c, 4m50s elapsed)
    Error applying plan:

    1 error(s) occurred:

    * aws_vpc.vpc (destroy): 1 error(s) occurred:

    * aws_vpc.vpc: DependencyViolation: The vpc 'vpc-057d3a6c' has dependencies and cannot be deleted.
	    status code: 400, request id: dcddb8c8-0381-4ad1-9d42-634f9915e6e7

    Terraform does not automatically rollback in the face of errors.
    Instead, your Terraform state file has been partially updated with
    any resources that successfully completed. Please address the error
    above and apply again to incrementally change your infrastructure.
    ```

5. Investigate status of gateways:

    ```
    $ aws ec2 describe-internet-gateways --filters Name=attachment.vpc-id,Values=vpc-057d3a6c
    {
        "InternetGateways": [
            {
                "Tags": [], 
                "Attachments": [
                    {
                        "State": "available", 
                        "VpcId": "vpc-057d3a6c"
                    }
                ], 
                "InternetGatewayId": "igw-0d7cef64"
            }
        ]
    }

    $ aws ec2 describe-vpn-gateways --filters Name=attachment.vpc-id,Values=vpc-057d3a6c
    {
        "VpnGateways": [
            {
                "State": "available", 
                "Type": "ipsec.1", 
                "VpnGatewayId": "vgw-0bce423b", 
                "VpcAttachments": [
                    {
                        "State": "attached", 
                        "VpcId": "vpc-057d3a6c"
                    }
                ]
            }
        ]
    }
    ```

   Notice that the gateways are still attached to the old VPC, which is why terraform can't delete it.

**Comment by dmrzzz** [comment] 2017-07-26 16:53
I should mention that a full `terraform destroy` has no trouble destroying the old VPC because it destroys both gateways first.

**Comment by radeksimko** [comment] 2017-07-27 07:01
This looks like a duplicate of https://github.com/hashicorp/terraform/issues/4754 - do you mind me closing this in favour of that issue?

Either way it's not something to be solved on the provider/resource side, but in core - or at least some core enhancements need to be implemented first.

**Comment by dmrzzz** [comment] 2017-07-27 15:54
I guess I don't really understand the core vs provider split; intuitively I would have thought this was very specific to AWS.  Anyway, sorry I didn't find hashicorp/terraform#4754 before submitting this one.  But I'm concerned about two things:
1. In the other issue it seems that you suggest a very simple fix for `aws_internet_gateway`, yet the bug has stayed open for 18 months without being fixed.  Am I missing something?
2. The other issue doesn't mention `aws_vpn_gateway`, which is just as much a problem as `aws_internet_gateway` as I demonstrate above.

If you think it's better to close this one and keep hashicorp/terraform#4754, I'll defer to your judgment, but then we should at least add a comment to the other one mentioning that `aws_vpn_gateway` has the same problem.

**Comment by radeksimko** [comment] 2017-07-27 19:16
> In the other issue it seems that you suggest a very simple fix for aws_internet_gateway

It's not as simple as I thought, unfortunately. I was a bit foolish at that time 😄 

> has stayed open for 18 months without being fixed. Am I missing something?

We'd obviously like to fix all issues, but the priority of this one, especially in this context is pretty low at this point. It is unexpected behaviour and it should work well out of the box, but the scenario of changing CIDR of a VPC (especially because it's heavily disruptive operation either way) is IMO not common enough that it would deserve special attention/priority over some other bugs and crashes which affect more people in more common scenarios in much worse way.

Most people don't redesign their network layouts every day, IMO. 😉 

> The other issue doesn't mention aws_vpn_gateway, which is just as much a problem as aws_internet_gateway as I demonstrate above.

Right, this is rather a generic problem for any resource that has to be recreated (a `ForceNew` field was modified) and has dependents. In this context it affects _all_ resources inside the VPC - `aws_instance`, `aws_autoscaling_group`, `aws_db_instance`, `aws_eip`, `aws_elb`, `aws_alb` etc. etc. Maybe half of all AWS resources can be attached to a VPC, so an exhaustive list would be very long.

I will mention that in the linked issue, just so everyone else is aware. Sometimes I feel certain things are obvious when you're head down in the internals, but for other people they're not - so thanks for the feedback - I really appreciate it.

**Closed by radeksimko** 2017-07-27 19:16 UTC
Labels: bug, waiting-response

**Comment by dmrzzz** [comment] 2017-07-27 19:25
> It's not as simple as I thought, unfortunately.

Ah, that's too bad (and given that, the low priority makes perfect sense).  Thanks for the explanation!

**Comment by romapi** [comment] 2018-09-14 07:11
I had similar issue solved by adding dependencies to resources.
The setup was: 
- create vpc1
- create gateway1 (attach it to vpc1)
- create privateSubnet1 (in vpc1)
- create privateIp1 (in privateSubnet1)
- create elasticIp1 (tie with privateIp1)
- create instance1 (elasticIp1)
With no dependencies it destroyed in it's own order.
So, in order to destroy a gateway resource it must be detached from a VPC.
Before you detach it from a VPC there shouldn't be any elastic IP-s related to VPC.
To destroy elastic IP you should detach it from a host.
So adding dependencies between VPC -> Gateway -> Elastic IP -> Instance resources made it more clear to terraform that destroy should start from Instance, not gateway.

**Comment by queglay** [comment] 2019-02-24 04:40
I cannot terraform destroy easily with this dependency problem.

I run into this dependency issue with open vpn.  if I create an eip for an open vpn instance, and setup a route, terraform destroy wont work.  it will try and destroy the internet gateway before destroying the eip and openvpn instance which wont work.

I would imagine that since aws understands these implicit dependencies that terraform implementation should be able to as well.
