### ISSUE TITLE
aws_waf_byte_match_set requires field_to_match 'data' when using 'URI' type

### ISSUE THREAD

**Issue by lukerosser** [terraform-providers/terraform-provider-aws#1069] opened 2017-07-06 10:36 UTC
### Terraform Version
> terraform -v
Terraform v0.9.11

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_waf_byte_match_set

### Terraform Configuration Files

resource "aws_waf_byte_match_set" "secure_magento_urls" {
  name  = "waf-magento-urls"

  byte_match_tuples = [
    {
      field_to_match {
        type = "URI"
      }
      text_transformation   = "LOWERCASE"
      target_string         = "/rss/catalog/review"
      positional_constraint = "STARTS_WITH"
    },
    {
      field_to_match {
        type = "URI"
      }
      text_transformation   = "LOWERCASE"
      target_string         = "/index.php/rss/catalog/review"
      positional_constraint = "STARTS_WITH"
    },
    {
      field_to_match {
        type = "URI"
      }
      text_transformation   = "LOWERCASE"
      target_string         = "/rss/catalog/notifystock"
      positional_constraint = "STARTS_WITH"
    },
    {
      field_to_match {
        type = "URI"
      }
      text_transformation   = "LOWERCASE"
      target_string         = "/index.php/rss/catalog/notifystock"
      positional_constraint = "STARTS_WITH"
    }
  ]
}

### Expected Behavior
Successful apply.

### Actual Behavior

* aws_waf_byte_match_set.secure_magento_urls: [ERROR] Error updating ByteMatchSet: [ERROR] Error updating ByteMatchSet: ValidationException: 4 validation errors detected: Value '' at 'updates.1.member.matchTuple.field.data' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'updates.2.member.matchTuple.field.data' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'updates.3.member.matchTuple.field.data' failed to satisfy constraint: Member must have length greater than or equal to 1; Value '' at 'updates.4.member.matchTuple.field.data' failed to satisfy constraint: Member must have length greater than or equal to 1
        status code: 400, request id: 1f905ce1-6236-11e7-b001-5f2ac51ee968

Errors due to missing 'data' value. field_to_match 'data' should be optional when using anything but 'HEADER' as the type:

https://www.terraform.io/docs/providers/aws/r/waf_byte_match_set.html#data

Confirmed this applies successfully by adding a 'data' value within field_to_match.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by nicwise** [comment] 2017-07-13 02:19
Same issue as https://github.com/terraform-providers/terraform-provider-aws/issues/1107

**Comment by radeksimko** [comment] 2017-07-16 08:30
Closing as duplicate of #966

Full explanation in https://github.com/terraform-providers/terraform-provider-aws/issues/966#issuecomment-310990195
[Bugfix](https://github.com/terraform-providers/terraform-provider-aws/pull/953) was shipped with version `0.1.2` of this provider.

**Closed by radeksimko** 2017-07-16 08:30 UTC
Labels: bug

**Comment by sandyfox** [comment] 2017-12-15 01:09
its working on v0.11.1 but more new issues
