### ISSUE TITLE
S3 bucket with blank encryption crashes Terraform

### ISSUE THREAD

**Issue by YakDriver** [terraform-providers/terraform-provider-aws#8775] opened 2019-05-24 21:53 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```console
$ terraform -v
Terraform v0.12.0
+ provider.aws v2.12.0
```

### Affected Resource(s)

* aws_s3_bucket

### Terraform Configuration Files

```console
$ export TF_VAR_sse_algorithm=
```

```hcl
provider "aws" {}

variable "sse_algorithm" {
  description = "The algorithm to use for server side encryption"
  type        = "string"
}

resource "aws_s3_bucket" "encrypted" {

  bucket = "yak-test-2000"

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm     = var.sse_algorithm
      }
    }
  }
}
```

NOTE: This is not correct usage. I've simplified as much as possible while still causing the crash.

### Panic Output

[panic](https://gist.github.com/YakDriver/ff4cafce54728ad25ee1b5119425a3a6)

[crash.log](https://gist.github.com/YakDriver/3613a16cd945ca917171113e478b4276#file-crash-log)

### Expected Behavior

```
Error: expected server_side_encryption_configuration.0.rule.0.apply_server_side_encryption_by_default.0.sse_algorithm to be one of [AES256 aws:kms], got 
```

### Actual Behavior

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### Steps to Reproduce

1. `export TF_VAR_sse_algorithm=`
2. `terraform apply`

**Comment by ryndaniels** [comment] 2019-11-22 15:23
Hi @YakDriver - thanks for taking the time to open this. I had a look at this with the most recent versions of Terraform and the AWS Provider (0.12.13 and 2.38.0 respectively right now) and was unable to reproduce this behavior - instead I saw the expected `Error: expected server_side_encryption_configuration.0.rule.0.apply_server_side_encryption_by_default.0.sse_algorithm to be one of [AES256 aws:kms], got` error rather than a crash. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md). 🙂

**Closed by ryndaniels** 2019-11-22 15:23 UTC
Labels: needs-triage, service/s3
