### ISSUE TITLE
Sagemaker endpoint not in service

### ISSUE THREAD

**Issue by sstoeckel** [terraform-providers/terraform-provider-aws#8713] opened 2019-05-20 09:54 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
* provider.aws: version = "~> 2.10"
* provider.null: version = "~> 2.1"

### Affected Resource(s)

* aws_sagemaker_endpoint_configuration
* aws_sagemaker_endpoint

### Terraform Configuration Files

```hcl
## Now existing: Sagemaker Terraform Ressources! :) 

resource "aws_sagemaker_endpoint" "some_endpoint" {
    name = "sagemaker_endpoint"
    endpoint_config_name = "some_ep_config"
}


resource "aws_sagemaker_model" "some_model" {
 // some model code
}

resource "aws_sagemaker_endpoint_configuration" "some_ep_config" {
    name = "some_ep_config_name"

    production_variants {
        variant_name            = "some_variant"
        model_name              = "some_model"
        initial_instance_count  = "1"
        instance_type           = "ml.t2.medium"
    
    }
}


```

### Expected Behavior

Should create an endpoint with the provided endpoint config

### Actual Behavior

Fails on first apply because sagemaker endpoint is not "in service"
ResourceNotReady: failed waiting for successful resource state

### Steps to Reproduce

Run script above or from official terraform documentation

**Comment by ryndaniels** [comment] 2019-11-22 17:07
Hi @sstoeckel! Thanks for taking the time to submit this issue. I had a look at this with the most recent versions of Terraform and the AWS Provider and was unable to reproduce this behavior. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md). 🙂

**Closed by ryndaniels** 2019-11-22 17:07 UTC
Labels: needs-triage, service/sagemaker

**Comment by adamantnz** [comment] 2019-11-29 15:17
Hey there - I had this exact issue. In my case, it was because the associated IAM role did not have         "ecr:GetDownloadUrlForLayer" permission. Hope this helps.
