### ISSUE TITLE
Missing iam_group breaks terraform refresh

### ISSUE THREAD

**Issue by luispabon** [terraform-providers/terraform-provider-aws#10532] opened 2019-10-17 11:16 UTC
# Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.14
AWS provider 2.23.0

### Affected Resource(s)
`aws_iam_group`

### Terraform Configuration Files

Simple config file:

```hcl
resource "aws_iam_group" "some_group" {
  name = "covfefe"
  path = "/yeah/"
}
```

### Debug Output
```
* aws_iam_group.XXXXX: aws_iam_group.XXXXX: Error reading IAM Group xxxxxxxxxxxxxxxxxxxxxxxxx: AccessDenied: User: arn:aws:sts::XXXXX:assumed-role/XXXXX/XXXXX is not authorized to perform: iam:GetGroup on resource: group xxxxxxxxxxxxxxxxxxxxxxxxx
status code: 403, request id: xxxxxxxxxxxxxxxxxxxx
```

### Panic Output

n/a

### Expected Behavior

AWS provider ensures `terraform refresh` can continue and remove the missing group from its state.

### Actual Behavior

During terraform refresh, if the group created via terraform is missing, the provider gets a 403 access denied on `iam:GetGroup`, and terraform stops dry on its tracks refusing to continue with refresh, to the point the state file still contains the missing group and we end up in a situation where the only solution is to either create the group again (which might not even be possible in an automated deployment environment) or perform manual terraform state surgery (which is dirty).

### Steps to Reproduce

  * iam group deployed via terraform as part of a stack
  * iam group is deleted outside terraform
  * `terraform refresh`

### Important Factoids

Nothing. A plain old `iam_group`

**Comment by ryndaniels** [comment] 2019-12-13 11:40
Hi @luispabon - Thanks for taking the time to submit this issue. I had a look at this with the most recent versions of Terraform and the AWS Provider and was unable to reproduce this behavior. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md). 🙂

**Closed by ryndaniels** 2019-12-13 11:40 UTC
Labels: needs-triage, service/iam
