### ISSUE TITLE
aws instance with root and attached volumes repeatedly asks to change names of volumes

### ISSUE THREAD

**Issue by CesarPantoja** [terraform-providers/terraform-provider-aws#9151] opened 2019-06-26 15:50 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.12.2
+ provider.aws v2.12.0
+ provider.template v2.1.2
```

### Affected Resource(s)

* aws_instance
* aws_volume_attachment
* aws_ebs_volume

### Terraform Configuration Files

```hcl
resource "aws_instance" "test" {
  ami = "ami-0a313d6098716f372"
  instance_type = "t3.nano"
  key_name = aws_key_pair.test-key.key_name
  tags = {
    Name = "test"
  }
  volume_tags = {
    Name = "test"
  }

  root_block_device {
    volume_type = "gp2"
    volume_size = "100"
  }
}

resource "aws_volume_attachment" "test" {
  device_name = "/dev/xvdh"
  volume_id   = aws_ebs_volume.test.id
  instance_id = aws_instance.test.id
  skip_destroy = true
  force_detach = true
}

resource "aws_ebs_volume" "test" {
  size = 400
  availability_zone = aws_instance.test.availability_zone
  tags = {
    Name = "test-data"
  }
}
```

### Debug Output

Step 1: https://gist.github.com/CesarPantoja/a91d382056720e9f5bfce5c5033ad2b0
Step 2: https://gist.github.com/CesarPantoja/e35ea5faccbe55fe0377dc64bca60cac

### Expected Behavior

It should not ask to update the name every time an instance that has an attached volume (apart from the root volume) is applied.

### Actual Behavior

The provider is asking to update the names of the volumes every time the instance is applied. 

### Steps to Reproduce

In this case, there's the root volume with tag Name= `test` and an attached volume with tag Name = `test-data`.

1. The first time `terraform apply` is run, it will create the instance and the volumes with the correct tags. 
2. The second time you do `terraform apply` (with no changes in the file), it asks to change the Name tag of the root volume from `test-data` to `test`.
3. If this change is applied, and `terraform apply` is run again (with no changes in the files) it will ask to change the name of the attached volume from `test` to `test-data`.
4. Even if this change is applied, and you do `terraform apply` again, the 2nd point will happen again, asking to change the root volume from `test-data` to `test`, and if this is applied, the 3rd point will happen again, and so on and so forth.

**Comment by ryndaniels** [comment] 2019-11-25 17:19
Hi @CesarPantoja - thanks for taking the time to open this. I had a look at this with the most recent versions of Terraform and the AWS Provider and was unable to reproduce this behavior. The second and later `terraform apply` didn't try to do a rename as you saw at all. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md). 🙂

**Closed by ryndaniels** 2019-11-25 17:19 UTC
Labels: needs-triage, service/ec2
