### ISSUE TITLE
Research: aws_acm_certificate redesign

### ISSUE THREAD

**Issue by breathingdust** [terraform-providers/terraform-provider-aws#13053] opened 2020-04-28 00:03 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The current `aws_acm_certificate` resource is old and its design has not aged well. It has and continues to be a significant source of frustration for the community. Many of the discussion and potential fixes for the behavior, come with their own limitations so the maintainers have decided to rewrite the resource to ensure it offers a good user experience for the community going forward.

Things to consider:
- Can we rewrite the internals and solve the issues that the community is experiencing without a breaking change?
- If not should this be included in version 3 of the provider.
- If not, how do we document the update path?

### New or Affected Resource(s)

* aws_acm_certficate

### References

* #8531

**Comment by johnhpatton** [comment] 2020-05-14 01:06
I have attempted to write an acm_certification module that uses for_each to drive the validation records (aws_route53_record) create/destroy, and it STILL recreates them on every run.  I've tried everything to get it to not revalidate the cert on every run on and off for months.
See: #13317

**Comment by bflad** [comment] 2020-05-18 23:45
## Background

[ACM ImportCertificate API](https://docs.aws.amazon.com/acm/latest/APIReference/API_ImportCertificate.html):

```json
{
   "Certificate": blob,
   "CertificateArn": "string",
   "CertificateChain": blob,
   "PrivateKey": blob,
   "Tags": [ 
      { 
         "Key": "string",
         "Value": "string"
      }
   ]
}
```

Current `aws_acm_certificate` resource (psuedo TF configuration - importing):

```hcl
resource "aws_acm_certificate" "example" {
  arn                        = ""        # TypeString, Computed
  certificate_body           = ""        # TypeString, "Required"
  certificate_chain          = ""        # TypeString, Optional
  domain_name                = ""        # TypeString, Computed
  private_key                = ""        # TypeString, "Required"
  subject_alternative_names  = [""]      # TypeList of TypeString, Computed
  tags                       = {"" = ""} # TypeMap of TypeString, Optional
}
```

[ACM RequestCertificate API](https://docs.aws.amazon.com/acm/latest/APIReference/API_RequestCertificate.html):

```json
{
   "CertificateAuthorityArn": "string",
   "DomainName": "string",
   "DomainValidationOptions": [ 
      { 
         "DomainName": "string",
         "ValidationDomain": "string"
      }
   ],
   "IdempotencyToken": "string",
   "Options": { 
      "CertificateTransparencyLoggingPreference": "string"
   },
   "SubjectAlternativeNames": [ "string" ],
   "Tags": [ 
      { 
         "Key": "string",
         "Value": "string"
      }
   ],
   "ValidationMethod": "string"
}
```

Current aws_acm_certificate resource (psuedo TF configuration - requesting):

```hcl
resource "aws_acm_certificate" "example" {
  arn                       = "" # TypeString, Computed
  certificate_authority_arn = "" # TypeString, Optional
  domain_name               = "" # TypeString, Required

  domain_validation_options {  # TypeList of Resource, Computed, NOTE: Eventual consistency during Read
    domain_name           = "" # TypeString, Computed
    resource_record_name  = "" # TypeString, Computed
    resource_record_type  = "" # TypeString, Computed
    resource_record_value = "" # TypeString, Computed
  }

  options { # TypeList of Resource, Optional
    certificate_transparency_logging_preference = "" # TypeString, Optional
  }

  subject_alternative_names = [""]      # TypeList of TypeString, Optional
  tags                      = {"" = ""} # TypeMap of TypeString, Optional
  validation_emails         = [""]      # TypeList of TypeString, Computed
  validation_method         = ""        # TypeString, Optional
}
```

[ACM DescribeCertificate API](https://docs.aws.amazon.com/acm/latest/APIReference/API_DescribeCertificate.html):

```json
{
   "Certificate": { 
      "CertificateArn": "string",
      "CertificateAuthorityArn": "string",
      "CreatedAt": number,
      "DomainName": "string",
      "DomainValidationOptions": [ 
         { 
            "DomainName": "string",
            "ResourceRecord": { 
               "Name": "string",
               "Type": "string",
               "Value": "string"
            },
            "ValidationDomain": "string",
            "ValidationEmails": [ "string" ],
            "ValidationMethod": "string",
            "ValidationStatus": "string"
         }
      ],
      "ExtendedKeyUsages": [ 
         { 
            "Name": "string",
            "OID": "string"
         }
      ],
      "FailureReason": "string",
      "ImportedAt": number,
      "InUseBy": [ "string" ],
      "IssuedAt": number,
      "Issuer": "string",
      "KeyAlgorithm": "string",
      "KeyUsages": [ 
         { 
            "Name": "string"
         }
      ],
      "NotAfter": number,
      "NotBefore": number,
      "Options": { 
         "CertificateTransparencyLoggingPreference": "string"
      },
      "RenewalEligibility": "string",
      "RenewalSummary": { 
         "DomainValidationOptions": [ 
            { 
               "DomainName": "string",
               "ResourceRecord": { 
                  "Name": "string",
                  "Type": "string",
                  "Value": "string"
               },
               "ValidationDomain": "string",
               "ValidationEmails": [ "string" ],
               "ValidationMethod": "string",
               "ValidationStatus": "string"
            }
         ],
         "RenewalStatus": "string",
         "RenewalStatusReason": "string",
         "UpdatedAt": number
      },
      "RevocationReason": "string",
      "RevokedAt": number,
      "Serial": "string",
      "SignatureAlgorithm": "string",
      "Status": "string",
      "Subject": "string",
      "SubjectAlternativeNames": [ "string" ],
      "Type": "string"
   }
}
```

---

Reported aws_acm_certificate resource issues:

- aws_acm_certificate SAN treatment doesn't match API if domain_name is duplicated: https://github.com/terraform-providers/terraform-provider-aws/issues/3543 (0 votes)
- add domain validation options parameter to aws_acm_certificate: https://github.com/terraform-providers/terraform-provider-aws/issues/3851 (27 votes)
- More advanced example for acm_certificate_validation involving SANs/How to iterate over list of maps: https://github.com/terraform-providers/terraform-provider-aws/issues/4200
- Destroying some Cloudfront certificates fail on first attempt: https://github.com/terraform-providers/terraform-provider-aws/issues/6082 (2 votes)
- resource/aws_acm_certificate: Error with private_key argument when updating an imported certificate: https://github.com/terraform-providers/terraform-provider-aws/issues/7401 (19 votes)
- aws_acm_certificate conflict with same domain_name in the same region: https://github.com/terraform-providers/terraform-provider-aws/issues/7760 (0 votes)
- aws_acm_certificate does not create new certificate for the existing domain: https://github.com/terraform-providers/terraform-provider-aws/issues/7909 (0 votes)
- aws_acm_certificate appears to be waiting for DNS validation to complete when SANs are present: https://github.com/terraform-providers/terraform-provider-aws/issues/8530 (24 votes)
- aws_acm_certificate subject_alternative_names & domain_validation_options get returned in a different order each time: https://github.com/terraform-providers/terraform-provider-aws/issues/8531 (301 votes)
- Removing subject_alternative_names parameter doesn't force a new certificate: https://github.com/terraform-providers/terraform-provider-aws/issues/8755 (3 votes)
- Changing certificate validation records, triggers diff bug: https://github.com/terraform-providers/terraform-provider-aws/issues/8848 (6 votes)
- Changing aws_acm_certificate from Amazon-issued to existing doesn't force new resource: https://github.com/terraform-providers/terraform-provider-aws/issues/9809 (5 votes)
- aws_acm_certificate "completes" too soon with incorrect state: https://github.com/terraform-providers/terraform-provider-aws/issues/9840 (26 votes)
- count is not working on certificate with multiple names: https://github.com/terraform-providers/terraform-provider-aws/issues/10098 (2 votes)
- Not possible to disable certificate_transparency_logging_preference in aws provider: https://github.com/terraform-providers/terraform-provider-aws/issues/10167 (3 votes)
- Local variable isn’t correctly evaluated before resource creation: https://github.com/terraform-providers/terraform-provider-aws/issues/10404 (4 votes)
- resource/aws_acm_certificate: Error with chain argument when updating an imported certificate: https://github.com/terraform-providers/terraform-provider-aws/issues/10847 (8 votes)
- ACM Certificate - Recreating every-time when I have multiple subject alternative names in the cert: https://github.com/terraform-providers/terraform-provider-aws/issues/10959 (10 votes)
- Using for_each with aws_acm_certificate.domain_validation_options: https://github.com/terraform-providers/terraform-provider-aws/issues/10997 (14 votes)
- Error: orphan resource aws_acm_certificate.default still has a non-empty state after apply; this is a bug in Terraform: https://github.com/terraform-providers/terraform-provider-aws/issues/11024 (29 votes)
- Importing certificate FROM an ACM CA via aws_acm_certificate forces re-creation every apply: https://github.com/terraform-providers/terraform-provider-aws/issues/11201 (0 votes)
- Impossible to update the intermediate chain on an imported ACM certificate: https://github.com/terraform-providers/terraform-provider-aws/issues/11615 (2 votes)
- aws_acm_certificate attributes reference - non existing attributes: https://github.com/terraform-providers/terraform-provider-aws/issues/11805 (3 votes)
- ACM Certificates have validation method set to NONE: https://github.com/terraform-providers/terraform-provider-aws/issues/12075 (2 votes)
- aws_acm_certificate appears to be waiting for DNS validation to complete when subject_alternative_names list is bigger than default service limit: https://github.com/terraform-providers/terraform-provider-aws/issues/12445 (0 votes)
- DNS validation records are always created and destroyed when creating aws_acm_certificate with aws_route53_record: https://github.com/terraform-providers/terraform-provider-aws/issues/13317

Existing aws_acm_certificate resource PRs:

- Add validation_domain argument to aws_acm_certificate: https://github.com/terraform-providers/terraform-provider-aws/pull/3853 (12 votes)
- Update aws_acm_certificate to add custom domain for email verification: https://github.com/terraform-providers/terraform-provider-aws/pull/4662 (3 votes)
- Sort ACM cert subject alternative names and domain validation opts: https://github.com/terraform-providers/terraform-provider-aws/pull/8708 (71 votes)
- WIP Create SANless certificate when removing all SANs from certificate: https://github.com/terraform-providers/terraform-provider-aws/pull/8756 (0 votes)
- Fix update of imported ACM certificates: https://github.com/terraform-providers/terraform-provider-aws/pull/9685 (3 votes)
- Sort ACM cert subject alternative names and domain validation option: https://github.com/terraform-providers/terraform-provider-aws/pull/10791 (51 votes)
- Update normalize function to put in state file full certificate data instead of hashes: https://github.com/terraform-providers/terraform-provider-aws/pull/10849 (9 votes) (adjusts `aws_iam_server_certificate` as well)
- [WIP] aws_acm_certificate: fix subject_alternative_names forces recreation: https://github.com/terraform-providers/terraform-provider-aws/pull/11300 (2 votes)
- Wait longer for ACM certificates creation: https://github.com/terraform-providers/terraform-provider-aws/pull/12371 (0 votes)

**Comment by bflad** [comment] 2020-05-19 01:06
## General Summary

- `validation_domain` argument missing under `domain_validation_options` per domain (or some other way to configure this setting) (#3851)
- Missing read-only `status` attribute (#3885)
- `certificate_body`, `certificate_chain`, and `private_key` are hashed in Terraform state (#7401, #9809, #10847, #11615)
- Missing `IdempotencyToken` prior to v2.23.0 (#7760, #7909)
- One minute of retries on creation unsuccessful for many SANs (#8530, #12445)
- `domain_validation_options` is ordered in Terraform, but not guaranteed order in AWS (#8531, #10997)
- `subject_alternative_names` is ordered in Terraform, but not guaranteed order in AWS (#8531, #10959, #13317)
- `domain_validation_options` length not known until apply (also including updating `subject_alternative_names`) returns confusing indexing/lengths (#10098, #10404)
- `certificate_transparency_logging_preference` cannot be adjusted with imported certificates (#10167)
- Upstream Terraform Core orphan resource TYPE.NAME still has non-empty state after apply (#11024 - https://github.com/hashicorp/terraform/issues/21559)
- Incorrect `validation_method` when `EMAIL` (#12075)

## Terraform Core / Terraform Plugin SDK v1+v2 Caveats

- `domain_validation_options` cannot be both an optional argument (for `validation_domain`) and computed attribute unless we require _every_ domain is configured in the TypeList/TypeSet or otherwise fill in the blanks for operators. Terraform expects that the length and values of an attribute remains constant for both the plan and the apply or it will return a "provider produced inconsistent results between plan and apply" type error. This is fairly guaranteed to occur for requested ACM certficates with DNS validation since the DNS record values always need to be referenced to create them.

## Proposal

Prior to 3.0.0 work (cleanup and minor fixes):

- Close issue #7760 and issue #7909 as resolved in v2.23.0 (we added `IdempotencyToken` to our ACM RequestCertificate API requests)
- Close issue #8848 with "diffs didn't match" standard reply (its likely due to issue #8531 -- just that Terraform 0.11 reports it incorrectly, will be addressed as part of 3.0.0)
- Close issue #10167 with "the API does not prevent the logs from being transmitted on import and disabling the logging afterwards does not remove the existing logs, so we do not want to give the impression that it would work as expected by allowing the configuration"
- Close issue #11024 with "likely upstream Terraform Core issue" since it applies to various Terraform resources and to follow upstream issue
- Close PR #4662 as duplicate of PR #3853
- Close PR #8756 as incomplete implementation and note this is due to how `Computed: true` attributes work (and it must be `Computed: true` due to imported certificates) -- set `subject_alternative_names = []` or use the `taint` command to forcibly remove SANs
- Close PR #8708 and close PR #10791 as we prefer `TypeSet` implementation (e.g. #12371) over complex sorting of `TypeList` implementations
- Provide review on PR #12371 that `Computed: true` must remain for imported certificates
- Increase creation timeout to 5 minutes (review and potentially merge #12371, closes issue #8530, closes issue #12445)
- Add `status` attribute (closes issue #3885)
- Increase deletion timeout to 20 minutes (closes issue #6082)
- Add documentation about `subject_alternative_names = []` or use the `taint` command to forcibly remove SANs (closes issue #8755)
- Fix `validation_method` lookup to also work with `domain_validation_options` `validation_method` (closes issue #12075)

Part of 3.0.0 work:

- Switch `subject_alternative_names` to `TypeSet` as a bugfix (could break references :cry:, review and potentially merge PR #12371, closes issue #10959, closes issue #13317)
- Remove `StateFunc` from `certificate_body`, `certificate_chain`, and `private_key` attributes (review and potentially merge PR #9685, closes issue #7401, closes issue #9809, closes issue #10847, closes issue #11615)

Unaccounted/uncertain:

- `validation_domain` argument missing under `domain_validation_options` per domain (or some other way to configure this setting) (I do not believe we can merge PR #3853 due to plan/apply caveat noted above, closes issue #3851)
- Consider adding `CustomizeDiff` for pre-calculating `domain_validation_options` (closes issue #10098, closes issue #10404)
- Switch `domain_validation_options` from `TypeList` to `TypeSet` (needs lots and lots of documentation HOWEVER this cannot be done unless `CustomizeDiff` works to appease `for_each` handling, closes issue #8531, closes issue #10997)

**Comment by johnhpatton** [comment] 2020-05-19 10:58
Thanks for the work that went into this, @bflad ... fantastic capture of all the issues with this group of resources. 
I'm not sure if PR [#12371](https://github.com/terraform-providers/terraform-provider-aws/pull/12371) is the PR you meant to capture related to switching subject_alternative_names to TypeSet, but that PR seems to be related to increasing the retry timeout from 1 to 5 mins.
Thanks for putting time into this!

**Comment by bflad** [comment] 2020-05-19 13:16
Thanks, @johnhpatton, fixed above.

**Comment by mrchief** [comment] 2020-05-22 04:10
Amazing work @bflad. Very thorough research and findings.

**Comment by bflad** [comment] 2020-05-27 13:16
I've gone through the pre-3.0.0 items and submitted the last part of the small improvements/fixes here: https://github.com/terraform-providers/terraform-provider-aws/pull/13513 👍

**Closed** 2020-07-24 14:17 UTC
Labels: enhancement, service/acm, thinking

**Comment by bflad** [comment] 2020-07-24 14:22
Everything is covered here now as part of the version 3.0.0 release with the last remaining bits being #3851 / #3853, which I have provided the community contributor with information on next steps forward here: https://github.com/terraform-providers/terraform-provider-aws/pull/3853#issuecomment-662045273 👍
