### ISSUE TITLE
Create a Firehose stream with Splunk endpoint and custom domain: InvalidArgumentException HECEndpoint

### ISSUE THREAD

**Issue by Kharkovlanok** [terraform-providers/terraform-provider-aws#6541] opened 2018-11-21 13:52 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8

### Affected Resource(s)

* aws_kinesis_firehose_delivery_stream

### Debug Output

```
Error: Error applying plan:

1 error(s) occurred:

* module.kinesis.aws_kinesis_firehose_delivery_stream.kinesis_stream: 1 error(s) occurred:

* aws_kinesis_firehose_delivery_stream.kinesis_stream: Error Updating Kinesis Firehose Delivery Stream: "splunk-firehose"
InvalidArgumentException: Invalid HECEndpoint. Supported endpoint format is https://<domain>:<port>.
        status code: 400, request id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

````

### Expected Behavior

The Splunk HECEndpoint should be updated with a custom domain and extension:
https://splunk.aws.id.custom:8888

### Actual Behavior

Error at the plan level, but works if I change the domain extension with a shorter value such as .com or .net ( https://splunk.aws.id.net:8888 works). I don't have this problem using the AWS console or CLI, so I think it's related to a misconfigured parameter sanitizer.

### Potential Terraform Configuration

```hcl
resource "aws_kinesis_firehose_delivery_stream" "kinesis_stream" {
  name     = "${var.kinesis_name}"
  destination = "splunk"

s3_configuration {
    role_arn           = "${aws_iam_role.firehose.arn}"
    bucket_arn         = "${var.s3_bucket_arn}"
    buffer_size        = 10
    buffer_interval    = 400
    compression_format = "GZIP"
  }

  splunk_configuration {
    hec_endpoint               = "https://splunk.aws.id.custom:8888"
    hec_token                  = "${var.hec_token}"
    hec_acknowledgment_timeout = 600
    hec_endpoint_type          = "Event"
    s3_backup_mode             = "FailedEventsOnly"
  
    processing_configuration = [
      {
        enabled = "true"
        processors = [
          {
            type = "Lambda"
            parameters = [
              {
                parameter_name  = "LambdaArn"
                parameter_value = "${aws_lambda_function.firehose_lambda.arn}:$LATEST"
              },
              {
                parameter_name  = "RoleArn"
                parameter_value = "${aws_iam_role.firehose.arn}"
              }
            ]
          },
        ]
      },
    ]
  }
}
```

**Comment by blontic** [comment] 2019-09-05 03:11
Strange but I get this same behaviour using the console or cloudformation. If i use a custom TLD it fails with `Invalid HECEndpoint. Supported endpoint format is https://<domain>:<port>.`

Not even using terraform. I think the issue is with Firehose

**Comment by bflad** [comment] 2019-11-13 20:23
Hi folks 👋 I'm able to confirm this issue by modifying one of our existing Splunk acceptance tests to using `hec_endpoint = "https://splunk.aws.id.custom:8888"`:

```
--- FAIL: TestAccAWSKinesisFirehoseDeliveryStream_SplunkConfigUpdates (21.68s)
    testing.go:615: Step 0 error: errors during apply:

        Error: error creating Kinesis Firehose Delivery Stream: InvalidArgumentException: Invalid HECEndpoint. Supported endpoint format is https://<domain>:<port>.
```

Terraform is not performing any validation/translation of this particular argument and the error is being returned from the Firehose API. Unfortunately in this case, it does not appear that anything can be done within the Terraform AWS Provider to handle this situation as it will need to be fixed in the Firehose API. We would suggest opening an AWS Support case or talking to your AWS account managers to raise this issue. 👍

**Closed by bflad** 2019-11-13 20:23 UTC
Labels: service/firehose, upstream
