### ISSUE TITLE
"autoscaling_groups": this field cannot be set on "aws_elastic_beanstalk_environment"

### ISSUE THREAD

**Issue by alexflav23** [terraform-providers/terraform-provider-aws#1174] opened 2017-07-18 09:22 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version

`Terraform v0.9.11`

### Affected Resource(s)

- aws_autoscaling_group
- aws_elastic_beanstalk_environment

### Terraform Configuration Files

```hcl
resource "aws_autoscaling_group" "bla_asg" {
  launch_configuration = "${aws_launch_configuration.bla-play-launch.id}"
  availability_zones = ["${data.aws_availability_zone.eu-west-1a.name}", "${data.aws_availability_zone.eu-west-1b.name}"]
  min_size = 1
  max_size = 2
  load_balancers = ["${aws_elb.bla-lb.id}"]
  health_check_type = "ELB"

  tag {
    key = "Name"
    value = "bla-autoscalling"
    propagate_at_launch = true
  }
}

resource "aws_elastic_beanstalk_environment" "bla-web-eb-env" {
  name = "bla-web-environment"
  application = "${aws_elastic_beanstalk_application.bla-web-eb-app.name}"
  cname_prefix = "bla_webapp"
  solution_stack_name = "64bit Amazon Linux running Java applications"
  tier = "WebServer"
  autoscaling_groups = ["${aws_autoscaling_group.bla_asg.id}"]
}
```

### Debug Output

No relevant debug output, terraform does not crash, but it errors out when trying to parse.

### Expected Behavior

According to the documentation found [here](https://www.terraform.io/docs/providers/aws/r/elastic_beanstalk_environment.html), `autoscalling_groups` should be a standard field on the resource  `aws_elastic_beanstalk_environment`, however it errors out during `terraform_plan`.

### Actual Behavior
```
module.dse.module.beanstalk.aws_elastic_beanstalk_environment.bla-web-eb-env: "autoscaling_groups": this field cannot be set
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
Nothing out of the ordinary with the application, standard Elastic Beanstalk deployment.

**Comment by Ninir** [comment] 2017-07-18 09:39
Hey @alexflav23 

Thanks for taking the time to open an issue! 🙂
Unfortunately, this is the expected behaviour: `autoscaling_groups` is not an argument, i.e. something you can set when declaring your resource, but an attribute, i.e. something you can get when the resource is actually created.

As per the API (http://docs.aws.amazon.com/elasticbeanstalk/latest/api/API_CreateEnvironment.html), this is not an option you can declare nor set, since BeanStalk will create the env for you: when the env is load-balanced, then an ELB/ALB is created (depending on your configuration) along with an autoscaling group and a launch configuration.

I will close this as there is nothing we could help on :(
If there is something I missed, tell us and we will discuss it, reopening the issue.

Thanks!

**Comment by alexflav23** [comment] 2017-07-18 09:40
Hi @Ninir What is the correct way to specify the configuration of an autoscalling group then?

**Closed by Ninir** 2017-07-18 09:39 UTC

**Comment by Ninir** [comment] 2017-07-18 09:44
@alexflav23 
You need to specify settings, as described here: http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-autoscalingasg
There are many ones, so you should be able to do anything you want to.

This is an example:

```hcl
...

resource "aws_elastic_beanstalk_environment" "main" {
  name                = "MyElb"
  application         = "${aws_elastic_beanstalk_application.main.name}"
  solution_stack_name = "64bit Amazon Linux 2017.03 v2.4.0 running PHP 5.6"

  setting {
    name = "MinSize"
    resource = "AWSEBAutoScalingGroup"
    namespace = "aws:autoscaling:asg"
    value = "1"
  } 

  setting {
    name = "MaxSize"
    resource = "AWSEBAutoScalingGroup"
    namespace = "aws:autoscaling:asg"
    value = "3"
  } 

  ...
}
```

Tell me how it goes :)

**Comment by alexflav23** [comment] 2017-07-18 09:45
Thank you.
