### ISSUE TITLE
upgrade to  terraform 0.10.0 from 0.9.10 resulted in a crash of terraform

### ISSUE THREAD

**Issue by tata2000** [terraform-providers/terraform-provider-aws#1384] opened 2017-08-10 16:25 UTC
After upgrading to terraform 0.10.0 from 0.9.10
Only on MAC the terraform crashes when running without -target.
for commands:
apply, plan, refresh

the error is
*terraform.EvalRefresh, err: aws_iam_role.role: connection is shut down
the resource is different every time.

It works fine on Linux with no problems with all same configs and tf files.

seems like a problem here

2017/08/10 19:18:06 [DEBUG] plugin: terraform-provider-aws_v0.1.3_x4: ---[ RESPONSE ]--------------------------------------
2017/08/10 19:18:06 [DEBUG] plugin: terraform-provider-aws_v0.1.3_x4: HTTP/1.1 200 OK
2017/08/10 19:18:05 [ERROR] root: eval: *terraform.EvalRefresh, err: aws_s3_bucket.logging: unexpected EOF
2017/08/10 19:18:06 [ERROR] root: eval: *terraform.EvalSequence, err: aws_s3_bucket.logging: unexpected EOF
2017/08/10 19:18:05 [ERROR] root: eval: *terraform.EvalRefresh, err: aws_s3_bucket.dlp.2: unexpected EOF
2017/08/10 19:18:06 [TRACE] [walkRefresh] Exiting eval tree: aws_s3_bucket.logging

**Comment by radeksimko** [comment] 2017-08-11 10:11
Hi @tata2000 
do you mind attaching more details which would allow us to reproduce the issue? e.g. full debug log (minus secret/sensitive data) and configs?

If you're worried about exposing secrets or sensitive data, feel free to encrypt the above using our PGP key available at https://keybase.io/hashicorp and send it to radek@hashicorp.com

Thanks.

**Comment by rowleyaj** [comment] 2017-08-11 10:48
Dupe of https://github.com/hashicorp/terraform/issues/15777

**Comment by radeksimko** [comment] 2017-08-11 11:56
Good point, thanks @rowleyaj 
Either way It's hard to tell whether this bug is in core or AWS provider without further details, so I'll keep both open for the moment.

**Comment by apparentlymart** [comment] 2017-08-14 18:24
Hi all,

I think this is the same issue as was fixed in #1316. @tata2000, would you mind trying again on AWS provider version 0.1.4? That PR was included in this newer release.

**Comment by tata2000** [comment] 2017-08-15 13:09
Thank you so much. the 0.1.4 version have fixed it.

**Closed** 2017-08-15 13:10 UTC
Labels: bug, waiting-response
