### ISSUE TITLE
Resource 'a' not found for variable 'aws_efs_file_system.a.id'

### ISSUE THREAD

**Issue by amadhavarao** [terraform-providers/terraform-provider-aws#5751] opened 2018-08-31 20:32 UTC
### Terraform version

$terraform -v
Terraform v0.11.8
+ provider.aws v1.34.0
+ provider.template v1.0.0

### Affected Resource(s)

* aws_efs_file_system

### Terraform Configuration Files

```
resource "aws_efs_file_system" "a" {

  encrypted                       = "true"
  kms_key_id                      = "${aws_kms_key.a.id}" #this should be arn and not id in my input value.
  provisioned_throughput_in_mibps = "10"
  throughput_mode                 = "provisioned"
}
```

### Expected Behavior:

Error out saying input kms_key_id is invalid.

### Actual Behavior:

Error stating Resource 'a' not found for variable 'aws_efs_file_system.a.id' when referencing file system id created.

### Steps to Reproduce:

1. `terraform plan`

**Comment by bflad** [comment] 2018-08-31 23:01
Hi @amadhavarao 👋 Sorry for the unexpected behavior here.

It turns out this is likely an issue upstream in Terraform core, rather than anything to do with the AWS provider specifically. This scenario basically occurs anytime we implement a resource attribute with a `ValidateFunc` and then that resource is then referenced by another resource. Terraform core, when the first resource is failing that validation, is preferring to return the invalid resource reference message instead of the resource validation error.

I'm going to close this issue out as we have a few upstream tracking issues relating to this:
* https://github.com/hashicorp/terraform/issues/18129
* https://github.com/hashicorp/terraform/issues/16332
* https://github.com/hashicorp/terraform/issues/14333

I would suggest commenting on and upvoting those for the latest updates on this. 👍

**Closed by bflad** 2018-08-31 23:01 UTC
Labels: bug, upstream-terraform
