### ISSUE TITLE
crash on validating because of wrong variables definition

### ISSUE THREAD

**Issue by DmitryShevkun** [terraform-providers/terraform-provider-aws#12117] opened 2020-02-21 13:30 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.20
Terraform v0.12.21
+ provider.aws v2.47.0

version.tf:
terraform { required_version = ">= 0.12" }

### Affected Resource(s)

aws_codestarnotifications_notification_rule
resourse module definition

### Terraform Configuration Files

https://gist.github.com/DmitryShevkun/425dc3b7a465b3f2265a9de36e41d310

### Debug Output

https://gist.github.com/DmitryShevkun/83cb087533e9886939a508b2c2d5679f

### Panic Output

https://gist.github.com/DmitryShevkun/23593947df993421a7036fb5e06d901e

### Expected Behavior

First time validating to find syntactic mistakes.
Expected to take standard error about empty string and/or empty list in part of required variables of main block

### Actual Behavior

TERRAFORM CRASH

### Steps to Reproduce

terraform validate

### Сause and Practice Recomendations

In fact, the cause of the problem is the use of empty objects "" and [] instead of zero for the variables marked as Required. I was expecting terraform to warn me of this error, but instead it is crushed. 

Also, looks like the crush is resolved in 2.50 plugin. But the lack of warnings about erroneous variable definitions can be confusing.

* #0000

**Comment by bflad** [comment] 2020-02-21 18:16
Hi @DmitryShevkun 👋 Thank you for reporting this and sorry you ran into trouble here.

The upstream hashicorp/terraform repository owns issues with Terraform CLI commands such as `terraform validate`. The Go stacktrace in https://gist.github.com/DmitryShevkun/23593947df993421a7036fb5e06d901e does confirm the issue is in the upstream Terraform CLI code.

Unfortunately since this repository lives in the terraform-providers GitHub organization and our GitHub bot only understands how to migrate issues from the hashicorp organization to the terraform-providers organization (and not the other way around), I'm going to close this issue here and ask that you resubmit it upstream since there is nothing actionable in this repository to be done here: https://github.com/hashicorp/terraform/issues/new?template=bug_report.md

**Closed by bflad** 2020-02-21 18:16 UTC
Labels: needs-triage, service/codestarnotifications
