### ISSUE TITLE
aws_route53_health_check.healthcheck requires specifying 3 regions

### ISSUE THREAD

**Issue by rajpolaris** [terraform-providers/terraform-provider-aws#1795] opened 2017-10-02 18:11 UTC
Hi there,

We suddenly started seeing an error related to aws_route53_health_check.

* aws_route53_health_check.healthcheck: InvalidParameter: 1 validation error(s) found.
- minimum field size of 3, UpdateHealthCheckInput.Regions.

regions - (Optional) A list of AWS regions that you want Amazon Route 53 health checkers to check the specified endpoint from.

### Terraform Version
0.10.4

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_route53_health_check

### Terraform Configuration Files
```hcl
resource "aws_route53_health_check" "healthcheck" {
  fqdn = "${var.webelb_generated_dns}"
  port = "${var.health_check_port}"
  type = "${var.health_check_type}"
  resource_path = "${var.health_check_resource_path}"
  failure_threshold = "${var.health_check_failure_threshold}"
  request_interval = "${var.health_check_request_interval}"
  measure_latency = true

  tags = {
    Name = "${var.health_check}"
   }
}
```

### Expected Behavior
I did not even make any change to this resource.

### Actual Behavior
Saw the error during apply.
1 error(s) occurred:

* module.dns.aws_route53_health_check.healthcheck: 1 error(s) occurred:

* aws_route53_health_check.healthcheck: InvalidParameter: 1 validation error(s) found.
- minimum field size of 3, UpdateHealthCheckInput.Regions.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
Create health check resource and don't specify regions property 
See the config shown above

### Important Factoids
Terraform plan did not show any errors.
Errors happen when applying the changes.
We are using Atlas to apply changes.
I was able to fix the error by setting the regions property. It seems to me that a minimum of 3 regions are required. Documentation should be updated to make this property required. This may be caused by AWS SDK changes.

  regions = ["us-east-1","us-west-1","us-west-2"]

**Comment by bflad** [comment] 2018-01-19 15:07
@rajpolaris are you still having this issue or did you figure out the problem? I'm not able to reproduce it with a simple configuration (below) nor have we seen this in our daily acceptance testing which features a few different use cases.

```hcl
resource "aws_route53_health_check" "example" {
  fqdn              = "foobar.example.com"
  port              = 80
  type              = "HTTP"
  resource_path     = "/"
  failure_threshold = 5
  request_interval  = 30
}
```

If the problem still exists, are you able to reproduce a configuration (or two if its a resource update) that might be causing this?

**Comment by bflad** [comment] 2018-01-23 13:23
To consolidate the discussion of this issue, I'm going to close this one in preference of an earlier duplicate report: #1437 In my limited personal testing, I was having a hard time reproducing this. Please drop a note in that issue if this is still happening for you.

**Closed by bflad** 2018-01-23 13:23 UTC
Labels: bug, service/route53, waiting-response
