### ISSUE TITLE
aws.resourceAwsS3BucketRead: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by icflournoy** [terraform-providers/terraform-provider-aws#1336] opened 2017-08-03 20:04 UTC
Hi there,

I have recently updated my terraform binary from v0.9.9 to v0.10.0. Once previous stable plans are now crashing every time I do a `terraform refresh`.

### Terraform Version
```
$ terraform --version
Terraform v0.10.0
```

### Affected Resource(s)
It looks to me that refreshing the lifecycle configuration for an S3 bucket is causing the fault.

### Terraform Configuration Files
This is inside a module, that is required by another module, that is pulled into my root terraform plan for the environment.
```hcl
resource "aws_s3_bucket" "bucket" {
    bucket = "${var.prefix}-${var.service_name}-logs"
    acl = "private"
    lifecycle_rule {
        id = "expire-all"
        prefix = "/"
        enabled = "true"

        expiration {
            days = "${var.expiration_days}"
        }
    }
}
```

### Panic/Debug Output
https://gist.github.com/icflournoy/0ec94596f6a760eb552e1c03f028f014

### Expected Behavior
Terraform completes a refresh of the state.

### Actual Behavior
During the refresh Terraform crashed.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform refresh`

### Important Factoids
Today I had refactored my plans and had a stable infrastructure under Terraform v0.9.9. I have upgraded to the v0.10.0 binary and am doing initial testing, but cannot move past the refresh phase.

I also have a secondary environment that shows the same stacktrace for the same resource, but much further back in the debug/trace log since the environment has more resources.  The refresh of these resources then fails with either `unexpected EOF` or `connection is shut down`.

**Comment by bsiegel** [comment] 2017-08-03 22:00
Believe this duplicates #1314

**Comment by bflad** [comment] 2017-08-03 23:02
Pinning AWS providers to 0.1.1 is working in our environment (until 0.1.4 is released)

**Comment by icflournoy** [comment] 2017-08-03 23:06
I can confirm that using 0.1.1 I no longer see an issue! (At least for `terraform plan`). Onwards with my testing...

**Comment by radeksimko** [comment] 2017-08-04 08:42
Hi @icflournoy 
thanks for the report.

Marking as duplicate of #1314 which was fixed in https://github.com/terraform-providers/terraform-provider-aws/pull/1316 and will be shipped as part of the next release 🔜 .

**Comment by radeksimko** [comment] 2017-08-04 08:42
Duplicate of #1314

**Closed by radeksimko** 2017-08-04 08:42 UTC
