### ISSUE TITLE
SQS queue name validation errors swallowed under certain conditions, or validation ignored

### ISSUE THREAD

**Issue by baldman** [terraform-providers/terraform-provider-aws#5506] opened 2018-08-10 17:07 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v0.11.7, aws provider version: v1.31.0

### Affected Resource(s)

* aws_sqs_queue

#### Example 1
This will result in the actual error:

main.tf
```hcl
provider "random" {
  version    = "~> 1.1"
}

resource "random_id" "prefix" {
  byte_length = 3
}

module "test" {
  source = "test"

  some_var = "${random_id.prefix.hex}"
}
```

test.tf
```hcl
variable "some_var" {}

resource "aws_sqs_queue" "terraform_queue" {
  name = "###-${var.some_var}"
  delay_seconds = 90
  max_message_size = 2048
  message_retention_seconds = 86400
  receive_wait_time_seconds = 10
}

resource "aws_sns_topic_subscription" "sns-subscription" {
  topic_arn = "arn:blah"
  protocol  = "sqs"
  endpoint  = "${aws_sqs_queue.terraform_queue.arn}"
}
```

#### Example 2
This should not result in a plan, but it does

main.tf
```hcl
provider "random" {
  version    = "~> 1.1"
}

resource "random_id" "prefix" {
  byte_length = 3
}

resource "aws_sqs_queue" "terraform_queue" {
  name = "###-${random_id.prefix.hex}"
  delay_seconds = 90
  max_message_size = 2048
  message_retention_seconds = 86400
  receive_wait_time_seconds = 10
}

resource "aws_sns_topic_subscription" "sns-subscription" {
  topic_arn = "arn:blah"
  protocol  = "sqs"
  endpoint  = "${aws_sqs_queue.terraform_queue.arn}"
}
```

### Panic Output

* No panic

### Expected Behavior

I should see the error complaining about incorrect queue name:
`module.test.aws_sqs_queue.terraform_queue: only alphanumeric characters and hyphens allowed in "name"`

### Actual Behavior

Example 1: I get a rather cryptic error about the queue resource not found:
`module.test.aws_sns_topic_subscription.sns-subscription: Resource 'aws_sqs_queue.terraform_queue' not found for variable 'aws_sqs_queue.terraform_queue.arn'`

Example 2: It seems that if you use a locally generated variable (say by using the `random` provider), the validation is actually skipped and will allow invalid characters, resulting in a plan to be executed.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

* There has to be a variable in the queue name (even if it contains valid characters, this bug occurs)
* To reproduce the issue, the variable in the queue name must be supplied to the `test.tf` script such that `test.tf` is a module
* To bug to occur, that variable must be generated by TF, passing just a string will not surface the issue. 
* The queue resource must be used (like attaching a policy in the example)

### References

* No references

**Comment by bflad** [comment] 2018-08-10 17:55
Hi @baldman! 👋 Sorry for the unexpected behavior here.

It turns out this is likely an issue upstream in Terraform core, rather than anything to do with the AWS provider specifically. This scenario basically occurs anytime we implement a resource attribute with a `ValidateFunc` and then that resource is then referenced by another resource. Terraform core, when the first resource is failing that validation, is preferring to return the invalid resource reference message instead of the resource validation error.

I'm going to close this issue out as we have a few upstream tracking issues relating to this:
* https://github.com/hashicorp/terraform/issues/18129
* https://github.com/hashicorp/terraform/issues/16332
* https://github.com/hashicorp/terraform/issues/14333

I would suggest commenting on and upvoting those for the latest updates on this. 👍

**Closed** 2018-08-10 17:55 UTC
Labels: bug, upstream-terraform
