### ISSUE TITLE
aws_s3_bucket replication incomplete!

### ISSUE THREAD

**Issue by gtmtech** [terraform-providers/terraform-provider-aws#2240] opened 2017-11-09 19:21 UTC
Terraform all versions. 

Terraform s3 bucket replication configuration contains the role, and the rules - id, prefix, status, enabled, and the destination - the target bucket and the storage class.

But it does not contain the owner. So this makes it impossible to do cross region cross account replication using terraform 

You can see how to do it here - http://docs.aws.amazon.com/AmazonS3/latest/dev/crr-change-owner.html

It would be useful to have this feature. There is virtually no point in cross-region bucket replication to the same account

**Comment by paddycarver** [comment] 2017-11-21 00:28
I'm going to close this out as a duplicate of #2221, so the feature request can be tracked there. If you feel this is a distinct feature request from #2221, please feel free to reply to this issue and we can reopen it.

**Closed by paddycarver** 2017-11-21 00:28 UTC
Labels: enhancement
