### ISSUE TITLE
Support restricted home directory for aws_transfer_user

### ISSUE THREAD

**Issue by cparmar** [terraform-providers/terraform-provider-aws#13794] opened 2020-06-17 13:00 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Transfer Family has an option to restrict a user to their home directory.
> For Restricted, select the check box so that your users can't access anything outside of that folder and can't see the Amazon S3 bucket or folder name.

Looking at the AWS CLI and Go SDK docs, there is a `home directory type` parameter which can be set to `PATH` or `LOGICAL`. I believe the provider currently uses `PATH` whereas the Restricted check box uses `LOGICAL` and uses the `home directory mapping` parameter to restrict the access. 

Here is the output from the AWS CLI:
```
aws transfer describe-user --server-id <REDACTED> --user-name cparmar
{
    "ServerId": "<REDACTED>",
    "User": {
        "Arn": "arn:aws:transfer:eu-west-1:<REDACTED>:user/<REDACTED>/cparmar",
        "HomeDirectoryMappings": [
            {
                "Entry": "/",
                "Target": "/<BUCKET NAME>/cparmar"
            }
        ],
        "HomeDirectoryType": "LOGICAL",
        "Role": "arn:aws:iam::<REDACTED>:role/transfer_service-user",
        "SshPublicKeys": [
            {
                "DateImported": "2020-06-17T12:38:40.485000+01:00",
                "SshPublicKeyBody": "<REDACTED>",
                "SshPublicKeyId": "<REDACTED>"
            }
        ],
        "Tags": [],
        "UserName": "cparmar"
    }
}
```

Support for the restricted check box using the terraform AWS provider.

### New or Affected Resource(s)

* aws_transfer_user

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://docs.aws.amazon.com/transfer/latest/userguide/edit-user-config.html#edit-user-details
* https://docs.aws.amazon.com/cli/latest/reference/transfer/create-user.html

**Comment by ewbankkit** [comment] 2020-06-17 13:06
@cparmar Thanks for raising this issue.
It is a duplicate of #11632. Please upvote that issue and add any additional comments there.

**Closed by ewbankkit** 2020-06-17 13:06 UTC
Labels: enhancement, needs-triage, service/transfer
