### ISSUE TITLE
Profile being blatted when module source contains a provider block

### ISSUE THREAD

**Issue by laithalissa** [terraform-providers/terraform-provider-aws#8946] opened 2019-06-11 16:21 UTC
I suspect there's a config merging bug when a terraform module with an aws provider block has a source mapping to another module which also has an provider block.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Discovered on:
Terraform v0.11.13
+ provider.aws v2.8.0

Reproduced (with reworded error message) on:
Terraform v0.12.1
+ provider.aws v2.8.0

### Terraform Configuration Files

Apologies that I can't post the actual source, but it's not really required anyway.
```
module "my_specialised_module" {
  source = "/home/laith/code/my-generic-module"
  # Some specialised config here
}

terraform {
  required_version = "= 0.11.13"
}

provider "aws" {
  region  = "eu-west-1"
  version = "2.8.0"
  profile = "my_aws_profile"
}
```
where /home/laith/code/my-generic-module/main.tf looks like this:

```
terraform {
  required_version = "= 0.11.13"
}

provider "aws" {
  region  = "eu-west-1"
  version = "2.8.0"
}

# resources etc
```

### Expected Behavior

Terraform should use the profile in the specialised module, overriding anything defined in the reference module.

### Actual Behavior

Terraform ignores (/deletes) the profile field

### Steps to Reproduce
1) Create an AWS user, generate keys, and put them under a profile
2) Create a module with a provider block, but without a profile field
3) Create another module which references the one in step 2, with a profile field referencing the profile from step 1
4) Try to plan and see that it doesn't use the profile (if you have no AWS creds in your environment it will complain that it can't fine keys anywhere)

### Important Factoids

When I run this, I get a permission error because the profile field has seemingly been overwritten. If you modify the version of the specialised module, say to 2.13.0, then I see this error message:

`No provider "aws" plugins meet the constraint "2.13.0,2.8.0".`

Indicating that the multiple provider blocks have been merged somehow. By removing the provider block from the generic module, the profile field is respected again.

For my purposes I'm happy to exclude the provider block from the generic module, as I don't think it's appropriate, but I thought you might appreciate the report.

**Comment by nywilken** [comment] 2019-06-11 16:42
@laithalissa thanks for this report. This is the current documented behaviour https://www.terraform.io/docs/configuration/modules.html#providers-within-modules

Adding @terraform-providers/core to help provide more info.

**Comment by laithalissa** [comment] 2019-06-11 17:01
@nywilken This behaviour makes sense after reading the documentation, but it caught 2 of us of guard. Is it worth outputting a warning when your child provider fields are ignored?

**Comment by apparentlymart** [comment] 2019-06-11 22:14
Since the example here is somewhat contrived I'm not sure I fully understand how the "real" system behind it fits together, but I will try to describe the current behavior here in the hope that we can figure out how the intended behavior, your expected behavior, and (if it's different) the actual behavior are differing:

Terraform (since 0.11) allows each module to have its own provider configurations, but also implements an automatic inheritance behavior to simplify the common case where a single provider configuration applies to the whole configuration tree.

In the simple, automatic case (which we recommend using whenever possible) only the root module has `provider` blocks, and every descendant module has no explicit configurations and instead assumes it will inherit a suitable configuration from the parent module.

For more complex situations where that model isn't suitable, there are two ways to explicitly model each module having its own set of provider configurations: the legacy approach (the only approach available in Terraform 0.10 and earlier) and the modern explicit-passing approach (introduced in Terraform 0.11). As my terminology might suggest, we recommend using the "modern" approach but continue to support the legacy approach for compatibility.

The legacy approach is for a child module to have its own `provider` blocks, as we see in the example that opened this issue. The behavior in that case is that the child module's `provider` block overrides the one that would otherwise have been inherited, and any resource _in that module_ will use the overridden configuration. However, it does _not_ affect any resources outside of that module, because the provider configuration is scoped to the single module. We don't recommend this approach because in practice it causes an annoying problem: removing the module from the configuration removes both the resource configurations and the `provider` blocks at the same time, so Terraform knows it needs to destroy all of those resources but it has no provider configuration to do it with. Because of this annoying edge, we switched to a different model in Terraform 0.11.

For Terraform 0.11, we observed that provider configurations must always outlive the resources that were created for them, and so we implemented a new approach where only the root module should include `provider` blocks, but you can selectively pass different aliased provider configurations down to individual modules:

```hcl
# Default provider configuration used for resources in this module, and inherited
# by child modules by default.
provider "aws" {
  region  = "eu-west-1"
  version = "2.8.0"
}

# Alternative ("aliased") provider configuration that exists only to pass to our
# specialized module below.
provider "aws" {
  alias = "foo"

  region  = "eu-west-1"
  profile = "my_aws_profile"
}

module "example" {
  source = "./modules/example"

  # Override the default inheritance behavior, so that within the child module
  # the default AWS provider configuration is set to the parent module's
  # "foo" alternative configuration.
  providers = {
    aws = aws.foo # (this is the 0.12 syntax; 0.11 syntax requires quotes around these)
  }
}
```

One key drawback of this new design in 0.11 was that the provider version constraint also lived inside the `provider` block, and so this design left no way for a child module to specify a version constraint without using the legacy approach.

In 0.12 we addressed that by separating the version constraints out from the provider blocks, which actually makes better sense in practice because the version selection is a property of the provider itself rather than the provider _configuration_ ... no matter how many `provider` blocks you write, there is still only one version of the `aws` provider installed. In Terraform 0.12, you'd remove the `version` argument from the `provider "aws"` block and write it inside the `terraform` block instead, like this:

```
terraform {
  required_providers {
    aws = "2.8.0"
  }
}
```

When setting a version constraint in a non-root module though, it's best to set it to a `>=` constraint rather than an exact constraint because otherwise, as you saw, all of the modules in the configuration will impose conflicting exact constraints on one another and thus Terraform will not be able to select a version that is compatible with everyone. Only a root module should set an exact version constraint.

**Comment by nywilken** [comment] 2019-07-29 18:44
@laithalissa it was indeed an interesting one, and not something I was familiar with. @apparentlymart, thank you for the detailed response and historical context. This is a great issue to keep as a reference issue. 

Seeing as this edge case has been documented and there has been active work to address these types of issues in Terraform core I would avoid trying to implement any logic on the AWS provider level to avoid playing catch if things should change.

I am going to close this issue for now. If in the future we find that we need to add (error/warning) messaging we can revisit it then. 

Thanks again folks for your time and effort in updating this issue.

**Closed by nywilken** 2019-07-29 18:44 UTC
Labels: upstream-terraform

**Comment by laithalissa** [comment] 2019-08-22 05:35
Hi, Sorry for not replying, I was away for some time.

Thanks for the thorough explanation @apparentlymart. It completely makes sense when you know the history, I just wish it was more obvious when you're debugging 😝 . Hope this issue saves someone time in the future.
