### ISSUE TITLE
Not throwing Error while creating multiple s3 buckets with same bucket name in a single AWS account using terraform. 

### ISSUE THREAD

**Issue by yerriswamykonanki** [terraform-providers/terraform-provider-aws#11022] opened 2019-11-26 13:53 UTC
Hello All,

When running terraform to create multiple s3 buckets with the same name in a single AWS account it is not throwing an error like the bucket has already existed.

Sample code:
 resource "aws_s3_bucket" "abc" {
  bucket = "demo-test"
}
resource "aws_s3_bucket" "abcd" {
  bucket = "demo-test"
}

CurrentOutput:
![image](https://user-images.githubusercontent.com/17057921/69639300-448b6380-1082-11ea-9317-63684291aafa.png)

ExpectedOutput:
![image](https://user-images.githubusercontent.com/17057921/69639085-f37b6f80-1081-11ea-9398-cf1dafb405fc.png)

**Comment by bflad** [comment] 2019-11-26 17:44
Related: https://github.com/hashicorp/terraform-plugin-sdk/issues/224

**Comment by ewbankkit** [comment] 2019-11-29 13:15
Similar:
* https://github.com/terraform-providers/terraform-provider-aws/issues/367

**Comment by bflad** [comment] 2019-12-02 17:09
Thanks @ewbankkit -- closing as a duplicate of #367. That issue and the upstream Terraform Plugin SDK issue can be tracked for further updates on this functionality.

**Closed by bflad** 2019-12-02 17:09 UTC
Labels: enhancement, service/s3
