### ISSUE TITLE
aws_emr_cluster.log_uri forces new resource

### ISSUE THREAD

**Issue by synhershko** [terraform-providers/terraform-provider-aws#1356] opened 2017-08-05 19:40 UTC
Once log_uri is set for an aws_emr_cluster resource, it will force a new resource every time:

Executing `terraform plan` will return something like this:

```
-/+ aws_emr_cluster.offline-reporting (new resource required)
     ....
     log_uri:   "s3n://my-emr-logs/offline-reporting/" => "s3://my-emr-logs/offline-reporting/" (forces new resource)
     ....
```

**Comment by radeksimko** [comment] 2017-08-07 07:39
Hi @synhershko 
I'm afraid there is no way to modify this field via the API once the cluster has been created.

http://docs.aws.amazon.com/ElasticMapReduce/latest/API/API_RunJobFlow.html

Feel free to correct me if I'm wrong.

Do you mind me closing this issue?

**Comment by synhershko** [comment] 2017-08-07 07:43
My point is it was never changed. Terraform is wrong by assuming it is. The value is just the same, but once set on initial launch terraform will continue prompting for new instance creation even though it wasn't changed.

**Comment by radeksimko** [comment] 2017-08-07 08:54
I see, thanks for the clarification. It looks like the EMR API is adding `n` to the log URI for some reason. That should be fairly easy to fix by adding `DiffSuppressFunc` to that field.

Before we do so I'd like to reproduce this bug though. I can try and build it myself, but sharing relevant configs would help to speed up this process and save some time.

**Comment by synhershko** [comment] 2017-08-07 09:03
You can use the EMR sample from your own docs

**Comment by radeksimko** [comment] 2017-08-07 11:20
Reproduced using the following config:

```hcl
resource "aws_s3_bucket" "s" {
  bucket = "radek-test-emr"
}

resource "aws_emr_cluster" "emr-test-cluster" {
  name          = "emr-test-arn"
  release_label = "emr-4.6.0"
  applications  = ["Spark"]

  termination_protection = false
  keep_job_flow_alive_when_no_steps = true

  master_instance_type = "m3.xlarge"
  core_instance_type   = "m3.xlarge"
  core_instance_count  = 1

  log_uri = "s3://${aws_s3_bucket.s.bucket}/"

  ec2_attributes {
    instance_profile = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:instance-profile/EMR_EC2_DefaultRole"
  }

  bootstrap_action {
    path = "s3://elasticmapreduce/bootstrap-actions/run-if"
    name = "runif"
    args = ["instance.isMaster=true", "echo running on master node"]
  }

  service_role = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/EMR_DefaultRole"
}

data "aws_caller_identity" "current" {}
```

**Closed** 2017-08-09 15:41 UTC
Labels: bug
