### ISSUE TITLE
aws_db_instance presented in plan with no changes

### ISSUE THREAD

**Issue by grahamjenson** [terraform-providers/terraform-provider-aws#8803] opened 2019-05-29 09:14 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.0
+ provider.aws v2.12.0
```

### Affected Resource(s)

* aws_db_instance

### Terraform Configuration Files

An `aws_db_instance` is being presented in the plan with no changes. Plan output (anonymized below).

```hcl
  # aws_db_instance.db_db will be updated in-place
  ~ resource "aws_db_instance" "db_db" {
        address                               = "app-dev.id.us-east-1.rds.amazonaws.com"
        allocated_storage                     = 5
        arn                                   = "arn:aws:rds:us-east-1:000000000000:db:app-dev"
        auto_minor_version_upgrade            = true
        availability_zone                     = "us-east-1c"
        backup_retention_period               = 2
        backup_window                         = "09:48-10:18"
        ca_cert_identifier                    = "rds-ca-2015"
        copy_tags_to_snapshot                 = true
        db_subnet_group_name                  = "developmentvpc"
        deletion_protection                   = false
        enabled_cloudwatch_logs_exports       = []
        endpoint                              = "app-dev.id.us-east-1.rds.amazonaws.com:5432"
        engine                                = "postgres"
        engine_version                        = "9.4.20"
        final_snapshot_identifier             = "app-dev-final"
        hosted_zone_id                        = "id"
        iam_database_authentication_enabled   = false
        id                                    = "app-dev"
        identifier                            = "app-dev"
        instance_class                        = "db.m4.xlarge"
        iops                                  = 0
        kms_key_id                            = "arn:aws:kms:us-east-1:000000000000:key/id"
        license_model                         = "postgresql-license"
        maintenance_window                    = "wed:03:54-wed:04:24"
        monitoring_interval                   = 0
        multi_az                              = true
        name                                  = "app"
        option_group_name                     = "default:postgres-9-4"
        parameter_group_name                  = "org-app-pg"
        performance_insights_enabled          = false
        performance_insights_retention_period = 0
        port                                  = 5432
        publicly_accessible                   = false
        replicas                              = []
        resource_id                           = "db-id"
        security_group_names                  = []
        skip_final_snapshot                   = true
        status                                = "available"
        storage_encrypted                     = true
        storage_type                          = "gp2"
        tags                                  = {
            "Name"          = "rds::org/app::db"
        }
        username                              = "root"
        vpc_security_group_ids                = [
            "sg-id",
        ]

        timeouts {}
    }

```

This is a regression from terraform v0.11.14 which does not show this in its plan. 

This is not a major issue, but I will probably not upgrade to v12 because I am unsure this will ty to change a property on the DB that is not being presented.

Cheers

**Comment by bflad** [comment] 2019-05-29 21:36
Hi @grahamjenson and others 👋 Sorry you are running into trouble here with the Terraform 0.12 upgrade.

Would anyone be able to provide the Terraform configuration that triggered this issue in their environment? While we can try to reconstruct it from the plan output above, we will want to ensure we are covering these cases in any potential fixes. Thanks!

**Comment by geekofalltrades** [comment] 2019-06-17 17:42
I'm seeing this as well. Here's the db definition:

```hcl
resource "aws_db_instance" "db" {
  allocated_storage = var.db_storage
  engine            = "postgres"
  instance_class    = var.instance_type

  username = "root"
  password = "changemequickly"

  availability_zone         = var.multi_az_enabled ? "" : data.aws_availability_zones.available.names[0]
  backup_retention_period   = 7
  backup_window             = "08:00-08:30"
  db_subnet_group_name      = aws_db_subnet_group.db.id
  deletion_protection       = var.termination_protection
  final_snapshot_identifier = "archivedb-${replace(var.name, ".", "-")}-final"
  identifier                = "archivedb-${replace(var.name, ".", "-")}"
  maintenance_window        = "wed:08:30-wed:09:00"
  multi_az                  = var.multi_az_enabled
  storage_encrypted         = "true"
  storage_type              = "gp2"

  vpc_security_group_ids = [
    aws_security_group.db.id,
    data.aws_security_group.bastions_access_psql.id,
    data.aws_security_group.ds_access_psql.id,
  ]

  tags = {
    Name              = "db.${var.name}"
    Project           = "research"
    ansible-archivedb = "true"
    ansible-managed   = "true"
    ansible-vpc       = var.name
  }

  lifecycle {
    ignore_changes = [
      # Terraform wants to delete and recreate the RDS instance if the
      # username or password change. We'll manage those credentials with
      # Ansible, instead.
      username,
      password,

      # Don't try to recreate the db if we created it by patching
      # a snapshot_identifier into the Terraform temporarily (as we do
      # during rebuilds).
      snapshot_identifier,
    ]
  }
}
```

Obviously some other resources and vars are missing. If you need those to repro let me know. Also, this configuration is post-`terraform 0.12upgrade`.

**Comment by geekofalltrades** [comment] 2019-06-17 19:09
I am also seeing this same thing happening with several "aws_instance" resources.

**Comment by a13xb** [comment] 2019-07-09 07:08
I get the same with 2.18.0 for an EC2 instance that has a EIP associated with it.

**Comment by sergiobuj** [comment] 2019-07-10 16:16
I'm using `Terraform v0.12.3` and `provider.aws v2.18.0`. I was getting the same output for `aws_db_instance`.

Reading through the DEBUG logs I found:

```
2019/07/09 10:11:23 [WARN] Provider "aws" produced an invalid plan for aws_db_instance.db, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .timeouts: planned for existence but config wants absense
```

I added the default [timeouts](https://www.terraform.io/docs/providers/aws/r/db_instance.html#timeouts) block and then got a clean plan.

```hcl
resource "aws_db_instance" "db" {
...
  timeouts {
    create = "40m"
    update = "80m"
    delete = "40m"
  }
}
```

Definitely seems like a problem with the way Terraform reports those expected blocks.

**Comment by phillipjf** [comment] 2019-07-17 13:33
@sergiobuj was spot on. I had an `aws_instance` showing up in a plan with no visible changes after migrating from v0.11.14 to v0.12.4. Running a plan as follows revealed the reason:
`$ TF_LOG=warn terraform plan -target=aws_instance.instance -out=plan.out > warn-plan.log 2>&1`
```
...
2019/07/17 08:23:36 [WARN] Provider "aws" produced an invalid plan for aws_instance.instance, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .root_block_device: block count in plan (1) disagrees with count in config (0)
      - .timeouts: planned for existence but config wants absense
...
```

**Comment by bflad** [comment] 2019-08-12 22:39
Hi folks 👋 Is anyone still having this problem with Terraform 0.12.6 and Terraform AWS Provider 2.23.0? There have been various changes to the Terraform Provider SDK since this was filed and Terraform AWS Provider 2.23.0 has the most up to date release. Thanks.

**Comment by bflad** [comment] 2019-09-04 18:28
It's been a long time since we heard from you here so we're going to close this out. If you're still having this problem on the latest versions of Terraform and the Terraform AWS Provider (v0.12.7 and v2.26.0 as of this writing), please feel free to open a new issue and complete all of the information requested in the [Bug Report template](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/ISSUE_TEMPLATE/Bug_Report.md) so that we can attempt to understand and reproduce the problem.

**Closed by bflad** 2019-09-04 18:28 UTC
Labels: service/rds, terraform-0.12, upstream-terraform, waiting-response
