### ISSUE TITLE
Extract All Account Ids using aws_organizations_organization resource

### ISSUE THREAD

**Issue by e-moshaya** [terraform-providers/terraform-provider-aws#8709] opened 2019-05-19 23:18 UTC
I need to extract all account ids under aws_organizations_organization resource.

I would like the output to be: ["0000000", "1111111", "2222222"]

Could you please help?

**Comment by nywilken** [comment] 2019-05-21 04:29
Duplicate of #6842.

@e-moshaya this functionality does not yet exist within the Terraform AWS provider. We have an open issue for tracking this feature request. Closing this issue to consolidate all comments on a single thread. Thanks for the request and help on improving the Terraform AWS provider.

**Closed by nywilken** 2019-05-21 04:29 UTC
Labels: question
