### ISSUE TITLE
Can't use logging with aws_sfn_state_machine

### ISSUE THREAD

**Issue by kuhnboy** [terraform-providers/terraform-provider-aws#14186] opened 2020-07-15 16:18 UTC
### Current Terraform Version

```
0.12.26
```

### Use-cases

Create cloud watch error logs for step functions

### Attempted Solutions

Look at documentation

### Proposal

Would be nice to have the logging configuration exposed in aws_sfn_state_machine.

### References

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-stepfunctions-statemachine-loggingconfiguration.html

**Comment by DrFaust92** [comment] 2020-07-15 17:30
duplicate of #12192

**Closed by DrFaust92** 2020-07-15 17:30 UTC
Labels: enhancement, needs-triage
