### ISSUE TITLE
aws_cloudwatch_log_metric_filter - default_value set even when not provided

### ISSUE THREAD

**Issue by marcinwyszynski** [terraform-providers/terraform-provider-aws#3131] opened 2018-01-25 15:13 UTC
Hi there,

looks like even when you do not provide `default_value` in `aws_cloudwatch_log_metric_filter`, it is set to 0 before being sent.

### Terraform Version
0.11.1

### Affected Resource(s)
`aws_cloudwatch_log_metric_filter`

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "aws_cloudwatch_log_metric_filter" "log-throughput" {
  name           = "calculate-log-throughput"
  pattern        = "[marker=EVENTS, events]"
  log_group_name = "/aws/lambda/${lookup(var.paperwatch_config, "function_name")}"

  metric_transformation {
    name      = "EventCount"
    namespace = "Logs/Paperwatch"
    value     = "$$events"
  }
}
```

### Expected Behavior

Default Value in AWS should be `None`.

### Actual Behavior

Default Value in AWS is `0`:

![cloudwatch_management_console](https://user-images.githubusercontent.com/571786/35395326-5997b826-01ea-11e8-966d-d272b6781be2.png)

### Steps to Reproduce

Try to create a metric filter with no Default Value.

**Comment by bflad** [comment] 2018-01-25 15:42
Hi @marcinwyszynski! I'm sorry you're having trouble with this and thank you for reporting it. It turns out this is a confirmed bug with an open issue (#2384) and an open PR to fix it (#2759). To consolidate our efforts, I'm going to close this issue in preference of the previously open one, which we will keep updated.

**Closed by bflad** 2018-01-25 15:42 UTC
Labels: bug, service/cloudwatchlogs
