### ISSUE TITLE
Setting aws credentials using aws profile is no more working since 1.44.0 version

### ISSUE THREAD

**Issue by dchaumond** [terraform-providers/terraform-provider-aws#6473] opened 2018-11-15 12:47 UTC
### Affected Resource(s)

* aws_1.45.0

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "..."
  profile = "..."
}
```
### Debug Output
```
Error: Error refreshing state: 1 error(s) occurred:

* provider.aws: error validating provider credentials: error calling sts:GetCallerIdentity: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

### Expected Behavior

Credentials are set using an aws profile. This was working fine for months but fail in new aws version (seems to break since 1.44.0 aws version)

### Actual Behavior

See error message, terraform complains for missing aws credentials.

### Steps to Reproduce

Rerun 

1. `terraform apply`

**Comment by christianhaller3000** [comment] 2018-11-15 12:56
https://github.com/terraform-providers/terraform-provider-aws/issues/6462

**Comment by bflad** [comment] 2018-11-15 14:31
Hi @dchaumond 👋 Thanks for reporting this and sorry for the trouble. This is likely a duplicate of #6462 so in order to consolidate discussions and efforts, I'm going to close this in preference of the earlier issue. 👍

**Closed by bflad** 2018-11-15 14:31 UTC

**Comment by dchaumond** [comment] 2018-11-15 16:44
Sure, as a workaround other credentials methods works or, as I've done, I can use 1.43 version for now
