### ISSUE TITLE
IAM user name change presents as a non-destructive change, but is, in fact, destructive

### ISSUE THREAD

**Issue by ryanjjung** [terraform-providers/terraform-provider-aws#8505] opened 2019-05-02 18:09 UTC
Quick description of the problem: changes to IAM user names are presented as a live property change, but in fact, AWS will destroy and recreate the resource. The output of a Terraform plan is inaccurate.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.10.7
AWS Provider v1.60.0

### Affected Resource(s)

IAM users. Here's my sanitized specific example:

    "aws_iam_user.resource_name": {
        "type": "aws_iam_user",
        "depends_on": [],
        "primary": {
            "id": "iam_user_name",
            "attributes": {
                "arn": "arn:aws:iam::11111111111:user/iam_user_name",
                "force_destroy": "false",
                "id": "iam_user_name",
                "name": "iam_user_name",
                "path": "/",
                "tags.%": "0",
                "unique_id": "ABCDEFGHIJKLMNOP"
            },
            "meta": {},
            "tainted": false
        },
        "deposed": [],
        "provider": ""
    }

### Terraform Configuration Files

    resource "aws_iam_user" "resource_name" {
      name = "iam_user_name"
    }

### Debug Output

    Terraform will perform the following actions:
         ~ aws_iam_user.resource_name
           name:               "iam_user_name" => "iam_user_name-environmentname"

### Expected Behavior

The output of a "terraform plan" wherein the name of an iam_user resource is changed should show up as a delete/recreate.

### Actual Behavior

It presents as a live property change.

### Steps to Reproduce

1. Create an iam_user resource with Terraform.
2. Change the name of the user.
3. Run a plan to see the "live change" output.
4. Run a create to see that AWS does not change the resource live, but instead deletes it and creates a new resource.

**Comment by ryndaniels** [comment] 2019-11-27 15:15
Hi @ryanjjung - Thanks for taking the time to submit this issue. I had a look at this with the most recent versions of Terraform and the AWS Provider and was unable to reproduce this behavior - the resource was instead updated in place in my testing. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md). 🙂

**Closed by ryndaniels** 2019-11-27 15:15 UTC
Labels: needs-triage, service/iam
