### ISSUE TITLE
Deletion of subnet and therefore VPC fails when Lambda ENIs are still attached in the subnets

### ISSUE THREAD

**Issue by Puneeth-n** [terraform-providers/terraform-provider-aws#5459] opened 2018-08-06 10:04 UTC
terraform-provides-aws: `1.27.0`
terraform-core: `0.10.8`

Seems to be related to hashicorp/terraform/issues/10272

I recently tried to destroy one of out test environments comprising of a VPC, around 50 lambdas all running within the VPC and 2 subnets.

I do not explicitly create any ENIs for lambdas so AWS creates it automagically upon lambda invocations.

When I tried to destroy my environment, the subnet deletion failed with a timeout as there were ENIs still attached and active in the subnets.

How does one go about fixing this?

**Comment by bflad** [comment] 2018-08-06 17:47
@Puneeth-n can you confirm if this is already reported by #829? It seems very similar. Thanks! (For what its worth, there's an open PR relating to this as well: #4884)

**Comment by Puneeth-n** [comment] 2018-08-07 08:13
@bflad Thanks for the pointers. Seems to be the same issue. Is there a timeline on when it will be merged?

**Comment by bflad** [comment] 2018-08-07 13:39
Closing as a duplicate of #829 to consolidate discussions and efforts there. Its not personally on my roadmap to look at currently and doesn't look like there's currently much community 👍  upvoting at the moment.

**Closed by bflad** 2018-08-07 13:39 UTC
Labels: service/ec2, service/lambda, waiting-response
