### ISSUE TITLE
Duplicate API

### ISSUE THREAD

**Issue by pomeara** [terraform-providers/terraform-provider-aws#7596] opened 2019-02-19 06:02 UTC
Terraform is creating duplicate API's and also not recognizing that I have an existing user created and throws errors about user already existing.

The Terraform 'refresh' command appears to do nothing with respect to syncing with AWS and the local state files if it did these two problems would not be happening

**Comment by aeschright** [comment] 2019-07-02 23:25
Hi @pomeara, I'm sorry to hear about this issue. In order to investigate, we need several more details. You can answer here, or close this and open a new issue using our [bug report form](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md). You might also find it helpful to make use the community forum: https://discuss.hashicorp.com/c/terraform-providers/tf-aws

Here's what to include:

### Terraform Version

Please run `terraform -v` to show the Terraform core version and provider version(s). If you are not running the latest version of Terraform or the provider, please upgrade because your issue may have already been fixed. [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions).

### Affected Resource(s)

Please list the affected resources and data sources.

* aws_XXXXX

### Terraform Configuration Files

Information about code formatting: https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Please provide a link to a GitHub Gist containing the complete debug output. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

To obtain the debug output, see the [Terraform documentation on debugging](https://www.terraform.io/docs/internals/debugging.html).

### Panic Output

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior

What should have happened?

### Actual Behavior

What actually happened?

### Steps to Reproduce

Please list the steps required to reproduce the issue.

1. `terraform apply`

### Important Factoids

Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic?

### References

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor documentation? For example:

**Comment by bflad** [comment] 2019-07-24 02:54
It's been a long time since we heard from you here so we're going to close this out. If you're still having this problem, please feel free to open a new issue and complete all of the information requested in the [Bug Report template](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/ISSUE_TEMPLATE/Bug_Report.md) so that we can attempt to understand and reproduce the problem.

**Closed by bflad** 2019-07-24 02:54 UTC
Labels: needs-triage, waiting-response
