### ISSUE TITLE
Spurious diffs after disabling dedicated master for Elasticsearch domain

### ISSUE THREAD

**Issue by joshuaspence** [terraform-providers/terraform-provider-aws#1067] opened 2017-07-06 06:46 UTC
On the latest version of Terraform (0.9.11), I am seeing spurious diffs from `terraform plan` after changing the value for `dedicated_master_enabled` from `true` to `false`. The issue can be easily reproduced using the following configuration:

```
resource "aws_elasticsearch_domain" "test" {
  domain_name           = "tf-test"
  elasticsearch_version = "5.3"

  cluster_config {
    instance_type = "m3.medium.elasticsearch"
    instance_count = 3

    dedicated_master_enabled = true
    dedicated_master_type    = "m3.medium.elasticsearch"
    dedicated_master_count   = 2
  }
}
```

After running `terraform apply`, change the configuration as follows:

```
resource "aws_elasticsearch_domain" "test" {
  domain_name           = "tf-test"
  elasticsearch_version = "5.3"

  cluster_config {
    instance_type = "m3.medium.elasticsearch"
    instance_count = 3

    dedicated_master_enabled = false
  }
}
```

Running `terraform plan` shows the following diff:

```
~ aws_elasticsearch_domain.test
    cluster_config.0.dedicated_master_count: "2" => "0"
    cluster_config.0.dedicated_master_type:  "m3.medium.elasticsearch" => ""
```

**Comment by atyndall** [comment] 2018-02-08 02:16
This is an issue for us too.

**Comment by endzyme** [comment] 2018-04-11 21:12
Same - this resolved at all?

**Comment by bflad** [comment] 2018-06-21 04:33
This issue is a duplicate of the earlier #252 -- in order to consolidate efforts and discussion, I'm going to closing this issue in preference of the earlier one to help clean up the repository issues. Don't forget to add a 👍  reaction to the original issue (on the earlier one), which helps prioritize things for the community and maintainers.

**Closed by bflad** 2018-06-21 04:33 UTC
Labels: bug, service/elasticsearch
