### ISSUE TITLE
Unable to Create MongoDB DMS Endpoint

### ISSUE THREAD

**Issue by mjalkio** [terraform-providers/terraform-provider-aws#6209] opened 2018-10-19 05:21 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.8
+ provider.aws v1.41.0
```

### Affected Resource(s)

* aws_dms_endpoint

### Terraform Configuration Files

```hcl
provider "aws" {
  region  = "us-east-1"
}

data "aws_kms_key" "default_dms_key" {
  key_id = "alias/aws/dms"
}

resource "aws_dms_endpoint" "mongodb" {
  endpoint_id   = "test"
  endpoint_type = "source"
  engine_name   = "mongodb"
  kms_key_arn   = "${data.aws_kms_key.default_dms_key.arn}"
}
```

### Debug Output

[Link](https://gist.github.com/mjalkio/38cd357186b51cc3b081adf6674d56b5)

### Expected Behavior

The resource should be created, or an informative error message should be returned.

### Actual Behavior

I get `aws_dms_endpoint.mongodb: Still creating... (5m20s elapsed)` for five minutes, and see 500 errors in the debug log.

### Steps to Reproduce

I have not tried to create a minimal version of this issue. I might tomorrow.

### References

None.

**Comment by bflad** [comment] 2018-10-19 17:19
In the Terraform debug logs there should be line with `[DEBUG] DMS create endpoint:` and right after that the actual AWS Go SDK call to `CreateEndpoint`. Using the [AWS CLI dms create-endpoint](https://docs.aws.amazon.com/cli/latest/reference/dms/create-endpoint.html) command you can try to replicate it. 👍

**Comment by mjalkio** [comment] 2018-10-19 17:20
Okay, I updated the Terraform Config that I provided because it does consistently reproduce. I will upload some updated debug logs as soon as the current attempt fails...

**Comment by mjalkio** [comment] 2018-10-19 17:31
Hm, I didn't use the Go SDK but this looks suspicious:
```
Michael-Jalkios-MacBook-Pro:debugging mjalkio$ aws dms create-endpoint --endpoint-identifier test --endpoint-type source --engine-name mongodb --mongo-db-settings KmsKeyId=arn:aws:kms:us-east-1:301199101081:key/1e258fe7-de46-4a91-8bde-389e88b7f4ca,Port=0 --port 0

Parameter validation failed:
Unknown parameter in MongoDbSettings: "KmsKeyId", must be one of: Username, Password, ServerName, Port, DatabaseName, AuthType, AuthMechanism, NestingLevel, ExtractDocId, DocsToInvestigate, AuthSource
```

This doesn't seem to be aligned with what's in the documentation (https://docs.aws.amazon.com/cli/latest/reference/dms/create-endpoint.html).

**Comment by mjalkio** [comment] 2018-10-19 21:57
I found the issue, within the `aws_dms_endpoint` you MUST specify `mongodb_settings.auth_mechanism`. If you do not specify it, it will get passed as an empty string, and AWS returns a 500 error.

**Comment by aeschright** [comment] 2019-07-01 19:26
Closing per above confirmation the issue is resolved. 👍

**Closed by aeschright** 2019-07-01 19:26 UTC
Labels: service/databasemigrationservice, upstream
