### ISSUE TITLE
Add "enable data capture" options to aws_sagemaker_endpoint_configuration

### ISSUE THREAD

**Issue by jrosen** [terraform-providers/terraform-provider-aws#15333] opened 2020-09-24 17:01 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Sagemaker has the ability to capture the inputs and outputs from endpoint apis.  This is configured at the endpoint configuration level.  There should be controls for enabling, bucket location for results, percentage of results to store, as well as some other capture settings.
### Affected Resource

* aws_sagemaker_endpoint_configuration

### Potential Terraform Configuration

```terraform
resource "aws_sagemaker_model" "model" {
  name = "sm-model-${replace(var.model_version, ".", "-")}-${var.terraform_environment}"
  execution_role_arn = aws_iam_role.api_role.arn

  primary_container {
    image = "123123123123.dkr.ecr.us-east-1.amazonaws.com/model:${var.model_version}"
   

}

resource "aws_sagemaker_endpoint_configuration" "configuration" {
  name = "model-${replace(var.model_version, ".", "-")}-${var.terraform_environment}" 
  data_capture {
    enable_capture = true
    initial_sampling_percentage = 5
    destination_s3_uri = "s3://capture-bucket/"
    ...
  }
  production_variants {
    variant_name = replace(var.model_version, ".", "-")
    model_name = aws_sagemaker_model.model.name
    instance_type = local.instance_type
    initial_instance_count = local.instance_count
  }
}
```

### References
For more details, here's the boto3 command with those details : https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Client.create_endpoint_config

* #0000

**Comment by DrFaust92** [comment] 2020-10-31 19:09
Duplicate of #14170

**Closed by DrFaust92** 2020-10-31 19:09 UTC
Labels: enhancement, service/sagemaker
