### ISSUE TITLE
Terraform RDS Aurora cluster instance- Does not support updating - ca_cert_identifier

### ISSUE THREAD

**Issue by phani308** [terraform-providers/terraform-provider-aws#10517] opened 2019-10-15 21:32 UTC
We are using Terraform 0.11.13 version and I see it does not support RDS cluster instance to add/modify "ca_cert_identifier" attribute .

We received a communication from AWS that the old "rds-ca-2015" will expire in March 2020 . I need to be able to update my RDS aurora instances to new certs and it is not possible now. Please let us know if there is a PR for it and when can that be released

@martinssipenko @kppullin @bflad @radeksimko @stefansundin @katbyte

**Comment by arpitairan** [comment] 2019-10-16 12:16
I am facing the same issue. We have also received the Notification from AWS and need to update our Aurora cluster with new "ca_cert_identifier".

Though "ca_cert_identifier" is mentioned in "aws_db_instance" section of the documentation, I still tried using the "ca_cert_identifier" attribute in "aws_rds_cluster_instance" resource block and got the following error -

Error: aws_rds_cluster_instance.cluster_instances: : invalid or unknown key: ca_cert_identifier

Kindly assist.

**Comment by tomelliff** [comment] 2019-10-16 14:03
I think this is a duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/10467

**Comment by ryndaniels** [comment] 2019-12-13 11:42
This does in fact look like a duplicate of #10467 so I'm going to close this so we can consolidate work and discussion there. 👍

**Closed by ryndaniels** 2019-12-13 11:42 UTC
Labels: enhancement, needs-triage
