### ISSUE TITLE
Error: Instance data.aws_region.current data could not be decoded from the state unsupported attribute "current

### ISSUE THREAD

**Issue by estebanes22** [terraform-providers/terraform-provider-aws#14763] opened 2020-08-20 21:55 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.24, hashicorp/aws v2.70.0

### Affected Resource(s)

 data "aws_region" "current" {}

### Terraform Configuration Files

```hcl
data "aws_region" "current" {}
```

### Expected Behavior

Terraform plan runs without issue

### Actual Behavior
**ALL** my team's pipelines have **_suddenly_** started failing when running terraform plan with the same error. This is across the board and no changes on our pipelines were made from the time things were working to the time this issue started.

Error: Invalid resource instance data in state

  on main.tf line 19:
  19: data "aws_region" "current" {}

Instance data.aws_region.current data could not be decoded from the state:
unsupported attribute "current".

### Steps to Reproduce

1. `terraform plan` with the versions specified above.

### References
![image](https://user-images.githubusercontent.com/51391611/90829746-f13efc80-e305-11ea-8af7-05c9ccaecc16.png)

* #0000

**Comment by chicken231** [comment] 2020-08-24 17:24
Running the command mentioned here resolved this same error for me: https://github.com/hashicorp/terraform/issues/25819#issuecomment-672939811

**Comment by marco-lancini** [comment] 2020-08-25 19:00
I can reproduce @estebanes22 issue, and the fix proposed in [hashicorp/terraform#25819 (comment)](https://github.com/hashicorp/terraform/issues/25819#issuecomment-672939811) did **not** solve the issue for me, unfortunately

**Comment by nigelellis** [comment] 2020-08-25 19:17
I'm also hitting this issue which attempting the upgrade and had to rollback to 0.12.29.  This looks like a duplicate of https://github.com/hashicorp/terraform/issues/25752 which is supposed to be fixed in the next release (0.13.1).

**Comment by marco-lancini** [comment] 2020-08-27 18:29
Upgraded to 0.13.1 and can confirm the error seems resolved

**Comment by bflad** [comment] 2020-08-27 18:33
Thanks for the confirmation, @marco-lancini. This should be resolved with Terraform CLI 0.13.1. 👍

**Closed by bflad** 2020-08-27 18:33 UTC
Labels: bug, upstream-terraform
