### ISSUE TITLE
ignore_changes not working for sets

### ISSUE THREAD

**Issue by ryzr** [terraform-providers/terraform-provider-aws#9776] opened 2019-08-15 01:15 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.6

### Affected Resource(s)

* aws_ecs_service
* likely many others

### Terraform Configuration Files

```hcl
resource "aws_ecs_service" "service" {
  # ...

  load_balancer {
    target_group_arn = var.target_group_a_arn
    container_name   = var.load_balancer_container_name
    container_port   = 80
  }

  lifecycle {
    ignore_changes = [load_balancer.0.target_group_arn]
  }
}
```

### Expected Behavior

The `target_group_arn` key of the first load_balancer set should be ignored.

### Actual Behavior

When running terraform plan, the following error is output:

```
Error: Cannot index a set value

  on deploy/ecs_web_service/main.tf line 52, in resource "aws_ecs_service" "service":
  52:     ignore_changes = [desired_count, task_definition, load_balancer.0.target_group_arn]

Block type "load_balancer" is represented by a set of objects, and set
elements do not have addressable keys. To find elements matching specific
criteria, use a "for" expression with an "if" clause.
```

### Steps to Reproduce

1. Create a resource similar to the one above
2. `terraform plan`

### Important Factoids

I have attempted many other variations, including

`load_balancer.target_group_arn`
`load_balancer.0.target_group_arn`
`load_balancer["*"].target_group_arn`
`load_balancer["%"].target_group_arn`
`load_balancer["#"].target_group_arn`

These all return the same error.

### References

* https://github.com/terraform-providers/terraform-provider-aws/issues/3819 (closed prematurely, or possibly now an issue with terraform)

**Comment by outime** [comment] 2019-08-16 10:24
I could reproduce this issue and under exact same circumstances (ECS service resource).

**Comment by bflad** [comment] 2019-08-16 13:29
Hi folks 👋 Thank you for reporting this.

The logic and behavior of the [`lifecycle` configuration block `ignore_changes` meta-argument](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) is managed upstream in [Terraform CLI code](https://github.com/hashicorp/terraform/) and applicable across all Terraform resources. The `lifecycle` configuration block itself is special in Terraform and is designed to control various aspects of ordering and difference handling without interaction or necessary implementation in Terraform Providers.

The mentioned `ignore_changes` limitation is unfortunately not something that we can perform any adjustments in the Terraform AWS Provider codebase to fix or workaround, as the provider never actually receives any information from the `lifecycle` configuration block. Once the feature is implemented in Terraform CLI, it will automatically work with the Terraform AWS Provider after upgrading to the Terraform CLI containing the change. Since there that can be done in this codebase and GitHub does not support migrating issues across GitHub organizations, we will close this issue but suggest that you re-open a new one upstream: https://github.com/hashicorp/terraform/issues/new/choose

**Closed by bflad** 2019-08-16 13:29 UTC
Labels: needs-triage, service/ecs, upstream-terraform

**Comment by ryzr** [comment] 2019-08-18 00:35
Hey @bflad, thank you for the response.

That makes sense. I got a little confused on where to open it, as the same issue was opened on hashicorp/terraform last year and then migrated to this repo :-P

@outime I've re-opened the issue on hashicorp/terraform here:
https://github.com/hashicorp/terraform/issues/22504

**Comment by outime** [comment] 2019-08-18 12:32
@ryzr thanks! Gave my upvote there as well.
