### ISSUE TITLE
aws_route53_record.dns_record must be replaced but isn't

### ISSUE THREAD

**Issue by hryatgit** [terraform-providers/terraform-provider-aws#9688] opened 2019-08-08 19:06 UTC
Given is a hosted zone on route53 exists, including records of type NS, MX, TXT, A and SOA. Issuing  terraform apply command (tf code see below) execution plan promises 'aws_route53_record.dns_record must be replaced', but instead a new record is added.

```
# OLD TF-FILE:
data "aws_route53_zone" mydomain {
    name = "mydomain.com"
}

resource "aws_route53_record" "dns_record" {

  zone_id = "${data.aws_route53_zone.mydomain.zone_id}"
  name    = "oldserver.${data.aws_route53_zone.mydomain.name}"
  type = "A"
  ttl = "1800"
  records = ["100.200.3.4"]
}

#NEW TF-FILE (diff):

#  - name    = "oldserver.${data.aws_route53_zone.mydomain.name}"
#  + name    = "newserver.${data.aws_route53_zone.mydomain.name}"

```
Intention here is to change the server's name, expecting that  existing record "oldserver.mydomain.com"  will be replaced by "newserver.mydomain.com".

Instead new record for hosted zone on route53 is created and the old one remains listed.

terraform plan says:

'# aws_route53_record.dns_record must be replaced' '~ name = "newmailserver.solaris-it.com" -> "oldmailserver.solaris-it.com" # forces replacement'

but it doesn't. Is this a bug?

**Comment by ryndaniels** [comment] 2019-08-09 14:11
Hi @hryatgit! Could you please edit this issue so it follows our template for [bug reports](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md)? Making sure we get all of that information in the issue will help us as maintainers to look at it more effectively. Thanks! 🙂

**Comment by hryatgit** [comment] 2019-08-13 13:45
information ok?

**Comment by Mochizuki-S2** [comment] 2019-12-09 03:34
This issue may be same as  #9024

**Comment by bflad** [comment] 2019-12-09 14:22
Thanks for the note, @Mochizuki-S2. This does appear to be a duplicate of #9024, so to consolidate efforts and discussions I'm going to close this one in preference of the earlier issue.

**Closed by bflad** 2019-12-09 14:22 UTC
Labels: service/route53
