### ISSUE TITLE
Hangs when installing RPM packages on CentOS

### ISSUE THREAD

**Issue by shanep2300** [terraform-providers/terraform-provider-aws#3293] opened 2018-02-08 15:47 UTC
Hi there,

Machine without 'remote-exec' are created just fine. Adding a simple 'yum' command hangs on the Terraform script, but doesn't hang when the command is executed locally after creating the machine with Terraform.

### Terraform Version
`0.11.3`

### Terraform Configuration Files
```hcl
provider "aws" {
	region = "us-east-1"
	profile = "saml"
}

resource "aws_instance" "influxdb_instance" {
	ami = "${var.ami}"
	instance_type = "${var.instanceType}"
	security_groups = "${var.securityGroups}"
	subnet_id = "${var.subnetId}"
	key_name = "${var.keyName}"	

	tags {
		Name = "${var.instanceName}"	
	}

	// Connects as the centos user using SSH
	connection {
		user = "centos"
		private_key = "${file("C:/Users/<user>/Downloads/InfluxDB.pem")}"
	}

	// Executes commands on the box
	provisioner "remote-exec" {
		inline = [
			"sudo yum install -y https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-4.6.3-1.x86_64.rpm"
		]
	}
}
```

### Debug Output
Left image is running the Terraform script. Right image is running the same command locally.
![09_53_58](https://user-images.githubusercontent.com/16820289/35981188-a6c105dc-0cba-11e8-9b32-dd19bf8d069e.jpg)

### Expected Behavior
The rest of the output that you see on the right side of the image and Terraform completing the creation of the machine.

### Actual Behavior
Terraform hangs right after the Dependencies Resolved chart. I can't ctr+c out of the cmd window and running `terraform show` after opening a new cmd prompt is blank even though in AWS, the machine exists with the package correctly installed. Also adds a random letter 'B' at the end of the last Terraform output.

### Steps to Reproduce
1. `terraform apply`

**Comment by vancluever** [comment] 2018-02-08 16:29
Hey @shanep2300 - this is indeed odd. A few questions:

* Can you try a different package payload here? Maybe add another package to your yum install.
* I'm assuming this is repeatable? Like it can be reliably reproduced?
* What OS/connection scheme are you trying this from, ie: is there a VPN involved? Corporate firewalls/routers, especially any doing any sort of inspection on your streams? Can you try from another OS, or different kind of connection (local to the instance, or what not)?

My intention here - if this is indeed a problem with Terraform and the provisioner, and given that you are seeing odd characters come through the console before the hang, I'm wondering if there are factors that are affecting or interrupting the SSH stream in any sort of way. Eliminating these factors will go a long way in determining what the problem is and will help us work to fix it.

**Comment by shanep2300** [comment] 2018-02-08 18:09
Installing the packages by adding the repository to the yum configuration worked.

```hcl
provisioner "file" {
		content = <<EOF
[grafana]
name=grafana
baseurl=https://packagecloud.io/grafana/stable/el/6/$basearch
repo_gpgcheck=1
enabled=1
gpgcheck=1
gpgkey=https://packagecloud.io/gpg.key https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
EOF

		destination = "~/grafana_repo"
	}

	// Executes commands on the box
	provisioner "remote-exec" {
		inline = [
			"cat grafana_repo | sudo tee /etc/yum.repos.d/grafana.repo",
                        "sudo yum install -y grafana"
		]
	}
```

Installing with an RPM package from a file doesn't work.

> Can you try a different package payload here? Maybe add another package to your yum install.

I've tried installing Influx and Grafana on two different modules. Both being installed by the RPM package from a file and both hanging at the same spot, also adding the letter 'B'.

> I'm assuming this is repeatable? Like it can be reliably reproduced?

Yes. I had another colleague try it on his local machine and with his scripts and ended up getting the same result.

> What OS/connection scheme are you trying this from, ie: is there a VPN involved? Corporate firewalls/routers, especially any doing any sort of inspection on your streams? Can you try from another OS, or different kind of connection (local to the instance, or what not)?

- Windows 10/7, no VPN involved.
- Corporate firewalls/routers should be allowing AWS connections.
- I don't have access to another OS.

**Comment by bflad** [comment] 2018-06-21 17:34
Hi @shanep2300 👋  Thanks for reporting this and sorry for the unexpected behavior with Terraform here. The `remote-exec` bits within Terraform are actually handled upstream in https://github.com/hashicorp/terraform/ so any code fixes will need to occur there. Specifically, this recently active upstream issue relating to Windows terminal escaping sequences seems to be very similar and likely related: https://github.com/hashicorp/terraform/issues/18113

The information you have in this issue here is awesome and will likely help that team. Thanks for being very thorough! While I'm going to close this issue here since it doesn't appear there is anything to be done in the AWS provider itself (again the `remote-exec` bits are separate even within an AWS instance resource), I will definitely cross-reference this issue upstream. I'd recommend following that one for additional updates. 👍 

If I made a mistake here, please do let me know. Thanks!

**Closed by bflad** 2018-06-21 17:34 UTC
Labels: bug, service/ec2, upstream-terraform
