### ISSUE TITLE
add ipv6_ip address to aws_network_interface

### ISSUE THREAD

**Issue by certnew** [terraform-providers/terraform-provider-aws#1707] opened 2017-09-20 11:57 UTC
Hi there,

Please add ipv6_ip address to aws_network_interface
http://docs.aws.amazon.com/cli/latest/reference/ec2/create-network-interface.html

Thank you.

**Comment by certnew** [comment] 2017-10-09 14:52
Need this please.

**Comment by ColinHebert** [comment] 2018-04-15 03:29
Duplicate of #1060

**Comment by benrobinsonsonos** [comment] 2018-05-03 22:48
The aws_network_interface data source supports IPv6, the aws_network_interface resource does not.

Currently working around by creating the aws_network_interface with Terraform, manually assigning a IPv6 address in the console or cli, then using the aws_network_interface data source back in Terraform to reference the IPv6 address for things such as R53 records.

resource "aws_network_interface" "eni1" {
  subnet_id = "subnet-123456"
  security_groups = ["sg-123456"]
  attachment {
    instance = "${aws_instance.instance.id}"
    device_index = 1
  }
}

data "aws_network_interface" "eni1" {
  id = "${aws_network_interface.eni1.id}"
}

resource "aws_route53_record" "www" {
  zone_id = "Z1234565678"
  name = "www"
  type = "AAAA"
  ttl = "60"
  multivalue_answer_routing_policy = true
  set_identifier = "asa1a"
  records = ["${data.aws_network_interface.eni1.ipv6_addresses}"]
  health_check_id = "${aws_route53_health_check.instance.id}"
}

**Comment by foxx** [comment] 2018-07-31 14:43
Any idea when support for this will be added? Kinda crucial feature for adopting IPv6 in AWS.

**Comment by tellnes** [comment] 2020-07-21 11:57
Commenting to keep this open. Last time I checked this was still missing.

**Comment by inkblot** [comment] 2020-10-06 02:10
I would also like to see this fixed

**Closed** 2020-10-16 20:09 UTC
Labels: enhancement, service/ec2

**Comment by bflad** [comment] 2020-10-16 20:12
Support for new `ipv6_addresses` and `ipv6_address_count` arguments in the `aws_network_interface` resource has been merged and will release with version 3.12.0 of the Terraform AWS Provider, next week. Thanks to @DrFaust92 for the implementation. 👍
