### ISSUE TITLE
aws_iam_policy_document not updated if reference to aws_iam_role.name changes

### ISSUE THREAD

**Issue by albuch** [terraform-providers/terraform-provider-aws#6691] opened 2018-12-03 14:32 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

+ Terraform v0.11.10
   + provider.aws v1.22.0

### Affected Resource(s)

* aws_iam_policy_document 
* aws_iam_group_policy
* aws_iam_role

### Terraform Configuration Files

* Default provider is Master Account of an AWS Organisation
* Provider `aws.iam` is Member account of the AWS Organisation

```hcl
data "aws_iam_policy_document" "iam_account_assume_role_policy" {
  statement {
    effect = "Allow"

    actions = [
      "sts:AssumeRole",
    ]

    principals {
      identifiers = ["arn:aws:iam::11111111111:root"]
      type        = "AWS"
    }
  }
}

resource "aws_iam_group" "master_account_billing_admins" {
  name = "MasterAccountBillingAdministrators"
  path = "/"

  provider = "aws.iam"
}

resource "aws_iam_role" "iam_to_master_billing_admin" {
  name = "IAMUserBillingAccessRole"
  
  assume_role_policy = "${data.aws_iam_policy_document.iam_account_assume_role_policy.json}"
}

data "aws_iam_policy_document" "master_account_billing_admin" {
  "statement" {
    effect = "Allow"

    actions = [...]

    resources = ["*"]
  }
}

resource "aws_iam_role_policy" "master_billing_admin" {
  policy = "${data.aws_iam_policy_document.master_account_billing_admin.json}"
  role = "${aws_iam_role.iam_to_master_billing_admin.name}"
}

data "aws_iam_policy_document" "master_account_billing_admin_assume_role" {
  "statement" {
    effect    = "Allow"
    actions   = ["sts:AssumeRole"]
    resources = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${aws_iam_role.iam_to_master_billing_admin.name}"]
  }
}

resource "aws_iam_group_policy" "billing_admin_group_policy" {
  name  = "AllowToAssumeMasterAccountBillingAdministratorRole"
  group = "${aws_iam_group.master_account_billing_admins.id}"

  provider = "aws.iam"

  policy = "${data.aws_iam_policy_document.master_account_billing_admin_assume_role.json}"
}
```

### Expected Behavior

When changing the name attribute of  `aws_iam_role.am_to_master_billing_admin` Terraform 

* creates new role with new name for `aws_iam_role.am_to_master_billing_admin`
* creates new role policy for `aws_iam_role_policy.master_billing_admin`
* updates `aws_iam_group_policy.billing_admin_group_policy` with the changed role name

### Actual Behavior

When changing the name attribute of  `aws_iam_role.am_to_master_billing_admin` only `aws_iam_role.am_to_master_billing_admin` (and the attached policy) are changend. 

The aws_iam_group_policy that references the name attribute via its `aws_iam_policy_document` is not changed. Only when calling `terraform apply` a second time it is changed

```
Terraform will perform the following actions:

-/+ aws_iam_role.iam_to_master_billing_admin (new resource required)
      id:                    "IAMUserBillingAccessRole" => <computed> (forces new resource)
      arn:                   "arn:aws:iam::00000000000:role/IAMUserBillingAccessRole" => <computed>
      assume_role_policy:    "..." => "...."
      create_date:           "2018-12-03T12:48:11Z" => <computed>
      force_detach_policies: "false" => "false"
      max_session_duration:  "3600" => "3600"
      name:                  "IAMUserBillingAccessRole" => "BillingAdministratorRole" (forces new resource)
      path:                  "/" => "/"
      unique_id:             "AROAJSMYAP2MMNAWZNYAQ" => <computed>

-/+ aws_iam_role_policy.master_billing_admin (new resource required)
      id:                    "IAMUserBillingAccessRole:terraform-20181203124812214200000001" => <computed> (forces new resource)
      name:                  "terraform-20181203124812214200000001" => <computed>
      policy:                "..." => "..."
      role:                  "IAMUserBillingAccessRole" => "BillingAdministratorRole" (forces new resource)


Plan: 2 to add, 0 to change, 2 to destroy.
```

I did try to make Terraform aware of the needed change by adding `depends_on = ["aws_iam_role.iam_to_master_billing_reader"]` to `aws_iam_policy_document.master_account_billing_admin_assume_role`. That resulted in the correct behaviour for the first run, but every subsequent run - even without any changes - resulted in the group_policy being identified to need to be updated (though no change was applied).

```
Terraform will perform the following actions:

 <= data.aws_iam_policy_document.master_account_billing_admin_assume_role
      id:                               <computed>
      json:                             <computed>
      statement.#:                      "1"
      statement.0.actions.#:            "1"
      statement.0.actions.2528466339:   "sts:AssumeRole"
      statement.0.effect:               "Allow"
      statement.0.resources.#:          "1"
      statement.0.resources.4240822228: "arn:aws:iam::00000000000:role/IAMUserBillingAccessRole"

  ~ aws_iam_group_policy.billing_admin_group_policy
      policy:                           "...." => "${data.aws_iam_policy_document.master_account_billing_admin_assume_role.json}"


Plan: 0 to add, 1 to change, 0 to destroy.

data.aws_iam_policy_document.master_account_billing_admin_assume_role: Refreshing state...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

* The two accounts are part of an AWS organization

**Comment by bflad** [comment] 2019-11-13 21:59
Hi @albuch 👋 Thank you for submitting this and sorry you ran into trouble.

Using the latest versions of the Terraform CLI (0.12.13) and Terraform AWS Provider (2.35.0), I was not able to reproduce this with the below self-contained configuration (and AWS profiles pointing at two accounts):

```hcl
terraform {
  required_providers {
    aws = "2.35.0"
  }
  required_version = "0.12.13"
}

provider "aws" {
  profile = "tf-acc"
  region  = "us-east-1"
}

provider "aws" {
  alias   = "alternate"
  profile = "tf-acc-alt"
  region  = "us-east-1"
}

data "aws_caller_identity" "current" {}

data "aws_iam_policy_document" "iam_account_assume_role_policy" {
  statement {
    effect = "Allow"

    actions = [
      "sts:AssumeRole",
    ]

    principals {
      identifiers = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"]
      type        = "AWS"
    }
  }
}

resource "aws_iam_group" "master_account_billing_admins" {
  provider = "aws.alternate"

  name = "MasterAccountBillingAdministrators"
  path = "/"
}

resource "aws_iam_role" "iam_to_master_billing_admin" {
  name = "IAMUserBillingAccessRole1"

  assume_role_policy = "${data.aws_iam_policy_document.iam_account_assume_role_policy.json}"
}

data "aws_iam_policy_document" "master_account_billing_admin" {
  statement {
    effect    = "Allow"
    actions   = ["*"]
    resources = ["*"]
  }
}

resource "aws_iam_role_policy" "master_billing_admin" {
  policy = "${data.aws_iam_policy_document.master_account_billing_admin.json}"
  role   = "${aws_iam_role.iam_to_master_billing_admin.name}"
}

data "aws_iam_policy_document" "master_account_billing_admin_assume_role" {
  statement {
    effect    = "Allow"
    actions   = ["sts:AssumeRole"]
    resources = ["arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${aws_iam_role.iam_to_master_billing_admin.name}"]
  }
}

resource "aws_iam_group_policy" "billing_admin_group_policy" {
  provider = "aws.alternate"

  name   = "AllowToAssumeMasterAccountBillingAdministratorRole"
  group  = "${aws_iam_group.master_account_billing_admins.id}"
  policy = "${data.aws_iam_policy_document.master_account_billing_admin_assume_role.json}"
}
```

Updating the configuration with:

```hcl
resource "aws_iam_role" "iam_to_master_billing_admin" {
  name = "IAMUserBillingAccessRole2"

  assume_role_policy = "${data.aws_iam_policy_document.iam_account_assume_role_policy.json}"
}
```

Results in the correct Terraform actions without needing a second apply:

```console
$ terraform apply
aws_iam_group.master_account_billing_admins: Refreshing state... [id=MasterAccountBillingAdministrators]
data.aws_caller_identity.current: Refreshing state...
data.aws_iam_policy_document.master_account_billing_admin: Refreshing state...
data.aws_iam_policy_document.iam_account_assume_role_policy: Refreshing state...
aws_iam_role.iam_to_master_billing_admin: Refreshing state... [id=IAMUserBillingAccessRole1]
aws_iam_role_policy.master_billing_admin: Refreshing state... [id=IAMUserBillingAccessRole1:terraform-20191113215240043700000001]
data.aws_iam_policy_document.master_account_billing_admin_assume_role: Refreshing state...
aws_iam_group_policy.billing_admin_group_policy: Refreshing state... [id=MasterAccountBillingAdministrators:AllowToAssumeMasterAccountBillingAdministratorRole]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement
 <= read (data resources)

Terraform will perform the following actions:

  # data.aws_iam_policy_document.master_account_billing_admin_assume_role will be read during apply
  # (config refers to values not yet known)
 <= data "aws_iam_policy_document" "master_account_billing_admin_assume_role"  {
      + id   = (known after apply)
      + json = (known after apply)

      + statement {
          + actions   = [
              + "sts:AssumeRole",
            ]
          + effect    = "Allow"
          + resources = [
              + "arn:aws:iam::--OMITTED--:role/IAMUserBillingAccessRole2",
            ]
        }
    }

  # aws_iam_group_policy.billing_admin_group_policy will be updated in-place
  ~ resource "aws_iam_group_policy" "billing_admin_group_policy" {
        group  = "MasterAccountBillingAdministrators"
        id     = "MasterAccountBillingAdministrators:AllowToAssumeMasterAccountBillingAdministratorRole"
        name   = "AllowToAssumeMasterAccountBillingAdministratorRole"
      ~ policy = jsonencode(
            {
              - Statement = [
                  - {
                      - Action   = "sts:AssumeRole"
                      - Effect   = "Allow"
                      - Resource = "arn:aws:iam::--OMITTED--:role/IAMUserBillingAccessRole1"
                      - Sid      = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
    }

  # aws_iam_role.iam_to_master_billing_admin must be replaced
-/+ resource "aws_iam_role" "iam_to_master_billing_admin" {
      ~ arn                   = "arn:aws:iam::--OMITTED--:role/IAMUserBillingAccessRole1" -> (known after apply)
      ~ assume_role_policy    = jsonencode( # whitespace changes
            {
                Statement = [
                    {
                        Action    = "sts:AssumeRole"
                        Effect    = "Allow"
                        Principal = {
                            AWS = "arn:aws:iam::--OMITTED--:root"
                        }
                        Sid       = ""
                    },
                ]
                Version   = "2012-10-17"
            }
        )
      ~ create_date           = "2019-11-13T21:52:39Z" -> (known after apply)
        force_detach_policies = false
      ~ id                    = "IAMUserBillingAccessRole1" -> (known after apply)
        max_session_duration  = 3600
      ~ name                  = "IAMUserBillingAccessRole1" -> "IAMUserBillingAccessRole2" # forces replacement
        path                  = "/"
      - tags                  = {} -> null
      ~ unique_id             = "AROASXIXB4ZJXG3HULDJQ" -> (known after apply)
    }

  # aws_iam_role_policy.master_billing_admin must be replaced
-/+ resource "aws_iam_role_policy" "master_billing_admin" {
      ~ id     = "IAMUserBillingAccessRole1:terraform-20191113215240043700000001" -> (known after apply)
      ~ name   = "terraform-20191113215240043700000001" -> (known after apply)
        policy = jsonencode(
            {
                Statement = [
                    {
                        Action   = "*"
                        Effect   = "Allow"
                        Resource = "*"
                        Sid      = ""
                    },
                ]
                Version   = "2012-10-17"
            }
        )
      ~ role   = "IAMUserBillingAccessRole1" -> "IAMUserBillingAccessRole2" # forces replacement
    }

Plan: 2 to add, 1 to change, 2 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_iam_role_policy.master_billing_admin: Destroying... [id=IAMUserBillingAccessRole1:terraform-20191113215240043700000001]
aws_iam_role_policy.master_billing_admin: Destruction complete after 0s
aws_iam_role.iam_to_master_billing_admin: Destroying... [id=IAMUserBillingAccessRole1]
aws_iam_role.iam_to_master_billing_admin: Destruction complete after 1s
aws_iam_role.iam_to_master_billing_admin: Creating...
aws_iam_role.iam_to_master_billing_admin: Creation complete after 0s [id=IAMUserBillingAccessRole2]
data.aws_iam_policy_document.master_account_billing_admin_assume_role: Refreshing state...
aws_iam_role_policy.master_billing_admin: Creating...
aws_iam_group_policy.billing_admin_group_policy: Modifying... [id=MasterAccountBillingAdministrators:AllowToAssumeMasterAccountBillingAdministratorRole]
aws_iam_group_policy.billing_admin_group_policy: Modifications complete after 1s [id=MasterAccountBillingAdministrators:AllowToAssumeMasterAccountBillingAdministratorRole]
aws_iam_role_policy.master_billing_admin: Creation complete after 2s [id=IAMUserBillingAccessRole2:terraform-20191113215353391200000001]

Apply complete! Resources: 2 added, 1 changed, 2 destroyed.

$ terraform apply
aws_iam_group.master_account_billing_admins: Refreshing state... [id=MasterAccountBillingAdministrators]
data.aws_caller_identity.current: Refreshing state...
data.aws_iam_policy_document.master_account_billing_admin: Refreshing state...
data.aws_iam_policy_document.iam_account_assume_role_policy: Refreshing state...
aws_iam_role.iam_to_master_billing_admin: Refreshing state... [id=IAMUserBillingAccessRole2]
aws_iam_role_policy.master_billing_admin: Refreshing state... [id=IAMUserBillingAccessRole2:terraform-20191113215353391200000001]
data.aws_iam_policy_document.master_account_billing_admin_assume_role: Refreshing state...
aws_iam_group_policy.billing_admin_group_policy: Refreshing state... [id=MasterAccountBillingAdministrators:AllowToAssumeMasterAccountBillingAdministratorRole]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

This likely was resolved by a Terraform CLI update at some point since that code controls the configuration conversion to proper resource and data source ordering. 👍

**Closed by bflad** 2019-11-13 21:59 UTC
Labels: needs-triage, service/iam, upstream-terraform
