### ISSUE TITLE
Cannot import Global Accelerator resource when AWS region is us-east-1

### ISSUE THREAD

**Issue by ocharles** [terraform-providers/terraform-provider-aws#7848] opened 2019-03-07 12:22 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v0.11.8
+ provider.aws v2.0.0
+ provider.heroku v1.8.0
+ provider.packet v1.4.1

Your version of Terraform is out of date! The latest version
is 0.11.11. You can update by downloading from www.terraform.io/downloads.html
```

### Affected Resource(s)

* aws_globalaccelerator_accelerator

### Debug Output

```
aws_globalaccelerator_accelerator.vpn-accelerator: Importing from ID "arn:aws:globalaccelerator::XXX:accelerator/XXX"...
2019/03/07 12:13:52 [TRACE] vertex 'root.aws_instance.api': walking
2019/03/07 12:13:52 [TRACE] vertex 'root.aws_globalaccelerator_accelerator.vpn-accelerator': walking
2019/03/07 12:13:52 [TRACE] [walkImport] Exiting eval tree: aws_globalaccelerator_accelerator.vpn-accelerator (import id: arn:aws:globalaccelerator::XXX:accelerator/XXX)
2019/03/07 12:13:52 [TRACE] vertex 'root.aws_globalaccelerator_accelerator.vpn-accelerator (import id: arn:aws:globalaccelerator::XXX:accelerator/XXX)': expanding/walking dynamic subgraph
2019/03/07 12:13:52 [TRACE] dag/walk: added new vertex: "import aws_globalaccelerator_accelerator.vpn-accelerator result: arn:aws:globalaccelerator::XXX:accelerator/XXX"
aws_globalaccelerator_accelerator.vpn-accelerator: Import complete!
2019/03/07 12:13:52 [TRACE] dag/walk: walking "import aws_globalaccelerator_accelerator.vpn-accelerator result: arn:aws:globalaccelerator::XXX:accelerator/XXX"
2019/03/07 12:13:52 [TRACE] vertex 'root.import aws_globalaccelerator_accelerator.vpn-accelerator result: arn:aws:globalaccelerator::XXX:accelerator/XXX': walking
2019/03/07 12:13:52 [TRACE] vertex 'root.import aws_globalaccelerator_accelerator.vpn-accelerator result: arn:aws:globalaccelerator::XXX:accelerator/XXX': evaluating
2019/03/07 12:13:52 [TRACE] [walkImport] Entering eval tree: import aws_globalaccelerator_accelerator.vpn-accelerator result: arn:aws:globalaccelerator::XXX:accelerator/XXX
2019/03/07 12:13:52 [TRACE] root: eval: *terraform.EvalSequence
2019/03/07 12:13:52 [TRACE] root: eval: *terraform.EvalGetProvider
2019/03/07 12:13:52 [TRACE] root: eval: *terraform.EvalRefresh
  Imported aws_globalaccelerator_accelerator (ID: arn:aws:globalaccelerator::XXX:accelerator/XXX)
aws_globalaccelerator_accelerator.vpn-accelerator: Refreshing state... (ID: arn:aws:globalaccelerator::XXX...r/XXX)
2019-03-07T12:13:52.991Z [DEBUG] plugin.terraform-provider-aws_v2.0.0_x4: 2019/03/07 12:13:52 [DEBUG] [aws-sdk-go] DEBUG: Request Global Accelerator/DescribeAccelerator Details:
2019-03-07T12:13:52.991Z [DEBUG] plugin.terraform-provider-aws_v2.0.0_x4: ---[ REQUEST POST-SIGN ]-----------------------------
2019-03-07T12:13:52.991Z [DEBUG] plugin.terraform-provider-aws_v2.0.0_x4: POST / HTTP/1.1
2019-03-07T12:13:52.991Z [DEBUG] plugin.terraform-provider-aws_v2.0.0_x4: Host: globalaccelerator.us-east-1.amazonaws.com
2019-03-07T12:13:52.991Z [DEBUG] plugin.terraform-provider-aws_v2.0.0_x4: User-Agent: aws-sdk-go/1.17.0 (go1.11.5; linux; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.11.9-beta1
2019-03-07T12:13:52.991Z [DEBUG] plugin.terraform-provider-aws_v2.0.0_x4: Content-Length: 109
2019-03-07T12:13:52.991Z [DEBUG] plugin.terraform-provider-aws_v2.0.0_x4: Authorization: AWS4-HMAC-SHA256 Credential=XXX/20190307/us-east-1/globalaccelerator/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date;x-amz-target, Signature=XXX
2019-03-07T12:13:52.991Z [DEBUG] plugin.terraform-provider-aws_v2.0.0_x4: Content-Type: application/x-amz-json-1.1
2019-03-07T12:13:52.991Z [DEBUG] plugin.terraform-provider-aws_v2.0.0_x4: X-Amz-Date: 20190307T121352Z
2019-03-07T12:13:52.991Z [DEBUG] plugin.terraform-provider-aws_v2.0.0_x4: X-Amz-Target: GlobalAccelerator_V20180706.DescribeAccelerator
2019-03-07T12:13:52.991Z [DEBUG] plugin.terraform-provider-aws_v2.0.0_x4: Accept-Encoding: gzip
2019-03-07T12:13:52.991Z [DEBUG] plugin.terraform-provider-aws_v2.0.0_x4: 
2019-03-07T12:13:52.991Z [DEBUG] plugin.terraform-provider-aws_v2.0.0_x4: -----------------------------------------------------
2019-03-07T12:13:53.016Z [DEBUG] plugin.terraform-provider-aws_v2.0.0_x4: 2019/03/07 12:13:53 [DEBUG] [aws-sdk-go] DEBUG: Send Request Global Accelerator/DescribeAccelerator failed, will retry, error RequestError: send request failed
2019-03-07T12:13:53.016Z [DEBUG] plugin.terraform-provider-aws_v2.0.0_x4: caused by: Post https://globalaccelerator.us-east-1.amazonaws.com/: dial tcp: lookup globalaccelerator.us-east-1.amazonaws.com on 127.0.0.1:53: no such host
2019/03/07 12:13:53 [ERROR] root: eval: *terraform.EvalRefresh, err: aws_globalaccelerator_accelerator.vpn-accelerator: Error reading Global Accelerator accelerator: RequestError: send request failed
caused by: Post https://globalaccelerator.us-east-1.amazonaws.com/: dial tcp: lookup globalaccelerator.us-east-1.amazonaws.com on 127.0.0.1:53: no such host
2019/03/07 12:13:53 [ERROR] root: eval: *terraform.EvalSequence, err: aws_globalaccelerator_accelerator.vpn-accelerator: Error reading Global Accelerator accelerator: RequestError: send request failed
caused by: Post https://globalaccelerator.us-east-1.amazonaws.com/: dial tcp: lookup globalaccelerator.us-east-1.amazonaws.com on 127.0.0.1:53: no such host
2019/03/07 12:13:53 [TRACE] [walkImport] Exiting eval tree: import aws_globalaccelerator_accelerator.vpn-accelerator result: arn:aws:globalaccelerator::XXX:accelerator/XXX
2019/03/07 12:13:53 [TRACE] dag/walk: upstream errored, not walking "provider.aws (close)"
```

### Expected Behavior

The existing Global Accelerator is imported.

### Actual Behavior

The importing failed as it tried to query a host that doesn't resolve (globalaccelerator.us-east-1.amazonaws.com).

### Steps to Reproduce

1. `terraform import aws_globalaccelerator_accelerator.vpn-accelerator arn:aws:globalaccelerator::XXX:accelerator/XXX` with a `aws` `provider` with `region = "us-east-1"`.

### Important Factoids

My region is set to `us-east-1`. I'm not sure the Global Accelerator is available there, but I don't know how to tell Terraform to query `us-west-1`.

**Comment by alex1x** [comment] 2019-04-17 16:21
The GAs are available in us-west-2.

Try:

```
provider "aws" {
    alias = "us-west-2"
    region = "us-west-2"
}

resource "aws_globalaccelerator_accelerator" "vpn-accelerator" {
  provider = "aws.us-west-2"
```

If that doesn't work, try also setting `export AWS_REGION=us-west-2` before importing.

**Comment by ocharles** [comment] 2019-04-17 16:23
Thanks @alex1x. I ended up adding a new aliased AWS provider for just this and it does work - thanks! But I still think this error could be improved - rather than trying to hit a missing endpoint it would be better to tell me this isn't supported.

**Comment by ryndaniels** [comment] 2019-12-12 14:00
Hi @ocharles - Thanks for taking the time to submit this issue. I had a look at this with the most recent versions of Terraform and the AWS Provider and was unable to reproduce this behavior. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md). 🙂

**Closed by ryndaniels** 2019-12-12 14:00 UTC
Labels: needs-triage, service/globalaccelerator
