### ISSUE TITLE
Changing read/write capacity of DynamoDB GSI shouldn't re-create the index

### ISSUE THREAD

**Issue by adamgotterer** [terraform-providers/terraform-provider-aws#2976] opened 2018-01-12 21:13 UTC
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, 
v0.11.1

### Affected Resource(s)
- provider.aws v1.7.0

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "aws_dynamodb_table" "example" {
  name = "example"
  hash_key = "query_string"
  range_key = "received_at"
  write_capacity = 200
  read_capacity = 200

  attribute {
    name = "query_string"
    type = "S"
  }

  attribute {
    name = "received_at"
    type = "N"
  }

  global_secondary_index {
    name = "received_at-index"
    hash_key = "received_at"
    projection_type = "ALL"
    write_capacity = 200
    read_capacity = 100
  }
}
```

### Debug Output
```

Terraform will perform the following actions:

  ~ aws_dynamodb_table.frontdoor
      global_secondary_index.3681192762.hash_key:             "" => "received_at"
      global_secondary_index.3681192762.name:                 "" => "received_at-indexs"
      global_secondary_index.3681192762.non_key_attributes.#: "0" => "0"
      global_secondary_index.3681192762.projection_type:      "" => "ALL"
      global_secondary_index.3681192762.range_key:            "" => ""
      global_secondary_index.3681192762.read_capacity:        "" => "100"
      global_secondary_index.3681192762.write_capacity:       "" => "200"
      global_secondary_index.3718184017.hash_key:             "received_at" => ""
      global_secondary_index.3718184017.name:                 "received_at-index" => ""
      global_secondary_index.3718184017.non_key_attributes.#: "0" => "0"
      global_secondary_index.3718184017.projection_type:      "ALL" => ""
      global_secondary_index.3718184017.range_key:            "" => ""
      global_secondary_index.3718184017.read_capacity:        "1" => "0"
      global_secondary_index.3718184017.write_capacity:       "10000" => "0"


Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behavior
The read and write capacity of DynamoDB GSI indexes can be modified. I expected the index to be updated.

### Actual Behavior
Terraform wants to remove the original index and re-create it. This is an expensive operation for large indexes.

**Comment by bflad** [comment] 2018-01-17 23:15
@adamgotterer have you confirmed that Terraform is actually deleting and recreating the GSI in this case? The underlying code should be written to only update read/write capacities in this situation. The plan output might look confusing as the read/write capacities are part of naming hash (`3681192762` and `3718184017` in your output) so Terraform shows the "entire" GSI as changing, when really its just the capacities updating as expected. Admittedly, it is a little confusing/scary to look at first and not great user experience.

If you can confirm its the right behavior but confusing plan output, we might want to update this ticket to migrate the GSI naming hash to not include extraneous items like read/write capacity.

**Comment by radeksimko** [comment] 2018-01-25 17:53
In addition to what @bflad mentioned I'd also say that in this case it's _actually_ desired to recreate the index since you're changing its name from `received_at-index` to `received_at-indexs`, not just changing the capacity.

I'm going to close this issue as I believe the resource works as intended, but feel free to raise a new one if you observe misbehaviour or a bug, ideally with a repro case.

Thanks.

Related: https://github.com/terraform-providers/terraform-provider-aws/issues/2071#issuecomment-360544945

**Closed by radeksimko** 2018-01-25 17:53 UTC
Labels: question, service/dynamodb, waiting-response
