### ISSUE TITLE
elasticsearch_domain_policy has perpetual diff

### ISSUE THREAD

**Issue by Gufran** [terraform-providers/terraform-provider-aws#2961] opened 2018-01-12 14:05 UTC
### Terraform Version

Terraform v0.11.1
+ provider.aws v1.6.0

### Affected Resource(s)
- elasticsearch_domain_policy

### Terraform Configuration Files

```hcl
# Assuming that an ElasticSearch domain is available
# on resource aws_elasticsearch_domain.elastic_search

data "aws_iam_policy_document" "access_policy" {
  statement {
    effect = "Allow"
    principals {
      identifiers = ["AWS"]
      type        = "*"
    }
    actions = ["es:*"]
    resources = ["${aws_elasticsearch_domain.elastic_search.arn}/*"]
  }
}

resource "aws_elasticsearch_domain_policy" "access_policy" {
  domain_name     = "${aws_elasticsearch_domain.elastic_search.domain_name}"
  access_policies = "${data.aws_iam_policy_document.access_policy.json}"
}
```

### Debug Output
NA

### Panic Output
NA

### Expected Behavior
Subsequent applies after first successful apply should result in no diff.

### Actual Behavior
Every apply results in a diff similar to following:
(newlines added by me to visually separate current and expected state)
```
aws_elasticsearch_domain_policy.access_policy
access_policies:
"{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Allow\",\"Principal\":\"*\",\"Action\":\"es:*\",\"Resource\":\"arn:aws:es:us-east-1:0987654321:domain/elastic-search/*\"}]}"
=>
 "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"\",\n      \"Effect\": \"Allow\",\n      \"Action\": \"es:*\",\n      \"Resource\": \"arn:aws:es:us-east-1:0987654321:domain/elastic-search/*\",\n      \"Principal\": {\n        \"*\": \"AWS\"\n      }\n    }\n  ]\n}"
```

As can be seen, the only difference between actual state and what terraform think should exist is whitespaces and newline literals (`'\n'`).
It is a problem because 

1. It is not actually a diff. It is confusing (startling?) and pollutes the output in automation tools.
2. Any change in AWS ElasticSearch service, doesn't matter how small, takes about 20 minutes to go through. That makes every terraform run at least that much longer no matter how small a change there is to make.

A workaround is to set lifecycle rule `ignore_changes` for ES domain access policies but that comes with its own problems. It has to be documented on a bright red banner in bold 72 pt font, drilled into every team member's head and will require unnecessary, manual changes in terraform configuration if anyone want to change it.

I believe it happens because the data source `aws_iam_policy_document` marshals the document with indentation (code: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_iam_policy_document.go#L151-L155).
Only possible solution that I can think of is to enforce same marshalling behaviour across all resources and data providers.

If anybody can suggest a better solution, which does not involve scrutiny of entire codebase, I am willing to work on it.

### Steps to Reproduce

1. `terraform apply`
1. `terraform plan`
1. `terraform apply`
1. `terraform plan`

**Comment by Puneeth-n** [comment] 2018-01-12 14:18
duplicate #576 

@Gufran It's a legacy issue. check https://github.com/terraform-providers/terraform-provider-aws/issues/576#issuecomment-352236494 for a way to get around this issue.

**Comment by bflad** [comment] 2018-01-23 13:29
Hi @Gufran, thanks for this bug report and as @Puneeth-n mentioned, this issue is indeed a duplicate of an old one: #576. In order to consolidate our efforts, I'm going to close this one in preference of the earlier existing issue.

**Closed by bflad** 2018-01-23 13:29 UTC
Labels: bug, service/elasticsearch
