### ISSUE TITLE
aws_elasticsearch_domain don't delete before create ? 

### ISSUE THREAD

**Issue by gocho1** [terraform-providers/terraform-provider-aws#9161] opened 2019-06-27 09:20 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.14

### Affected Resource(s)
aws_elasticsearch_domain

### Terraform Configuration Files
```hcl
resource "aws_elasticsearch_domain" "elasticsearch" {
  domain_name           = "domain"
  elasticsearch_version = "6.5"

  cluster_config {
    instance_type            = "t2.medium.elasticsearch"
    instance_count           = "4"
    dedicated_master_enabled = "false"
    dedicated_master_type    = "0"
    dedicated_master_count   = "0"
    zone_awareness_enabled   = "true"
  }

  vpc_options {
    subnet_ids         = ["${var.subnet_ids}"]
    security_group_ids = ["${aws_security_group.elasticsearch_sg.id}"]
  }

  ebs_options {
    ebs_enabled = "true"
    volume_type = "gp2"
    volume_size = "35"
    iops        = "0"
  }

  encrypt_at_rest {
    enabled = "true"
    kms_key_id = "kms_key_arn"
  }

  node_to_node_encryption {
    enabled = "true"
  }

  snapshot_options {
    automated_snapshot_start_hour = "3"
  }

  advanced_options {
    "rest.action.multi.allow_explicit_index" = "true"
  }

  log_publishing_options {
    cloudwatch_log_group_arn = "${aws_cloudwatch_log_group.cloudwatch_log_group.arn}"
    log_type                 = "ES_APPLICATION_LOGS"
  }

  access_policies = <<CONFIG
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "es:*",
      "Resource": "arn:aws:es:${aws_region}:${account_id}:domain/${domain_name}/*"
    }
  ]
}
CONFIG

  tags {
    Env            = "dev"
    Name           = "data"
    Project        = "data"
    Component      = "elk"
    CreationMethod = "terraform"
    TeamName       = "name"
    Owner          = "owner"
  }
}
```

### Expected Behavior

I firstly created an elasticsearch cluster without 
```hcl
encrypt_at_rest {
    enabled = "true"
    kms_key_id = "kms_key_arn"
  }

  node_to_node_encryption {
    enabled = "true"
  }
```
Then I wanted to add these settings and rerun my terraform.
As expected, the plan indicated that a new resource is needed (I just let what whas indicated as forcing a new resource, the rest is unchanged)
```yaml
-/+ module.elk_stack.aws_elasticsearch_domain.elasticsearch (new resource required)
      id:                                                         "arn" => <computed> (forces new resource)
      encrypt_at_rest.0.enabled:                                  "false" => "true" (forces new resource)
      encrypt_at_rest.0.kms_key_id:                               "" => "key_arn" (forces new resource)
      node_to_node_encryption.#:                                  "1" => "1"
      node_to_node_encryption.0.enabled:                          "false" => "true" (forces new resource)
```
So I expected terraform to first delete the resource then recreate it with the right parameters.

### Actual Behavior
When I applied, terraform directly tried to create a new resource without destroying the first
and ended up with 
```bash
Error: Error applying plan:

1 error occurred:
	* module.elk_stack.aws_elasticsearch_domain.elasticsearch: 1 error occurred:
	* aws_elasticsearch_domain.elasticsearch: ElasticSearch domain data-elk already exists

```

### Steps to Reproduce

1. `terraform apply` with a resource without "encrypt_at_rest" and "node_to_node_encryption" arguments.
2. Add those 2 arguments
3. `terraform plan`
4. `terraform apply`

**Comment by ryndaniels** [comment] 2019-11-28 14:30
Hi @gocho1 - thanks for taking the time to submit this issue. I had a look at this with the most recent versions of Terraform and the AWS Provider and was unable to reproduce this behavior. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md). 🙂

**Closed by ryndaniels** 2019-11-28 14:30 UTC
Labels: needs-triage, service/elasticsearch
