### ISSUE TITLE
aws_default_vpc errors first time "terraform apply", then succeeds second time

### ISSUE THREAD

**Issue by sea001** [terraform-providers/terraform-provider-aws#1250] opened 2017-07-26 20:23 UTC
### Terraform Version
0.9.11 and 0.10.0

### Affected Resource(s)
aws_default_vpc.default

### Terraform Configuration Files

```hcl
variable "aws_profile" {
    default = "default"
}
variable "aws_region" {
    default = "us-east-1"
}
provider "aws" {
    profile = "${var.aws_profile}"
    region  = "${var.aws_region}"
}

resource "aws_default_vpc" "default" {
    tags {
        Name = "Default VPC"
    }
}

resource "aws_flow_log" "vpcflow" {
  log_group_name = "${aws_cloudwatch_log_group.vpcflow_loggroup.name}"
  iam_role_arn   = "${aws_iam_role.vpcflow_role.arn}"
  vpc_id         = "${aws_default_vpc.default.id}"
  traffic_type   = "ALL"
}

resource "aws_cloudwatch_log_group" "vpcflow_loggroup" {
    name = "vpcflow_loggroup"
    retention_in_days = 30
}

resource "aws_iam_role" "vpcflow_role" {
  name = "vpcflow_role"
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "vpc-flow-logs.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
}

resource "aws_iam_role_policy" "vpcflow_loggroup_policy" {
  name = "vpcflow_loggroup_policy"
  role = "${aws_iam_role.vpcflow_role.id}"
  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents",
        "logs:DescribeLogGroups",
        "logs:DescribeLogStreams"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
EOF
}
```

### Expected Behavior
Default VPC id should have been available the first time.

### Actual Behavior
First run:

* aws_default_vpc.default: 1 error(s) occurred:
* aws_default_vpc.default: UnauthorizedOperation: You are not authorized to perform this operation.
	status code: 403, request id: f6c7fed4-a3e5-475d-a66b-f73d68e5df7e

Default VPC id only available on subsequent runs (no errors).

```
$ diff tfstate.first_run1 tfstate.second_run 
```
```diff
4c4
<     "serial": 0,
---
>     "serial": 1,
19c19,31
<                             "id": "vpc-e723b09e"
---
>                             "cidr_block": "172.31.0.0/16",
>                             "default_network_acl_id": "acl-876c69fe",
>                             "default_route_table_id": "rtb-7cd9ff04",
>                             "default_security_group_id": "sg-2f19655e",
>                             "dhcp_options_id": "dopt-e1e89c87",
>                             "enable_classiclink": "false",
>                             "enable_dns_hostnames": "true",
>                             "enable_dns_support": "true",
>                             "id": "vpc-e723b09e",
>                             "instance_tenancy": "default",
>                             "main_route_table_id": "rtb-7cd9ff04",
>                             "tags.%": "1",
>                             "tags.Name": "Default VPC"
```

### Steps to Reproduce
0. remove terraform.tfstate*
1. `terraform apply`
2. `terraform apply`

**Comment by radeksimko** [comment] 2017-08-04 05:51
Hi @sea001 
I tried reproducing this with no luck. All of the resources in the config (including Default VPC) were created after the 1st time.

That said I looked into the code of the resource and it works more like a data source as it doesn't actually create a default VPC, it just finds the default one, if it already exists and reads all details about it & expose it as attributes.

Because AWS [recently introduced](https://aws.amazon.com/about-aws/whats-new/2017/07/create-a-new-default-vpc-using-aws-console-or-cli/) API calls for creating a default VPC (without having to call support) we can implement this and make it work more like a resource, instead of turning it into a data source.

My second observation, which is more relevant to this issue is that you were able to pull the VPC ID for the first time, which means that you're allowed to call `ec2/DescribeVpcs` apparently.

We use subsequent API calls to get more details about the VPC, which may have failed, namely:

 - `ec2/DescribeVpcAttribute`
 - `ec2/DescribeVpcClassicLink`
 - `ec2/DescribeVpcClassicLinkDnsSupport`
 - `ec2/DescribeRouteTables`
 - `ec2/DescribeNetworkAcls`
 - `ec2/DescribeSecurityGroups`

Is it possible that your IAM user/role that you use to run `apply` is restricted in making any of those API calls via attached polic(y/ies)? 

I'm merely guessing what may be happening here. We may be able to find the root cause more easily and faster if I had the chance to see debug log from the first failed run. Our debug logs contain details about every API call to AWS, so we could find the one which has failed w/ `UnauthorizedOperation`. Do you mind providing me the [debug log](https://www.terraform.io/docs/internals/debugging.html) (minus any secrets)? If you're worried about sharing it publicly you can GPG-encrypt it using [my key](https://keybase.io/radeksimko) and send it to radek@hashicorp.com

**Comment by sea001** [comment] 2017-08-07 22:01
My AWS access has changed again, and now I no longer see the issue.  I agree with your guess, in that I was previously not allowed to make one (or more) of those ec2 API calls.  My bug was that it "failed" the first run, but returned the vpc_id anyway, and then succeeded from then on. You'd think if I still didn't have permissions then it should continue to fail on subsequent runs too.  So it appears that Terraform checks a different set of permissions the first time than it does from then on. Further, it didn't say which access failed the first time.  It just said UnauthorizedOperation.

Your call on whether to close this issue :).  It is no longer on our "critical" path :).

**Comment by radeksimko** [comment] 2017-08-08 05:28
> You'd think if I still didn't have permissions then it should continue to fail on subsequent runs too.

That is what I'd expect too. 

> Further, it didn't say which access failed the first time. It just said UnauthorizedOperation.

That is unfortunately common theme across most error messages coming from the AWS API. We'd have to wrap literally every single API/SDK call with something like `service_name/method_name failed: %s` to get around that, which isn't quite real given the amount of calls we make across the whole AWS provider in hundreds of resources.

> Your call on whether to close this issue

I'd love to get to the bottom of this, but I can't - not without a debug log, so I'll have to close it.

If you come across the same error next time please [do capture the debug log](https://www.terraform.io/docs/internals/debugging.html), so we can dig in and figure out what the problem is. 🙂

**Closed by radeksimko** 2017-08-08 05:28 UTC
Labels: bug, waiting-response
