### ISSUE TITLE
Global Accelerator Endpoint Group Health Check Path repeated updated in-place with ALB

### ISSUE THREAD

**Issue by ax-cgray** [terraform-providers/terraform-provider-aws#10712] opened 2019-11-01 14:42 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.12
+ provider.aws v2.34.0

### Affected Resource(s)

resource "aws_globalaccelerator_endpoint_group" "alb" {
  listener_arn = aws_globalaccelerator_listener.listener.id
  health_check_port = 443
  endpoint_configuration {
    endpoint_id = aws_lb.alb.arn
    weight      = 100
  }
}
* aws_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
locals {
  tags = {
    service                = var.service
    environment            = var.environment
    owner                  = var.owner
    infrastructure_version = var.infrastructure_version
  }
}

resource "aws_globalaccelerator_accelerator" "accelerator" {
  name            = "${var.service}-${var.function}"
  ip_address_type = "IPV4"
  enabled         = true

  attributes {
    flow_logs_enabled = false
  }
}

resource "aws_globalaccelerator_listener" "listener" {
  accelerator_arn = aws_globalaccelerator_accelerator.accelerator.id
  client_affinity = "NONE"
  protocol        = "TCP"

  port_range {
    from_port = 443
    to_port   = 443
  }
}

resource "aws_globalaccelerator_endpoint_group" "alb" {
  listener_arn = aws_globalaccelerator_listener.listener.id
  health_check_port = 443
  endpoint_configuration {
    endpoint_id = aws_lb.alb.arn
    weight      = 100
  }
}

resource "aws_lb" "alb" {
  name               = "${var.service}-${var.function}"
  internal           = false
  load_balancer_type = "application"
  security_groups    = var.security_groups
  subnets            = var.public_subnets

  enable_deletion_protection = false

  tags = local.tags
}
```

### Expected Behavior
terraform apply
Creates resources
terraform apply again
just give outputs

### Actual Behavior
terraform apply
Creates resources
terraform apply again
change detected on endpoint group

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.proxy-frontend.aws_globalaccelerator_endpoint_group.alb will be updated in-place
  ~ resource "aws_globalaccelerator_endpoint_group" "alb" {
        endpoint_group_region         = "us-west-2"
        health_check_interval_seconds = 30
      + health_check_path             = "/"
...

### Steps to Reproduce

Each time I deploy, it does an update on the global accelerator endpoint group for the path. I have tried adding a path and removing but doesn't seem to make a difference.

1. `terraform apply`

### References

* #0000

**Comment by brucex** [comment] 2019-12-16 15:03
i'm running into this as well. it'll also try to continally remove the healthcheck port too if not specified

```

      + health_check_path             = "/"

      - health_check_port             = 443 -> null
```

**Comment by kp-autorola** [comment] 2020-01-06 11:50
Duplicate of #9329

**Comment by bflad** [comment] 2020-01-06 12:47
Thanks, @kp-autorola, this does appear to be a duplicate or very similar to #9329. To consolidate any discussions and efforts, I'm going to close this issue in preference of the earlier one.

**Closed by bflad** 2020-01-06 12:47 UTC
Labels: needs-triage, service/elbv2, service/globalaccelerator
