### ISSUE TITLE
AWS: Create composite resource 'aws_iam_policy_with_attachment'

### ISSUE THREAD

**Issue by HaraldNordgren** [terraform-providers/terraform-provider-aws#4799] opened 2018-06-08 23:19 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I think we can simply the workflow by introducing composite functions, like 'aws_iam_policy_with_attachment'. This one creates a policy and attaches it at the same time.

### New or Affected Resource(s)

* aws_iam_policy_with_attachment

### References

* Pull request: https://github.com/terraform-providers/terraform-provider-aws/pull/4798

**Comment by bflad** [comment] 2018-07-02 21:41
Copied response from https://github.com/terraform-providers/terraform-provider-aws/pull/4798#issuecomment-401944302 below

---

Hi again, @HaraldNordgren. 👋  We understand what you are trying to accomplish here, but there are a lot of associated costs with introducing another Terraform resource like this, just for the purpose of simplification -- I will explain.

> I am aware the Terraform implements the policy-attachment workflow already. This is intended as a simplification

The provider is meant to give operators the basic building blocks for working with individual AWS API relationships/objects, which are separated to cover all possible use cases. We do not want to prescribe that you must work with your infrastructure in a certain way. There are more subtle complexities when trying to manage multiple-purpose Terraform resources, usually leading to maintenance burden within the provider and operator confusion from multiple ways to do something. So by design, we do not try to manage multiple API relationships/objects within one resource.

Admittedly, there are a few exceptions to this case with a historically problematic one being the `aws_security_group` and `aws_security_group_rule` resources, where they conflict with each other. There is a disproportionately higher number of operator issues opened for conflicting management problems like these than the individual resources themselves, despite large warnings in the documentation.

> possibly a replacement for the aws_iam_policy and aws_iam_user_policy_attachment resources.

Its perfectly valid to have completely separate users/Terraform configurations that create IAM policies in one place and attach them in other. Here are some examples that immediately present problems with using this implementation as the prescribed way:
* An organizational administrative account may handle creating/editing all policies across all member AWS accounts (e.g. for compliance reasons), while those member accounts manage attaching to those policies.
* Creating an IAM policy intended for attaching to groups or roles
* Creating an IAM policy intended for attaching to two separate users

Especially in the last case, [IAM limitations on the number of managed policies](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-limits.html) makes it undesirable to create separate IAM policies per user attachment. In quite a few cases, Terraform is used by organizations with thousands of users.

> The implementation makes sure to call the CRUD functions of the underlying resources so that aws_iam_user_policy_with_attachment works as a full replacement for the two resources. The two underlying resources move in sync.

Under the hood, the resource will still be making multiple API calls to manage multiple pieces of infrastructure. Having the code in one resource versus two (or more) resources does not change any of the complexities when working with multiple API calls, especially with [IAM eventual consistency](https://docs.aws.amazon.com/IAM/latest/UserGuide/troubleshoot_general.html#troubleshoot_general_eventual-consistency) in this case. Creating an IAM policy does not immediately make it available for attachment because its within the same Terraform resource.

---

We definitely appreciate your idea, however given that this functionality is not likely to be merged for the reasons above, I am going to close this pull request.

Without any changes to the provider, its also possible to simplify the same end behavior by switching to using in-line IAM user policies instead of managed IAM policies. Below is an example of how to do this via the [`aws_iam_user_policy` resource](https://www.terraform.io/docs/providers/aws/r/iam_user_policy.html):

```hcl
resource "aws_iam_user_policy" "example" {
  name = "test-policy"
  user  = "${aws_iam_user.user.name}"
  policy = "{ ... }"
```

Alternatively and more typically outside this case (since usually there are not two ways to do a similar action/behavior within an API), we would expect any high level simplification like this pull request suggests to be implemented in a [Terraform module](https://www.terraform.io/docs/modules/usage.html), to abstract the configuration details for operators and (optionally) published on https://registry.terraform.io/ for anyone's usage. Below is a very brief example of creating a module for this simplification:

```hcl
variable "description" {
  type = "string"
}

variable "policy" {
  type = "string"
}

variable "policy_name" {
  type = "string"
}

variable "user" {
  type = "string"
}

resource "aws_iam_policy" "policy" {
    name        = "${var.policy_name}"
    description = "${var.description}"
    policy      = "${var.policy}"
}

resource "aws_iam_user_policy_attachment" "test-attach" {
    user       = "${aws_iam_user.user.name}"
    policy_arn = "${aws_iam_policy.policy.arn}"
}
```

Which can be invoked via something like:

```hcl
module "aws_iam_user_policy_with_attachment" {
  source = "..."

  policy_name = "test-policy"
  description = "A test policy"
  policy      = "{ ... }"
  user        = "${aws_iam_user.user.name}"
}
```

I hope either of these alternatives help. 👍

**Closed by bflad** 2018-07-02 21:41 UTC
Labels: new-resource, service/iam
