### ISSUE TITLE
aws_ecs_service InvalidParameterException: You cannot specify an IAM role for services that require a service linked role when using multiple loadbalancers

### ISSUE THREAD

**Issue by ghostsquad** [terraform-providers/terraform-provider-aws#10332] opened 2019-10-01 21:25 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

`Terraform v0.11.14` We cannot upgrade terraform at the moment due to breaking changes between 0.11 and 0.12. But I think this is a bug in the AWS provider, not terraform.

```
* provider.aws: version = "~> 2.30"
* provider.random: version = "~> 2.2"
* provider.template: version = "~> 2.1"
```

### Affected Resource(s)

* aws_ecs_service

### Terraform Configuration Files

```hcl
resource "aws_ecs_service" "foo" {
  name                               = "foo"
  task_definition                    = "${aws_ecs_task_definition.foo.family}:${max("${aws_ecs_task_definition.foo.revision}", "${data.aws_ecs_task_definition.foo.revision}")}"
  desired_count                      = 0
  cluster                            = "${var.ecs_cluster_id}"
  iam_role                           = "${var.ecs_service_role_arn}"
  health_check_grace_period_seconds  = 300

  ordered_placement_strategy {
    field = "attribute:ecs.availability-zone"
    type = "spread"
  }

  ordered_placement_strategy {
    field = "cpu"
    type = "binpack"
  }

  load_balancer {
    target_group_arn = "${aws_alb_target_group.foo.arn}"
    container_name   = "foo"
    container_port   = 80
  }

  load_balancer {
    target_group_arn = "${aws_alb_target_group.bar.arn}"
    container_name   = "foo"
    container_port   = 80
  }

  lifecycle {
    ignore_changes = ["task_definition", "desired_count"]
  }
}
```

### Debug Output

I'm currently not comfortable providing the debug output at this time, but I can provide specific information when appropriate

### Panic Output

N/A

### Expected Behavior

Service is destroyed and recreated

### Actual Behavior

```
Error: Error applying plan:

1 error occurred:
	* module.containers.module.foo.aws_ecs_service.foo: 1 error occurred:
	* aws_ecs_service.foo: InvalidParameterException: You cannot specify an IAM role for services that require a service linked role.
	status code: 400, request id: <REDACTED> "foo"
```

### Steps to Reproduce

1. Create an `aws_ecs_service` with the following attributes:
    * 2 Loadbalancers
    * `iam_role` not empty

2. `terraform apply`

### Important Factoids

Commenting out the 2nd loadbalancer block results in a successful creating of the ECS service

Commenting out the `iam_role` results in a successful apply, however, it has the undesired effect of being assigned the wrong role.

### References

* #4657
* #4673

**Comment by marcghorayeb** [comment] 2019-10-03 22:19
I'm seeing this as well - commenting the `iam_role` attribute makes the apply pass though... Have you found another workaround?

**Comment by ghostsquad** [comment] 2019-10-03 22:57
This workaround allows me to apply, but does not have the desired effect, as the service is assigned the wrong role.

**Comment by marcghorayeb** [comment] 2019-10-04 19:08
@ghostsquad we could probably help anyone reading this by improving the *Steps to reproduce* description, could you edit it to explicitly say that you need to have an `iam_role` set?

**Comment by ghostsquad** [comment] 2019-10-04 19:41
@marcghorayeb done.

**Comment by bflad** [comment] 2019-10-06 17:57
Hi folks 👋

Similar to [this comment](https://github.com/terraform-providers/terraform-provider-aws/issues/4657#issuecomment-392054077) in the referenced issue, this behavior is controlled by the ECS service itself and not Terraform. In particular, the [ECS documentation for registering multiple target groups](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/register-multiple-targetgroups.html) notes this in the considerations:

> When creating a service that specifies multiple target groups, the Amazon ECS service-linked role must be created. The role is created by omitting the role parameter in API requests, or the Role property in AWS CloudFormation. For more information, see [Using Service-Linked Roles for Amazon ECS](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using-service-linked-roles.html).

Since there is nothing to be done within Terraform, I'm going to close this issue. If you would like to see an improvement with the ECS service to support custom IAM roles when registering multiple target groups, you can reach out to AWS Support or your AWS TAMs. It may also be worth checking out https://github.com/aws/containers-roadmap/ to see if the feature request is already being tracked.

**Closed by bflad** 2019-10-06 17:57 UTC
Labels: service/ecs
