### ISSUE TITLE
Request: new resource to run one off ECS tasks

### ISSUE THREAD

**Issue by Ashtonian** [terraform-providers/terraform-provider-aws#5893] opened 2018-09-15 19:40 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I may be missing something, but it doesn't seem like there is a way to run a one off task without creating a service for it in terraform. The aws_ecs_service doc stats "Provides an ECS service - effectively a task that is expected to run until an error occurs or a user terminates it (typically a webserver or a database)." You can run tasks on a one-off basis and it would be nice if terraform could support this for docker utilities and things like db migrations. It would be cool if you could also have a dependency/reference to the task execution result so you can make sure it executes before building additional infrastructure.

### New or Affected Resource(s)

* aws_ecs_task - used to setup a task
* aws_ecs_task_execution - used to track execute result of a given task

**Comment by jochen42** [comment] 2018-09-17 11:13
hi. i think this is a duplicate of #1703

**Comment by bflad** [comment] 2018-09-17 13:04
Hi @Ashtonian 👋  Thanks for this feature request! I believe @jochen42 is correct here and that this is a duplicate of #1703 (or at least very similar). In order to consolidate discussions and any efforts for this, I am going to close this issue in preference of the earlier one. 👍

**Closed by bflad** 2018-09-17 13:04 UTC
Labels: new-resource, service/ecs
