### ISSUE TITLE
aws_acm_certificate - domain_validation_options is empty for new certificates

### ISSUE THREAD

**Issue by giridharmp** [terraform-providers/terraform-provider-aws#9627] opened 2019-08-05 10:05 UTC
Tried creating a new certificate using the code below:

provider "aws" {
  version                   = ">= 1.57.0"
  region     = "ap-southeast-2"
  access_key = ""
  secret_key = ""
}

data "aws_route53_zone" "cluster_hosted_zone" {
  name      = "example.com"
}

resource "aws_acm_certificate" "alb_certificate" {
  domain_name               = "example.com"
  subject_alternative_names = [
    "api.example.com"
  ]
  validation_method         = "DNS"
}

output "created_cert" {
  value = "${aws_acm_certificate.alb_certificate.domain_validation_options}"
}

For the newly issued certificate, domain_validation_options attribute is not populated and is returning as empty.

**Comment by zygimantas** [comment] 2019-08-05 13:08
Duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/9596

**Comment by bflad** [comment] 2019-08-05 14:02
Hi @giridharmp 👋 Thank you for reporting this and sorry you are having trouble. This does appear to be a duplicate of #9596, so to consolidate discussion and efforts I'm going to close this issue in preference of the previous issue. Please follow #9596 for further updates, thanks.

**Closed by bflad** 2019-08-05 14:02 UTC
Labels: needs-triage, service/acm, service/route53
