### ISSUE TITLE
Feature Request: DynamoDB Point-in-time Recovery Control

### ISSUE THREAD

**Issue by jantman** [terraform-providers/terraform-provider-aws#4271] opened 2018-04-19 17:45 UTC
It appears that this provider does not support controlling [Point-in-time recovery (PITR)](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/PointInTimeRecovery.html) for DynamoDB tables. It would be very helpful if it did.

PITR is enabled/disabled via the [UpdateContinuousBackups](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateContinuousBackups.html) API call and queried using the [DescribeContinuousBackups](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_DescribeContinuousBackups.html) API call.

**Comment by bflad** [comment] 2018-04-20 15:09
Thanks for submitting this @jantman! 

This is a duplicate of issue #3927 with an open PR #4063 - so closing this to consolidate issues in the repository.

**Closed by bflad** 2018-04-20 15:09 UTC
Labels: enhancement, service/dynamodb

**Comment by jantman** [comment] 2018-04-20 15:12
Oops, apologies! I know I _tried_ searching... :(
