### ISSUE TITLE
EIP Tagging is failed with permission denied, when updating tags

### ISSUE THREAD

**Issue by andylockran** [terraform-providers/terraform-provider-aws#3184] opened 2018-01-29 17:56 UTC
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Running version 0.11.2 - appreciate it's not the latest - if that's the issue, then please hit me with a stick.

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_eip

### Terraform Configuration Files
Before:
```hcl
resource "aws_eip" "inter-nat" {
  vpc   = true
  count = 2

  tags {
    Name        = "${local.prefix} NAT Gateway ${count.index}"
    Environment = "${local.prefix}"
  }
}
```
After:
```hcl
resource "aws_eip" "inter-nat" {
  vpc   = true
  count = 2

  tags {
    Name        = "${local.prefix} NAT Gateway ${count.index}"
    Environment = "${local.prefix}"
    Product = "Sample"
    vpc = "test"
  }
}
```
### Debug Output
```
Error: Error applying plan:

2 error(s) occurred:

* aws_eip.inter-nat[1]: 1 error(s) occurred:

* aws_eip.inter-nat.1: AuthFailure: You do not have permission to access the specified resource.
	status code: 400, request id: f06c6dc1-58a2-4f3c-XXXX-cbfbe90875d6
* aws_eip.inter-nat[0]: 1 error(s) occurred:

* aws_eip.inter-nat.0: AuthFailure: You do not have permission to access the specified resource.
	status code: 400, request id: eca2bb74-e619-490c-XXXX-a44dade17b90
```

### Expected Behavior
Terraform should have updated the tags on the EIP to the new configuration.

### Actual Behavior
Despite multiple runs (the latter I associated Administrator Access with the terraform role) - I always get a permission denied error when attempting to modify eip tags.  The first run (to create them) worked fine, but making a modification to the tag is what fails.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Modify your aws_eip resource to add a new tag.  (there must already be tags present).
2. Run `terraform apply`
3. Watch the run fail

### Important Factoids
The eip is referenced by a NAT gateway, but unsure whether this has an impact.
```hcl
resource "aws_nat_gateway" "inter" {
  subnet_id     = "${aws_subnet.dmz.*.id[count.index]}"
  allocation_id = "${aws_eip.inter-nat.*.id[count.index]}"
  count         = 2
}
```

### References
The original PR to enable tagging of EIPS:
- #2768

**Comment by conversicachrisr** [comment] 2018-02-06 20:00
Confirmed this is an issue. The same credentials will work to change/add/delete tags manually.
Also tested 0.11.3, same issue.

**Comment by conversicachrisr** [comment] 2018-02-12 22:12
This now works in provider version 1.9.

**Comment by andylockran** [comment] 2018-02-12 22:25
Awesome. Thank you!

**Comment by Ninir** [comment] 2018-03-02 13:52
Closing since it has been fixed!
Thanks @conversicachrisr for the feedback :)

**Closed by Ninir** 2018-03-02 13:52 UTC
Labels: bug, service/ec2
