### ISSUE TITLE
aws_elb ssl certificate does not change when changing resource.

### ISSUE THREAD

**Issue by jnatten** [terraform-providers/terraform-provider-aws#1870] opened 2017-10-12 08:39 UTC
Hi there I'm having an issue where ELB listener ssl certificates does not get replaced when i update a resource.
If i change ELB listener certificates manually when it is attempting to destroy, everything seems to work out and terraform successfully exits.

### Terraform Version
Terraform v0.10.7

### Affected Resource(s)
 - aws_iam_server_certificate
 - aws_elb

#### iam_component.tf
```hcl
resource "aws_iam_server_certificate" "main" {
  name_prefix = "main-${var.env_name}"
  certificate_body = <<EOF
<certBodyHere>
EOF
  certificate_chain = <<EOF
<certChainHere>
EOF
  private_key = <<EOF
<privkeyHere>
EOF

  lifecycle {
    create_before_destroy = true
  }
}
```

#### component_public/main.tf
```hcl
data "aws_iam_server_certificate" "cert" {
  name_prefix = "${var.certificate_name_prefix}"
  latest = true
}

resource "aws_elb" "instance" {
 ...
  listener {
    instance_port     = 80
    instance_protocol = "http"
    lb_port           = 443
    lb_protocol       = "https"
    ssl_certificate_id = "${data.aws_iam_server_certificate.cert.arn}"
  }
...
}
```

### Terraform plan
```
-/+ aws_iam_server_certificate.main (new resource required)
      id:                        "1234" => <computed> (forces new resource)
      arn:                       "arn:aws:iam::1234:server-certificate/main1234" => <computed>
      certificate_body:          "1234" => "5678" (forces new resource)
      certificate_chain:         "1234" => "1234"
      name:                      "main1234" => <computed>
      name_prefix:               "main" => "main"
      path:                      "/" => "/"
      private_key:               <sensitive> => <sensitive> (attribute changed)
```

### Expected Behavior
1. The certificate is uploaded to IAM
2. The ELB's listener certificate is changed to the newly uploaded certificate
3. The old certificate is deleted from IAM

### Actual Behavior
1. The certificate is uploaded to IAM
2. Terraform repeatedly tries to delete certificate outputting `aws_iam_server_certificate.main (deposed #0): Still destroying... (ID: 1234, 10m0s elapsed)`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Change certificate body of aws_iam_server_certificate resource.
2. terraform apply

**Comment by radeksimko** [comment] 2017-10-15 06:43
Hi @jnatten 
it seems from your attached configs that you have two directories and you only manage the cert in the first one (`iam_component.tf`) and then read it in the other one (`component_public/main.tf`) - **unless you use modules** and resources in these configs somehow depend on each other - in which case that's a different story (and may be a bug) and ignore the rest of my post.

Terraform always operates in the context of a given path/directory. It won't read or evaluate files in other directories, even if they're subdirectories, unless they're explicitly referenced. When you run `apply` on your first config it cannot update the reference in ELB because it doesn't even see that config at that point.

One solution is to place both your SSL cert & ELB config to the same directory and reference it directly:

```hcl
resource "aws_elb" "instance" {
 ...
  listener {
    instance_port     = 80
    instance_protocol = "http"
    lb_port           = 443
    lb_protocol       = "https"
    ssl_certificate_id = "${aws_iam_server_certificate.main.arn}"
  }
...
}

resource "aws_iam_server_certificate" "main" {
  name_prefix = "main-${var.env_name}"
  certificate_body = <<EOF
<certBodyHere>
EOF
  certificate_chain = <<EOF
<certChainHere>
EOF
  private_key = <<EOF
<privkeyHere>
EOF

  lifecycle {
    create_before_destroy = true
  }
}
```

I believe that Terraform is working as intended in this case, so I'm going to close this issue, let me know if you believe that's not the case.

**Closed by radeksimko** 2017-10-15 06:43 UTC
Labels: question

**Comment by jnatten** [comment] 2017-10-17 05:59
@radeksimko, I'm sorry i was probably a bit unclear on the setup. 
`./` includes files like the `iam_component.tf` but also modules which source from `./component_public`.

Those look something like this:

```
module "some-component" {
  source = "./component_public"
  certificate_name_prefix = "${aws_iam_server_certificate.main.name_prefix}"
...
}
```

**Comment by radeksimko** [comment] 2017-10-17 08:12
@jnatten my response/suggestion applies to that too though. You need to pass exact certificate name/ARN to the module and reference it directly from the resource and avoid the data source.

```hcl
module "some-component" {
  source = "./component_public"
  certificate_arn = "${aws_iam_server_certificate.main.arn}"
...
}
```

The data source has no way of knowing _when_ does the certificate get updated and whether it has the previous or current version as there's no relationship between the resource (responsible for updating) and the data source.

**Comment by jnatten** [comment] 2017-10-17 09:41
Oh that was the issue. Thanks! I was unable to set the arn of the iam_server_certificate arn, but using names instead of name_prefix'es fixed it.
