### ISSUE TITLE
incorrect behaviour on missing default_route_table

### ISSUE THREAD

**Issue by gtmtech** [terraform-providers/terraform-provider-aws#9403] opened 2019-07-18 14:05 UTC
Terraform 0.11.14

Terraform mostly acts nicely/correctly when an external force has deleted its objects. On a plan/refresh/apply it will analyse the state of stuff it knows about, finds it doesnt exist any more, and then delete it from the state file to match without complaining. This makes certain situations awesome where you have to manage some destructive things outside terraform (such as nuking a whole test account for example using one of the nuke things out there)

aws_default_route_table doesnt play ball when the vpc it refers to has been deleted. It should just silently go away into the place where terraform state goes to die, but instead it throws an error complaining it cant be found. 

It would be awesome if this resource's behaviour would be brought into line with other resources when its underlying cloud resource no longer exists. 

Thanks!

**Comment by bflad** [comment] 2019-07-18 19:20
Hi @gtmtech 👋 Thank you for reporting this inconsistency. Can you please provide the error message you are receiving when this happens? We'll want to confirm we are reproducing your issue before closing this. Thanks.

**Comment by bflad** [comment] 2019-09-04 18:31
It's been a long time since we heard from you here so we're going to close this out. If you're still having this problem, please feel free to open a new issue and complete all of the information requested in the [Bug Report template](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/ISSUE_TEMPLATE/Bug_Report.md) so that we can attempt to understand and reproduce the problem.

**Closed by bflad** 2019-09-04 18:31 UTC
Labels: bug, service/ec2, waiting-response
