### ISSUE TITLE
Guard Duty "The request is rejected because the input detectorId is not owned by the current account"

### ISSUE THREAD

**Issue by awworrell** [terraform-providers/terraform-provider-aws#6937] opened 2018-12-20 14:10 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

I am running terraform enterprise. It is currently running Terraform v0.11.11.

### Affected Resource(s)

* aws_guardduty_member
  aws_guardduty_detector
### Terraform Configuration Files

This is my guard duty member module

`resource "aws_guardduty_detector" "default_member_detector" {  
  enable = "${var.member_isEnabled}"
}
resource "aws_guardduty_member" "default_member" {
  account_id         = "${aws_guardduty_detector.default_member_detector.account_id}"
  detector_id        = "${var.master_id}"
  email              = "${var.member_email}"
  invite             = true
  invitation_message = "please accept guardduty invitation"
}`

This is the implementation to that module and the master module

`provider "aws" {
  alias = "master_account"
  access_key = "${var.master_remote_access_key}"
  secret_key = "${var.master_remote_secret_key}"
  region     = "${var.master_remote_region}"

}

provider "aws" {
  alias = "master_non_master_account"
  access_key = "${var.master_non_master_remote_access_key}"
  secret_key = "${var.master_non_master_remote_secret_key}"
  region     = "${var.master_non_master_remote_region}"

}

provider "aws" {
  alias = "master_master_account"
  access_key = "${var.master_master_remote_access_key}"
  secret_key = "${var.master_master_remote_secret_key}"
  region     = "${var.master_master_remote_region}"
}

module "guardduty_master" {
  source = "./modules/master"  
  master_isEnabled   = true
  providers = {
    "aws" = "aws.master_account"
  }
}

module "guardduty_non_master" {
  source = "./modules/member"  
  member_isEnabled = "${var.guardduty_non_master_isEnabled}"
  master_id = "${module.guardduty_master.id}"
  member_email = "${var.guardduty_non_master_email}"
  providers = {
    "aws" = "aws.master_non_master_account"
  }  
}

module "guardduty_master" {
  source = "./modules/member"  
  member_isEnabled = "${var.guardduty_master_isEnabled}"
  master_id = "${module.guardduty_master.id}"  
  member_email = "${var.guardduty_master_email}"
  providers = {
    "aws" = "aws.master_master_account"
  } 
}`

### Debug Output

Here is the output for the implementation

`account_id:          "" => "member account id"
  detector_id:         "" => "master account id"
  email:               "" => "master email"
  invitation_message:  "" => "please accept guardduty invitation"
  invite:              "" => "true"
  relationship_status: "" => "<computed>"`

`aws_guardduty_member.default_member: Creating GuardDuty Member failed: BadRequestException: The request is rejected because the input detectorId is not owned by the current account.
	status code: 400, request id: request id`
The account id and detector id are two different numbers. They are the ids of both AWS accounts. I removed them so that they are not public.

### Expected Behavior

Guard Duty is enabled on all accounts and the detector account would have two invites sent to the other two accounts.

### Actual Behavior

All three accounts are active. The two member accounts failed to receive an invite because of the error above.

### Steps to Reproduce

Create a module with the code above where the structure of that module is as followes
modules
     master --implements the master
     member- creates default member and enables the default member account
main.tf --wraps both member and masters into a single module and implements each aws module for three accounts.
environment
main.tf implements the module fully with all variables being sent to modules.main.tf

1. `terraform apply`

### References

* #0000

**Comment by awworrell** [comment] 2019-01-08 19:43
I modfied it today and this seems to be solved. Can you update the example at https://www.terraform.io/docs/providers/aws/r/guardduty_member.html. it shows that the example is using the id not the detector id.

**Comment by bflad** [comment] 2019-01-08 19:57
The example there is using the `id` attribute, which is correct and verified in our acceptance tests:

* https://www.terraform.io/docs/providers/aws/r/guardduty_detector.html#id
* https://github.com/terraform-providers/terraform-provider-aws/blob/4f46df8d0f0cb07f75f4d3e962d1466aeac7b016/aws/resource_aws_guardduty_member_test.go#L227

**Comment by bflad** [comment] 2019-01-09 01:06
Closing as I believe the issue is resolved and the documentation is already correct, but please reach out if that is not the case, thanks.

**Closed by bflad** 2019-01-09 01:06 UTC
Labels: service/guardduty
