### ISSUE TITLE
AWS resource VPC Managed Prefix List

### ISSUE THREAD

**Issue by hamza-t** [terraform-providers/terraform-provider-aws#14039] opened 2020-07-03 09:44 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon Virtual Private Cloud (VPC) now allows you to create your own Prefix Lists that can be easily audited and applied across all your accounts to have a consistent security posture and routing behavior. A Prefix List is a collection of CIDR blocks that can be used to configure VPC security groups and route tables and shared with other AWS accounts using Resource Access Manager (RAM).

### New or Affected Resource(s)

- New resource proposal: `aws_prefix_list`
- Existing data source: `aws_prefix_list`

### Potential Terraform Configuration

```hcl
resource "aws_prefix_list" "company-cidrs" {
  name             = string    # Prefix list name
  max_entries      = number    # Maximum number od prefix list entries
  address_family   = string    # IPv4 or IPv6
  entries          = list      # Prefix list entries
  tags             = map       # Map of tags
}
```

### References

* Amazon Virtual Private Cloud (VPC) customers can now use their own Prefix Lists to simplify the configuration of security groups and route tables https://aws.amazon.com/about-aws/whats-new/2020/06/amazon-virtual-private-cloud-customers-use-prefix-lists-simplify-configuration-security-groups-route-tables/
* Documentation: Managed prefix lists https://docs.aws.amazon.com/vpc/latest/userguide/managed-prefix-lists.html

**Comment by ewbankkit** [comment] 2020-07-03 13:22
@hamza-t Thanks for raising this issue.
It is a duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/13986 so I will close this one. Please add any additional comments to the linked issue.

**Closed by ewbankkit** 2020-07-03 13:22 UTC
Labels: enhancement, service/ec2
