### ISSUE TITLE
provider retries invalid request for a long time

### ISSUE THREAD

**Issue by time4tea** [terraform-providers/terraform-provider-aws#854] opened 2017-06-14 10:57 UTC
### Terraform Version
 0.9.8

### Affected Resource(s)

aws_lambda_function

### Terraform Configuration Files

cannot really share at the mo.

### Debug Output
its just a couple of lines
plugin: terraform: aws-provider (internal) 2017/06/14 11:35:56 [DEBUG] [aws-sdk-go] {"Type":"User","message":"The role defined for the function cannot be assumed by Lambda."}
plugin: terraform: aws-provider (internal) 2017/06/14 11:35:56 [DEBUG] Error creating Lambda Function: InvalidParameterValueException: The role defined for the function cannot be assumed by Lambda.
plugin: terraform: aws-provider (internal) 2017/06/14 11:35:56 [DEBUG] Received InvalidParameterValueException: The role defined for the function cannot be assumed by Lambda.
plugin: terraform: 	status code: 400, request id: xxx, retrying CreateFunction
 plugin: terraform: aws-provider (internal) 2017/06/14 11:35:56 [TRACE] Waiting 1s before next try

### Expected Behavior

request should not have been retried, this is a 400 error. it won't work next time.

### Actual Behavior
request was retried for 14 minutes.

### Steps to Reproduce
terraform apply

**Comment by Ninir** [comment] 2017-06-14 12:36
Hey @time4tea 

Thanks for reporting this issue, and sorry for the noise on this.
Do you think you could share a dummy example, so that we can reproduce without using any specific / sensitive data you used?

I saw this 400 issue a lot when creating / updating lambdas, always resulting in a success. Sometimes it is due to the ZIP being retrieved / uploaded.

Thanks for your answer!

**Comment by time4tea** [comment] 2017-06-14 13:03
```
resource "aws_lambda_function" "my_lambda" {
  filename         = "${var.src}/lambdas.zip"
  role             = "${aws_iam_role.lambda-execution-role.arn}"
  function_name    = "my_function"
  handler          = "lambda.lambda_handler"
  runtime          = "python3.6"
  timeout          = 20

  environment {
    variables = {
      A = "a"
      B = "b"
    }
  }
}

resource "aws_iam_role" "lambda-execution-role" {
  name = "lambda-execution-role"
   assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
EOF
}
```

Notice that the assume role has a typo, and is 'ec2', not 'lambda'
I hope i didn't make a mistake when anonymising the rules...

thanks for taking a look!

james

**Comment by ryndaniels** [comment] 2020-01-13 17:29
Hi @time4tea - thanks for taking the time to submit this issue. I had a look at this with the most recent versions of Terraform and the AWS Provider and was unable to reproduce this behavior (I got the 400 error in under a minute, not close to the 14 minutes you saw earlier). We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md). 🙂

**Closed by ryndaniels** 2020-01-13 17:29 UTC
Labels: bug, service/lambda
