### ISSUE TITLE
aws_transfer_server resource is always recreated

### ISSUE THREAD

**Issue by probert-gameloft** [terraform-providers/terraform-provider-aws#10546] opened 2019-10-18 12:28 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.10

### Affected Resource(s)

* aws_transfer_server

### Terraform Configuration Files

```hcl
resource "aws_transfer_server" "workday_sftp" {
  identity_provider_type = "SERVICE_MANAGED"
  logging_role           = var.logging_role

  tags = {
    ManagedBy   = "Terraform"
    Environment = var.env
    Project     = var.name
    Service     = var.tag
    Department  = var.dep
    Owner       = var.owner
  }

}
```

### Debug Output

https://gist.github.com/probert-gameloft/26a6eb3940cb80bdc2b6a7375f832f1a

### Expected Behavior

When running plan/apply on the same resource definition, it should use the same resource.

### Actual Behavior

It is creating a new resource instead of reusing the same resource. In short, it's creating a new SFTP server each time plan/apply is called, even if the resource name didn't change.

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

### References

* #0000

**Comment by probert-gameloft** [comment] 2019-10-18 19:44
Well. I can't recreate the issue. It seems to happen when an 'apply' is failing for another resource (in my case, a aws_kms_grant). I guess the state is not saved in that case, and the new resource is created at the next run.

**Comment by bflad** [comment] 2019-11-04 22:28
Hi @probert-gameloft 👋 Thanks for filing this. If you're no longer able to reproduce it and since there are no other upvotes, we are going to opt to close this issue.

If you or anyone has a reproducible configuration for this issue in the future, please create a new GitHub issue. Thanks. 👍

**Closed by bflad** 2019-11-04 22:28 UTC
Labels: needs-triage, service/transfer
