### ISSUE TITLE
RDS instance: Terraform insisting on destroy-recreate Oracle RDS, while applying the patch 

### ISSUE THREAD

**Issue by Nareshkg** [terraform-providers/terraform-provider-aws#6075] opened 2018-10-05 02:23 UTC
RDS instance: Terraform insisting on destroy-recreate Oracle RDS, while applying the patch 12.1.0.2.v13

id: "test123" => (forces new resource)
-/+ module.oracle.aws_db_instance.rds (new resource required)
id: "test123" => (forces new resource)

However I am able to apply the patch for Mysql RDS from 5.7.17 to 5.7.22 without any issues and terraform successful and changes are applied during maintenance window.

Version details -

terraform_version: 0.11.7
aws provider - 1.30.0

**Comment by bflad** [comment] 2018-10-05 02:28
Hi @Nareshkg 👋  Sorry you're having trouble. Are you able to provide the full `terraform plan` output (removing any sensitive information) so we can confirm the behavior you are seeing? Thanks so much.

**Comment by Nareshkg** [comment] 2018-10-05 16:03
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
 ~ update in-place
-/+ destroy and then create replacement

Terraform will perform the following actions:

**-/+ module.oracle.aws_db_instance.rds (new resource required)
 id: "testpr" => <computed> (forces new resource)**
 address: "<ENDPOINT>" => <computed>
 allocated_storage: "100" => "100"
 apply_immediately: "false" => "false"
 arn: "<ARN>:db:testpr" => <computed>
 auto_minor_version_upgrade: "false" => "false"
 availability_zone: "us-east-1a" => <computed>
 backup_retention_period: "30" => "30"
 backup_window: "00:00-03:00" => "00:00-03:00"
 ca_cert_identifier: "rds-ca-2015" => <computed>
 character_set_name: "AL32UTF8" => "AL32UTF8"
 copy_tags_to_snapshot: "false" => "false"
 db_subnet_group_name: "<SG>" => "<SG>"
 endpoint: "<ENDPOINT>:1521" => <computed>
 engine: "oracle-ee" => "oracle-ee"
 engine_version: **"12.1.0.2.v12" => "12.1.0.2.v13"**
 final_snapshot_identifier: "testpr-finalsnapshot" => "testpr-finalsnapshot"
 hosted_zone_id: "<ZN>" => <computed>
 iam_database_authentication_enabled: "false" => "false"
 identifier: "testpr" => "testpr"
 identifier_prefix: "" => <computed>
 instance_class: "db.m3.xlarge" => "db.m3.xlarge"
 iops: "0" => "0"
 kms_key_id: "<KMS_ARN>" => "<KMS_ARN>"
 license_model: "bring-your-own-license" => "bring-your-own-license"
 maintenance_window: "sun:05:00-sun:06:00" => "sun:05:00-sun:06:00"
 monitoring_interval: "5" => "5"
 monitoring_role_arn: "<ROLE>" => "<ROLE>"
 multi_az: "true" => "true"
 **name: "TESTPR" => "testpr" (forces new resource)**
 option_group_name: "testpr-option-group" => "${local.option_group_name}"
 parameter_group_name: "testpr-param-grp" => "${local.parameter_group_name}"
 password: <sensitive> => <sensitive> (attribute changed)
 port: "1521" => "1521"
 publicly_accessible: "false" => "false"
 replicas.#: "0" => <computed>
 resource_id: "<ID>" => <computed>
 skip_final_snapshot: "false" => "false"
 status: "available" => <computed>
 storage_encrypted: "true" => "true"
 storage_type: "gp2" => "gp2"
 timezone: "" => <computed>
 username: "masteruser" => "masteruser"
 vpc_security_group_ids.#: "1" => "1"
 vpc_security_group_ids.3<SG'S>" => "<SG's>"

 ~ module.oracle.aws_route53_record.rds_route53
 records.#: "" => <computed>

-/+ module.oracle.module.db_option_group.aws_db_option_group.dboptions (new resource required)
 **id: "testpr-option-group" => <computed> (forces new resource)**
 arn: "arn:aws:rds:<ARN>" => <computed>
 engine_name: "oracle-ee" => "oracle-ee"
 major_engine_version: "12.1" => "12.1"
 name: "testpr-option-group" => <computed>
 name_prefix: "" => "testpr-option-group-" (forces new resource)
 option.#: "4" => "4"
 option.123455.db_security_group_memberships.#: "0" => "0"
 option.123455.option_name: "SQLT" => "SQLT"
 option.123455.option_settings.#: "1" => "1"
 option.123455.option_settings.1202594640.name: "LICENSE_PACK" => "LICENSE_PACK"
 option.123455.option_settings.1202594640.value: "T" => "T"
 option.123455.port: "0" => ""
 option.123455.version: "2016-04-29.v1" => "2016-04-29.v1"
 option.123455.vpc_security_group_memberships.#: "0" => "0"
 option.123455.db_security_group_memberships.#: "0" => "0"
 option.123455.option_name: "Timezone" => "Timezone"
 option.123455.option_settings.#: "1" => "1"
 option.123455.option_settings.124550033.name: "TIME_ZONE" => "TIME_ZONE"
 option.123455.option_settings.1245550033.value: "US/Eastern" => "US/Eastern"
 option.123455.port: "0" => ""
 option.2298335747.version: "" => ""
 option.2298335747.vpc_security_group_memberships.#: "0" => "0"
 option.2811532231.db_security_group_memberships.#: "0" => "0"
 option.2811532231.option_name: "OEM_AGENT" => "OEM_AGENT"
 option.2811532231.option_settings.#: "3" => "3"
 option.2811532231.option_settings.2009018056.name: "OMS_HOST" => "OMS_HOST"
 option.2811532231.option_settings.2009018056.value: "<HOSTNAME>" => "<HOSTNAME>"
 option.2811532231.option_settings.3400864634.name: "OMS_PORT" => "OMS_PORT"
 option.2811532231.option_settings.3400864634.value: "1159" => "1159"
 option.2811532231.option_settings.600202264.name: "AGENT_REGISTRATION_PASSWORD" => "AGENT_REGISTRATION_PASSWORD"
 option.282323231.option_settings.600202264.value: "XXXXX" => "XXXXX"
 option.22323232.port: "3872" => "3872"
 option.28232323321.version: "12.1.0.5.v1" => "12.1.0.5.v1"
 option.2812324241.vpc_security_group_memberships.#: "1" => "1"
 option.2823343431.vpc_security_group_memberships.2956765449: "<SG>" => "<SG>"
 option.2848217145.db_security_group_memberships.#: "0" => "0"
 option.2848217145.option_name: "UTL_MAIL" => "UTL_MAIL"
 option.2848217145.option_settings.#: "0" => "0"
 option.2848217145.port: "0" => ""
 option.2848217145.version: "" => ""
 option.2848217145.vpc_security_group_memberships.#: "0" => "0"
 option_group_description: "Database option group for testpr" => "Database option group for testpr"
 tags.%: "8" => "8"

-/+ module.oracle.module.db_parameter_group.aws_db_parameter_group.dbparameter (new resource required)
 **id: "testpr-param-grp" => <computed> (forces new resource)**
 arn: "<ARN>" => <computed>
 description: "Database parameter group for testpr" => "Database parameter group for testpr"
 family: "oracle-ee-12.1" => "oracle-ee-12.1"
 name: "testpr-param-grp" => <computed>
 name_prefix: "" => "testpr-param-grp-" (forces new resource)
 parameter.#: "3" => "3"
 parameter.2834343419177.apply_method: "pending-reboot" => "pending-reboot"
 parameter.2823433177.name: "processes" => "processes"
 parameter.2825419177.value: "600" => "600"
 parameter.3870525386.apply_method: "pending-reboot" => "immediate"
 parameter.3870525386.name: "job_queue_processes" => "job_queue_processes"
 parameter.3870525386.value: "50" => "50"
 parameter.4031350060.apply_method: "immediate" => "immediate"
 parameter.4031350060.name: "undo_retention" => "undo_retention"
 parameter.4031350060.value: "21600" => "21600"


Plan: 3 to add, 1 to change, 3 to destroy.

**Comment by bflad** [comment] 2018-10-05 16:18
The `terraform plan` output notes which attributes are causing the recreation with `(forces new resource)`. The left side shows what configuration AWS has and the right side shows what your Terraform configuration has.

In your plan its showing the `name` change as the cause for the `module.oracle.aws_db_instance.rds` recreation, not `engine_version`:

```
engine_version: "12.1.0.2.v12" => "12.1.0.2.v13"
name: "TESTPR" => "testpr" (forces new resource)
```

You will need to switch your Terraform configuration to the uppercase `TESTPR` or add [`ignore_changes`](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) to that resource to prevent Terraform from trying to update the `name` argument, e.g.

```hcl
resource "aws_db_instance" "rds" {
  # ... other configuration ...

  lifecycle {
    ignore_changes = ["name"]
  }
}
```

For the `aws_db_option_group` and `aws_db_parameter_group` resources, its showing the change of `name_prefix` being the cause:

```
name_prefix: "" => "testpr-option-group-" (forces new resource)
```

```
name_prefix: "" => "testpr-param-grp-" (forces new resource)
```

Since the names for these cannot be updated in-place by RDS, Terraform would need to recreate those resource to apply the configuration. You can similarly use `ignore_changes` to prevent the planned difference until you actually want to apply the recreation:

```hcl
resource "aws_db_option_group" "dboptions" {
  # ... other configuration ...

  lifecycle {
    ignore_changes = ["name_prefix"]
  }
}

resource "aws_db_parameter_group" "dbparameter" {
  # ... other configuration ...

  lifecycle {
    ignore_changes = ["name_prefix"]
  }
}
```

Does this help?

**Comment by Nareshkg** [comment] 2018-10-09 21:20
Thanks for your response. Before I try your suggestions, I have one question . the instance was created with lower case, why the tf plan showing as upper case? 

id: "testpr" => (forces new resource)
name: "TESTPR" => "testpr" (forces new resource)

And also for the parameter group and option group, I am using name not the name_prefix in my module.

**Comment by anandka** [comment] 2018-10-10 02:34
@bflad  : I am facing a similar issue where I am forced to recreate RDS and the only **(forces new resource)** line I see in my apply is below.

**id:  "cp-dev-frank-anand-test-normal" => <computed> [31m(forces new resource)**

 Not sure why it is showing my id as computed though I am providing an absolute value to it.

**Comment by Nareshkg** [comment] 2018-10-15 20:28
> @Nareshkg : I know about the name related problem "TESTPR" => "testpr" (forces new resource) that you are referring to its because AWS by default converts it into uppercase and stores it.
> However, when you access the DB it is case insensitive.
> 
> So the fix I did was to convert it into uppercase in my main.tf as shown below
> name = "${upper(var.database_name)}"

I used the fix you suggested and I can see the plan now which is not destroying the resources and it was success. However the changes are not affected and I don't see the Mult-AZ enabled in RDS console.

**Plan/output:**
Terraform will perform the following actions:

 ~ module.oracle.aws_db_instance.rds
 final_snapshot_identifier: "testpr-finalsnapshot" => "TESTPR-finalsnapshot"
 multi_az: "false" => "true"
tags.Name: "testpr-testpr" => "testpr-TESTPR"

Plan: 0 to add, 1 to change, 0 to destroy.



output:

+ terraform apply -input=false -auto-approve=true plan.out
module.oracle.aws_db_instance.rds: Modifying... (ID: testpr)
 final_snapshot_identifier: "testpr-finalsnapshot" => "TESTPR-finalsnapshot"
 multi_az: "false" => "true"
 tags.Name: "testpr-testpr" => "testpr-TESTPR"
module.oracle.aws_db_instance.rds: Still modifying... (ID: testpr, 10s elapsed)
module.oracle.aws_db_instance.rds: Still modifying... (ID: testpr, 20s elapsed)
module.oracle.aws_db_instance.rds: Still modifying... (ID: testpr, 30s elapsed)
module.oracle.aws_db_instance.rds: Modifications complete after 31s (ID: testpr)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

**Comment by bflad** [comment] 2018-10-15 21:06
@Nareshkg is `apply_immediately` set to `true` for your resource? Otherwise, as the [resource documentation](https://www.terraform.io/docs/providers/aws/r/db_instance.html) notes at the top, the change will not occur until the next maintenance window.

**Comment by Nareshkg** [comment] 2018-10-16 15:07
Ah my bad. apply_immediately set to false, I have changed to true and worked fine. Good Catch. 

Is the "name" issue only for Oracle RDS ? As I don't see the issue with mysql rds when I did minor upgrade.

**Comment by bflad** [comment] 2018-10-16 15:57
I believe that is Oracle engine specific. The API documentation for `CreateDBInstance` doesn't give much guidance on the subject other than it defaults to `ORCL` for `DBName`: https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html

**Comment by bflad** [comment] 2018-10-16 16:02
I'm going to close this issue out since we try to keep this issue tracker here for bug reports and feature requests with the AWS provider codebase, but feel free to continue the discussion or reach out on the other [Terraform community forums](https://www.terraform.io/docs/extend/community/index.html) for additional questions, where there are many more practitioners active (instead of just code maintainers here).

**Closed by bflad** 2018-10-16 16:02 UTC
Labels: service/rds, waiting-response

**Comment by Nareshkg** [comment] 2018-10-30 15:58
Sure, Thanks @bflad
