### ISSUE TITLE
api_gateway_deployment does not require a stage

### ISSUE THREAD

**Issue by jasonrichardsmith** [terraform-providers/terraform-provider-aws#5723] opened 2018-08-29 12:45 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8
+ provider.aws (unversioned)
+ provider.template (unversioned)

### Affected Resource(s)

* aws_api_gateway_deployment

### Expected Behavior

stage_name should not be a requirement for a deployment

### Actual Behavior

stage_name is required for a deployment

### References

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-deployment.html#cfn-apigateway-deployment-stagename

This forces the creation of a stage I can not customize in TF.  I have to create another stage along with the one that is created for me to enable caching.

**Comment by bflad** [comment] 2018-08-29 13:05
Hi @jasonrichardsmith 👋  

You might be interested in this previous thread: https://github.com/terraform-providers/terraform-provider-aws/issues/2918#issuecomment-356684239

That thread suggests it might be possible to use `stage_name = ""` to skip the stage creation.

Another possible workaround until any potential code changes can be made: it is now possible to [import API Gateway stages into Terraform](https://www.terraform.io/docs/providers/aws/r/api_gateway_stage.html#import) in [version 1.33.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1330-august-22-2018) so you should be able assume management of the stage created by the deployment.

**Comment by ela34** [comment] 2018-09-10 06:44
Using Terraform v0.11.8 with provider.aws v1.33.0, setting the stage to an empty string seems no more valid, I get the error:

> module.test.module.lambda.aws_api_gateway_usage_plan.test: Resource 'aws_api_gateway_deployment.agd' does not have attribute 'stage_name' for variable 'aws_api_gateway_deployment.agd.stage_name'

Is there any other work around for this?

**Comment by bflad** [comment] 2018-09-10 15:28
@ela34 you will need to point your `aws_api_gateway_usage_plan` resource at the `aws_api_gateway_stage` resource (the one actually creating the stage), instead of the `aws_api_gateway_deployment` resource where you are using `stage_name = ""` (since the deployment is no longer creating a stage with this configuration)

---

Longer details:

>  Resource XXX does not have attribute YYY

These types of errors are caused by:
* The resource being created by Terraform and then not being available for immediate read, where we generally call `d.SetId("")` -- e.g. eventual consistency with the API
* `d.Set()` not being called for the attribute

While the first case can be confirmed by searching for `removing from state` in the debug logging, this appears to be more the second case:

https://github.com/terraform-providers/terraform-provider-aws/blob/9382d841d1ddd208453dd449aa3af0aea52d880a/aws/resource_aws_api_gateway_deployment.go#L100-L139

Given my brief encounters with this resource in the past, I believe its not setup with the `d.Set("stage_name", ...)` during the read function because the API does not return it in the response.

**Comment by ela34** [comment] 2018-09-11 11:53
@bflad thanks a lot. This has fixed my issue.Hope it will help other people encountering this issue.

**Comment by bflad** [comment] 2018-09-11 14:04
I have submitted #5837 to update the resource documentation page to include the following from the [upstream AWS documentation](https://docs.aws.amazon.com/apigateway/api-reference/link-relation/deployment-create/):
> * `stage_name` - (Required) The name of the stage. If the specified stage already exists, it will be updated to point to the new deployment. If the stage does not exist, a new one will be created and point to this deployment. Use `""` to point at the default stage.

We can likely make the argument optional in the future given the behavior.

**Comment by austinbutler** [comment] 2018-12-04 21:33
There's an open PR that makes it optional: https://github.com/terraform-providers/terraform-provider-aws/pull/6459

**Comment by bflad** [comment] 2019-03-15 20:52
The change to allow to allow the `stage_name` argument to be optional has been merged and will release with version 2.3.0 of the Terraform AWS Provider, likely middle of next week. 👍

**Closed by bflad** 2019-03-15 20:52 UTC
Labels: enhancement, service/apigateway
