### ISSUE TITLE
Feature request: Support AWS Glue

### ISSUE THREAD

**Issue by darrenhaken** [terraform-providers/terraform-provider-aws#1416] opened 2017-08-15 09:00 UTC
AWS Glue has now become GA https://aws.amazon.com/glue/

It would be nice to have this running through Terraform. Do you accept PR's as I could look to add it?

**Comment by Ninir** [comment] 2017-08-15 09:27
Hey @darrenhaken 

It seems the service is available in the Go SDK and CRUDs operations are also available.
Feel free to open a PR for that, we'll be more than happy to review & help on that :)

**Comment by darrenhaken** [comment] 2017-08-15 09:31
Thanks :-) is there any docs on how to write Terraform to hook into the SDK? I'll do some digging myself of course.
		
		

		
	




On Tue, Aug 15, 2017 at 10:27 AM +0100, "Gauthier Wallet" <notifications@github.com> wrote:












Hey @darrenhaken


It seems the service is available in the Go SDK and CRUDs operations are also available.

Feel free to open a PR for that, we'll be more than happy to review & help on that :)

**Comment by Ninir** [comment] 2017-08-15 10:04
#### Vendor dependencies
Generally speaking, you first need to vendor the dependencies, as exposed here: https://github.com/terraform-providers/terraform-provider-aws/pull/1417.

#### Connection management
To be able to interact with the SDK and thus the API, you would need to hook the connection, in the aws/config.go file. Then, you would be able to get & use it in the resource.

#### Resource creation
A good start is the plugin provider [documentation page](https://www.terraform.io/docs/plugins/provider.html), along with the [core repository documentation](https://github.com/hashicorp/terraform#developing-terraform).

At first you would need to create a HCL structure that matches the API. This is about creating a schema, which is an abstraction of the resource itself. 

#### Tests
Adding acceptance tests is a good way of testing without the need of compiling yourself but reproducing a real-world use-case.
I encourage you to check what was already made by other contributors, which is a good start.

Once the test is written, run it:

    make testacc TEST=./aws TESTARGS='-run=TestAccAWSResourceGlueClassifier_'

This will run only the test with name prefix being `TestAccAWSResourceGlueClassifier_`.

#### Documentation
The documentation is a required step for people to use it. It should be crystal clear about how to use each options, what is required, optional.
Again, I encourage you to check what was already done, will help a lot 😄 

#### Global example
Check out [this example](https://github.com/terraform-providers/terraform-provider-aws/commit/106b7ea6cbed6665297697dc3389b85498314f27) about hooking into the SDK, resource, tests, documentation, etc.

Also, as per the 0.10 providers split, you may then need to build your local provider version using the [README page](https://github.com/terraform-providers/terraform-provider-aws) to check it locally.

Last bit, if you could open a PR for the vendoring, and then 1 for each resource, it would be awesome.
For instance, 1 PR for the classifier + tests + doc, 1 for the devendpoint + tests + doc, etc.
If you need any review (even in a WIP), just ask :)

Have fun :)

**Comment by drewsonne** [comment] 2018-01-12 07:08
I'm (probably) going to work my way through the resources. If anyone has any wishes as to which resource they would want after the above database resource, let me know. 

I'm taking requests, but can't promise anything.

**Comment by darrenhaken** [comment] 2018-01-12 07:41
@drewsonne I'd like the crawlers next and complete the data catalogue part of the product.

Do you need any help working on it?

**Comment by bflad** [comment] 2018-01-12 14:32
The `aws_glue_catalog_database` resource has been released in [terraform-provider-aws version 1.7.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#170-january-12-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by darrenhaken** [comment] 2018-01-12 14:43
When did that land?

________________________________

**Comment by darrenhaken** [comment] 2018-01-15 09:36
@drewsonne have you done any work on the crawlers? If not I will pick this up.

**Comment by drewsonne** [comment] 2018-01-15 10:15
I have not yet. My first plan was to build a test case with test steps in a similiar manner to the database catalogue. I might get onto this in the test week, but let me know how you go and if you start work on this in another repo

**Comment by darrenhaken** [comment] 2018-01-15 13:22
@drewsonne I'll take a look at the Crawlers. Is the vendor code up to date and contains the AWS SDK API for it?

**Comment by drewsonne** [comment] 2018-01-15 13:29
Can't remember, but it's in the vendor json file

**Comment by drewsonne** [comment] 2018-01-15 19:03
@darrenhaken I've added a skeleton test case for the crawler here. https://github.com/drewsonne/terraform-provider-aws/commit/2dcd3c6c4eaafae76ac6e45301e24113441c78d9 . It's by no means exhaustive, but would definitely be a start.

Not sure how you want to do this, but that's a start for you.

**Comment by darrenhaken** [comment] 2018-01-16 12:43
@drewsonne thanks, I'll use that to start looking at it.

**Comment by darrenhaken** [comment] 2018-01-18 12:00
@drewsonne I'm pretty close to having the crawlers finished

**Comment by drewsonne** [comment] 2018-01-18 16:36
@darrenhaken sweet, I assume it's the "glue_crawlers" branch in your repo?

**Comment by darrenhaken** [comment] 2018-01-18 18:27
@drewsonne that's the one. I haven't pushed it because I've been wrangling some issues with defining a schema.

Have you done much with TF before? Maybe you can provide a pointer or two if I show you.

**Comment by drewsonne** [comment] 2018-01-20 17:10
@darrenhaken I've got a bit of experience writing providers. What are the issues you've been wrangling with the schema specifically?

**Comment by darrenhaken** [comment] 2018-01-21 20:01
@drewsonne I'm working on creating the Crawler with the required fields `Name`, `DatabaseName` and `Targets`. See https://docs.aws.amazon.com/sdk-for-go/api/service/glue/#CreateCrawlerInput

Here is the struct definition for Targets:

```
type CrawlerTargets struct {

    // Specifies JDBC targets.
    JdbcTargets []*JdbcTarget `type:"list"`

    // Specifies Amazon S3 targets.
    S3Targets []*S3Target `type:"list"`
    // contains filtered or unexported fields
}
```
What I am trying to work out is what is the correct TF schema to map to the CrawlerTargets struct. I made an attempt in the acceptance test to do this but I didn't get any luck.

FYI the acceptance test isn't complete yet - you need to have an AWS account with an S3 bucket and an AWS Glue DB.

**Comment by drewsonne** [comment] 2018-01-22 08:39
In these cases (and I think there's some precedence for this, but I can not remember where), I would flatten the schema a bit, eg:

```golang
"s3_targets": {
	Type:          schema.TypeList,
	Optional:      true,
	MinItems:      1,
	Elem: &schema.Resource{
		Schema: map[string]*schema.Schema{
			"path": {
				Type:     schema.TypeString,
				Required: true,
			},
			"exclusions": {
				Type:     schema.TypeSet,
				Optional: true,
				Elem:     schema.TypeString,
			},
		},
	},
},
"jdbc_targets": {
	Type:          schema.TypeList,
	Optional:      true,
	MinItems:      1,
	Elem: &schema.Resource{
		Schema: map[string]*schema.Schema{
			"connection_name": {
				Type:     schema.TypeString,
				Required: true,
			},
			"path": {
				Type:     schema.TypeString,
				Required: true,
			},
			"exclusions": {
				Type:     schema.TypeSet,
				Optional: true,
				Elem:     schema.TypeString,
			},
		},
	},
},
```

I think this is simpler as the two top-level attributes have very specific schemas. And then put them back into the schema structure back in the Read/Write/Update handlers.

Hoping maybe @Ninir, @bflad, or @radeksimko would weigh in on this?

**Comment by darrenhaken** [comment] 2018-01-22 08:58
@drewsonne I'd thought about flattening the schema. The only drawback is that it affects required fields, you only need s3_targets **or** jdbc_targets so declaring them as both being required doesn't make sense.

**Comment by bflad** [comment] 2018-01-22 12:20
In general, we tend to prefer to follow the AWS API/schema unless the user experience can be heavily improved by doing our own implementation due to future maintenance costs.

While we cannot set a `Required: true` type schema definition to say require one of `s3_targets` or `jdbc_targets` (at the moment anyways -- its a decent request we could use in other places as well and probably worth submitting a feature request upstream into Terraform core), we can do the logic in create/update to essentially require one or the other.

e.g. something like this should do the trick
```go
jdbc_targets, jdbc_targets_ok := d.GetOk("jdbc_targets")
s3_targets, s3_targets_ok := d.GetOk("s3_targets")
if !jdbc_targets_ok && !s3_targets_ok {
    return fmt.Errorf("jdbc_targets or s3_targets configuration is required")
}
```

**Comment by darrenhaken** [comment] 2018-01-22 12:58
@bflad that makes sense. I'll look at combining both yours and @drewsonne suggestions.

**Comment by drewsonne** [comment] 2018-01-25 06:26
btw, @darrenhaken if you keep your git branch up to date, I can write some acceptance tests for you with the S3 bucket and the glue db and even run them.

**Comment by darrenhaken** [comment] 2018-01-25 06:31
Sure I’ll pull in the changes today then that will be handy

________________________________

**Comment by darrenhaken** [comment] 2018-01-25 06:32
I can give you write permissions to the branch if you’d like?

________________________________

**Comment by cemo** [comment] 2018-02-16 20:05
@darrenhaken what is the situation of your work? Any progress?

**Comment by darrenhaken** [comment] 2018-02-19 07:50
@cemo I’ll start looking at it again this week. I had to flip back to finishing off another TF PR which has been accepted now. Sorry for the delay!

**Comment by chwevans** [comment] 2018-03-02 22:02
I'm interested in using this as well, is there any expected timeline?

**Comment by darrenhaken** [comment] 2018-03-02 23:06
I’ll add crawlers this week (hopefully) with the required fields added. I will link the repo/branch.

**Comment by darrenhaken** [comment] 2018-03-13 14:59
@drewsonne did you still want to work on this?

**Comment by darrenhaken** [comment] 2018-03-14 16:47
I've been working on this some more and I have an acceptance test with the following TF:

```
resource "aws_glue_catalog_crawler" "test" {
	  name = "test"
	  database_name = "db_name"
	  role = "${aws_iam_role.glue.arn}"
	  s3_target {
		path = "s3://bucket"
	  }
	}
	
	resource "aws_iam_role_policy_attachment" "aws-glue-service-role-default-policy-attachment" {
  		policy_arn = "arn:aws:iam::aws:policy/AWSGlueServiceRole"
  		role = "${aws_iam_role.glue.arn}"
	}
	
	resource "aws_iam_role" "glue" {
  		name = "AWSGlueServiceRoleDefault"
  		assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "glue.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
	}
```

I receive the following error:
```
=== RUN   TestAccAWSGlueCrawler_full
--- FAIL: TestAccAWSGlueCrawler_full (13.25s)
	testing.go:513: Step 0 error: Error applying: 2 error(s) occurred:

		* aws_iam_role_policy_attachment.aws-glue-service-role-default-policy-attachment: 1 error(s) occurred:

		* aws_iam_role_policy_attachment.aws-glue-service-role-default-policy-attachment: [WARN] Error attaching policy arn:aws:iam::aws:policy/AWSGlueServiceRole to IAM Role arn:aws:iam::697329683179:role/AWSGlueServiceRoleDefault: ValidationError: The specified value for roleName is invalid. It must contain only alphanumeric characters and/or the following: +=,.@_-
			status code: 400, request id: 43da944e-27a7-11e8-8481-452f34f141d6
		* aws_glue_catalog_crawler.test: 1 error(s) occurred:

		* aws_glue_catalog_crawler.test: error creating Glue crawler: InvalidInputException: Service is unable to assume role arn:aws:iam::697329683179:role/AWSGlueServiceRoleDefault. Please verify role's TrustPolicy
			status code: 400, request id: 4405c2e7-27a7-11e8-9a99-111706a35ce0
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	13.293s
make: *** [testacc] Error 1
```

Any ideas?

**Comment by bflad** [comment] 2018-03-15 06:56
This error is being generated from the AWS API:

```
		* aws_iam_role_policy_attachment.aws-glue-service-role-default-policy-attachment: [WARN] Error attaching policy arn:aws:iam::aws:policy/AWSGlueServiceRole to IAM Role arn:aws:iam::697329683179:role/AWSGlueServiceRoleDefault: ValidationError: The specified value for roleName is invalid. It must contain only alphanumeric characters and/or the following: +=,.@_-
			status code: 400, request id: 43da944e-27a7-11e8-8481-452f34f141d6
```

Relevant code:

https://github.com/terraform-providers/terraform-provider-aws/blob/cc36c1d6c312b0e2cc024f97bb35ba6b59c3f8c2/aws/resource_aws_iam_role_policy_attachment.go#L41-L44

It looks like we're missing some validation to ensure its an IAM role name being passed in instead of a IAM role ARN (or properly handle this situation by parsing the name out of the ARN). We should probably make a separate issue for that. 😉 

You can fix your Terraform configuration by changing the `role` attribute to use `name` of `arn` for
 now 👍 

```hcl
resource "aws_iam_role_policy_attachment" "aws-glue-service-role-default-policy-attachment" {
  policy_arn = "arn:aws:iam::aws:policy/AWSGlueServiceRole"
  role = "${aws_iam_role.glue.name}"
}
```

**Comment by darrenhaken** [comment] 2018-03-15 07:04
I've tried the name and I still had the same issue. I'll be in the office in a couple of hours, I'll push my WIP on my fork if you wouldn't mind taking a look? The error is raised by Amazon around the crawler input and something about trust policy.

Any help is appreciated :-)

**Comment by darrenhaken** [comment] 2018-03-15 14:00
@bflad here is the changed code:

```
resource "aws_glue_catalog_crawler" "test" {
	  name = "test"
	  database_name = "db_name"
	  role = "${aws_iam_role.glue.name}"
	  s3_target {
		path = "s3://bucket"
	  }
	}
	
	resource "aws_iam_role_policy_attachment" "aws-glue-service-role-default-policy-attachment" {
  		policy_arn = "arn:aws:iam::aws:policy/AWSGlueServiceRole"
  		role = "${aws_iam_role.glue.name}"
	}
	
	resource "aws_iam_role" "glue" {
  		name = "AWSGlueServiceRoleDefault"
  		assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "glue.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
	}
```

**Comment by bflad** [comment] 2018-03-22 15:55
Hi, everyone! :wave: I'm going to split this work into more manageable issues so that there can be a clear definition of done for various support. Looking at the API, here are what look like relevant resources and data sources for Terraform to manage with the AWS Glue service:

* New `aws_glue_classifier` resource: #3873
* New `aws_glue_connection` resource: #3874
* New `aws_glue_crawler` resource: #3875
* New `aws_glue_dev_endpoint` resource: #3876
* New `aws_glue_job` resource: #3877
* New `aws_glue_partition` resource: #3878
* New `aws_glue_script` data source: #3879
* New `aws_glue_table` resource: #3880
* New `aws_glue_trigger` resource: #3882
* New `aws_glue_user_defined_function` resource: #3883

Please follow along the split issues and note any that you would like to contribute in the new issues. Personally, I will be picking up connections and jobs shortly. Thanks!

**Closed by bflad** 2018-03-22 15:55 UTC
Labels: new-resource, service/glue
