### ISSUE TITLE
Terraform not reading aws credentials file

### ISSUE THREAD

**Issue by iKarthik** [terraform-providers/terraform-provider-aws#1695] opened 2017-09-19 02:23 UTC
When doing a terraform plan, i expect terraform to read my aws credentials file located in /Users/myuser/.aws/credential. But instead I get the below as the response

**Terraform Version:  **v0.10.2****
**Debug Output**
Error running plan: 1 error(s) occurred:
* provider.aws: No valid credential sources found for AWS Provider.
  Please see https://terraform.io/docs/providers/aws/index.html for more information on
  providing credentials for the AWS Provider 

**Expected Behaviour**
I expect Terraform to read the credentials file and use them to authenticate with AWS

**Actual Behavior**
Terraform fails to run plan because it can't find the proper credentials.

**Steps to Reproduce**
Use the following test case
```
provider "aws" {
  region = "us-east-1"
  shared_credentials_file = "/Users/karthikbalasubramanian/.aws/credentials"
  profile = "testing"
}
resource "aws_instance" "example" {
  ami           = "ami-2757f631"
  instance_type = "t2.micro"
}
```

And here is my credential file

```
[testing]
aws_access_key = ********
aws_secret_access_key = *******
```

**Comment by trung** [comment] 2017-09-25 15:29
`aws_access_key_id` instead of `aws_access_key` in your credential file? 
If that doesn't work, you could run with TF_LOG=DEBUG and paste the output here for easy troubleshooting

**Comment by iKarthik** [comment] 2017-09-27 11:39
Thanks for the info, that change seemed to have worked. can someone update the document here https://www.terraform.io/intro/getting-started/build.html, it still says 
> 
Replace the ACCESS_KEY_HERE and SECRET_KEY_HERE with your AWS access key and secret key, available from this page. We're hardcoding them for now, but will extract these into variables later in the getting started guide.


Thanks
K

**Comment by trung** [comment] 2017-09-27 15:41
I don't see any issue with the doc which refers to `access_key` and `secret_key` attributes in `provider` block.
Whereas you use `shared_credentials_file` attribute and the format of the credential file has to follow [AWS guide](https://aws.amazon.com/blogs/security/a-new-and-standardized-way-to-manage-credentials-in-the-aws-sdks/).

**Comment by radeksimko** [comment] 2017-10-23 14:04
@trung is right - the format needs to follow the mentioned guide, i.e.

```
aws_access_key_id = ACCESS_KEY
aws_secret_access_key = SECRET_KEY
```

I'm going to close this issue as Terraform works as intended here.

**Closed by radeksimko** 2017-10-23 14:04 UTC
Labels: question
