### ISSUE TITLE
When attached to a NIC, `aws_eip does not contain attributes `network_interface`, `private_dns` and `private_ip` on first run.

### ISSUE THREAD

**Issue by guillaumedonval** [terraform-providers/terraform-provider-aws#15093] opened 2020-09-09 19:47 UTC
Hello !

Here’s a code sample that breaks idempotency:

```terraform
data "aws_vpc" "default" {
  default = true
}

data "aws_subnet_ids" "default" {
  vpc_id = data.aws_vpc.default.id
}

resource "aws_eip" "test" {
  vpc = true
}

resource "aws_eip_association" "test" {
  network_interface_id = aws_network_interface.test.id
  allocation_id        = aws_eip.test.id
}

resource "aws_network_interface" "test" {
  subnet_id = flatten(data.aws_subnet_ids.default.ids)[0]
}

output "test" {
  value = aws_eip.test
}
```

First run: no `network_interface`, `private_dns` nor `private_ip` in output.
Second run: the output contains `network_interface`, `private_dns` and `private_ip`.

I expect consecutive runs to be consistent.

Thanks!

Versions:
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/aws v3.5.0

(also tested with Terraform 0.12.29)

**Comment by bflad** [comment] 2020-09-11 00:46
Hi @guillaumedonval 👋  Thank you for submitting this.

In Terraform, each individual resource is executed once on the execution graph. Terraform Providers, such as the Terraform AWS Provider, cannot influence this behavior. In the given configuration, since the `aws_eip_association` resource is being separately used from the `aws_eip` resource, the `aws_eip` resource is created and saved into the Terraform state, then the `aws_eip_association` resource is created and saved into the Terraform state. Terraform, nor the Terraform AWS Provider, can go back and fill in the details of the `aws_eip` resource until it is fully refreshed during a second Terraform run (`terraform refresh` or `terraform apply`) with that configuration.

In this case, it may be possible to get this information in a single Terraform run by either using `network_interface` argument in the `aws_eip` resource instead of the `aws_eip_association` resource, e.g.

```terraform
resource "aws_eip" "test" {
  network_interface = aws_network_interface.test.id
  vpc               = true
}
```

Or adding a followup data source into the graph that can fetch the updated information, e.g.

```terraform
# Please note: Using a data source when the same resource is present is typically an anti-pattern,
# however in this case, the EIP information is not available until after the association.
data "aws_eip" "test" {
  id = aws_eip_association.test.allocation_id
}

output "test" {
  value = data.aws_eip.test
}
```

The first solution is generally preferable though. Given this is expected behavior in this case and the Terraform AWS Provider cannot change it, I'm going to close this issue. If you have followup questions, we would recommend posting them on the [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help.

**Closed by bflad** 2020-09-11 00:46 UTC
Labels: needs-triage, service/ec2

**Comment by guillaumedonval** [comment] 2020-09-11 19:46
@bflad Thanks for that complete answer.

I simply realise I should not at all use outputs from EIP to read things like private_ips or DNS, because these information belongs to the NIC. `aws_eip` is just forwarding it. I’m wondering then when it would be useful to read such data from the `eip` itself?

Thanks again for the answer!
