### ISSUE TITLE
resource aws_elasticsearch_domain missing encryption at rest

### ISSUE THREAD

**Issue by tsiq-meltahan** [terraform-providers/terraform-provider-aws#3074] opened 2018-01-19 22:52 UTC
Hi there, I see the AWS console supports creating ES clusters with encryption at rest enabled, but I failed to find support for it in the terraform docs for the aws_elasticsearch_domain resource. Is there a plan to support configuring encryption at rest for the aws_elasticsearch_domain resource?

**Comment by radeksimko** [comment] 2018-01-21 16:12
Hi @tsiq-meltahan 
thanks for expressing the interest.

I'm going to close this as a duplicate of #2591 which will be soon addressed by #2632
Feel free to subscribe to either of those issues.

**Closed by radeksimko** 2018-01-21 16:12 UTC
Labels: enhancement, service/elasticsearch
