### ISSUE TITLE
terraform try to recreate ecs service with default launch_type

### ISSUE THREAD

**Issue by loivis** [terraform-providers/terraform-provider-aws#4065] opened 2018-04-05 09:39 UTC
### Terraform Version
Terraform v0.11.5
+ provider.aws v1.13.0
+ provider.external v1.0.0
+ provider.spotinst (unversioned)
+ provider.template v1.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
- ecs_service

### Terraform Configuration Files
just create an ecs service without setting `launch_type`, which should have default `EC2`.

### Expected Behavior
ecs is created and a second plan should show no change

### Actual Behavior
second plan tries to replace the resource because of `launch_type` change.
```
      launch_type:                                 "" => "EC2" (forces new resource)
```

### Steps to Reproduce
`TestAccAWSEcsService_withLaunchTypeEC2AndNetworkConfiguration` is failing because of the same error. It seems like aws is not returning default launch type.

**Comment by s-maj** [comment] 2018-04-05 09:47
Some issue using TERRAFORM_VERSION=0.11.2 and PROVIDER_AWS_VERSION=1.7.0 in eu-west-1.

**Comment by sterfield** [comment] 2018-04-05 10:08
Got the same issue even with setting `launch_type` to EC2.

What's really strange is that it seems to work in some regions but not in others.

State is not updated in us-east-2, but it's updated fine in us-east-1 and us-west-2 (I went directly looking at state file to ensure of the values).

TF v 0.10.8, and tested many AWS providers, including the latest one, same issue.

Thanks !

**Comment by loivis** [comment] 2018-04-05 10:12
Even if you set `launch_type` to `EC2`, it's not set in terraform state because aws doesn't return the attribute. We're in `eu-west-1` with the issue. It looks like AWS is rolling out the change.

**Comment by Puneeth-n** [comment] 2018-04-05 10:14
@loivis I was just about to create this issue. This is so much crap.

**Comment by bamdadd** [comment] 2018-04-05 10:15
We have the same problem with terraform version `0.11.3` and aws provider: `1.13`. Its introducing down time on our deployments as it keeps destroying the ecs service and recreating it which takes longer that just updating task definition.

**Comment by hazmeister** [comment] 2018-04-05 10:24
@joffreydupire getting the same issue with terraform 0.10.8

**Comment by sterfield** [comment] 2018-04-05 10:26
Hmm that's weird. I'm using 0.10.8 and the ignore_changes just fixed it. I can see in the state that the field is still empty, but TF is now happy.

**Comment by Puneeth-n** [comment] 2018-04-05 10:29
@sterfield Can confirm! fixed it!
```hcl
 .
 .
 .
  launch_type                        = "EC2"
 .
 .
  lifecycle {
    ignore_changes  = ["launch_type"]
    prevent_destroy = true
  }
```

**Comment by joffreydupire** [comment] 2018-04-05 10:31
@Puneeth-n which tf_version are u using ?

**Comment by bamdadd** [comment] 2018-04-05 10:31
@sterfield @Puneeth-n worked for us too, thanks.

**Comment by Puneeth-n** [comment] 2018-04-05 10:32
@joffreydupire `Terraform: 0.10.8` and `terraform-provider-aws: 0.12.0`

**Comment by bamdadd** [comment] 2018-04-05 10:33
I'm wondering why this is happening today ? has there been any changes to the AWS API today?

**Comment by loivis** [comment] 2018-04-05 10:34
@sterfield `ignore_changes` works with latest terraform and aws provider.

**Comment by Katona** [comment] 2018-04-05 10:38
Another workaround is setting `launch_type = ""` explicitly for the `aws_ecs_service`resource.

**Comment by egarbi** [comment] 2018-04-05 10:46
@Katona the right fix is set launch_type = "EC2"

**Comment by joffreydupire** [comment] 2018-04-05 10:46
Still have ```launch_type:                               "" => "EC2" (forces new resource)``` even with launch_type = "" and ignore_changes on launch_type,

So sad

**Comment by Katona** [comment] 2018-04-05 10:50
@egarbi my assumption is `launch_type` property doesn't exist for ECS services in these regions, so setting `launch_type` to other than `""` doesn't work since Terraform will detect changes. At least, setting it to `""` helped in our case.

**Comment by egarbi** [comment] 2018-04-05 10:54
@katona got it, thanks

**Comment by egarbi** [comment] 2018-04-05 10:59
@joffreydupire  don't use `launch_type` and `ignore_changes` at the same time or you will be invalidating the value set

**Comment by joffreydupire** [comment] 2018-04-05 11:03
@egarbi i've try with launch_type = "" doesn't work, then try with ignore_changes = ["launch_type"] still the same issue

**Comment by lenaing** [comment] 2018-04-05 11:07
I confirm the same behavior with :

- AWS region eu-west-1
- Terraform v0.11.3
- AWS Provider v1.7.0

Both seems ok :
`launch_type = ""`
or 
```
  lifecycle {
    ignore_changes = ["launch_type"]
  }
```

However, as TF isn't persisting the launch_type in the state file and that we can't specifically set it to EC2, does that me that we are at risk to have them launched through fargate ?

**Comment by devvesa** [comment] 2018-04-05 11:14
@lenaing Fortunately not. According to the [ecs_service](https://www.terraform.io/docs/providers/aws/r/ecs_service.html):

    launch_type - (Optional) The launch type on which to run your service. The valid values are EC2 and FARGATE. Defaults to EC2.

**Comment by devvesa** [comment] 2018-04-05 11:16
BTW, I am starting looking these changes too in our loadbalancers:

      ~ module.webclient.aws_alb.prod-extelb-webclient                                                                                           │not based on any personally identifiable information. To create
      enable_cross_zone_load_balancing:          "" => "false"    

Am I the only one? 

(Sorry for the pseudo-offtopic)

**Comment by Puneeth-n** [comment] 2018-04-05 11:53
@loivis Looks like the aws_ecs_service is not updated when the new task definition is created
```hcl
resource "aws_ecs_task_definition" "service" {
  count                 = "${var.enable}"
  family                = "${var.name}-${var.environment}"
  container_definitions = "${var.container_definition}"
  task_role_arn         = "${var.task_role_arn}"
  network_mode          = "${var.network_mode}"
}

resource "aws_ecs_service" "service" {
  count                              = "${var.enable * var.alb_listener_count > 0 ? 1 : 0}"
  name                               = "${var.name}"
  cluster                            = "${var.cluster_id}"
  task_definition                    = "${aws_ecs_task_definition.service.arn}"
  launch_type                        = "EC2"
  desired_count                      = "${lookup(var.capacity, "desired", 1)}"
  iam_role                           = "${aws_iam_role.ecs_lb_role.arn}"
  deployment_maximum_percent         = "${var.max_healthy_percent}"
  deployment_minimum_healthy_percent = "${var.min_healthy_percent}"

  placement_strategy    = "${var.placement_strategy}"
  placement_constraints = "${var.placement_constraints}"

  load_balancer {
    target_group_arn = "${aws_alb_target_group.service.arn}"
    container_name   = "${var.name}"
    container_port   = "${lookup(var.port_mappings[0], "containerPort")}"
  }

  depends_on = ["aws_iam_role.ecs_lb_role", "aws_ecs_task_definition.service"]

  lifecycle {
    ignore_changes  = ["launch_type"]
    prevent_destroy = true
  }
}
```

**Comment by s-maj** [comment] 2018-04-05 12:16
@Puneeth-n it seems to be caused by:
```
lifecycle {
  ignore_changes = ["desired_count", "launch_type"]
}
```
but if you use `launch_type = ""` instead, it works fine.

**Comment by Puneeth-n** [comment] 2018-04-05 12:26
@s-maj The solution that works for me is `launch_type = ""` and then a new task definition is created and ECS service updated. so ```hcl
lifecycle {
  ignore_changes = ["launch_type"]
}
``` is a bad idea

**Comment by sterfield** [comment] 2018-04-05 13:04
@Puneeth-n I don't see why.

There's a change on `launch_type`, TF ignores that and this lead to `No changes`.

If you have a problem where setting `launch_type` as `ignore_changes` doesn't update your service accordingly, that's a separate issue.

I don't see how ignoring this field, which is a default one both in AWS and TF can create any problem.

I have still explicitly defined `launch_type` to `EC2` because explicit > implicit, but it's just to be on the safe side.

**Comment by Puneeth-n** [comment] 2018-04-05 13:30
@sterfield Me neither! Honestly ATM I don't have enough time to look into it. I just said what works for me.

**Comment by oarmstrong** [comment] 2018-04-05 15:36
The API definitely isn't returning `launchType` for my services. Could we default to `EC2` for these cases?

Presumably the SDK is returning us a blank string here:

https://github.com/terraform-providers/terraform-provider-aws/blob/6afb81fba282818c76c9006e4979d7663cf9b420/aws/resource_aws_ecs_service.go#L409

**Comment by bflad** [comment] 2018-04-05 15:41
The open PR here will likely be merged and released to handle this scenario: #4066 

I was doing some investigative work on the different regions and responses before merging, but it does not seem like the information returned from the ECS API moved somewhere else in the response.

**Comment by oarmstrong** [comment] 2018-04-05 15:51
Ha, I missed that - exactly what I was suggesting in my previous comment.

**Comment by aaithal** [comment] 2018-04-05 16:30
Hi All,

We identified a transient scenario where the launchType field was not being returned in the describe service calls. We have addressed it and confirmed that it is is now appearing in all API responses.

Thanks,
Anirudh

**Comment by bflad** [comment] 2018-04-05 16:31
Thanks @aaithal! I was just about to post that I could no longer reproduce this in eu-west-1 and us-east-2. It seems to be working as before.

**Comment by Puneeth-n** [comment] 2018-04-05 16:34
@aaithal 🙏

**Comment by bflad** [comment] 2018-04-05 16:46
Closing this issue out as the ECS API responses should now be working same as before. Please write in if there is reason to reopen this issue.

**Closed by bflad** 2018-04-05 16:46 UTC
Labels: bug, service/ecs, upstream

**Comment by ricardson** [comment] 2018-04-30 00:37
Hi all,

The same problem here today, I'm using FARGATE. (terraform version: 0.11.7 and aws provider v1.16.0)

```
-/+ aws_ecs_service.high (new resource required)
      id:                                                 "arn:aws:ecs:us-east-1:543614741373:service/enju-workers-high" => <computed> (forces new resource)
      cluster:                                            "arn:aws:ecs:us-east-1:543614741373:cluster/enjoei-workers" => "arn:aws:ecs:us-east-1:543614741373:cluster/enjoei-workers"
      deployment_maximum_percent:                         "100" => "200"
      deployment_minimum_healthy_percent:                 "0" => "100"
      desired_count:                                      "2" => "0"
      iam_role:                                           "aws-service-role" => "aws-service-role"
      launch_type:                                        "FARGATE" => "FARGATE"
      name:                                               "enju-workers-high" => "enju-workers-high"
      network_configuration.#:                            "1" => "0"
      network_configuration.0.assign_public_ip:           "true" => "false"
      network_configuration.0.security_groups.#:          "1" => "0"
      network_configuration.0.security_groups.1058997031: "sg-485f8b34" => ""
      network_configuration.0.subnets.#:                  "4" => "0"
      network_configuration.0.subnets.1391951714:         "subnet-7bc1ed32" => ""
      network_configuration.0.subnets.1721701309:         "subnet-78502423" => ""
      network_configuration.0.subnets.2707220468:         "subnet-c949f3f5" => ""
      network_configuration.0.subnets.28458670:           "subnet-9c126cb1" => ""
      service_registries.#:                               "1" => "0" (forces new resource)
      service_registries.2155141651.port:                 "0" => "0"
      service_registries.2155141651.registry_arn:         "arn:aws:servicediscovery:us-east-1:543614741373:service/srv-4j75efeha2kwatwk" => ""
      task_definition:                                    "enju-workers-high-deploy:18" => "arn:aws:ecs:us-east-1:543614741373:service/enju-workers-high"

```

**Comment by jsm** [comment] 2018-10-12 20:49
This is back for me in 1.40, after upgrading from 1.37
