### ISSUE TITLE
Issue with CLB certificate and cookie stickiness

### ISSUE THREAD

**Issue by bauteb-sci** [terraform-providers/terraform-provider-aws#13617] opened 2020-06-04 20:12 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.26
+ provider.archive v1.3.0
+ provider.aws v2.58.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2

### Affected Resource(s)

* aws_elb, aws_app_cookie_stickiness_policy

### Terraform Configuration Files

```
resource "aws_elb" "classic-lb-test" {
  provider                    = aws.proxy
  count                       = 1
  name                        = "clb-test"
  security_groups             = ["sg-123a456b"]
  subnets                     = ["subnet-12345z67"]

  internal                    = true
  cross_zone_load_balancing   = true
  connection_draining         = true
  idle_timeout                = 400
  connection_draining_timeout = 400

  listener {
    instance_port     = 8000
    instance_protocol = "http"
    lb_port           = 80
    lb_protocol       = "http"
  }

  listener {
    instance_port      = 8000
    instance_protocol  = "http"
    lb_port            = 443
    lb_protocol        = "https"
    ssl_certificate_id = "arn:aws:acm:us-east-1:123456789012:certificate/1-a-2-b-3"
  }

  health_check {
    healthy_threshold   = 2
    unhealthy_threshold = 2
    timeout             = 3
    target              = "HTTP:8000/"
    interval            = 30
  }
}

resource "aws_app_cookie_stickiness_policy" "clb-test-cookies" {
  provider                 = aws.proxy
  count                    = 1
  name                     = "${aws_elb.classic-lb-test[0].name}-wlcookie-policy"
  load_balancer            = aws_elb.classic-lb-test[0].id
  lb_port                  = 443
  cookie_name              = "CLB-8080-PORTAL-PSJSESSIONID"
 }
```

### Steps to Reproduce

Apply the original 2 resources.  
Change the ssl_certificate_id for the elb.  The subsequent apply will update the aws_elb {Apply complete! Resources: 0 added, 1 changed, 0 destroyed.}
Now run a plan and the result is:
Terraform will perform the following actions:

  # module.main.module.raw-test.aws_app_cookie_stickiness_policy.clb-test-cookies[0] will be created
  + resource "aws_app_cookie_stickiness_policy" "clb-test-cookies" {
      + cookie_name   = "CLB-8080-PORTAL-PSJSESSIONID"
      + id            = (known after apply)
      + lb_port       = 443
      + load_balancer = "clb-test"
      + name          = "clb-test-wlcookie-policy"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

### Expected Behavior

The apply of the certificate change indicated 0 destroyed, but it clearly did destroy the stickiness policy.  It should either not destroy it as indicated or automatically put it back without having to run a second apply.

Thanks

**Comment by ewbankkit** [comment] 2020-06-05 15:41
@bauteb-sci Thanks for opening this issue.
It is a duplicate of #187. Please add any comments to that issue.

**Closed by ewbankkit** 2020-06-05 15:41 UTC
Labels: needs-triage, service/elb
