### ISSUE TITLE
Add reader connection endpoint for aws_elasticache_replication_group

### ISSUE THREAD

**Issue by Shivang44** [terraform-providers/terraform-provider-aws#11313] opened 2019-12-16 19:45 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating an elasticache redis cluster (with cluster mode disabled) you get a "primary" endpoint and a read-only "reader" endpoint. The aws_elasticache_replication_group doesn't output the reader endpoint, despite this information being displayed (both the primary and reader) when you click the redis cluster in AWS: https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Endpoints.html

### New or Affected Resource(s)

`aws_elasticache_replication_group`

### Attempted Solutions

A workaround right now is to `replace` the word "master" in the primary endpoint with "replica". However this seems brittle as AWS could change their naming scheme. It would be nice to use the `Reader URL` returned directly in the AWS response.

### Proposal

add `reader_endpoint_address` to the output of `aws_elasticache_replication_group`

**Comment by dntosas** [comment] 2020-01-26 12:08
@Shivang44 check this https://github.com/terraform-providers/terraform-provider-aws/pull/6014

**Comment by brettcave** [comment] 2020-02-24 21:23
Duplicate of #10519

**Comment by anGie44** [comment] 2020-08-24 19:27
Closing as it is a duplicate and #10519 is still open.

**Closed by anGie44** 2020-08-24 19:27 UTC
Labels: enhancement
