### ISSUE TITLE
Feature: Support multiple TLS certificates on an ALB / ELBv2 listener

### ISSUE THREAD

**Issue by pranspach** [terraform-providers/terraform-provider-aws#1947] opened 2017-10-17 21:05 UTC
With AWS's recent announcement for [multiple TLS certificates on a single listener](https://aws.amazon.com/blogs/aws/new-application-load-balancer-sni/), I'd like to see this supported in Terraform.

From AWS cli:
`aws elbv2 add-listener-certificates --listener-arn <listener-arn> --certificates CertificateArn=<cert-arn>`

### Current Terraform Configuration Files
```hcl
resource "aws_lb_listener" "front_end" {
  certificate_arn   = "arn:aws:iam::187416307283:server-certificate/test_cert_rab3wuqwgja25ct3n4jdj2tzu4"
}
```

From the current terraform configuration syntax I don't see how to attach multiple certificate arns. Is this on the roadmap?

**Comment by longwave** [comment] 2017-10-18 19:34
Duplicate of #1853

**Comment by radeksimko** [comment] 2017-10-23 14:17
Closing in favour of https://github.com/terraform-providers/terraform-provider-aws/issues/1853

**Closed by radeksimko** 2017-10-23 14:17 UTC
Labels: enhancement
