### ISSUE TITLE
AWS ECS services are force updated on each apply

### ISSUE THREAD

**Issue by EmmN** [terraform-providers/terraform-provider-aws#2345] opened 2017-11-17 12:18 UTC
After the aws plugin update from 1.2.0 to 1.3.0 I started to see that on each apply terraform was doing `(forces new resource)` on the same services.

Something is broken in the delta checking between the current state and the actual infrastructure.

I've fixed the issue by setting `version = "~> 1.2.0"` 

From what I've debugged, the `container_definition` of the service is containing the JSON instead of a hash which identifies the definition.

**Comment by myoung34** [comment] 2017-11-17 14:29
Im filing a bug for this also, it happens in a lot of other resources
Will attach output as proof

**Comment by radeksimko** [comment] 2017-11-17 17:45
I believe this is a duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/2336 which has a proposal of solution in https://github.com/terraform-providers/terraform-provider-aws/pull/2339

For that reason I'm going to close this issue, but we'd certainly use some of your help in testing #2339

**Closed by radeksimko** 2017-11-17 17:45 UTC
