### ISSUE TITLE
No RAM Resource Share (arn:aws:ram:eu-west-2:XXXXXXX:resource-share/XXXXXXXXXXXXX) invitation found

### ISSUE THREAD

**Issue by scott-mccracken-friday** [terraform-providers/terraform-provider-aws#11785] opened 2020-01-28 16:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.20
+ provider.aws v2.46.0

### Affected Resource(s)

* aws_ram_resource_share_accepter

### Terraform Configuration Files

```hcl



// First account owns the transit gateway and accepts the VPC attachment.
provider "aws" {
  alias = "first" 
}

provider "aws" {
  alias  = "alternate"
  region = "eu-west-2"
  assume_role {
    role_arn     = "arn:aws:iam::XXXXXX:role/XXXXXXXX"
    session_name = "XXXXXXXX"
  }
}



resource "aws_ram_resource_share" "sender_share" {
  provider = "aws.alternate"

  name                      = "tf-test-resource-share"
  allow_external_principals = true

  tags = {
      Name = "tf-test-resource-share"
  }
}

resource "aws_ram_principal_association" "sender_invite" {
  provider = "aws.alternate"

  principal          = data.aws_caller_identity.receiver.account_id
  resource_share_arn = aws_ram_resource_share.sender_share.arn
  depends_on = [aws_ram_resource_share.sender_share]
}

data "aws_caller_identity" "receiver" {}

resource "aws_ram_resource_share_accepter" "receiver_accept" {
  share_arn = aws_ram_principal_association.sender_invite.resource_share_arn
  depends_on = [aws_ram_principal_association.sender_invite, aws_ram_resource_share.sender_share]
}

```

### Panic Output

Error: No RAM Resource Share (arn:aws:ram:eu-west-2:XXXXXXXXX:resource-share/XXXXXXXXXXX) invitation found

NOTE: If both AWS accounts are in the same AWS Organization and RAM Sharing with AWS Organizations is enabled, this resource is not necessary

### Expected Behavior

aws_ram_resource_share_accepter accepts a connection in another AWS account.

### Actual Behavior

aws_ram_resource_share_accepter throws an error.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The error appears sporadically. It appears to be dependent on the speed of the network. When running on a slow connection (locally), it succeeds. When running on EC2/through CI, it appears to fail (however, works on a re-run).

### References

* #0000

**Comment by joerg** [comment] 2020-01-31 14:52
I am seeing the same behavior/problem here at my setup. Last week I created a Transit Gateway and resource shares across a few accounts, today I receive the above errors.

```
% terraform apply
[long output omitted]
Error: No RAM Resource Share (arn:aws:ram:eu-central-1:994929050802:resource-share/b6b70cb4-d009-2817-d33a-73456b6a1135) invitation found

NOTE: If both AWS accounts are in the same AWS Organization and RAM Sharing with AWS Organizations is enabled, this resource is not necessary

  on account_bytesource_production.tf line 31, in resource "aws_ram_resource_share_accepter" "bytesource_production_receiver_accept":
  31: resource "aws_ram_resource_share_accepter" "bytesource_production_receiver_accept" {

% terraform --version
Terraform v0.12.20
+ provider.aws v2.47.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
+ provider.tls v2.1.1
```

Checking manually I can confirm that the resource share exists and everything is working from a network perspective (the Transit Gateway in my case). Also the resource share ID does exist, so the error message that no RAM invite was found must be misleading in some way.
The DEBUG logs also show that the AWS API call returns the correct resource share ID
```
2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: 2020/01/31 15:44:46 [DEBUG] setting computed for "resources" from ComputedKeys
2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: 2020/01/31 15:44:46 [DEBUG] [aws-sdk-go] DEBUG: Request RAM/GetResourceShareInvitations Details:
2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: ---[ REQUEST POST-SIGN ]-----------------------------
2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: POST /getresourceshareinvitations HTTP/1.1
2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: Host: ram.eu-central-1.amazonaws.com
2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: User-Agent: aws-sdk-go/1.28.8 (go1.13.5; linux; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.12.20 (+https://www.terraform.io)
2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: Content-Length: 115
2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: Authorization: AWS4-HMAC-SHA256 Credential=<removed>/20200131/eu-central-1/ram/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date;x-amz-security-token, Signature=<removed>
2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: Content-Type: application/json
2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: X-Amz-Date: 20200131T144446Z
2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: X-Amz-Security-Token: <removed>
2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: Accept-Encoding: gzip
2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: 
2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: {"resourceShareArns":["arn:aws:ram:eu-central-1:994929050802:resource-share/b6b70cb4-d009-2817-d33a-73456b6a1135"]}
2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: -----------------------------------------------------
```

Any ideas for a workaround? Currently I can't run my terraform baseline any more because of this.

**Comment by bflad** [comment] 2020-02-18 14:55
The fix for this has been merged and will release with version 2.50.0 of the Terraform AWS Provider, Thursday this week. Thanks to @benoit74 for the implementation. 👍

**Closed** 2020-02-18 14:54 UTC
Labels: bug, service/ram, service/sts

**Comment by chriswise-pac** [comment] 2020-03-02 17:28
> I am seeing the same behavior/problem here at my setup. Last week I created a Transit Gateway and resource shares across a few accounts, today I receive the above errors.
> 
> ```
> % terraform apply
> [long output omitted]
> Error: No RAM Resource Share (arn:aws:ram:eu-central-1:994929050802:resource-share/b6b70cb4-d009-2817-d33a-73456b6a1135) invitation found
> 
> NOTE: If both AWS accounts are in the same AWS Organization and RAM Sharing with AWS Organizations is enabled, this resource is not necessary
> 
>   on account_bytesource_production.tf line 31, in resource "aws_ram_resource_share_accepter" "bytesource_production_receiver_accept":
>   31: resource "aws_ram_resource_share_accepter" "bytesource_production_receiver_accept" {
> 
> % terraform --version
> Terraform v0.12.20
> + provider.aws v2.47.0
> + provider.null v2.1.2
> + provider.random v2.2.1
> + provider.template v2.1.2
> + provider.tls v2.1.1
> ```
> 
> Checking manually I can confirm that the resource share exists and everything is working from a network perspective (the Transit Gateway in my case). Also the resource share ID does exist, so the error message that no RAM invite was found must be misleading in some way.
> The DEBUG logs also show that the AWS API call returns the correct resource share ID
> 
> ```
> 2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: 2020/01/31 15:44:46 [DEBUG] setting computed for "resources" from ComputedKeys
> 2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: 2020/01/31 15:44:46 [DEBUG] [aws-sdk-go] DEBUG: Request RAM/GetResourceShareInvitations Details:
> 2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: ---[ REQUEST POST-SIGN ]-----------------------------
> 2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: POST /getresourceshareinvitations HTTP/1.1
> 2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: Host: ram.eu-central-1.amazonaws.com
> 2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: User-Agent: aws-sdk-go/1.28.8 (go1.13.5; linux; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.12.20 (+https://www.terraform.io)
> 2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: Content-Length: 115
> 2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: Authorization: AWS4-HMAC-SHA256 Credential=<removed>/20200131/eu-central-1/ram/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date;x-amz-security-token, Signature=<removed>
> 2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: Content-Type: application/json
> 2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: X-Amz-Date: 20200131T144446Z
> 2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: X-Amz-Security-Token: <removed>
> 2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: Accept-Encoding: gzip
> 2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: 
> 2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: {"resourceShareArns":["arn:aws:ram:eu-central-1:994929050802:resource-share/b6b70cb4-d009-2817-d33a-73456b6a1135"]}
> 2020-01-31T15:44:46.426+0100 [DEBUG] plugin.terraform-provider-aws_v2.47.0_x4: -----------------------------------------------------
> ```
> 
> Any ideas for a workaround? Currently I can't run my terraform baseline any more because of this.
> 
> UPDATE: I just found that this will probably be fixed by #11562

I don't think it was - we're still seeing this issue with 2.50

**Comment by benoit74** [comment] 2020-03-02 18:48
Did you already accepted the invitation on the receiving account ? (i.e.
did you already ran "terraform apply" with the ram_resource_share_accepter
? When ? With 2.47.0 or 2.50.0 ?)

Is there any new error message with 2.50.0 ?

Did you tried to import the ram_resource_share_accepter ?

Thanks in advance for your help

Le lun. 2 mars 2020 à 18:28, chriswise-pac <notifications@github.com> a
écrit :

**Comment by chriswise-pac** [comment] 2020-03-03 10:35
@benoit74 I've run some more tests this morning and got it working, the issue was the resource share was created in 2.47.  Recreating it all in 2.50 worked without any problems.

Please feel free to ignore my previous comment! :)

**Comment by benoit74** [comment] 2020-03-03 11:21
Good to know that the fix works.

Your issue is however a good point to be aware of, I did not tested this
specific case of a ressource created with <2.50 ... Obviously it does not
work in a straightforward way. ;-)

What did you exactly had to do to make it work ?

Le mar. 3 mars 2020 à 11:36, chriswise-pac <notifications@github.com> a
écrit :

**Comment by chancez** [comment] 2020-03-12 16:59
I'm also hitting this issue, even with 2.52. The error is simply
```
Error: No RAM Resource Share (arn:aws:ram:us-west-2:XXXXXXX:resource-share/XXXXXXXX) invitation found
```

I tried destroying and recreating the share, re-running it again after to ensure it's not a race condition, but it's failing every time no matter what I do. I see the share invite in the receiver account with a "pending" status.
