### ISSUE TITLE
AWS IAM user import doesn't set force_destroy

### ISSUE THREAD

**Issue by rwolfson** [terraform-providers/terraform-provider-aws#7859] opened 2019-03-07 22:00 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
dev1:terratest20190307$ terraform --version
Terraform v0.11.7
+ provider.aws v1.60.0
```
### Affected Resource(s)

* aws_iam_user

### Terraform Configuration Files

```hcl
dev1:terratest20190307$ cat test.tf
provider "aws" {
  region = "us-east-1"
  profile = "<removed>"
  version = "~> 1.60.0"
}

resource "aws_iam_user" "ross-import-test" {
    name = "ross-import-test"
}

```
### Expected Behavior

I would expect force_destroy to be set on import, so `terraform plan` would not show a divergence. Since I believe this is a TF-side value (not Amazon side), there's no way to have this "properly" set to avoid a state divergence. If this is expected, feel free to close the request.

### Actual Behavior

Terraform always shows a divergence after import, no matter which value force_destroy is set to.

```
dev1:terratest20190307$ terraform import aws_iam_user.ross-import-test ross-import-test
aws_iam_user.ross-import-test: Importing from ID "ross-import-test"...
aws_iam_user.ross-import-test: Import complete!
  Imported aws_iam_user (ID: ross-import-test)
aws_iam_user.ross-import-test: Refreshing state... (ID: ross-import-test)

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

dev1:terratest20190307$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aws_iam_user.ross-import-test: Refreshing state... (ID: ross-import-test)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ aws_iam_user.ross-import-test
      force_destroy: "" => "false"


Plan: 0 to add, 1 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

```

### Steps to Reproduce

1. Import an existing IAM user that has TF configuration associated with it (i.e., `terraform import aws_iam_user.<username> <username>`)
2. Run `terraform plan`

**Comment by ryndaniels** [comment] 2019-12-12 13:51
Hi @rwolfson - Thanks for taking the time to submit this issue. I had a look at this with the most recent versions of Terraform and the AWS Provider and was unable to reproduce this behavior. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md). 🙂

**Closed by ryndaniels** 2019-12-12 13:51 UTC
Labels: needs-triage, service/iam
