### ISSUE TITLE
r/aws_spot_instance_request: Tag-on-create

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#14114] opened 2020-07-09 12:45 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> EC2 Spot now enables customers to tag their Spot Instances Requests on creation.

### New or Affected Resource(s)

* [`aws_spot_instance_request`](https://www.terraform.io/docs/providers/aws/r/spot_instance_request.html)

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/07/amazon-ec2-now-supports-tagging-ec2-spot-instance-requests/).

Requires [AWS SDK v1.33.4](https://github.com/aws/aws-sdk-go/releases/tag/v1.33.4):
* #14000

**Comment by tdmalone** [comment] 2020-08-18 07:08
Possible duplicate of:
- https://github.com/terraform-providers/terraform-provider-aws/issues/32
- https://github.com/terraform-providers/terraform-provider-aws/issues/5207

**Comment by ewbankkit** [comment] 2020-08-18 20:51
@tdmalone Those linked issues refer to being able to specify tags that will be applied to the instance that fulfills the spot fleet request. This issue refers to the tags on the spot instance request itself (which is a separate resource in AWS).
I will update the linked issues with a way to use the new(ish) [`aws_ec2_tag`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_tag) resource to tag the created EC2 instance.

**Comment by bflad** [comment] 2020-08-19 18:05
Support for this has been merged and will release with version 3.3.0 of the Terraform AWS Provider, likely tomorrow. 👍

**Closed** 2020-08-19 18:05 UTC
Labels: enhancement, service/ec2
