### ISSUE TITLE
Dependent aws_alb_listener_rule blocks an aws_alb_target_group from being destroyed

### ISSUE THREAD

**Issue by RobVK-MP** [terraform-providers/terraform-provider-aws#5699] opened 2018-08-28 11:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform - 0.11.7
AWS Provider - 1.33.0

### Affected Resource(s)

* aws_alb_target_group
* aws_alb_listener_rule

### Terraform Configuration Files

```hcl
### HTTPS listener for the load balancer
resource "aws_alb_listener" "bug_demo_listener" {
  port              = "80"
  protocol          = "HTTP"
  load_balancer_arn = "${aws_alb.svc_alb.arn}"

  default_action {
    target_group_arn = "${aws_alb_target_group.svc_alb_default_tg.arn}"
    type             = "forward"
  }
}

### Create a rule for each item in var.AlbListenerRules and forward to the appropriate target group
resource "aws_alb_listener_rule" "bug_demo_rule" {
  listener_arn = "${aws_alb_listener.bug_demo_listener.arn}"

  action {
    type = "forward"
    target_group_arn = "${aws_alb_target_group.bug_demo_tg.arn}"
  }

  condition {
    field = "host-header"
    values = ["test.com"]
  }

  depends_on = ["aws_alb_target_group.bug_demo_tg"]
}

### Create a target group for each rule listed in var.AlbListenerRules
resource "aws_alb_target_group" "bug_demo_tg" {
  name     = "bugtg"
  port     = 8080
  protocol = "HTTP"
  vpc_id   = "${data.terraform_remote_state.mainvpc.vpc_id}"

  health_check {
    protocol            = "HTTP"
    port                = 8080
    healthy_threshold   = "3"
    unhealthy_threshold = "3"
    timeout             = "20"
    path                = "/"
    matcher             = "200-399"
  }
}
```

### Debug Output

https://gist.github.com/RobVK-MP/c4a1846ec3ed1ead78e53396bc9e0be5

### Expected Behavior

When the target group needs to be destroyed, the dependent listener rule should be destroyed first.

### Actual Behavior

The target group cannot be destroyed as the listener is still referencing it. Terraform exits with the above error.

### Steps to Reproduce

1. Create an ALB, ALB listener, ALB listener rule and Target Group all hooked up
2. `terraform apply`
3. Make a change to the target group that requires a rebuild, e.g. change the port
4. `terraform apply`

**Comment by bflad** [comment] 2018-08-28 21:52
Hi @RobVK-MP 👋  Sorry you were running into trouble here.

Does it help if you add the [`create_before_destroy` lifecycle configuration](https://www.terraform.io/docs/configuration/resources.html#create_before_destroy) to the `aws_alb_target_group` resource in this situation? e.g.

```hcl
resource "aws_alb_target_group" "bug_demo_tg" {
  // ... other existing configuration ...
  lifecycle {
    create_before_destroy = true
  }
}
```

This should instruct Terraform to create a new target group, update the listener, then destroy the old target group. Let us know!

**Comment by RobVK-MP** [comment] 2018-08-29 14:37
No, that still doesn't work. Initially it errors out on the name already being in use, so I changed it to use a name_prefix instead. With that it creates the new target group and then still errors on the old target group being in use. It doesn't seem to make any attempts to move the listener rule across to the new target group.

**Comment by bflad** [comment] 2018-08-29 14:46
It would be great if we could get a [Gist](https://gist.github.com) with [debug logging enabled](https://www.terraform.io/docs/internals/debugging.html) so we can further troubleshoot with the `create_before_destroy` added. The expected ordering should be create, update dependencies, then destroy. If you are worried about any sensitive data, it can be encrypted with the [HashiCorp GPG Key](https://keybase.io/hashicorp) or redacted as necessary.

**Comment by RobVK-MP** [comment] 2018-08-29 16:04
I have enabled debug logging and sent the output to file, this is the encrypted result: https://gist.github.com/RobVK-MP/d799b0316452e53924e751aceb81c825

**Comment by bflad** [comment] 2018-08-29 17:03
@RobVK-MP odd, I only see the `DeleteTargetGroup` API call during apply. Are you sure `create_before_destroy` is set in the configuration? I don't think it needs to be applied into the state first before attempting to use it, but I could be wrong.

**Comment by RobVK-MP** [comment] 2018-08-30 07:36
@bflad yeah it's still set. In the state I end up with a primary and a deposed version of the target group. Trying to re-apply it falls over saying the deposed version can't be destroyed.

I've snipped the relevant part of the state and put it in a gist, encrypted, if it helps: https://gist.github.com/RobVK-MP/77989bc3309934fa9dd8d2d4ed7bde04

You can see the dependency from the listener, and the two versions of the target group.

**Comment by bflad** [comment] 2019-11-05 03:22
Hi again @RobVK-MP 👋 I'm not able to reproduce this issue given recent versions of Terraform CLI. There's a good chance there was previously a bug that was fixed with `create_before_destroy` behavior in between then and now.

Here's a working configuration, that allows you to modify the target group without issue:

```hcl
terraform {
  required_providers {
    aws = "2.34.0"
  }

  required_version = "0.12.13"
}

provider "aws" {
  region = "us-east-2"
}

data "aws_availability_zones" "available" {
  state = "available"
}

resource "aws_vpc" "test" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_subnet" "test" {
  count = 2

  availability_zone = data.aws_availability_zones.available.names[count.index]
  cidr_block        = "10.0.${count.index}.0/24"
  vpc_id            = aws_vpc.test.id
}

resource "aws_lb" "test" {
  internal           = true
  load_balancer_type = "application"
  name               = "bflad-testing"
  subnets            = aws_subnet.test[*].id
}

resource "aws_lb_listener" "test" {
  port              = "80"
  protocol          = "HTTP"
  load_balancer_arn = aws_lb.test.arn

  default_action {
    target_group_arn = aws_lb_target_group.test.arn
    type             = "forward"
  }
}

resource "aws_lb_listener_rule" "test" {
  listener_arn = aws_lb_listener.test.arn

  action {
    type = "forward"
    target_group_arn = aws_lb_target_group.test.arn
  }

  condition {
    field = "host-header"
    values = ["test.com"]
  }
}

resource "aws_lb_target_group" "test" {
  name_prefix = "test"
  port        = 80
  protocol    = "HTTP"
  vpc_id      = aws_vpc.test.id

  lifecycle {
    create_before_destroy = true
  }
}
```

```console
$ terraform apply
data.aws_availability_zones.available: Refreshing state...
aws_vpc.test: Refreshing state... [id=vpc-047dfc104115c9f39]
aws_subnet.test[1]: Refreshing state... [id=subnet-01a79dd662ef9fea4]
aws_subnet.test[0]: Refreshing state... [id=subnet-065cd019fdc0ee897]
aws_lb_target_group.test: Refreshing state... [id=arn:aws:elasticloadbalancing:us-east-2:--OMITTED--:targetgroup/bflad-testing/48c38bfe75a8225e]
aws_lb.test: Refreshing state... [id=arn:aws:elasticloadbalancing:us-east-2:--OMITTED--:loadbalancer/app/bflad-testing/06dd1f9dcb7787f6]
aws_lb_listener.test: Refreshing state... [id=arn:aws:elasticloadbalancing:us-east-2:--OMITTED--:listener/app/bflad-testing/06dd1f9dcb7787f6/3c9e1a8fefb00738]
aws_lb_listener_rule.test: Refreshing state... [id=arn:aws:elasticloadbalancing:us-east-2:--OMITTED--:listener-rule/app/bflad-testing/06dd1f9dcb7787f6/3c9e1a8fefb00738/c6d716523e21ca35]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
+/- create replacement and then destroy

Terraform will perform the following actions:

  # aws_lb_listener.test will be updated in-place
  ~ resource "aws_lb_listener" "test" {
        arn               = "arn:aws:elasticloadbalancing:us-east-2:--OMITTED--:listener/app/bflad-testing/06dd1f9dcb7787f6/3c9e1a8fefb00738"
        id                = "arn:aws:elasticloadbalancing:us-east-2:--OMITTED--:listener/app/bflad-testing/06dd1f9dcb7787f6/3c9e1a8fefb00738"
        load_balancer_arn = "arn:aws:elasticloadbalancing:us-east-2:--OMITTED--:loadbalancer/app/bflad-testing/06dd1f9dcb7787f6"
        port              = 80
        protocol          = "HTTP"

      ~ default_action {
            order            = 1
          ~ target_group_arn = "arn:aws:elasticloadbalancing:us-east-2:--OMITTED--:targetgroup/bflad-testing/48c38bfe75a8225e" -> (known after apply)
            type             = "forward"
        }
    }

  # aws_lb_listener_rule.test will be updated in-place
  ~ resource "aws_lb_listener_rule" "test" {
        arn          = "arn:aws:elasticloadbalancing:us-east-2:--OMITTED--:listener-rule/app/bflad-testing/06dd1f9dcb7787f6/3c9e1a8fefb00738/c6d716523e21ca35"
        id           = "arn:aws:elasticloadbalancing:us-east-2:--OMITTED--:listener-rule/app/bflad-testing/06dd1f9dcb7787f6/3c9e1a8fefb00738/c6d716523e21ca35"
        listener_arn = "arn:aws:elasticloadbalancing:us-east-2:--OMITTED--:listener/app/bflad-testing/06dd1f9dcb7787f6/3c9e1a8fefb00738"
        priority     = 1

      ~ action {
            order            = 1
          ~ target_group_arn = "arn:aws:elasticloadbalancing:us-east-2:--OMITTED--:targetgroup/bflad-testing/48c38bfe75a8225e" -> (known after apply)
            type             = "forward"
        }

        condition {
            field  = "host-header"
            values = [
                "test.com",
            ]
        }
    }

  # aws_lb_target_group.test must be replaced
+/- resource "aws_lb_target_group" "test" {
      ~ arn                                = "arn:aws:elasticloadbalancing:us-east-2:--OMITTED--:targetgroup/bflad-testing/48c38bfe75a8225e" -> (known after apply)
      ~ arn_suffix                         = "targetgroup/bflad-testing/48c38bfe75a8225e" -> (known after apply)
        deregistration_delay               = 300
      ~ id                                 = "arn:aws:elasticloadbalancing:us-east-2:--OMITTED--:targetgroup/bflad-testing/48c38bfe75a8225e" -> (known after apply)
        lambda_multi_value_headers_enabled = false
      ~ name                               = "bflad-testing" -> (known after apply)
      + name_prefix                        = "test" # forces replacement
      ~ port                               = 8080 -> 80 # forces replacement
        protocol                           = "HTTP"
        proxy_protocol_v2                  = false
        slow_start                         = 0
      - tags                               = {} -> null
        target_type                        = "instance"
        vpc_id                             = "vpc-047dfc104115c9f39"

      ~ health_check {
          ~ enabled             = true -> (known after apply)
          ~ healthy_threshold   = 5 -> (known after apply)
          ~ interval            = 30 -> (known after apply)
          ~ matcher             = "200" -> (known after apply)
          ~ path                = "/" -> (known after apply)
          ~ port                = "traffic-port" -> (known after apply)
          ~ protocol            = "HTTP" -> (known after apply)
          ~ timeout             = 5 -> (known after apply)
          ~ unhealthy_threshold = 2 -> (known after apply)
        }

      ~ stickiness {
          ~ cookie_duration = 86400 -> (known after apply)
          ~ enabled         = false -> (known after apply)
          ~ type            = "lb_cookie" -> (known after apply)
        }
    }

Plan: 1 to add, 2 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_lb_target_group.test: Creating...
aws_lb_target_group.test: Creation complete after 0s [id=arn:aws:elasticloadbalancing:us-east-2:--OMITTED--:targetgroup/test20191105031709585200000001/c6c3212acb4f5877]
aws_lb_listener.test: Modifying... [id=arn:aws:elasticloadbalancing:us-east-2:--OMITTED--:listener/app/bflad-testing/06dd1f9dcb7787f6/3c9e1a8fefb00738]
aws_lb_listener.test: Modifications complete after 1s [id=arn:aws:elasticloadbalancing:us-east-2:--OMITTED--:listener/app/bflad-testing/06dd1f9dcb7787f6/3c9e1a8fefb00738]
aws_lb_listener_rule.test: Modifying... [id=arn:aws:elasticloadbalancing:us-east-2:--OMITTED--:listener-rule/app/bflad-testing/06dd1f9dcb7787f6/3c9e1a8fefb00738/c6d716523e21ca35]
aws_lb_listener_rule.test: Modifications complete after 0s [id=arn:aws:elasticloadbalancing:us-east-2:--OMITTED--:listener-rule/app/bflad-testing/06dd1f9dcb7787f6/3c9e1a8fefb00738/c6d716523e21ca35]
aws_lb_target_group.test: Destroying... [id=arn:aws:elasticloadbalancing:us-east-2:--OMITTED--:targetgroup/bflad-testing/48c38bfe75a8225e]
aws_lb_target_group.test: Destruction complete after 0s

Apply complete! Resources: 1 added, 2 changed, 1 destroyed.
```

If you are still running into trouble, please submit a fresh bug report following the template and we'll be happy to take another look. 👍

**Closed by bflad** 2019-11-05 03:22 UTC
Labels: needs-triage, service/elbv2
