### ISSUE TITLE
Terraform codepipeline action block doesnt support region to run cross-region lambda function

### ISSUE THREAD

**Issue by mohitdayalzomato** [terraform-providers/terraform-provider-aws#10835] opened 2019-11-11 14:33 UTC
The issue is that the action block for a particular stage in AWS Codepipeline as specified here: https://www.terraform.io/docs/providers/aws/r/codepipeline.html#action doesnt supports region key. While integrating cross-region lambda function to be invoked as a codepipeline stage, it is mandatory. The region needs to be specified as a key value in the codepipeline actions. The json reference of the same is given here: https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-Lambda.html 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by gdavison** [comment] 2019-11-13 00:43
Thanks for taking the time to submit this issue.

This documentation provides some more background on cross-region actions: https://docs.aws.amazon.com/codepipeline/latest/userguide/actions-create-cross-region.html

**Comment by bflad** [comment] 2019-11-13 21:34
@gdavison is this a duplicate of #6871 (or related)?

**Comment by gdavison** [comment] 2019-11-13 21:38
Yes,addressing #6871 would address this one, too. I'm going to close this ticket

**Closed by gdavison** 2019-11-13 21:38 UTC
Labels: enhancement, service/codepipeline
