### ISSUE TITLE
aws_codebuildproject requires two "applys" when created with a new IAM role

### ISSUE THREAD

**Issue by sethcleveland** [terraform-providers/terraform-provider-aws#11741] opened 2020-01-23 21:03 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
terraform -v
Terraform v0.12.20
+ provider.aws v2.45.0
```

### Affected Resource(s)

* aws_codebuild_project

### Terraform Configuration Files

A terraform apply with this module demonstrates the issue - https://github.com/tmknom/terraform-aws-codebuild/tree/master/examples/complete

### Expected Behavior

First `terraform apply` creates the codebuild project successfully.

### Actual Behavior

The first `terraform apply` errors with this message

```
Error: Error creating CodeBuild project: InvalidInputException:

  on ../../main.tf line 6, in resource "aws_codebuild_project" "default":
   6: resource "aws_codebuild_project" "default" {
```

Running `terraform apply` again resolves the issue.

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### Important Factoids

Creating the iam_role and waiting a few seconds seems to resolve this issue. However, that seems to defeat the purpose of a well-contained module.

### References

My best guess is that this is related to the following IAM eventual consistency issues.

- related issue: https://github.com/hashicorp/terraform/issues/15536
- related pull request: https://github.com/terraform-providers/terraform-provider-aws/pull/1165

* #0000

**Comment by bflad** [comment] 2020-01-24 12:55
Hi @sethcleveland 👋 Thank you for reporting this issue and sorry you are running into trouble. This is due to a regression in version 2.45.0 of the Terraform AWS Provider (https://github.com/terraform-providers/terraform-provider-aws/issues/11682) and was resolved in [Terraform AWS Provider version 2.46.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2460-january-23-2020), which was released January 23rd. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading. 👍

**Closed by bflad** 2020-01-24 12:55 UTC
Labels: regression, service/codebuild
