### ISSUE TITLE
It doesn't take effect if delete argument "target_group_arns" from "aws_autoscaling_group"

### ISSUE THREAD

**Issue by ckyoog** [terraform-providers/terraform-provider-aws#1208] opened 2017-07-22 00:56 UTC
### Terraform Version
0.9.11

### Affected Resource(s)
- aws_autoscaling_group

### Terraform Configuration Files
```hcl
resource "aws_autoscaling_group" "ecs" {
  name                 = "${data.template_file.ecs_cluster_name.rendered}-ecs-asg"
  vpc_zone_identifier  = ["${aws_subnet.main.*.id}"]
  min_size             = "${var.asg_min}"
  max_size             = "${var.asg_max}"
 #desired_capacity     = "${var.asg_desired}"   #[1]
  launch_configuration = "${aws_launch_configuration.ecs.name}"

  load_balancers       = ["${aws_elb.sockstunnel_public.name}"]
  target_group_arns    = ["${aws_alb_target_group.portal_public.arn}"]
  
}
```

### Issue Description
If I delete argument "target_group_arns" from "aws_autoscaling_group", then run _plan/apply_, the output message shows "No changes". If you go to AWS console -> "Auto Scaling Groups" -> Tab "Details", you can see the "Target Groups" is not changed, it is supposed to be empty, but it still shows the old setting. 

If I want to delete target groups from auto scaling groups, I must set "target_group_arns" to an empty list, like
```target_group_arns    = []```

**Comment by grubernaut** [comment] 2017-07-24 15:01
Hi @ckyoog, thanks for the issue!

This has the unfortunate side-effect of Terraform not being able to know the difference between an attribute being "removed" and being "empty". 

See: https://github.com/hashicorp/terraform/issues/5290, for more details. 

Feel free to reach out for any more questions, but for now going to close this as it's a duplicate of the core issue linked above. Thanks!

**Closed by grubernaut** 2017-07-24 15:01 UTC

**Comment by ckyoog** [comment] 2017-07-25 18:09
Thank you, I knew it, I knew it must be related to a certain core issue. That's it. It found the root.
