### ISSUE TITLE
Race condition when requesting DNS validated certificate

### ISSUE THREAD

**Issue by patrickherrera** [terraform-providers/terraform-provider-aws#9616] opened 2019-08-04 04:24 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

bash-5.0$ terraform -v
Terraform v0.12.6
provider.aws v2.22.0

### Affected Resource(s)

- aws_acm_certificate
- aws_route53_record
- aws_acm_certificate_validation

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 0.12.6"
  backend "s3" {
    encrypt = "true"
  }
}
provider "aws" {
  version = "~> 2.22"
  region = "ap-southeast-2"
}

resource "aws_acm_certificate" "cert" {
  domain_name = "myapp-pf-api.aws-technet-dev-au.mycompany.online"
  validation_method = "DNS"
  tags = merge(var.common_tags, map("Name", "myapp-pf-api.aws-technet-dev-au.mycompany.online-cert"))

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_route53_record" "cert_validation" {
  name = aws_acm_certificate.cert.domain_validation_options[0].resource_record_name
  type = aws_acm_certificate.cert.domain_validation_options[0].resource_record_type
  records = [aws_acm_certificate.cert.domain_validation_options[0].resource_record_value]

  zone_id = var.hosted_zone_id
  ttl = 60
}

resource "aws_acm_certificate_validation" "cert" {
  certificate_arn = aws_acm_certificate.cert.arn
  validation_record_fqdns = [aws_route53_record.cert_validation.fqdn]
}

```

### Debug Output

https://gist.github.com/patrickherrera/77bf986cb6b830939113b464100c96b6

### Panic Output

None

### Expected Behavior

domain_validation_options should have been read from the certificate and used to complete the validation process:
```
module.cert_creation_validation_apigateway.aws_acm_certificate.cert: Creating...
module.cert_creation_validation_apigateway.aws_acm_certificate.cert: Creation complete after 1s [id=arn:aws:acm:ap-southeast-2:xxx:certificate/yyyy]
module.cert_creation_validation_apigateway.aws_route53_record.cert_validation: Creating...
module.cert_creation_validation_apigateway.aws_route53_record.cert_validation: Still creating... [10s elapsed]
module.cert_creation_validation_apigateway.aws_route53_record.cert_validation: Still creating... [20s elapsed]
module.cert_creation_validation_apigateway.aws_route53_record.cert_validation: Still creating... [30s elapsed]
module.cert_creation_validation_apigateway.aws_route53_record.cert_validation: Still creating... [40s elapsed]
module.cert_creation_validation_apigateway.aws_route53_record.cert_validation: Creation complete after 40s [id=Z3xxxFGZ42__8080xxxafaa2fffeeb677b3d81.ci04cc625193-myapp-pf-api.aws-technet-dev-au.mycompany.online._CNAME]
module.cert_creation_validation_apigateway.aws_acm_certificate_validation.cert: Creating...
module.cert_creation_validation_apigateway.aws_acm_certificate_validation.cert: Still creating... [10s elapsed]
module.cert_creation_validation_apigateway.aws_acm_certificate_validation.cert: Still creating... [20s elapsed]
module.cert_creation_validation_apigateway.aws_acm_certificate_validation.cert: Still creating... [30s elapsed]
module.cert_creation_validation_apigateway.aws_acm_certificate_validation.cert: Still creating... [40s elapsed]
module.cert_creation_validation_apigateway.aws_acm_certificate_validation.cert: Creation complete after 48s [id=2019-08-04 01:03:22 +0000 UTC]
```

### Actual Behavior

```
module.cert_creation_validation_apigateway.aws_acm_certificate.cert: Creating...
module.cert_creation_validation_apigateway.aws_acm_certificate.cert: Creation complete after 2s [id=arn:aws:acm:ap-southeast-2:xxx:certificate/yyyy]

Error: Invalid index
--
  |  
  | on modules/cert-creation-validation/main.tf line 12, in resource "aws_route53_record" "cert_validation":
  | 12:   name = aws_acm_certificate.cert.domain_validation_options[0].resource_record_name
  | \|----------------
  | \| aws_acm_certificate.cert.domain_validation_options is empty list of object
  |  
  | The given key does not identify an element in this collection value.
  |  
  |  
  | Error: Invalid index
  |  
  | on modules/cert-creation-validation/main.tf line 13, in resource "aws_route53_record" "cert_validation":
  | 13:   type = aws_acm_certificate.cert.domain_validation_options[0].resource_record_type
  | \|----------------
  | \| aws_acm_certificate.cert.domain_validation_options is empty list of object
  |  
  | The given key does not identify an element in this collection value.
  |  
  |  
  | Error: Invalid index
  |  
  | on modules/cert-creation-validation/main.tf line 14, in resource "aws_route53_record" "cert_validation":
  | 14:   records = [aws_acm_certificate.cert.domain_validation_options[0].resource_record_value]
  | \|----------------
  | \| aws_acm_certificate.cert.domain_validation_options is empty list of object
  |  
  | The given key does not identify an element in this collection value.
  |  
  | 🚨 Error: The command exited with status 1
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This has only started happening in the last few days (since about July 31st).
**I am based in Australia**, and this particular application generates two certificates: 
- one in `ap-southeast-2` for an API Gateway, 
- one in `us-east-1` for CloudFront

The `us-east-1` cert always succeeds, and we are using a module to generate the cert and validate it so the same code is used for both, only a different AWS Provider is passed in with the correct region.
Furthermore, when I apply this Terraform on my home laptop, it always succeeds, but when it runs in a cloud CI agent also in `ap-southeast-2`, it always fails.

I believe there is a race condition whereby the certificate details are loaded back from AWS after creation, but before all values are available.  Running on an EC2 instance in same region triggers the behaviour, while a higher latency connection has time for these values to populate.

It can be seen here (https://gist.github.com/patrickherrera/77bf986cb6b830939113b464100c96b6#file-terraform_debug_output-txt-L117) that the result of `acm/DescribeCertificate` does not return values for ValidationMethod and DomainName amongst other things:
```
{"Certificate":{"CertificateArn":"arn:aws:acm:ap-southeast-2:999999592532:certificate/99937dcf-cc16-488c-8c05-5910d6958837","CreatedAt":1.564815822E9,"InUseBy":[],"Issuer":"Amazon","Options":{"CertificateTransparencyLoggingPreference":"ENABLED"},"RenewalEligibility":"INELIGIBLE","Status":"PENDING_VALIDATION","Type":"AMAZON_ISSUED"}}
```

Then here (https://gist.github.com/patrickherrera/77bf986cb6b830939113b464100c96b6#file-terraform_debug_output-txt-L173) it can be seen that these missing values overwrite Terraform's internal state and there is no record of the required DomainValidationOptions.

The next step then fails instantly as the array of options is empty.  I don't even get a message saying that the creation process has started.

What should be returned (as it does from `us-east-1`) is something like:
```
{"Certificate":{"CertificateArn":"arn:aws:acm:us-east-1:xxx:certificate/yyy","CreatedAt":1.564792541E9,"DomainName":"ci4740407174-myapp-pf-api.aws-technet-dev-au.mycompany.online ","DomainValidationOptions":[{"DomainName":"ci4740407174-myapp-pf-api.aws-technet-dev-au.mycompany.online ","ResourceRecord":{"Name":"_bedaf946a5080428db4b18b0842279a4.ci4740407174-myapp-pf-api.aws-technet-dev-au.mycompany.online.","Type":"CNAME","Value":"_b9124ba6e30ba61bbdf73e989af5004e.duyqrilejt.acm-validations.aws."},"ValidationDomain":"ci4740407174-myapp-pf-api.aws-technet-dev-au.mycompany.online ","ValidationMethod":"DNS","ValidationStatus":"PENDING_VALIDATION"}],"ExtendedKeyUsages":[],"InUseBy":[],"Issuer":"Amazon","KeyAlgorithm":"RSA-2048","KeyUsages":[],"Options":{"CertificateTransparencyLoggingPreference":"ENABLED"},"RenewalEligibility":"INELIGIBLE","SignatureAlgorithm":"SHA256WITHRSA","Status":"PENDING_VALIDATION","Subject":"CN=ci4740407174-myapp-pf-api.aws-technet-dev-au.mycompany.online ","SubjectAlternativeNames":["ci4740407174-myapp-pf-api.aws-technet-dev-au.mycompany.online "],"Type":"AMAZON_ISSUED"}}
```
However, viewing the failing cert in the console, or via the AWS CLI returns the correct values - it is only that point in time directly after it has been created that it is missing, and only in a low latency environment.

I wonder if this issue as always been there and a recent upgrade somewhere has improved performance to the point where the problem is visible.

I have run dozens of builds trying various things to address it and every one has failed for the same reason so it doesn't look like it will solve itself.  For the moment I have worked around it by running two separate Terraform deploys, one for just the certificate creation and one for the rest and this works fine but is not ideal.

I have raised this with AWS and they are looking at it, but could a delay be added in the AWS module, or a poll, to ensure the values are consistent?

### References

None

**Comment by ebgc** [comment] 2019-08-05 06:17
must be a timing issue - same here - on aws ec2 instance it fails (inside container or  native on instance) - here (outside the u.s.) using same region (us.east) it does work (container or native) 

to note - i could reproduce the error local only once (tried several times, with different dns name, cleaning up tfstate every time, docker or nativ)

started around the same time as mentioned above

**Comment by bflad** [comment] 2019-08-05 14:14
Hi @patrickherrera 👋 Thank you very much for reporting this and sorry you are running into trouble here. This does appear to be a problematic change in the API behavior for the Terraform resource and specifically similar to the report in #9596. The error messaging in this report happens to be the Terraform 0.12 and later error reporting for the (unexpectedly) empty attribute. In order to consolidate any discussion and efforts for fixing the root cause, I'm going to close this issue to that issue. Please follow #9596 for continuing updates on this issue and we are hoping to get this resolved this week. 👍

**Closed by bflad** 2019-08-05 14:14 UTC
Labels: service/acm, upstream
