### ISSUE TITLE
Terraform Crashes

### ISSUE THREAD

**Issue by triplejay2013** [terraform-providers/terraform-provider-aws#14019] opened 2020-07-01 18:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.28    
+ provider.aws v2.60.0

### Debug Output

`
2020-07-01T11:44:54.993-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0x3c75443]
2020-07-01T11:44:54.993-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4:
2020-07-01T11:44:54.993-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: goroutine 62 [running]:
2020-07-01T11:44:54.993-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsDynamoDbTableCreate(0xc00101bc70, 0x4e61580, 0xc00015ef00, 0x2, 0x9670900)
2020-07-01T11:44:54.993-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_dynamodb_table.go:408 +0xd53
2020-07-01T11:44:54.993-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0002521b0, 0xc000fcb540, 0xc00104ed40, 0x4e61580, 0xc00015ef00, 0xc00103a001, 0xc00104bf50, 0xc00103a0b8)
2020-07-01T11:44:54.993-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:310+0x365
2020-07-01T11:44:54.993-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000108b80,0xc000b699c8, 0xc000fcb540, 0xc00104ed40, 0xc00104dca8, 0xc000ee14c0, 0x4c75d60)
2020-07-01T11:44:54.993-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/provider.go:294+0x99
2020-07-01T11:44:54.993-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00060f078, 0x631ce80, 0xc00105b770, 0xc000255420, 0xc00060f078, 0xc00105b770, 0xc0000aeb30)
2020-07-01T11:44:54.993-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:885+0x8b4
2020-07-01T11:44:54.994-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x57ed900, 0xc00060f078, 0x631ce80, 0xc00105b770, 0xc000f0b8c0, 0x0, 0x631ce80, 0xc00105b770, 0xc00106e000, 0x585)
2020-07-01T11:44:54.994-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3305+0x217
2020-07-01T11:44:54.994-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000295080, 0x633e860, 0xc000295800, 0xc00012c500, 0xc000af8420, 0x9643560, 0x0, 0x0, 0x0)
2020-07-01T11:44:54.994-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:1024 +0x4f4
2020-07-01T11:44:54.994-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: google.golang.org/grpc.(*Server).handleStream(0xc000295080, 0x633e860, 0xc000295800, 0xc00012c500, 0x0)
2020-07-01T11:44:54.994-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:1313 +0xd97
2020-07-01T11:44:54.994-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00039e250, 0xc000295080, 0x633e860, 0xc000295800, 0xc00012c500)
2020-07-01T11:44:54.994-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:722 +0xbb
2020-07-01T11:44:54.994-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-07-01T11:44:54.994-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/google.golang.org/grpc/server.go:720 +0xa1

`

### Actual Behavior

Frequently crashes with:
`
2020-07-01T11:44:54.993-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0x3c75443]
2020-07-01T11:44:54.993-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4:
2020-07-01T11:44:54.993-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: goroutine 62 [running]:
2020-07-01T11:44:54.993-0600 [DEBUG] plugin.terraform-provider-aws_v2.60.0_x4: github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsDynamoDbTableCreate(0xc00101bc70, 0x4e61580, 0xc00015ef00, 0x2, 0x9670900)
`

### Steps to Reproduce

1. `terraform apply`

### References

* #11640  -- similar failures

**Comment by ewbankkit** [comment] 2020-07-01 21:13
Similar:
* https://github.com/terraform-providers/terraform-provider-aws/issues/13673

@triplejay2013 Thanks for raising this issue.
It looks similar to the linked issue which was resolved in https://github.com/terraform-providers/terraform-provider-aws/pull/13925 and released in [version 2.68.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/v2.68.0/CHANGELOG.md).
Could you upgrade to this version and see if the problem is resolved?

**Comment by triplejay2013** [comment] 2020-07-06 21:13
upgrading to "2.68.0" seemed to resolve this particular issue for me.

**Comment by ewbankkit** [comment] 2020-07-06 22:13
@triplejay2013 Thanks for verifying.

**Closed by ewbankkit** 2020-07-06 22:13 UTC
Labels: crash, service/dynamodb
