### ISSUE TITLE
regional WAF not fully supported and too different from cloudfront WAF

### ISSUE THREAD

**Issue by craiglink** [terraform-providers/terraform-provider-aws#1029] opened 2017-06-30 18:31 UTC
### Terraform Version
0.9.10

### Affected Resource(s)
aws_waf_*
aws_wafregional_*

Currently terraform only supports regional ByteMatchSet and IPSet.  It does't provide any wasy to create a regional rule.  Given that the WAF api is nearly identical for CloudFront and regional, I'd expect the interfaces to be fully implemented and leverage the same code paths and just branching out to the different AWS Api call which requires a region for the regional. Ideally the existing WAF resources would just be extended to have a "regional" boolean added to them.  This would also make the resources consistent.

Current the waf_ipset uses "ip_set_descriptors" while waf_regional_ipset uses "ip_set_descriptor"

This would allow one to easily manage regional and global (cloudfront) WAFs with a single set of scripts.

**Comment by tomgoren** [comment] 2017-08-21 12:09
I think this might be a duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/1333.

**Comment by colin-lyman** [comment] 2017-12-07 13:23
+1

**Comment by radeksimko** [comment] 2018-03-28 15:38
Hi @craiglink  
[`v1.12.0`](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1120-march-23-2018) (latest release) does contain a number of WAF Regional resources and all the remaining resources will be part of [`v1.13.0`](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1130-unreleased) (upcoming release).

In regards to drifted naming conventions the plan is to deprecate fields in existing resources in favour of new ones. Typically we prefer singular names over plural. I don't have any timelines to share at this point, but I just re-labelled this issue to reflect this.

**Comment by bflad** [comment] 2018-06-25 18:34
There has been a ton of new resources added to the AWS provider over the last few months regarding WAF vs WAF Regional, so going to opt to close this issue. If you have specific bugs or feature requests, please do create new issues. Thanks!

**Closed by bflad** 2018-06-25 18:34 UTC
Labels: enhancement, service/waf
