### ISSUE TITLE
Add support for ECS tags

### ISSUE THREAD

**Issue by matthewduren** [terraform-providers/terraform-provider-aws#6481] opened 2018-11-15 22:30 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Add support for tagging ECS resources

As of 11/15, all ECS resources support tagging, including clusters, services, tasks, task definitions, container instances, etc.

### New or Affected Resource(s)

* aws_ecs_cluster
* aws_ecs_service
* aws_ecs_task_definition

### Potential Terraform Configuration

```hcl
resource "aws_ecs_service" "example" {
  tags {
    tag1 = "value"
    tag2 = "value"
  }
}
```

### References

https://console.aws.amazon.com/ecs/home?region=us-east-1#/clusters/optIn/resourceIdArnFormat

https://aws.amazon.com/ecs/faqs/#Transition_to_new_ARN_and_ID_format

**Comment by bflad** [comment] 2018-11-16 01:02
Luckily this was already work in progress! More soon. 😄

**Comment by edvalenciano** [comment] 2018-11-16 15:58
I've used locals within our microservices.tf and then and merged resource specific tags with the locals to ensure all tags are applied to resources provisioned within the microservice.tf, that is, those that support tagging on creation.  I my mind the tags for ECS would apply as with any other resource. However, I cannot test at this time due to Terraform not recognizing the "tags" key.  

Resource tag, similar to the example above:

resource "aws_ecs_service" "example" {
tags = "${merge(
			local.common_tags,
			map(
			  "tag5", "tag5_value",
			  "tag6", "tag6_value"
			)
		  )}"
}

Locals would be added at the top of the file but are not depicted in this example.

**Closed** 2018-11-16 16:51 UTC
Labels: enhancement, service/ecs

**Comment by bflad** [comment] 2018-11-16 16:54
The `tags` argument has been added, tested, and documented for the three available ECS resources. This support will be released with version 1.46.0 of the AWS provider, likely sometime before Wednesday.

**Comment by bflad** [comment] 2018-11-20 02:51
This has been released in [version 1.46.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1460-november-20-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by kl4w** [comment] 2018-12-04 17:45
@andrewotoole to do this on the whole account level, you need to log in using the root AWS account and enable it per region you want.

**Comment by andrewotoole** [comment] 2018-12-06 13:59
@kl4w thank you! I have spoken to our SRE team and will check back once they are done to let you know if that worked.

**Comment by ozbillwang** [comment] 2018-12-17 01:11
@kl4w  & @bflad 

In my company, we have to run with assume role only, we are not possible to use root aws account to deploy the infrastructure codes. Are there ways to fix the issue directly in terraform codes?

I got this error  `InvalidParameterException: Long arn format must be used for tagging operations` today and we can't apply tags to `aws_ecs_service` resource.

**Comment by ozbillwang** [comment] 2018-12-17 02:05
Test with my own aws account (which I have root access), now I understood the difference. 

* Login as assume role, which I can only opted-in for this role. In this case, even I enable to opt in to the new ARN and resource ID format it is useless, I still get the same issue.

![screen shot 2018-12-17 at 12 24 41 pm](https://user-images.githubusercontent.com/8954908/50062557-d694b600-01fb-11e9-91dc-2e1254fe499f.png)

* Login as root account, I can see the choices (setting scope) now:

1) set for root (override account default)
2) set for specific IAM user
3) set for specific IAM role

![screen shot 2018-12-17 at 1 00 13 pm](https://user-images.githubusercontent.com/8954908/50062563-d85e7980-01fb-11e9-87ae-ea0ea1564950.png)

**Comment by ebarault** [comment] 2019-01-15 08:57
@bflad : although this is working perfectly fine for new ECS resources, this raises an error for resources created before AWS added the support for ECS tags.
I have opted in at root account level.

**Comment by bflad** [comment] 2019-01-15 11:48
@ebarault can you please file a new bug report issue filling out the issue template details so we can further triage? Thanks.

**Comment by rantecki** [comment] 2019-03-28 03:32
@ebarault I just ran into the same issue.  Interestingly, AWS wouldn't let me add tags to the ECS service via the AWS console either, so I don't think the issue is Terraform-specific.  I had to destroy and recreate the service before I could add tags.

**Comment by matthewduren** [comment] 2019-03-28 19:10
The new long arn has to be used in order to tag any ecs resources. This isn't a bug but rather an expected behavior. This issue is closed and I believe it's working as intended.
