### ISSUE TITLE
Terraform modified root domain that wasn't managed by terraform instead of throwing an error

### ISSUE THREAD

**Issue by Defozo** [terraform-providers/terraform-provider-aws#7920] opened 2019-03-13 16:08 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.13
+ provider.aws v1.49.0
+ provider.null v2.0.0
+ provider.template v2.0.0

### Affected Resource(s)

* aws_route53_record

### Terraform Configuration Files

```hcl
data "aws_route53_zone" "example_com" {
  name = "example.com."
}

data "aws_elastic_beanstalk_hosted_zone" "current" {}

resource "aws_route53_record" "default" {
  zone_id = "${data.aws_route53_zone.example_com.zone_id}"
  name    = ""
  type    = "A"

  alias {
    name                   = "something.beanstalk.com"
    zone_id                = "${data.aws_elastic_beanstalk_hosted_zone.current.id}"
    evaluate_target_health = false
  }
}
```

### Expected Behavior

Terraform should show an error that hostname (`aws_route53_record.default.name`) can't be empty or that `example.com` record already exists.

### Actual Behavior

Terraform modified `example.com`.

### Steps to Reproduce

1. Use the above snippet.
2. Execute `terraform apply`.
3. Now, your root domain should point to the provided alias name.

**Comment by bflad** [comment] 2019-03-13 18:48
Hi @Defozo 👋 Sorry you ran into this unexpected behavior here. The default behavior for the `aws_route53_record` resource was updated in version 2.0.0 of the Terraform AWS Provider to require a special flag to overwrite existing records:

* https://github.com/terraform-providers/terraform-provider-aws/pull/7734
* https://www.terraform.io/docs/providers/aws/guides/version-2-upgrade.html#resource-aws_route53_record
* https://github.com/terraform-providers/terraform-provider-aws/pull/2926

Since this issue should already be resolved by default when using an updated version of the Terraform AWS Provider, I'm going to close this issue, but please reach out if the updated behavior has problems.

**Closed by bflad** 2019-03-13 18:48 UTC
Labels: service/route53
