### ISSUE TITLE
IAM Group Data Source does not return iam members in group

### ISSUE THREAD

**Issue by dminnear** [terraform-providers/terraform-provider-aws#10652] opened 2019-10-28 15:41 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Right now the data source aws_iam_group returns `arn`, `path`, and `group_id`. Our team has a few use cases (especially with Terraform v12) for getting users from a group and using those iam users for further interpolation.

The aws sdk call we are making ([GetGroup](https://docs.aws.amazon.com/sdk-for-go/api/service/iam/#IAM.GetGroup)) in [data_source_aws_iam_group.go](aws/data_source_aws_iam_group.go) already supports returning a paginated list of users. In fact, `resourceAwsIamGroupMembershipRead` in [resource_aws_iam_group_membership.go](aws/resource_aws_iam_group_membership.go) currently fetches all the users in a group.

### New or Affected Resource(s)

* data_source_aws_iam_group

**Comment by bflad** [comment] 2019-11-07 11:28
Hi folks 👋 Please note that this feature request appears to be a duplicate of the previous issue #7076 with associated pull request #7132. To consolidate discussions and efforts, I'm going to close this issue in preference of those. Thanks.

**Closed by bflad** 2019-11-07 11:28 UTC
Labels: enhancement, needs-triage, service/iam
