### ISSUE TITLE
Version 1.16 breaks in aws_instance resources in govcloud

### ISSUE THREAD

**Issue by dotspec** [terraform-providers/terraform-provider-aws#4372] opened 2018-04-26 18:58 UTC
Hi there,

### Terraform Version
0.11.1

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_instance possibly others

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
Picture a .tf file with a vanilla aws_instance resource in it.

### Debug Output
This is probably the only thing of importance here.

"DEBUG: Validate Response ec2/DescribeInstanceCreditSpecifications failed, not retrying, error UnsupportedOperation: The functionality you requested is not available in this region."

### Expected Behavior
The plan should have executed successfully. 

### Actual Behavior
"aws_instance.instance-4: aws_instance.instance-4:: UnsupportedOperation: The functionality you requested is not available in this region.
	status code: 400, request id: a6ff93d2-88bc-48c8-ade0-9992009c1fd0"

### Steps to Reproduce
1. Don't pin your provider version
2. `terraform plan`

### Important Factoids
Pinning to version 1.15 works as expected.

**Comment by bflad** [comment] 2018-04-26 19:47
Sorry you ran into trouble here. This is a duplicate of #4359 which already has the fix #4362 merged in and will be released with v1.17.0 of the AWS provider, middle of next week.

**Closed by bflad** 2018-04-26 19:47 UTC
Labels: bug, partition/aws-us-gov, service/ec2
