### ISSUE TITLE
Remote State issue

### ISSUE THREAD

**Issue by beakerman29** [terraform-providers/terraform-provider-aws#1251] opened 2017-07-26 22:47 UTC
### Terraform Version
0.9.11

### Affected Resource(s)
terraform_remote_state

### Terraform Configuration Files

in tfvars.tf:

```hcl
terraform {
  backend "s3" {
    bucket = "state-terraform"
    key = "test/albtest.tfstate"
    profile = "AWSPROD"
    region = "us-west-1"
  }
}
variable regions_east { default = "us-east-1"}
variable profile {}
variable pws_alb_name { default = "pws-development"}
variable pws_alb_vpc_name { default = "ecomtest"}
variable pws_alb_internal { default = "true"}
```

in state.tf:

```hcl
data "terraform_remote_state" "remote_state" {
  backend = "s3"
}

provider "aws" {
    shared_credentials_file = "/terraform/credentials"
      profile = "${var.profile}"
      region = "${var.regions_east}"
}

data "aws_vpc" "pws_vpc_id" {
  filter {
      name = "tag:Name"
      values = ["${var.pws_alb_vpc_name}"]
  }
}

data "aws_security_group" "env_pws_security_group" {
    filter {
        name = "group-name"
        values = ["pws-elb-env"] 
    }
}   

data "aws_subnet_ids" "pws_subnet_ids" {
    vpc_id = "${data.aws_vpc.pws_vpc_id.id}"
    tags {
        Name = "ecomtest-pub"
    }
}

module "pws-development-us-east-1-alb" {
    source = "../modules/aws_alb"
    vpc_name = "${var.pws_alb_vpc_name}"
    platform_name = "envname"
    env = "global"
    region = "${var.regions_east}"
    profile_name = "${var.profile}"
    alb_name = "${var.pws_alb_name}"
    alb_internal = "${var.pws_alb_internal}"
    security_group = ["${data.aws_security_group.env_pws_security_group.id}"]
    subnets = "${data.aws_subnet_ids.pws_subnet_ids.ids}"
}
```

### Expected Behavior
Remote State should be saved when it completes
 
### Actual Behavior
Recieve an error

"data.terraform_remote_state.remote_state: data.terraform_remote_state.remote_state: error initializing backend: Not a valid region:" 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
The region I am creating resources in is different than the region that the remote state is saved in. I.E. the resource is created in us-east-1 and the state file is supposed to be stored in the bucket in us-west-1

I am able to run the terraform init successfully just not plan or apply

**Comment by radeksimko** [comment] 2017-07-27 07:47
Hi @beakerman29 
thanks for opening this issue.

Please be aware that remote state is actually still part of [the main Terraform codebase/project](https://github.com/hashicorp/terraform), not AWS provider.

This small misunderstanding of abstraction layers and responsibilities inside Terraform in fact be the root cause of your problem here and I'm sorry for the confusion which may have risen from any docs or guides. We always aim to improve relevant docs accordingly to avoid confusions, where possible.

The `terraform` block you have specified in `tfvars.tf` is responsible for setting up+reading+writing state of any resources and data sources in the rest of any `*.tf` configs in the directory.

On the other side `terraform_remote_state` **data source** is supposed to be used by **consumers** of such remote state.

So with `terraform` block you're a **producer** of a remote state potentially exposing the state (outputs within the state) to another team or another Terraform config. With `data "terraform_remote_state"` you're a consumer reading previously exposed state and building more infrastructure on top of it.

You can be **both consumer & producer**, but you'd never use both a `data "terraform_remote_state"` and `terraform` _with the same configuration_ in the same directory (which is interpreted by a single `terraform plan/apply/destroy`)

These two concepts are implemented as two independent units (intentionally) - so `region` in your provider block cannot be inferred by `terraform_remote_state` as that's technically [a different provider](https://github.com/terraform-providers/terraform-provider-terraform) leveraging some core code as backends remain part of core codebase even after [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/).

I hope this make more sense now. Maybe it's worth documenting this ^ somewhere in https://www.terraform.io/docs/backends/index.html ? Is there any specific part of docs where you'd look when reading about this topic?

**Comment by beakerman29** [comment] 2017-07-27 16:28
So I removed the data "terraform_remote_state" and it started working as expected. If i understand your response correctly this "data" statement was overriding my terraform block in the tfvars which was causing the problem. So you either have the terraform in the tfvars or the terraform_remote_state but not both in the same directory. I think understanding how the various components override or take precedence would be good to understand

**Comment by radeksimko** [comment] 2017-07-27 18:49
@beakerman29 the data source should never be _writing_ anything, but the data source will always require full detailed (explicit) configuration including region, bucket, key etc. because it is independent abstraction layer in Terraform. It does _not_ inherit any configuration from anywhere else. That is where the error message is coming from.

Theoretically it would've worked if you added details like this:

```hcl
data "terraform_remote_state" "remote_state" {
  backend = "s3"
  config {
    bucket = "state-terraform"
    key = "test/albtest.tfstate"
    profile = "AWSPROD"
    region = "us-west-1"
  }
}
```
but as explained above it doesn't make any sense to be writing the state file and reading from it in the same context/config.

**Comment by beakerman29** [comment] 2017-07-27 19:28
Agreed completely and understood. Essentially since I put the terraform in my vars and then used the data without configuring the one overlapped the other essentially passing no information on the remote backend. Thanks for the quick response and I'm good to close.

**Comment by bflad** [comment] 2018-05-30 18:16
Closing due to

> Thanks for the quick response and I'm good to close.

**Closed by bflad** 2018-05-30 18:16 UTC
Labels: documentation, upstream-terraform
