### ISSUE TITLE
Error apply plan when removing IPv6 CIDR block

### ISSUE THREAD

**Issue by oboudry** [terraform-providers/terraform-provider-aws#8515] opened 2019-05-03 15:41 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.13
+ provider.aws v2.8.0

### Affected Resource(s)

* aws_vpc

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "eu-central-1"
}

data "aws_security_group" "default" {
  name   = "default"
  vpc_id = "${module.vpc.vpc_id}"
}

module "vpc" {
  source = "github.com/terraform-aws-modules/terraform-aws-vpc.git?ref=v1.64.0"

  name = "development"

  cidr = "10.20.0.0/16"

  azs             = ["eu-central-1a", "eu-central-1b", "eu-central-1c"]
  private_subnets = ["10.20.1.0/24", "10.20.2.0/24", "10.20.3.0/24"]
  public_subnets  = ["10.20.101.0/24", "10.20.102.0/24", "10.20.103.0/24"]

  assign_generated_ipv6_cidr_block = true

  enable_nat_gateway = true
  single_nat_gateway = true

  tags = {
    Owner       = "user"
    Environment = "dev"
  }

  vpc_tags = {
    Name = "vpc-name"
  }
}
```

### Debug Output

https://gist.github.com/oboudry/3291aaf5fb851e607008b0988841fd4e 

### Expected Behavior

The IPv6 CIDR block should have been removed from the VPC

### Actual Behavior

The IPv6 CIDR block is not removed, and terraform apply fails with the following error
```
* aws_vpc.this: InvalidVpcCidrBlockAssociationId.Malformed: The vpc CIDR block with association ID  is malformed
        status code: 400, request id: ab1107b7-490c-49e4-9f21-e007660738eb
```

### Steps to Reproduce

1. `terraform apply`
2. Change like 20 `assign_generated_ipv6_cidr_block = true` to `assign_generated_ipv6_cidr_block = false`
3. `terraform apply`

**Comment by ryndaniels** [comment] 2019-11-27 15:08
Hi @oboudry - thanks for taking the time to submit this issue. I had a look at this with the most recent versions of Terraform and the AWS Provider and was unable to reproduce this behavior. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md). 🙂

**Closed by ryndaniels** 2019-11-27 15:08 UTC
Labels: needs-triage, service/ec2
