### ISSUE TITLE
aws_cognito_user_pool.schema.# change should not force new resource

### ISSUE THREAD

**Issue by tonyxiao** [terraform-providers/terraform-provider-aws#8826] opened 2019-05-31 19:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.11

### Affected Resource(s)

aws_cognito_user_pool

### Terraform Configuration Files

```hcl
resource "aws_cognito_user_pool" "pool_v2" {
  schema {
    attribute_data_type = "String"
    name                = "phone_number"
    mutable             = true
    required            = true

    string_attribute_constraints = {
      min_length = 0
      max_length = 2048
    }
  }

  schema {
    attribute_data_type = "String"
    name                = "user_id"
    mutable             = true
    required            = false

    string_attribute_constraints = {
      min_length = 0
      max_length = 2048
    }
  }
```

### Debug Output

```
-/+ module.alka.aws_cognito_user_pool.pool_v2 (new resource required)
      id:                                                                 "us-east-1_9StTLQJs7" => <computed> (forces new resource)
      schema.#:                                                           "1" => "2" (forces new resource)
      schema.2576433360.attribute_data_type:                              "String" => "String"
      schema.2576433360.developer_only_attribute:                         "false" => ""
      schema.2576433360.mutable:                                          "true" => "true"
      schema.2576433360.name:                                             "phone_number" => "phone_number"
      schema.2576433360.number_attribute_constraints.#:                   "0" => "0"
      schema.2576433360.required:                                         "true" => "true"
      schema.2576433360.string_attribute_constraints.#:                   "1" => "1"
      schema.2576433360.string_attribute_constraints.0.max_length:        "2048" => "2048"
      schema.2576433360.string_attribute_constraints.0.min_length:        "0" => "0"
      schema.97745089.attribute_data_type:                                "" => "String" (forces new resource)
      schema.97745089.developer_only_attribute:                           "" => ""
      schema.97745089.mutable:                                            "" => "true" (forces new resource)
      schema.97745089.name:                                               "" => "user_id" (forces new resource)
      schema.97745089.number_attribute_constraints.#:                     "" => "0"
      schema.97745089.required:                                           "" => "false" (forces new resource)
      schema.97745089.string_attribute_constraints.#:                     "" => "1" (forces new resource)
      schema.97745089.string_attribute_constraints.0.max_length:          "" => "2048" (forces new resource)
      schema.97745089.string_attribute_constraints.0.min_length:          "" => "0" (forces new resource)
```

I added an additional custom attribute, it should not require creating of a new user pool as AWS allows adding custom schema attributes without live pool. 

```
  schema {
    attribute_data_type = "String"
    name                = "user_id"
    mutable             = true
    required            = false

    string_attribute_constraints = {
      min_length = 0
      max_length = 2048
    }
  }
```

**Comment by ringods** [comment] 2019-06-19 19:07
@tonyxiao I am bitten by this too. What is the AWS provider version you are using?

Here is my version info:
```
Terraform v0.11.14
+ provider.aws v2.15.0
```

**Comment by ringods** [comment] 2019-06-19 19:10
Seems this is a duplicate of #3891 
@tonyxiao Can you close this one?

**Comment by aeschright** [comment] 2019-06-19 21:44
Duplicate of #3891.

**Closed by aeschright** 2019-06-19 21:44 UTC
