### ISSUE TITLE
Error when attaching an aws_iam_instance_profile to an instance

### ISSUE THREAD

**Issue by fallertsen** [terraform-providers/terraform-provider-aws#2046] opened 2017-10-25 09:23 UTC
Hi there,

I found a problem that is occurring not consistently, but quite often (once every 5 tries, roughly).
The problem is that when I apply the following simple configuration, I sometimes get an error from AWS mentioning that there is an invalid parameter for the IAM instance profile name.

### Terraform Version
```
$ terraform -v
Terraform v0.10.7
```

### Affected Resource(s)
- aws_iam_instance_profile
- aws_spot_instance_request

### Terraform Configuration Files
```hcl
resource "aws_iam_role" "role" {
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

resource "aws_iam_role_policy" "s3_policy" {
  role = "${aws_iam_role.role.id}"
  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:PutObject",
        "s3:GetObject",
        "s3:DeleteObject",
        "s3:ListObject",
        "s3:ListBucket"
      ],
      "Resource": [
        "arn:aws:s3:::*"
      ]
    }
  ]
}
EOF
}

resource "aws_iam_instance_profile" "profile" {
  role = "${aws_iam_role.role.name}"
}

resource "aws_spot_instance_request" "main" {
  ami           = "ami-405f7226"
  instance_type = "m3.medium"
  spot_price    = "0.02"
  wait_for_fulfillment = true
  iam_instance_profile = "${aws_iam_instance_profile.profile.name}"
}
```

### Expected Behavior
Create a spot instance with the IAM role attached as specified.

### Actual Behavior
Error creating the spot instance because of an invalid parameter

### Steps to Reproduce
1. `terraform apply`

### Output
```
Error applying plan:

1 error(s) occurred:

* aws_spot_instance_request.main: 1 error(s) occurred:

* aws_spot_instance_request.main: Error requesting spot instances: InvalidParameterValue: Value (terraform-20171025084913059400000002) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name
        status code: 400, request id: 95bcdd9b-81b3-4a7c-a0fe-4ab425e0d7f6

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

If needed I can attach the terraform state or provide more information.

**Comment by bflad** [comment] 2017-10-25 21:18
This seems like a duplicate of #2012 and likely due to IAM's eventual consistency.

**Comment by fallertsen** [comment] 2017-10-27 07:22
Sorry, I missed it.
Should I close the issue? Or should you? How does the project handle it?

**Comment by Ninir** [comment] 2017-10-27 12:26
Hey @fallertsen 

We can do it, like you: we don't have any rules for that hah 😄 
Let's keep the issue in the other thread to better keep track :)

Thanks for the ping @bflad :)

**Closed by Ninir** 2017-10-27 12:26 UTC
