### ISSUE TITLE
step_scaling_policy_configuration doesn't allow negative numbers without glitching

### ISSUE THREAD

**Issue by paulcdejean** [terraform-providers/terraform-provider-aws#4812] opened 2018-06-11 19:48 UTC
Maybe related to:

https://github.com/terraform-providers/terraform-provider-aws/issues/2063

When I have a scaling policy like so:

```
  step_scaling_policy_configuration {
    adjustment_type = "ExactCapacity"
    cooldown = 30
    metric_aggregation_type = "Average"
    step_adjustment {
      metric_interval_lower_bound = -19998

      scaling_adjustment = 0
    }
  }
```

I get the error: "ValidationException: Both lower and upper bounds of a step adjustment cannot be left unspecified"

When I do a repeat apply it says "Apply complete! Resources: 0 added, 0 changed, 0 destroyed." which is also a glitch.

However positive values work without issue.

**Comment by bflad** [comment] 2018-06-29 14:20
Hi @paulcdejean 👋 Sorry you're running into trouble here. This does indeed seem related or exactly a duplicate of #2063. In order to consolidate discussions and efforts with the bug, let's track this in the earlier #2063. 👍

**Closed by bflad** 2018-06-29 14:20 UTC
Labels: bug, service/autoscaling
