### ISSUE TITLE
Unable to create aws_lambda_function

### ISSUE THREAD

**Issue by aomega08** [terraform-providers/terraform-provider-aws#2128] opened 2017-11-01 09:47 UTC
I'm trying to create a lambda function. No complex configurations, just the function. I tried different runtimes and zip contents, but the problem doesn't get solved.

**EDIT: After trying all possible variations of my code, I switched to region eu-central-1 from eu-west-1 and it worked immediately. I didn't try all regions but it didn't work on any US region I tried, plus eu-west-1. The account was created a few months ago, but it was completely empty.**

### Terraform Version
Terraform v0.10.8 on Mac OS X Sierra 10.12.6

### Affected Resource(s)
- aws_lambda_function

### Terraform Configuration Files
The assume role policy:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "sts:AssumeRole",
            "Principal": {
                "Service": "lambda.amazonaws.com"
            },
            "Effect": "Allow"
        }
    ]
}
```

```hcl
data "archive_file" "lambda_archive" {
    type        = "zip"
    output_path = "${path.module}/lambdas.zip"

    source_dir  = "../lambda"
}

resource "aws_iam_role" "lambda_role" {
    name = "lambda_role"
    assume_role_policy = "${file("templates/lambda-role.json")}"
}

resource "aws_lambda_function" "upload_complete" {
    function_name    = "upload_complete"
    role             = "${aws_iam_role.lambda_role.arn}"
    handler          = "handlers.upload_complete"
    runtime          = "python3.6"

    filename         = "${data.archive_file.lambda_archive.output_path}"
    source_code_hash = "${data.archive_file.lambda_archive.output_base64sha256}"
}
```

### Debug Output
```
aws_lambda_function.upload_complete: Creating...
  arn:              "" => "<computed>"
  filename:         "" => "/Users/aomega/Projects/up/inf/lambdas.zip"
  function_name:    "" => "upload_complete"
  handler:          "" => "handlers.upload_complete"
  invoke_arn:       "" => "<computed>"
  last_modified:    "" => "<computed>"
  memory_size:      "" => "128"
  publish:          "" => "false"
  qualified_arn:    "" => "<computed>"
  role:             "" => "arn:aws:iam::084741000686:role/lambda_role"
  runtime:          "" => "python3.6"
  source_code_hash: "" => "W+v9ZbcaKlhbJMGmtWytyyf4h/1g0dwx6JN/US9AYmc="
  timeout:          "" => "3"
  tracing_config.#: "" => "<computed>"
  version:          "" => "<computed>"
aws_lambda_function.upload_complete: Still creating... (10s elapsed)
aws_lambda_function.upload_complete: Still creating... (20s elapsed)
aws_lambda_function.upload_complete: Still creating... (30s elapsed)
[...]
Error: Error applying plan:

1 error(s) occurred:

* aws_lambda_function.upload_complete: 1 error(s) occurred:

* aws_lambda_function.upload_complete: Error creating Lambda function: timeout while waiting for state to become 'success' (timeout: 10m0s)
```

If I set TF_LOG=DEBUG, I get the following (heavily trimmed) output, which may help:

```

2017-11-01T09:53:31.980Z [DEBUG] plugin.terraform-provider-aws_v1.2.0_x4: 2017/11/01 09:53:31 [DEBUG] [aws-sdk-go] DEBUG: Request lambda/CreateFunction Details:
2017-11-01T09:53:31.980Z [DEBUG] plugin.terraform-provider-aws_v1.2.0_x4: ---[ REQUEST POST-SIGN ]-----------------------------
2017-11-01T09:53:31.980Z [DEBUG] plugin.terraform-provider-aws_v1.2.0_x4: POST /2015-03-31/functions HTTP/1.1
2017-11-01T09:53:31.980Z [DEBUG] plugin.terraform-provider-aws_v1.2.0_x4: Host: lambda.eu-west-1.amazonaws.com
2017-11-01T09:53:31.980Z [DEBUG] plugin.terraform-provider-aws_v1.2.0_x4: User-Agent: aws-sdk-go/1.12.19 (go1.9; darwin; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.10.9-dev
2017-11-01T09:53:31.980Z [DEBUG] plugin.terraform-provider-aws_v1.2.0_x4: Content-Length: 532
2017-11-01T09:53:31.980Z [DEBUG] plugin.terraform-provider-aws_v1.2.0_x4: Authorization: AWS4-HMAC-SHA256 Credential=[REDACTED]/20171101/eu-west-1/lambda/aws4_request, SignedHeaders=content-length;host;x-amz-date, Signature=ff991a103ba0936ffdd8453a926eb59cd480070099b8abafeaf1b226edb564bf
2017-11-01T09:53:31.980Z [DEBUG] plugin.terraform-provider-aws_v1.2.0_x4: X-Amz-Date: 20171101T095331Z
2017-11-01T09:53:31.980Z [DEBUG] plugin.terraform-provider-aws_v1.2.0_x4: Accept-Encoding: gzip
2017-11-01T09:53:31.980Z [DEBUG] plugin.terraform-provider-aws_v1.2.0_x4:
2017-11-01T09:53:31.980Z [DEBUG] plugin.terraform-provider-aws_v1.2.0_x4: -----------------------------------------------------
aws_lambda_function.upload_complete: Still creating... (20s elapsed)
2017-11-01T09:53:42.267Z [DEBUG] plugin.terraform-provider-aws_v1.2.0_x4: 2017/11/01 09:53:42 [DEBUG] [aws-sdk-go] DEBUG: Send Request lambda/CreateFunction failed, will retry, error RequestError: send request failed
```

### Expected Behavior
I expected an AWS Lambda function to be created.

### Actual Behavior
Terraform tried to create the Lambda function a few times and then timed out after 10m.

### Steps to Reproduce
1. `terraform apply`

**Comment by aomega08** [comment] 2017-11-02 13:04
After further investigation, it seems I'm having EXACTLY the same issue as #1392.

It seems to be caused by a company DNS misconfiguration, even though I am able to resolve the lambda hostname using dig, and to create the function with the aws cli, just like in #1392. The problem seems to exist only within terraform.

The problem remains reproducible on selected regions. I'm moving to a remote machine to run terraform.

**Comment by paddycarver** [comment] 2017-11-21 00:55
Seeing as this is a duplicate of #1392, I'm going to close it in favor of tracking the issue there. If you think we should keep both issues open, reply to this issue and we can talk about it. Sorry for the issues!

**Closed by paddycarver** 2017-11-21 00:55 UTC
