### ISSUE TITLE
Add hostname property for aws_transfer_server

### ISSUE THREAD

**Issue by dbuzolin-nfl** [terraform-providers/terraform-provider-aws#6956] opened 2018-12-21 00:04 UTC
Is there way to add hostname property to transfer service, and/or also integrate it with Route53? Current implementation creates service with empty hostname: "-"

**Comment by bflad** [comment] 2018-12-21 15:23
Hi @dbuzolin-nfl 👋 Can you verify creating Route53 records is correct? https://github.com/terraform-providers/terraform-provider-aws/pull/6639#issuecomment-449186415

There is not currently anything in the AWS Transfer API to set this: https://docs.aws.amazon.com/transfer/latest/userguide/API_CreateServer.html

If so, maybe we should add an example `aws_route53_record` configuration to the `aws_transfer_server` documentation.

**Comment by dbuzolin-nfl** [comment] 2018-12-21 16:16
Creation of the SFTP service from AWS console allows entering DNS name for service and then it creates CNAME entry in route53 for you. Two tags show up in sftp service, ex:

aws:transfer:route53HostedZoneId | /hostedzone/ABCDEFGHIGFK
aws:transfer:customHostname | mysftphost.myco.com

Can we use this route (tags) - since they are "aws.*" ?

**Comment by ntman4real** [comment] 2018-12-21 16:33
I see when I create the service manually, via console, it adds this tag which reflects the hostname:"aws:transfer:customHostname" 

But when i try to apply this via TF, it successfully appears that it applied it, but it doesn't show up, and then when I run the plan again it shows that it is needed and isn't there.

**Comment by dbuzolin-nfl** [comment] 2018-12-21 17:05
Yeah, probably because "aws.*" tags are considered "system" tags and can't be applied externally? Just a guess...

**Comment by gazoakley** [comment] 2019-01-28 15:17
That's how the AWS console is doing it (see the XHR requests made from the browser):

```json
{
    "headers": {
        "X-Amz-User-Agent": "aws-sdk-js/2.41.0 promise",
        "Content-Type": "application/x-amz-json-1.1",
        "X-Amz-Target": "TransferService.TagResource"
    },
    "path": "/",
    "method": "POST",
    "region": "eu-central-1",
    "params": {},
    "contentString": "{\"Arn\":\"arn:aws:transfer:eu-central-1:123456789012:server/s-12345678901234567\",\"Tags\":[{\"Key\":\"aws:transfer:customHostname\",\"Value\":\"sftp.example.com\"}]}",
    "operation": "tagResource"
}
```

I think it's appropriate here to allow creating `aws.*` tags if that's how the console achieves what it does.

**Comment by ntman4real** [comment] 2019-03-26 04:28
any update?

**Comment by nickvollmar** [comment] 2019-04-14 01:34
Workaround: if the AWSCLI is installed on the machine where you're running Terraform, you can use `local-exec` to create the hostname. I ended up doing this:

```
resource "aws_transfer_server" "this" { ... }
resource "aws_route53_record" "custom_hostname" { ... }

resource "null_resource" "associate_custom_hostname" {
  provisioner "local-exec" {
    command = <<EOF
aws transfer tag-resource \
  --arn '${aws_transfer_server.this.arn}' \
  --tags \
    'Key=aws:transfer:customHostname,Value=${aws_route53_record.custom_hostname.name}' \
    'Key=aws:transfer:route53HostedZoneId,Value=/hostedzone/${aws_route53_record.custom_hostname.zone_id}'
EOF
  }
  depends_on = ["aws_transfer_server.this", "aws_route53_record.custom_hostname"]
}
```

**Comment by nexxai** [comment] 2019-06-07 20:53
Has anyone had any success using @nickvollmar 's method, but with a non-Route53-hosted customHostname?

I did the following:
```
resource "null_resource" "company-sftp-server-custom-hostname" {
  provisioner "local-exec" {
    command = <<EOF
aws transfer tag-resource \
  --arn '${aws_transfer_server.company-sftp-server.arn}' \
  --tags 'Key=aws:transfer:customHostname,Value=sftp.company.com'
EOF
  }
  depends_on = ["aws_transfer_server.company-sftp-server"]
}
```
but no matter what I do, it keeps throwing "Invalid ARN", including when I try the CLI directly:

```
Error: Error running command 'aws transfer tag-resource \
  --arn 'arn:aws:transfer:ca-central-1:############:server/s-#################' \
  --tags 'Key=aws:transfer:customHostname,Value=sftp.company.com'
': exit status 255. Output: 
An error occurred (InvalidRequestException) when calling the TagResource operation: Invalid ARN
```

I've tried literally copying and pasting the ARN from the contentString, from within the POST request in my browser's DevTools network panel, but I still get the same problem.  I've also had 2 other people confirm that my request matches character-for-character, including re-typing the entire thing in the unlikely event that a homograph was unintentionally being copied.

I'm pulling my hair out here, but I don't know what else to try. Anyone have any ideas?

**Comment by tracypholmes** [comment] 2019-07-01 22:09
Hi, @dbuzolin-nfl! Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. I looks like you've gotten some great feedback and solutions i this thread. Please use https://discuss.hashicorp.com/c/terraform-providers for additional feedback, community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.

**Closed by tracypholmes** 2019-07-01 22:09 UTC
Labels: question, service/transfer

**Comment by atrepca** [comment] 2019-07-30 21:42
@nickvollmar's workaround only partly solves this - the `local-exec` adds the `aws:` tags, but that doesn't trigger the route 53 CNAME creation further. AWS support confirmed that this is not supported, and an internal request was put in with the SFTP team for it.
