### ISSUE TITLE
bug in deleting user and login profile: login profile deleted from state but not from aws

### ISSUE THREAD

**Issue by kzw** [terraform-providers/terraform-provider-aws#4205] opened 2018-04-13 21:46 UTC
### Terraform Version

Terraform v0.11.5
### Affected Resource(s)
```
aws_iam_user.metest
aws_iam_user_login_profile.metest
```

### Terraform Configuration Files
```
#iam.tf
resource "aws_iam_user" "metest" {
  name          = "metest"
  path          = "/"
  force_destroy = false
}

resource "aws_iam_user_login_profile" "metest" {
  user    = "${aws_iam_user.metest.name}"
  pgp_key = "${file("gpg-keys/me.gpg")}"
}

output "password" {
  value = "${aws_iam_user_login_profile.metest.encrypted_password}"
}

#provider.tf
provider "aws" {
  region  = "us-east-1"
  version = "1.9.0"
}
```

### Debug Output
.
### Panic Output
.
### Expected Behavior
user and user login profile to get deleted with no errors

### Actual Behavior
user login profile gets deleted but user not deleted because AWS says login profile is not deleted

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply; rm iam.tf; terraform apply`

```
aws_iam_user_login_profile.metest: Destroying... (ID: metest)
aws_iam_user_login_profile.metest: Destruction complete after 0s
aws_iam_user.metest: Destroying... (ID: metest)

Error: Error applying plan:

1 error(s) occurred:

* aws_iam_user.metest (destroy): 1 error(s) occurred:

* aws_iam_user.metest: Error deleting IAM User metest: DeleteConflict: Cannot delete entity, must delete login profile first.
	status code: 409, request id: a81d2f76-3f62-11e8-879a-23d5dfa9dbd2
```
The workaround when i get the error is to delete the login profile with 

```
aws iam delete-login-profile --user-name metest
```
and then I can proceed with one more

```
terraform apply
```

**Comment by bflad** [comment] 2018-04-17 14:33
Hi @kzw 👋  Sorry you ran into unexpected behavior.

Turns out there's two things at play here:
* Destroying `aws_iam_user_login_profile` does not remove the user's password: #3856
* Since `force_destroy = true` is not set and applied on the `aws_iam_user` resource, it will not forcibly remove the existing login profile and instead bubble up the API error you see

Given the second behavior is correct and the first behavior already has an assigned issue, I'm going to close this in preference of the existing issue: #3856

**Closed by bflad** 2018-04-17 14:33 UTC
Labels: service/iam

**Comment by ericluria** [comment] 2019-11-13 19:13
For anyone else running into this issue, run the following command first:

```
aws iam delete-login-profile --user-name
```
