### ISSUE TITLE
Access Denied to Certificate

### ISSUE THREAD

**Issue by rexsuecia** [terraform-providers/terraform-provider-aws#2414] opened 2017-11-22 20:34 UTC
When trying to create an AWS ALB HTTPS Listener with an ACM certificate it fails to download the certificate.  Error message: 

`aws_lb_listener.front_end_https: Error creating LB Listener: AccessDenied: Access denied to certificate 'arn:aws:acm:eu-west-1:XXXXXXXXXXX:certificate/ddc9fea0-3f07-455a-af07-xxxxxxxxxxxx'
        status code: 403, request id: 69080320-cfc1-11e7-bd7e-xxxxxxxxxxx
`

Running 

` aws acm get-certificate --certificate-arn arn:aws:acm:eu-west-1:XXXXXXXXXX:certificate/xxxxx-3f07-455a-af07-xxxxxxxxxx` 

Using the same credentials the certificate is downloaded perfectly. Also the data request works perfectly fine. I am pretty confident that the credentials cover it (It is a AWS AdministratorAccess vanilla policy).

Terraform config anonymized and I dare not put the full debug log onto a gist due to confidentiality, can be provided "privately" though

````hcl

terraform {
  required_version = "~> 0.11.0" # FIXED
}

provider "aws" {
  region  = "eu-west-1"
  version = "1.3"
}

data "aws_acm_certificate" "example" {
  domain   = "*.examlple.com"
  statuses = ["ISSUED"]
}

resource "aws_lb" "alb_prototype" {
  name            = "temp"
  internal        = false
  security_groups = ["sg-xxxx"]

  subnets = [
    "subnet-xxxx",
    "subnet-xxxx",
  ]

  enable_deletion_protection = false
}

# Ooops, for some reason it gets access denied when trying to fetch the certificate?
resource "aws_lb_listener" "front_end_https" {
  load_balancer_arn = "${aws_lb.alb_prototype.arn}"
  port              = "443"
  protocol          = "HTTPS"
  ssl_policy        = "ELBSecurityPolicy-2015-05"

  certificate_arn = "${data.aws_acm_certificate.example.arn}"

  default_action {
    target_group_arn = "${aws_lb_target_group.alb_prototype_https.arn}"
    type             = "forward"
  }
}

# And forward to 443 (HTTPS)
resource "aws_lb_target_group" "alb_prototype_https" {
  name     = "test"
  port     = 443
  protocol = "HTTPS"
  vpc_id   = "vpc-xxxx"
}
````

Terraform Version
```$ terraform.exe -version
Terraform v0.11.0
+ provider.aws v1.3.0
```
Platform:
```
$ file /c/git/terraform.exe
/c/git/terraform.exe: PE32 executable (console) Intel 80386 (stripped to external PDB), for MS Windows
```

**Comment by rexsuecia** [comment] 2017-11-23 07:31
Well, problem is that the underlying request to AWS does not accept ACM certificate arns. By creating a IAM server certificate it works. Huge difference between
`arn:aws:iam::XXXXXXXXX:server-certificate/some_test_cert`

and

`arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/ddc9fea0-3f07-455a-af07-xxxxxxxxxxxxx`

In the console you can use ACM certificates, the console does not use the regular ReST API, but when I post the following through the console that works fine. (note the **acm** in the certificate arn `arn:aws:acm;eu-west-1:xxxxx`)

```json
{
  "port": 443,
  "protocol": "HTTPS",
  "loadBalancerArn": "arn:aws:elasticloadbalancing:eu-west-1:XXXXXXXXXXXX:loadbalancer/app/ALB-Prototype/xxxxxxxxxxxxxxxx",
  "defaultActions": [
    {
      "targetGroupArn": "arn:aws:elasticloadbalancing:eu-west-1:XXXXXXXXXXXX:targetgroup/ALB-Prototype-HTTPS/xxxxxxxxxxxxxxxxx",
      "type": "forward"
    }
  ],
  "certificates": [
    {
      "CertificateArn": "arn:aws:acm:eu-west-1:XXXXXXXXXXX:certificate/ddc9fea0-3f07-455a-af07-xxxxxxxxxx"
    }
  ],
  "sslPolicy": "ELBSecurityPolicy-2016-08",
  "region": "eu-west-1"
}
```
So, the problem is then that the AWS ReST API does not apparently support this. And [the documentation](http://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateListener.html) does not really say anything about where the server certificate should be stored. Though the example implies iam.

**Comment by jurajseffer** [comment] 2017-11-23 20:36
@rexsuecia I'm quite sure this works in AWS provider 1.2.0 and 1.3.0 as we were doing exactly that - using `data "aws_acm_certificate" ...` to lookup the ARN of an ACM cert that was created manually by name and then pass it to the listener.

Both ACM and IAM certs are accepted as per http://docs.aws.amazon.com/sdk-for-go/api/service/elb/#ELB.CreateLoadBalancerListeners
`* ErrCodeCertificateNotFoundException "CertificateNotFound"
The specified ARN does not refer to a valid SSL certificate in AWS Identity
and Access Management (IAM) or AWS Certificate Manager (ACM). Note that if
you recently uploaded the certificate to IAM, this error might indicate that
the certificate is not fully available yet.`

Are you absolutely sure you're using the same credentials when doing CLI calls and using Terraform? There can be a difference in assuming a role or another profile being picked up based on your env variable etc.

**Comment by rexsuecia** [comment] 2017-11-24 06:07
@jurajseffer thanks for your reply, yes, I am pretty confident I am using the proper credentials. I have replayed the request you are making in PostMan (with "hard coded" credentials, and to my surprise I get the same error). Maybe this is an AWS problem?

Interesting is that the documentation you refer to links to the "old" AWS API i.e. "Classic ELB", and specifically the `CreateLoadBalancerListeners` action. While from the debug log I can tell that you are actually invoking the `CreateListener` Action.

`Action=CreateListener&Certificates.member.1.CertificateArn=arn:aws:acm:eu-west-1:XXXXXXXXXXXX:certificate/ddc9fea0-3f07-455a-af07-nnnnnnnnnnn&DefaultActions.member.1.TargetGroupArn=arn:aws:elasticloadbalancing:eu-west-1:XXXXXXXXXXXX:targetgroup/test/a284e2da9c0e32dd&DefaultActions.member.1.Type=forward&LoadBalancerArn=arn:aws:elasticloadbalancing:eu-west-1:XXXXXXXXXXXX:loadbalancer/app/temp/93b5e2c2c711a0e6&Port=443&Protocol=HTTPS&SslPolicy=ELBSecurityPolicy-2015-05&Version=2015-12-01`

Hmmm, I am starting to lean towards this is an AWS problem. I was hoping you could confirm.

**Comment by apparentlymart** [comment] 2017-12-18 16:47
Hi @rexsuecia! Sorry this isn't working as expected.

I don't have direct experience with the interactions between ALB and ACM, but the behavior here seems similar to a common problem that tends to arise when two AWS services are being used together: requests to one service implicitly interact with the other service, and this interaction must usually be described in IAM policy somehow.

Unfortunately I was not able to find any explicit documentation on how ACM handles the control of which resources (such as ALB listeners, Cloudfront distributions, etc) are allowed to use a particular certificate, so I can't be sure that this is an example of this problem, but it would appear to be the case since you saw it work as expected when using the ACM API directly but fail when accessing ACM indirectly via ALB.

It would be interesting to see if the same behavior can be observed using [the `aws elbv2 create-listener` command](http://docs.aws.amazon.com/cli/latest/reference/elbv2/create-listener.html) using the same credentials and arguments. If so, I might suggest asking AWS support (using the AWS CLI commands to illustrate, rather than Terraform config) to see if they can assist with debugging the interaction between ALB and ACM.

**Comment by rexsuecia** [comment] 2017-12-18 20:15
@apparentlymart thanks for your reply, though late.

I can still reproduce this problem in the original environment (and also with latest version 1.6 of the AWS provider). However I have also been able to proceed in other configurations where the problem does not occur. Hence it is not an urgent issue for me either. 

I did post a question on AWS but they have not answered etiher (https://forums.aws.amazon.com/thread.jspa?threadID=268090)

Since I managed to create a listener in an almost identical scenario I lean to believe that it has to do with the order the certificates were created. If I create the US version before the EU version etc.... ACM not being the most polished service atm. (Note also that terraform/AWS cannot distinguish certificates that refer to the same base FQDN/CN (if i have two certc with the FQDN/CN e.g. *.example.com terraform/AWS provider breaks nicely)

I do not have the time or resources to investigate this further but if anyone else see the same issue please reach out. 

I suggest you close this issue for now.

**Comment by bflad** [comment] 2018-03-02 00:02
Given this issue hasn't had any movement in awhile and this comment:

> I suggest you close this issue for now.

I'm going to close this issue out for now to clean up the repository a little. Please don't hesitate to reach back out if you have additional insight or can determine a reproducible configuration. 😄

**Closed by bflad** 2018-03-02 00:02 UTC
Labels: question, service/elbv2, waiting-response

**Comment by alexeykuptsov** [comment] 2018-08-07 20:43
I suppose, I've reproduced the access denied error.

I get the error on `terraform apply` with a TF file which defines only a load balancer listener - https://github.com/alexeykuptsov/terraform-acceptance-tests/blob/ebb69ecd387d0678cb0c4293f1e6c3df8075af97/test_01_b/main.tf

To setup an environment before running the command in directory `test_01_b`:
1) apply https://github.com/alexeykuptsov/terraform-acceptance-tests/blob/ebb69ecd387d0678cb0c4293f1e6c3df8075af97/test_01_a/main.tf to create a load balancer and a target group to use their ARNs while applying `test_01_b/main.tf`;
2) request a certificate to use its ARN while applying `test_01_b/main.tf`

**Comment by alexeykuptsov** [comment] 2018-08-08 11:13
An update to my previous commit.

It looks like I should contact to AWS support. I've reproduced the error with `boto3` (Python API) by calling `boto3.client('elbv2').create_listener(...)` function.
