### ISSUE TITLE
aws_cloudfront_distribution.distribution: diffs didn't match during apply

### ISSUE THREAD

**Issue by aaronshaf** [terraform-providers/terraform-provider-aws#9169] opened 2019-06-27 16:52 UTC
## Terraform Version

> v0.11.14

## Terraform Configuration Files

```terraform
terraform {
  backend "s3" {}
}

provider "aws" {
  region = "${var.cg_region}"
}

locals {
  build_number = "${timestamp()}-${substr(uuid(), 0, 8)}"
  s3_origin_id = "myS3Origin"
}

data "aws_caller_identity" "current" {}

data "aws_iam_policy_document" "app_role_s3_policy_document" {
  statement {
    effect = "Allow"

    actions = [
      "s3:GetObject",
      "s3:GetObjectAcl",
      "s3:DeleteObject",
      "s3:PutObject",
      "s3:PutObjectAcl",
    ]

    resources = [
      "${aws_s3_bucket.site.arn}",
      "${aws_s3_bucket.site.arn}/*",
    ]
  }
}

resource "aws_iam_policy" "app_role_s3_policy" {
  name        = "${var.cg_app_name}-${var.cg_environment}-${var.cg_region}-s3"
  description = "grant permissions to the cg ${var.cg_app_name}-${var.cg_environment}-${var.cg_region} environment to talk to s3"

  policy = "${data.aws_iam_policy_document.app_role_s3_policy_document.json}"
}

resource "aws_iam_role_policy_attachment" "app_role_s3_attach" {
  role       = "${var.cg_app_role}"
  policy_arn = "${aws_iam_policy.app_role_s3_policy.arn}"
}

resource "aws_s3_bucket" "site" {
  bucket = "${var.cg_app_name}-${var.cg_environment}-${var.cg_region}-static-assets"
  acl    = "public-read"

  website {
    index_document = "index.html"
    error_document = "index.html"
  }

  tags {
    Project     = "${var.cg_app_name}"
    Environment = "${var.cg_environment}"
    Role        = "StaticAssets"
  }
}

resource "null_resource" "remove_and_upload_to_s3" {
  triggers = {
    build_number = "${local.build_number}"
  }

  provisioner "local-exec" {
    command = "aws s3 sync ../../../client/build s3://${aws_s3_bucket.site.id}/${local.build_number} --acl public-read"
  }
}

resource "aws_cloudfront_distribution" "distribution" {
  origin {
    domain_name = "${aws_s3_bucket.site.bucket_regional_domain_name}"
    origin_path = "/${local.build_number}"
    origin_id   = "${local.s3_origin_id}"
  }

  enabled             = true
  is_ipv6_enabled     = true
  default_root_object = "index.html"

  custom_error_response {
    error_code         = 404
    response_code      = 200
    response_page_path = "/index.html"
  }

  default_cache_behavior {
    allowed_methods  = ["GET", "HEAD", "OPTIONS"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "${local.s3_origin_id}"
    compress         = true

    viewer_protocol_policy = "allow-all"
    default_ttl            = 3600

    forwarded_values {
      query_string = false

      cookies {
        forward = "none"
      }
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  tags {
    Project     = "${var.cg_app_name}"
    Environment = "${var.cg_environment}"
    Role        = "StaticAssets"
  }

  depends_on = ["null_resource.remove_and_upload_to_s3"]
}

output "STATIC_ASSETS_BUCKET" {
  value = "${aws_s3_bucket.site.id}"
}

output "BUCKET_DOMAIN_NAME" {
  value = "${aws_s3_bucket.site.bucket_domain_name}"
}

output "WEBSITE_ENDPOINT" {
  value = "${aws_s3_bucket.site.website_endpoint}"
}

output "CLOUDFRONT_DOMAIN" {
  value = "${aws_cloudfront_distribution.distribution.domain_name}"
}
```

## Crash output

```
1 error occurred:
	* aws_cloudfront_distribution.distribution: aws_cloudfront_distribution.distribution: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.14
    Resource ID: aws_cloudfront_distribution.distribution
    Mismatch reason: attribute mismatch: origin.3391411602.custom_header.#
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"default_cache_behavior.0.target_origin_id":*terraform.ResourceAttrDiff{Old:"s3Origin", New:"myS3Origin", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.1424599686.custom_header.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.1424599686.custom_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.1424599686.domain_name":*terraform.ResourceAttrDiff{Old:"[obfuscated].s3.amazonaws.com", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.1424599686.origin_id":*terraform.ResourceAttrDiff{Old:"s3Origin", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.1424599686.origin_path":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.1424599686.s3_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3391411602.custom_header.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3391411602.custom_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3391411602.domain_name":*terraform.ResourceAttrDiff{Old:"", New:"[obfuscated].s3.us-west-2.amazonaws.com", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3391411602.origin_id":*terraform.ResourceAttrDiff{Old:"", New:"myS3Origin", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3391411602.origin_path":*terraform.ResourceAttrDiff{Old:"", New:"/2019-06-27T16:37:41Z-bd369a2a", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3391411602.s3_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"default_cache_behavior.0.target_origin_id":*terraform.ResourceAttrDiff{Old:"s3Origin", New:"myS3Origin", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.1424599686.custom_header.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.1424599686.custom_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.1424599686.domain_name":*terraform.ResourceAttrDiff{Old:"[obfuscated].s3.amazonaws.com", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.1424599686.origin_id":*terraform.ResourceAttrDiff{Old:"s3Origin", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.1424599686.origin_path":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.1424599686.s3_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3111152367.custom_header.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3111152367.custom_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3111152367.domain_name":*terraform.ResourceAttrDiff{Old:"", New:"[obfuscated].s3.us-west-2.amazonaws.com", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3111152367.origin_id":*terraform.ResourceAttrDiff{Old:"", New:"myS3Origin", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3111152367.origin_path":*terraform.ResourceAttrDiff{Old:"", New:"/2019-06-27T16:37:42Z-fa5b1b24", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "origin.3111152367.s3_origin_config.#":*terraform.ResourceAttrDiff{Old:"0", New:"0", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
```

## Expected Behavior

CloudFront should have successfully updated

## Actual Behavior

The CloudFront fails to update.

**Comment by bflad** [comment] 2019-06-27 21:22
Hi @aaronshaf 👋 Sorry you are running into trouble here.

Can you please let us know what version of the Terraform AWS Provider you are running with this configuration? e.g. from the directory containing the configuration:

```
$ terraform version -v
# ... or ...
$ terraform providers
```

There have been some large fixes for the `aws_cloudfront_distribution` resource starting since version 2.0.0. My recommendation would be to try upgrading to the latest ([2.16.0 as of this writing](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2160-june-20-2019)) to see if the issue still replicates, e.g.

```hcl
provider "aws" {
  region = "${var.cg_region}"
  version = "2.16.0"
}
```

That said, `diffs didn't match` errors in Terraform 0.11 are generally very problematic to track down since the error is typically generated in the wrong resource. Usually this type of error the affect of some other resource or reference in the configuration on the specific attribute mentioned in the error report. Terraform 0.12 uses a completely different logic to report these types of problems, so if upgrading to Terraform 0.12 is a possibility, it may also help narrow down the true problem if there still is one after upgrading the provider to the latest.

**Comment by bflad** [comment] 2019-07-24 04:14
It's been a long time since we heard from you here so we're going to close this out. Our recommendations here would be to ensure you're running a recent version of the Terraform AWS Provider (e.g. 2.20.0) as well as Terraform 0.12. If you're still having this problem on those versions, please feel free to open a new issue and complete all of the information requested in the [Bug Report template](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/ISSUE_TEMPLATE/Bug_Report.md) so that we can attempt to understand and reproduce the problem.

**Closed by bflad** 2019-07-24 04:14 UTC
Labels: service/cloudfront, waiting-response
