### ISSUE TITLE
AWS provider version error for SSM Maintenance window

### ISSUE THREAD

**Issue by thrinadh238** [terraform-providers/terraform-provider-aws#6733] opened 2018-12-05 21:36 UTC
I am using 0.10.8 version of terraform. we created SSM maintenance window with this version a while ago. I tried running same code before 2 days but i got error, please find the error below. I find provider.aws version has been upgraded.we used to use version 1.48 but now it was upgraded to 1.50. we tried degrading version to 1.48 and it worked. Please advise us on this issue. Is it a bug of new version???

module.ssm.aws_ssm_maintenance_window_task.task_install_patches: 1 error(s) occurred:

* aws_ssm_maintenance_window_task.task_install_patches: InvalidParameter: 2 validation error(s) found.
- minimum field size of 1, RegisterTaskWithMaintenanceWindowInput.Description.
- minimum field size of 3, RegisterTaskWithMaintenanceWindowInput.Name.

**Comment by bflad** [comment] 2018-12-05 22:04
Hi @thrinadh238 👋 It looks like this was already submitted as #6715. I'm going to close this as a duplicate of the earlier issue.

**Closed by bflad** 2018-12-05 22:04 UTC
