### ISSUE TITLE
aws_eks_node_group's resources attribute shouldn't be a list

### ISSUE THREAD

**Issue by yann-soubeyrand** [terraform-providers/terraform-provider-aws#11775] opened 2020-01-27 17:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.20
+ provider.aws v2.46.0
```

### Affected Resource(s)

* aws_eks_node_group

### Expected Behavior

`aws_eks_node_group`'s `resources` attribute is a list whereas it shouldn't. Indeed, `aws eks describe-nodegroup` doesn't return a list for this attribute.

### Actual Behavior

`aws_eks_node_group`'s `resources` attribute is a list.

**Comment by bflad** [comment] 2020-01-28 20:23
Hi @yann-soubeyrand 👋 Thank you for submitting this.

The representation of "structure" attributes within Terraform as a list or set is an implementation detail that cannot currently be changed by Terraform Providers. This type of schema design is the only option at the moment for "configuration block" argument syntax and their read-only nested attribute equivalents. Any enhancements to the supported schema designs by [Terraform core](https://github.com/hashicorp/terraform) and [Terraform Plugin SDK](https://github.com/hashicorp/terraform-plugin-sdk) will need to be handled in those locations before any implementation is possible within this codebase. Since this request is not currently actionable here, we are going to opt to close this here for now.

There are no short-term or middle-term plans that the maintainers here are aware of for potentially addressing this as an operator issue, since it has not been reported before. If this is causing implementation issues, our best suggestion in this case would be opening a feature request in either one of those repositories that outlines the general problem attempting to be solved (we would recommend only _referencing_ the example resources and attributes so the issue is not transferred back here unintentionally) and reasons why the current implementation is not sufficient so the maintainers of those projects can evaluate the ask. 👍

**Closed by bflad** 2020-01-28 20:23 UTC
Labels: needs-triage, service/eks

**Comment by yann-soubeyrand** [comment] 2020-01-29 12:55
Hi @bflad, thanks for the explanations!

So, if I understand correctly, there is no technical solution in sight due to actual Terraform core limitation. But does it mean that it's safe to assume that these list attributes will **always** contain **one and only one** element and that we can access it by hardcoding [0] after the attribute name (for example `aws_eks_node_group.resources[0].autoscaling_groups`)?

**Comment by bflad** [comment] 2020-01-29 13:04
@yann-soubeyrand that's correct -- I wouldn't expect that to ever change, except potentially in a major version release. 👍
