### ISSUE TITLE
aws_iam_user_login_profile - The validation function validates a string length for an integer.

### ISSUE THREAD

**Issue by chdorb** [terraform-providers/terraform-provider-aws#3912] opened 2018-03-26 09:00 UTC
Hi,

Commit #3702

https://github.com/terraform-providers/terraform-provider-aws/blob/639332e4e82a50ecb5cfcd931a86287848bbe4cb/aws/resource_aws_iam_user_login_profile.go#L39

The password length is an integer, the validate function checks string length (between 4 and 128), so terraform raises an error:
`expected type of password_length to be string`.

Step to reproduce:
- set password_length to an aws_iam_user_login_profile resource

**Comment by bflad** [comment] 2018-03-26 15:29
Hi @chdorb 👋  Sorry you ran into trouble with this resource and that a regression was introduced in the v1.12.0 release with some technical debt cleanup. Thank you very much for pointing to the PR that introduced this. It turns out there was not an acceptance test covering the `password_length` attribute on the `aws_iam_user_login_profile` resource. 😓 

I have submitted #3919 which adds an acceptance test and fixes the regression. We'll get this merged ASAP.

**Closed** 2018-03-26 16:37 UTC
Labels: bug, regression, service/iam

**Comment by bflad** [comment] 2018-03-26 16:39
The fix for this has been merged into master and will release with v1.13.0 of the AWS provider, likely at the end of next week.

**Comment by chdorb** [comment] 2018-03-26 16:44
Thanks !

For other users:
use `version    = "1.11"`  on your `provider "aws" {}` block is a workaround until v1.13.0 is released.

**Comment by bflad** [comment] 2018-03-29 14:46
Ahead of schedule, this has been released in [version 1.13.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1130-march-28-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
