### ISSUE TITLE
Terraform can not validate empty IPv4 address with 2.65.0

### ISSUE THREAD

**Issue by FarshadHadei** [terraform-providers/terraform-provider-aws#13626] opened 2020-06-05 02:24 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14 and Terraform AWS provider 2.65.0

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

```hcl
variable "private_ip" {
  default     = ""
  type        = "string"
  description = "Private IP address to associate with the instance in a VPC."
}
resource "aws_instance" "ec2_node" {
  private_ip = "${var.private_ip}"
}

```

### Expected Behavior

should ignore when no IPv4 is provided

### Actual Behavior

Error: module.x.aws_instance.ec2_node: expected private_ip to contain a valid IPv4 address, got: 

### Steps to Reproduce

1. lockdown the provider to 2.65.0 and `terraform plan`

### References

* #0000

**Comment by manohar-balaram** [comment] 2020-06-05 03:53
I'm facing same issue as of today.

```
$ terraform plan

Error: aws_instance.jump_host1: expected private_ip to contain a valid IPv4 address, got: 
```

**Comment by saurabhgcect** [comment] 2020-06-05 04:39
I am facing same issue 

$ terraform plan

Error: aws_instance.test1: expected private_ip to contain a valid IPv4 address, got:

**Comment by v3se** [comment] 2020-06-05 06:29
Facing the same issue with the new provider version 2.65.0.

Forcing an old version solved the issue:

```
terraform {
    required_providers {
    aws = "~> 2.64.0"
  }
}
```

**Comment by epluginsprivate** [comment] 2020-06-05 07:05
Same for me

**Comment by alizeyj** [comment] 2020-06-05 07:38
Facing this issue while trying to create spot instances at my organisation :(

**Comment by iasinDev** [comment] 2020-06-05 08:02
Seems an issue on latest version: https://github.com/terraform-providers/terraform-provider-aws/commit/1a1ddc5bae2513c9e8f9da63eb0c2292c8e76afd

Maybe related with this:* resource/aws_instance: Add plan time validation to `volume_type`(in `ebs_block_device` and `root_block_device` blocks), `private_ip`, `ipv6_addresses`, and `tenancy` [GH-13033]

So as workaround as @v3se said 2.64 also worked for me

**Comment by gek0** [comment] 2020-06-05 08:26
Can confirm, 2.64.0 version of the provider is fine. But this change will very likely remain since validation function is totally legit. :)

As a workaround, this is a part of our code for `aws_instance` resource and seems to be doing its job
```hcl
resource "aws_instance" "instance" {
  ...    
  private_ip                  = var.private_ip == "" ? null : var.private_ip
  ...

  dynamic "root_block_device" {
    for_each = var.root_block_device
    content {
      delete_on_termination = lookup(root_block_device.value, "delete_on_termination", null)
      encrypted             = lookup(root_block_device.value, "encrypted", null)
      iops                  = lookup(root_block_device.value, "iops", null)
      kms_key_id            = lookup(root_block_device.value, "kms_key_id", null)
      volume_size           = lookup(root_block_device.value, "volume_size", null)
      volume_type           = lookup(root_block_device.value, "volume_type", null)
    }
  }
  dynamic "ephemeral_block_device" {
    for_each = var.ephemeral_block_device
    content {
      device_name  = ephemeral_block_device.value.device_name
      no_device    = lookup(ephemeral_block_device.value, "no_device", null)
      virtual_name = lookup(ephemeral_block_device.value, "virtual_name", null)
    }
  }
}
```

**Comment by beingamarnath** [comment] 2020-06-05 12:26
I'm facing the same issues. And how do we address this with Terraform 0.11 as there is no null we could assign to the object.

**Comment by alizeyj** [comment] 2020-06-05 12:48
> I'm facing the same issues. And how do we address this with Terraform 0.11 as there is no null we could assign to the object.

This hack should help.

```
terraform {
    required_providers {
    aws = "~> 2.64.0"
  }
}
```

**Comment by tdmalone** [comment] 2020-06-05 13:34
We have a module that takes an optional `private_ip` variable, and sets it blank as a default to have AWS automatically assign an IP when we don't wish to set one explicitly. Given sending a blank input here is valid for the AWS API, I think this validation is probably a _little_ over-zealous. (It's also a breaking change that possibly should have waited till a version 3 of the provider).

**Comment by kwerey** [comment] 2020-06-05 13:49
Thanks for that workaround of explicitly setting the version, @v3se . 

Note that if you have explicitly defined an AWS provider you'll need to set that version within that block, not the top level terraform block, eg:

```
provider "aws" {
  region  = "us-east-1"
  version = "~> 2.64.0"
}
```

**Comment by stelah1423** [comment] 2020-06-05 19:33
I was about to comment and say I just hit the same issue, and I am using the private_ip in a similar fashion to everyone else, and since it seems logical to use it in such a fashion, the validation tests should be updated to also consider a blank/null value..

However, I see someone else has already submitted such a PR to address this issue: https://github.com/terraform-providers/terraform-provider-aws/pull/13640

**Closed** 2020-06-05 19:35 UTC
Labels: bug, regression, service/ec2

**Comment by anGie44** [comment] 2020-06-05 19:40
Fix (allowing for `private_ip = "" `) has been merged and will release with `v2.66.0` of the Terraform AWS Provider, expected in next week's release. Apologies for the unintended interruptions in your environments!

**Comment by BrainMonkey** [comment] 2020-06-05 20:24
Also experiencing this issue now on version 11

**Comment by DanielZhangQD** [comment] 2020-06-11 01:47
> Fix (allowing for `private_ip = "" `) has been merged and will release with `v2.66.0` of the Terraform AWS Provider, expected in next week's release. Apologies for the unintended interruptions in your environments!

@anGie44 Will v2.66.0 be released this week?

**Comment by anGie44** [comment] 2020-06-11 15:24
yes, will be released later today @DanielZhangQD!

**Comment by luckyvalentine** [comment] 2020-06-23 01:29
I'm still getting this error with provider.aws v2.67.0

**Comment by anGie44** [comment] 2020-06-26 03:05
hi @luckyvalentine! thanks or commenting here. What does your config look like?  Using the config provided in this issue's example and the same terraform version `11.14`, I haven't been able to reproduce the error with `v2.67.0` but I'd be happy to look into the behavior you're experiencing  :)

**Comment by elpy1** [comment] 2020-06-30 23:49
Just ran into this when setting variable `mount_target_ip_address` default to `""`, to create resource:
```
resource "aws_efs_mount_target" "default" {
  count           = length(var.subnets) > 0 ? length(var.subnets) : 0
  file_system_id  = aws_efs_file_system.default.id
  ip_address      = var.mount_target_ip_address
  subnet_id       = var.subnets[count.index]
  security_groups = [aws_security_group.efs.id]
}
```
This is on `aws   = "~> 2.67.0"`.

Setting the default variable value to `null` fixes it:
```
variable "mount_target_ip_address" {
  type        = string
  description = "The address (within the address range of the specified subnet) at which the file system may be mounted via the mount target"
  default     = null
}
```

**Comment by anGie44** [comment] 2020-07-01 00:40
hi @elpy1, I believe what you're experiencing relates to the validation for IPv4 addresses added in https://github.com/terraform-providers/terraform-provider-aws/pull/13650. The fix https://github.com/terraform-providers/terraform-provider-aws/pull/13958 will be in `v2.69.0` of the provider, expected to be released on Thursday.
