### ISSUE TITLE
AWS Tags as service discovery

### ISSUE THREAD

**Issue by llibicpep** [terraform-providers/terraform-provider-aws#5974] opened 2018-09-25 00:21 UTC
Originally it’s been a bug report to kops: https://github.com/kubernetes/kops/issues/5700. TL;DR: kops, when supplied with existing subnets, creates some extra tags on them. TF nukes unknown tags at the next apply.

But after having some discussions with collegues, it seems like oppinions have been split. The tag (or a list of it), if seen as a separate entity (I know it’s not a case accordingly to AWS reference docs, but still) that goes into a state file and have a separate `*_attachement` resource actually makes sense. It’s clearly that some tools may want to use tags as service discovery, kops being an example. The tags given to a resource by something else than a resource definition in TF generally is not that bad idea. Lifecycle ignore_changes trick won’t work for it since in this case we want to ignore only tags that wasn’t added by TF.

Since we did not got a consensus on this issue with my collegues, I thought it’s worth opening a discussion ticket here.

**Comment by blckct** [comment] 2018-09-25 08:44
Possibly duplicate of #6632?

**Comment by llibicpep** [comment] 2018-09-25 13:03
Ah, thanks for pointing out. A duplicate of https://github.com/hashicorp/terraform/issues/6632 indeed. didn't come up in google search for me for some reason.

**Comment by llibicpep** [comment] 2019-01-23 01:53
Just to link a discussions opened in k8s: https://github.com/kubernetes/kubernetes/issues/73190

**Comment by tracypholmes** [comment] 2019-07-08 14:46
Thank you for using Terraform and for opening up this question! Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-providers for community discussions, and questions around Terraform.

This issue is being closed as a duplicate of [#6632](https://github.com/hashicorp/terraform/issues/6632)

**Closed by tracypholmes** 2019-07-08 14:46 UTC
Labels: question
