### ISSUE TITLE
iam_database_authentication_enabled not supported for aurora-postgres

### ISSUE THREAD

**Issue by hardingian** [terraform-providers/terraform-provider-aws#6592] opened 2018-11-26 18:21 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.10
+ provider.aws v1.39.0
+ provider.random v2.0.0

### Affected Resource(s)

* aws_XXXXX

aws_db_instance

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

resource "aws_rds_cluster" "this" {
  cluster_identifier              = "${var.name}"
  iam_database_authentication_enabled = "true"
  availability_zones              = ["${var.availability_zones}"]
  engine                          = "${var.engine}"
  engine_version                  = "${var.engine_version}"
  kms_key_id                      = "${var.kms_key_id}"
  master_username                 = "${var.username}"
  master_password                 = "${local.master_password}"
  final_snapshot_identifier       = "${var.final_snapshot_identifier_prefix}-${var.name}-${random_id.snapshot_identifier.hex}"
  skip_final_snapshot             = "${var.skip_final_snapshot}"
  backup_retention_period         = "${var.backup_retention_period}"
  preferred_backup_window         = "${var.preferred_backup_window}"
  preferred_maintenance_window    = "${var.preferred_maintenance_window}"
  port                            = "${local.port}"
  db_subnet_group_name            = "${var.db_subnet_group_name}"
#  vpc_security_group_ids          = ["${aws_security_group.this.id}"]
  snapshot_identifier             = "${var.snapshot_identifier}"
  storage_encrypted               = "${var.storage_encrypted}"
  apply_immediately               = "${var.apply_immediately}"
#  db_cluster_parameter_group_name = "${var.db_cluster_parameter_group_name}"

  tags = "${var.tags}"
}

```

### Expected Behavior

An Aurora PostgreSQL instance with iam authentication enabled should have been created,.

### Actual Behavior

Error: Error applying plan:

1 error(s) occurred:

* module.aurora.aws_rds_cluster.this: 1 error(s) occurred:

* aws_rds_cluster.this: error creating RDS cluster: InvalidParameterCombination: IAM Database Authentication is not supported for this configuration.
	status code: 400, request id: c0760769-5887-45c8-bbd0-c0ebfe6afaf5

### Steps to Reproduce

Try to create an aurora postgres rds instance with iam_database_authentication_enabled set to true.
1. `terraform apply`

### Important Factoids

I know this isn't exactly a bug but rather a new option that has not been implemented.  Since they've been promising it forever it might have been easier to support it and let AWS throw the error until they finally implemented it...

### References

* #0000

**Comment by bflad** [comment] 2018-12-02 06:37
Hi @hardingian 👋 Thanks for submitting this.

Terraform is already passing through the `iam_database_authentication_enabled` parameter via your `aws_rds_cluster` resource configuration (we do not limit its usage in that resource) and the error message below is already being returned from the RDS API:

> InvalidParameterCombination: IAM Database Authentication is not supported for this configuration.
> status code: 400, request id: c0760769-5887-45c8-bbd0-c0ebfe6afaf5

If the ask here is to support this incorrect configuration (`iam_database_authentication_enabled = true`), we do not implement logic within Terraform resources to workaround incorrect configurations as that creates confusing behavior. Until the RDS API supports the feature, set `iam_database_authentication_enabled = false` when using Aurora Postgres.

Since this is dependent on an upstream RDS API enhancement and the Terraform resource is already performing the expected behavior, I'm going to close this issue since there is nothing actionable.

**Closed by bflad** 2018-12-02 06:37 UTC
Labels: enhancement, service/rds, upstream
