### ISSUE TITLE
AWS Feature Release: Encrypt Root Volumes at Launch

### ISSUE THREAD

**Issue by dannyleesmith** [terraform-providers/terraform-provider-aws#8624] opened 2019-05-14 07:17 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS have released functionality to launch instances with encrypted root volumes in a single step and some AWS resources will need to be updated to take advantage of this useful feature. According to the release post the SDK's have been updated with these changes so hopefully updates can be made. Some of the AWS documentation, at time of writing, still refer to encrypting unencrypted snapshots at point of use as impossible.

### New or Affected Resource(s)

This may not be an exhaustive list:
* aws_instance (`root_block_device` map change)
* aws_launch_configuration (`root_block_device` map change)
* aws_launch_template (add option to encrypt AMI volumes and potentially `ebs.encrypted` can be used with snapshots)
* aws_spot_fleet_request (perhaps `launch_specification`, documentation for spot fleet hasn't been updated)
* aws_ebs_volume (may already work as it doesn't state `encrypted` won't work with `snapshot_id`)

### Potential Terraform Configuration

```hcl
# aws_instance

resource "aws_instance" "example" {
  ami = "ami-00000000000000000"
  
  root_block_device {
    [..]
    encrypted = true
  }

  ebs_block_device {
    [..]
    snapshot_id = "snap-00000000000000000"
    encrypted   = true
  }
}

# aws_launch_configuration

resource "aws_launch_configuration" "example" {
  [..]
  encrypted = true
  image_id  = "ami-00000000000000000"
}

# aws_launch_template

resource "aws_launch_template" "example" {
  [..]
  encrypted = true
  image_id  = "ami-00000000000000000"
}

# aws_spot_fleet_request

resource "aws_spot_fleet_request" "example" {
  [..]
  launch_specification {
    ami       = "ami-d06a90b0"
    encrypted = true
  }
}

# aws_ebs_volume

resource "aws_ebs_volume" "example" {
  encrypted   = true
  snapshot_id = snap-00000000000000000
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2019/05/launch-encrypted-ebs-backed-ec2-instances-from-unencrypted-amis-in-a-single-step/

**Comment by stonefury** [comment] 2019-05-14 15:08
Is there any work-around till support is added in TF?

**Comment by dannyleesmith** [comment] 2019-05-14 15:20
> Is there any work-around till support is added in TF?

I guess business-as-usual, @stonefury, so still having to create encrypted root AMI's rather than specifying the encryption at launch. Unless anyone else has any hacky alternatives?

**Comment by michaelahern** [comment] 2019-05-14 23:14
Related, would also add this should also include specifying a different kms_key_id.

```
resource "aws_instance" "example" {
  ami = "ami-00000000000000000"
  
  root_block_device {
    [..]
    encrypted = true
    kms_key_id = "00000000-0000-0000-0000-000000000000"
  }

  ebs_block_device {
    [..]
    snapshot_id = "snap-00000000000000000"
    encrypted   = true
    kms_key_id = "00000000-0000-0000-0000-000000000000"
  }
}
```

More details at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIEncryption.html

**Comment by dayglojesus** [comment] 2019-05-15 20:18
This is a duplicate of #6246, but 👍 .

**Comment by dannyleesmith** [comment] 2019-05-15 21:02
Hi @dayglojesus, thanks for pointing out that one. Didn't see it and didn't think it would exist given this is a new feature and wasn't possible before now. I'll let the mods decide whether to work from this or the other.

Cheers,

-- Danny

**Comment by trj922** [comment] 2019-05-23 23:14
Our server admin recreated our corporate linux AMI without encrypting the root volume after this feature came out.   We really need this

**Comment by dannyleesmith** [comment] 2019-05-24 05:54
@trj922 in the meantime this release from yesterday may be of interest to you to solve for that problem: https://aws.amazon.com/about-aws/whats-new/2019/05/with-a-single-setting-you-can-encrypt-all-new-amazon-ebs-volumes/

**Comment by rmarable** [comment] 2019-06-11 15:01
Unfortunately that encrypts all EBS volumes within the account which in turn limits the instance types that can be launched:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#EBSEncryption_supported_instances

It would be super helpful if this feature could be made available in the root EBS volume template.

**Comment by FernandoMiguel** [comment] 2019-06-11 17:40
@rmarable limits to almost every single instance ehe

**Comment by thanura1988** [comment] 2019-06-26 22:33
need this very badly folks

**Comment by FernandoMiguel** [comment] 2019-06-27 05:33
@thanura1988 this is out already.
I've already deployed this yesterday in our accounts

**Comment by Nklya** [comment] 2019-06-27 10:43
@FernandoMiguel what do you mean?
This issue is still open, linked PRs too. Where it's out?

**Comment by FernandoMiguel** [comment] 2019-06-27 10:59
@Nklya https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2160-june-20-2019

> New Resource: aws_ebs_encryption_by_default (#8771)

**Comment by thanura1988** [comment] 2019-06-27 15:18
Thanks @FernandoMiguel 
this did what i wanted 
Eventho its not doing it with "root_block_device", this solves my issue
https://www.terraform.io/docs/providers/aws/r/ebs_encryption_by_default.html

**Comment by atiftw** [comment] 2019-07-06 19:41
Hi,

More details here-:

https://aws.amazon.com/blogs/security/how-to-quickly-launch-encrypted-ebs-backed-ec2-instances-from-unencrypted-amis/

Going by the cli, this currently works by passing an EBS volume with the device_name as /dev/xvda, do you think it makes sense to have it as follows?

```
resource "aws_instance" "example" {
  ami = "ami-00000000000000000"

//root block device  
  ebs_block_device {
    device_name = "/dev/xvda"
    snapshot_id = "snap-00000000000000000"
    encrypted   = true
    kms_key_id = "00000000-0000-0000-0000-000000000000"
  }
}
```
I'll open a PR with the changes soon.

**Comment by pompbediener** [comment] 2019-07-30 14:58
👍 Would like to see this.

**Comment by bflad** [comment] 2019-08-02 04:53
Hi everyone 👋 

The following were previously supported:

* `aws_ebs_default_kms_key` resource to set region KMS Key for encyrption for all newly launched volumes
* `aws_ebs_encryption_by_default` resource to enable KMS encryption by default for all newly launched volumes
* `aws_ebs_volume` resource already supported the `encrypted` and `kms_key_id` arguments
* `aws_launch_template` resource `block_device_mappings` `ebs` configuration block already supported the `encrypted` and `kms_key_id` arguments

The following were just merged and will be releasing in version 2.23.0 of the Terraform AWS Provider, next week:

* `aws_instance` resource `ebs_block_device` and `root_block_device` configuration block `encryption` and `kms_key_id` arguments
* `aws_launch_configuration` resource `root_block_device` configuration block encrypted argument

The following were just submitted and likely to also release in version 2.23.0 of the Terraform AWS Provider, next week:

* `aws_spot_fleet_request` resource `ebs_block_device` and `root_block_device` `kms_key_id` arguments

Cheers 🎉

**Closed** 2019-08-07 11:32 UTC
Labels: enhancement, service/ec2

**Comment by bflad** [comment] 2019-08-07 11:34
Hi again 👋 

This functionality was also just merged:

* `aws_spot_fleet_request` resource `ebs_block_device` and `root_block_device` `kms_key_id` arguments

We should be releasing version 2.23.0 of the Terraform AWS Provider in the next day or two. 👍

**Comment by dannyleesmith** [comment] 2019-08-07 11:43
@bflad are we sure everything this issue requested has been resolved? As one example, looking at [aws_instance](https://www.terraform.io/docs/providers/aws/r/instance.html) I see no option to set encryption on a root volume that may not be encrypted at the AMI level.

**Comment by bflad** [comment] 2019-08-07 11:47
@dannyleesmith https://github.com/terraform-providers/terraform-provider-aws/issues/8624#issuecomment-517547724

> The following were just merged and will be releasing in version 2.23.0 of the Terraform AWS Provider, next week:
> 
> aws_instance resource ebs_block_device and root_block_device configuration block encryption and kms_key_id arguments

**Comment by dannyleesmith** [comment] 2019-08-07 11:48
@bflad ah the phrasing confused me, I read it as those might be properties of the `aws_spot_fleet_request` resource as they were all on the same bullet point

I look forward to seeing the changes, thank you very much

**Comment by priyadhanam** [comment] 2019-10-07 07:30
Thank   you a lot for providing individuals with a very spectacular possibility to   read critical reviews from this site.
--
[Salesforce online training](https://www.gangboard.com/crm-training/salesforce-training)
