### ISSUE TITLE
Add support for AWS ALB redirect action

### ISSUE THREAD

**Issue by fdearle** [terraform-providers/terraform-provider-aws#5475] opened 2018-08-08 10:33 UTC
Amazon have recently announced support for redirects natively within Application Load Balancers. [See Announcement](https://aws.amazon.com/about-aws/whats-new/2018/07/elastic-load-balancing-announces-support-for-redirects-and-fixed-responses-for-application-load-balancer/).

This is a useful addition to the ALB as is removes the need to have a separate web server to handle HTTP -> HTTPS redirects.

Configuring the feature requires changes to the aws_lb_listener in terraform. Specifically the default_action needs to support redirect as a type and must also implement a new field type to support the new [RedirectActionConfig](https://github.com/aws/aws-sdk-go/tree/v1.14.33) that has been added to default_action.

The AWS Go SDK has already been updated to support RedirectActionConfig in [version 1.14.33](https://github.com/aws/aws-sdk-go/tree/v1.14.33).

I would attempt to implement this myself except my limited Go experience does not extend to the schema changes that would need to be implemented to support  a new redirect_action_config field type.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_lb_listener

### Potential Terraform Configuration

```hcl
# The default action will need to support a redirect_action_config, something like:
resource "aws_lb_listener" "default_listener"  {
    ....
    default_action {
        type = "redirect"
        redirect_action_config = {
            protocol = "HTTPS | HTTP | #{protocol}"
            host = "hostname | #{host}"
            port = "port | #{port}"
            path = "path | #{path}"
            query = "query | #{query}"
        }
    }
}
```

### References

* #0000

**Comment by mathieumalfeyt** [comment] 2018-08-08 11:35
There is already an issue filled for this and a PR pending:
https://github.com/terraform-providers/terraform-provider-aws/issues/5344
https://github.com/terraform-providers/terraform-provider-aws/pull/5430

**Comment by bflad** [comment] 2018-08-08 13:11
Closing as duplicate of the above mentioned issue and PR to consolidate discussions/efforts. Please track those for further updates. 👍

**Closed by bflad** 2018-08-08 13:11 UTC
Labels: enhancement, service/elbv2
