### ISSUE TITLE
Support for Express Workflows for AWS Step Functions

### ISSUE THREAD

**Issue by ramadso** [terraform-providers/terraform-provider-aws#11914] opened 2020-02-05 20:19 UTC
### Version
Terraform v0.12.20

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by Clete2** [comment] 2020-03-11 18:01
Related to https://github.com/terraform-providers/terraform-provider-aws/issues/11348

**Comment by DrFaust92** [comment] 2020-05-21 21:30
duplicate of #11348

**Closed by DrFaust92** 2020-05-21 21:30 UTC
Labels: enhancement, needs-triage, service/sfn
