### ISSUE TITLE
aws_ecs_task_definition validation failures obscured when attempting to use the resource 

### ISSUE THREAD

**Issue by jmahowald** [terraform-providers/terraform-provider-aws#1160] opened 2017-07-14 22:25 UTC
### Terraform Version

0.9.3+

### Affected Resource(s)

Please list the resources as a list, for example:
- aws_ecs_task_definition
- aws_ecs_service 

I believe this would happen with any resource that uses an `aws_ecs_task_definition` but the `aws_ecs_service` is the most natural partner 

### Terraform Configuration Files
```hcl

variable "vpc_id" { }
variable "listener_arn" {}
variable "cluster_id" {}
variable "ecs_role_arn" {}
variable "task_def" {}


variable "lb_container_name" {
    description = "The name of the container in your task defintion that will be hit by the load balancer"
}
variable "container_port" { }
variable "desired_count" {
    default = 2
}
variable "service_name" {
    description = "Name of the ECS service"
}
variable "hostnamerule" {
    description = "what is the pattern to match for"
}
variable "priority" {
    description = "the priority amongst all the rules of the listener (unfortunately must be unique)"
}


resource "aws_alb_target_group" "default" {
  name = "${terraform.env}-${var.service_name}"
  //This shouldn't be required since we'll be using dynamic port mapping 
  port     = 80
  protocol = "HTTP"
  vpc_id   = "${var.vpc_id}"
}

resource "aws_alb_listener_rule" "host_based_routing" {
  listener_arn = "${var.listener_arn}"
  priority     = "${var.priority}"

  action {
    type             = "forward"
    target_group_arn = "${aws_alb_target_group.default.arn}"
  }
  condition {
    field  = "host-header"
    values = ["${var.hostnamerule}"]
  }
}

resource "aws_ecs_service" "default" {
  name            = "${var.lb_container_name}"
  cluster         = "${var.cluster_id}"

  task_definition = "${aws_ecs_task_definition.default.arn}"
  desired_count   = "${var.desired_count}"
  iam_role        = "${var.ecs_role_arn}"

  load_balancer {
    target_group_arn = "${aws_alb_target_group.default.arn}" 
    container_name = "${var.lb_container_name}"
    container_port = "${var.container_port}"
  }

  # Track the latest ACTIVE revision
  // task_definition = "${aws_ecs_task_definition.default.family}:${max("${aws_ecs_task_definition.default.revision}", "${data.aws_ecs_task_definition.default.revision}")}"

}

resource "aws_ecs_task_definition" "default" {
  family = "${var.service_name}"
  container_definitions = "${var.task_def}"
}

```

Valid Task Definition:
```json
[
    {
      "name": "nginx",
      "image": "nginx:alpine",
      "memory": 128,
      "portMappings": [
        {
          "containerPort": 80,
          "protocol": "tcp"
        }
      ]    
    }
]

```

Invalid Task Definition:

```json
{
  "family": "nginx",
  "containerDefinitions": [
    {
      "name": "nginx",
      "image": "nginx:alpine",
      "memory": 128,
      "portMappings": [
        {
          "containerPort": 80,
          "protocol": "tcp"
        }
      ]    
    }
  ]
}
```

### Debug Output

https://gist.github.com/jmahowald/0d629553f86d507fe13f31d5ee412d9a

### Expected Behavior

When having an invalid task definition, you should have an error to the effect of 

``ECS Task Definition container_definitions is invalid: Error decoding JSON: json: cannot unmarshal object into Go value of type []*ecs.ContainerDefinition]``

What should have happened?

### Actual Behavior

When using the invalid definition the error is obscured and confusing

```

* module.ecs_tg.aws_ecs_service.default: 1 error(s) occurred:

* module.ecs_tg.aws_ecs_service.default: Resource 'aws_ecs_task_definition.default' not found for variable 'aws_ecs_task_definition.default.arn'
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
-  https://github.com/hashicorp/terraform/pull/12161  is when validations for aws_ecs_task_definition was introduced and this behavior started (though I don't believe that is the root cause)

**Comment by pecigonzalo** [comment] 2017-08-01 14:29
Related to https://github.com/hashicorp/terraform/issues/15156

**Comment by Dominik-K** [comment] 2017-10-20 16:18
@pecigonzalo Better link to corresponding AWS provider issues. Here: https://github.com/terraform-providers/terraform-provider-aws/issues/1644

**Comment by bflad** [comment] 2018-06-15 16:51
Hi folks! 👋 Sorry for the unexpected behavior here.

It turns out this is likely an issue upstream in Terraform core, rather than anything to do with the AWS provider specifically. This scenario basically occurs anytime we implement a resource attribute with a `ValidateFunc` and then that resource is then referenced by another resource. Terraform core, when the first resource is failing that validation, is preferring to return the invalid resource reference message instead of the resource validation error.

I'm going to close this issue out as we have a few upstream tracking issues relating to this:
* https://github.com/hashicorp/terraform/issues/18129
* https://github.com/hashicorp/terraform/issues/16332
* https://github.com/hashicorp/terraform/issues/14333

I would suggest commenting on and upvoting those for the latest updates on this. 👍

**Closed by bflad** 2018-06-15 16:51 UTC
Labels: bug, service/ecs
