### ISSUE TITLE
Git Source code repository for sagemaker

### ISSUE THREAD

**Issue by vdahmane** [terraform-providers/terraform-provider-aws#15245] opened 2020-09-21 16:07 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
It's not possible to create git repository code for AWS sagemaker

![image](https://user-images.githubusercontent.com/30653479/93792176-75521000-fc35-11ea-8d42-1a84cfe05162.png)

### New or Affected Resource(s)
It is possible to have a new resource we create source code repository for AWS Sagemaker?

### Potential Terraform Configuration

For example: 

```hcl
resource "aws_sagemaker_notebook_git_repository" "example" {
  name         = "foo"
  type           = <aws code commit> or <github/gitlab>
  git_config  = "foo"
}
```

### References

* #0000

**Comment by gdavison** [comment] 2020-09-23 00:11
This enhancement will require two changes:
1. Adding Git repository fields to `aws_sagemaker_notebook_instance`

```terraform
resource "aws_sagemaker_notebook_instance" "example" {
  ...
  default_code_repository    = <name of aws_sagemaker_code_repository> or <git url> # optional
  additional_code_repository = <array of <name of aws_sagemaker_code_repository> or <git url>> # optional, max 3
  ...
}
```

2. Creating `aws_sagemaker_code_repository`

```terraform
resource "aws_sagemaker_code_repository" "example" {
  name = "example"
  git_config {
    repository_url = <git url>
    branch         = <branch name> # optional
    secret_arn     = <ARN of secrets manager secret> # optional
  }
}
```

**Comment by DrFaust92** [comment] 2020-10-22 21:30
duplicate of #13817

**Closed by DrFaust92** 2020-10-22 21:30 UTC
Labels: enhancement, service/sagemaker
