### ISSUE TITLE
aws_vpc_peering_connection can't find owner_id from aws_vpc data source

### ISSUE THREAD

**Issue by MikaYuoadas** [terraform-providers/terraform-provider-aws#9311] opened 2019-07-11 13:29 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.3
provider.aws v2.18.0

### Affected Resource(s)

* data aws_vpc
* resource aws_vpc_peering_connection

### Terraform Configuration Files

I have a module handling the vpc peering:
```hcl
resource "aws_vpc_peering_connection" "source-to-target" {
  peer_owner_id = var.target-vpc.owner_id
  peer_vpc_id   = var.target-vpc.id
  peer_region   = var.target-region
  vpc_id        = var.source-vpc.id
}
```

which is called like this in the root module:
```hcl
data "aws_vpc" "target" {
  provider = aws.A
  filter {
    name   = "tag:Name"
    values = ["target"]
  }
}

module "peering-A" {
  source = "./modules/peering/"
  providers = {
    aws.target-account = aws.A  }

  source-vpc                  = aws_vpc.cobra-apps
  target-region               = data.aws_region.A.name
  target-vpc                  = data.aws_vpc.target
}
```

### Debug Output

```
Error: Error creating VPC Peering Connection: InvalidParameterValue: Invalid value '46912302727' for peerOwnerId.
	status code: 400, request id: 2c9bcb6b-5827-4c1d-b740-1724f144733b

  on modules/vpc/modules/peering/main.tf line 3, in resource "aws_vpc_peering_connection" "source-to-target":
   3: resource "aws_vpc_peering_connection" "source-to-target" {
```

### Expected Behavior

Successfully create the peering

### Actual Behavior

It  works on 2 out of our 4 accounts. It seems to only fail on account whose id starts with a leading 0.
For example here with an account id '012345678901', the error message displays '12345678901'.

### Steps to Reproduce

1. Create 2 VPCs in two separate aws account
2. `terraform apply`

### Workaround

Hardcoding the value for `peer_owner_id` by hand (with the leading 0) works as expected.

**Comment by ewbankkit** [comment] 2019-07-12 14:32
My guess is that this is caused by some subtle difference between TF 0.11 and 0.12.
Can you try putting `"` around the variable references?

**Comment by MikaYuoadas** [comment] 2019-07-12 14:35
You mean in the resource `aws_vpc_peering_connection` like so:
```
resource "aws_vpc_peering_connection" "source-to-target" {
  peer_owner_id = "${var.target-vpc.owner_id}"
  peer_vpc_id   = var.target-vpc.id
  peer_region   = var.target-region
  vpc_id        = var.source-vpc.id
}
?

**Comment by MikaYuoadas** [comment] 2019-07-12 14:38
(If so, I get the same error).

**Comment by bflad** [comment] 2019-07-30 22:40
Hi @MikaYuoadas 👋 Are you still having this issue on the latest versions of Terraform and the Terraform AWS Provider? I'm not able to reproduce this with the following configuration in an AWS account ID that begins with zero:

```hcl
# main.tf

terraform {
  required_providers {
    aws = "2.21.1"
  }

  required_version = "0.12.5"
}

provider "aws" {
  region = "us-west-2"
}

resource "aws_vpc" "test1" {
  cidr_block = "10.0.0.0/24"
}

resource "aws_vpc" "test2" {
  cidr_block = "10.0.1.0/24"
}

module "test" {
  source = "./module1"

  source_vpc = aws_vpc.test1
  target_vpc = aws_vpc.test2
}

output "source_owner_id" {
  value = module.test.source_owner_id
}

output "target_owner_id" {
  value = module.test.target_owner_id
}

# module1/main.tf

variable "source_vpc" {}

variable "target_vpc" {}

resource "aws_vpc_peering_connection" "source-to-target" {
  peer_owner_id = var.target_vpc.owner_id
  peer_vpc_id   = var.target_vpc.id
  vpc_id        = var.source_vpc.id
}

output "source_owner_id" {
  value = var.source_vpc.owner_id
}

output "target_owner_id" {
  value = var.target_vpc.owner_id
}
```

Applies successfully without number issue:

```console
$ terraform apply
...
aws_vpc.test1: Creating...
aws_vpc.test2: Creating...
aws_vpc.test1: Creation complete after 5s [id=vpc-0e5e29f503b078f87]
aws_vpc.test2: Creation complete after 5s [id=vpc-0f01d4f83f9f2b09a]
module.test.aws_vpc_peering_connection.source-to-target: Creating...
module.test.aws_vpc_peering_connection.source-to-target: Creation complete after 2s [id=pcx-018921c41ebda803f]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Outputs:

source_owner_id = 0678--OMITTED--
target_owner_id = 0678--OMITTED--
```

**Comment by bflad** [comment] 2019-09-04 18:30
It's been a long time since we heard from you here so we're going to close this out. If you're still having this problem on the latest versions of Terraform and the Terraform AWS Provider (v0.12.7 and v2.26.0 as of this writing), please feel free to open a new issue and complete all of the information requested in the [Bug Report template](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/ISSUE_TEMPLATE/Bug_Report.md) so that we can attempt to understand and reproduce the problem.

**Closed by bflad** 2019-09-04 18:30 UTC
Labels: needs-triage, service/ec2, waiting-response

**Comment by MikaYuoadas** [comment] 2019-10-04 14:30
I don't have the issue anymore with latest terraform and aws provider.
