### ISSUE TITLE
Support for AWS Elasticsearch across 3 availability zones

### ISSUE THREAD

**Issue by dornera** [terraform-providers/terraform-provider-aws#7504] opened 2019-02-11 15:45 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon Elasticsearch Service now enables you to deploy your instances across three Availability Zones (AZs) providing better availability for your domains.

### Affected Resource(s)

* aws_elasticsearch_domain

### References

* https://aws.amazon.com/about-aws/whats-new/2019/02/amazon-elasticsearch-service-now-supports-three-availability-zone-deployments/
* https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains.html#es-managedomains-multiaz

**Comment by jtran-sigsci** [comment] 2019-02-11 23:13
afaictl it looks like the version of aws-sdk-go needs to be updated:

```
2019-02-11T14:56:00.795-0800 [DEBUG] plugin.terraform-provider-aws_v1.58.0_x4: 2019/02/11 14:56:00 [DEBUG] [aws-sdk-go] {"message":"You must choose an even number of data nodes for a two Availability Zone deployment"}
2019-02-11T14:56:00.795-0800 [DEBUG] plugin.terraform-provider-aws_v1.58.0_x4: 2019/02/11 14:56:00 [DEBUG] [aws-sdk-go] DEBUG: Validate Response es/CreateElasticsearchDomain failed, not retrying, error ValidationException: You must choose an even number of data nodes for a two Availability Zone deployment
```

**Comment by dornera** [comment] 2019-02-11 23:20
> 
> 
> afaictl it looks like the version of aws-sdk-go needs to be updated:
> 
> ```
> 2019-02-11T14:56:00.795-0800 [DEBUG] plugin.terraform-provider-aws_v1.58.0_x4: 2019/02/11 14:56:00 [DEBUG] [aws-sdk-go] {"message":"You must choose an even number of data nodes for a two Availability Zone deployment"}
> 2019-02-11T14:56:00.795-0800 [DEBUG] plugin.terraform-provider-aws_v1.58.0_x4: 2019/02/11 14:56:00 [DEBUG] [aws-sdk-go] DEBUG: Validate Response es/CreateElasticsearchDomain failed, not retrying, error ValidationException: You must choose an even number of data nodes for a two Availability Zone deployment
> ```

It looks the feature was added on 2/07
* https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v11630-2019-02-07
* https://github.com/aws/aws-sdk-go/commit/130e7e7f5cfa00e267b884bd2772ae986f9e8273

**Comment by jhenry82** [comment] 2019-03-12 19:58
Should I still be experiencing this issue in v2.1 of the AWS provider? It looks like it was merged well ahead of the 2.1 release but I still see the error message when trying to boot a 3-node cluster across 3 AZ's. Are there new as-yet undocumented options I need to pass to my resource?
```
  cluster_config.0.instance_count:                           "" => "3"
  vpc_options.#:                                             "" => "1"
  vpc_options.0.availability_zones.#:                        "" => "<computed>"
  vpc_options.0.security_group_ids.#:                        "" => "1"
  vpc_options.0.security_group_ids.1404430042:               "" => "sg-0a8ad12369b03a1ea"
  vpc_options.0.subnet_ids.#:                                "" => "3"
  vpc_options.0.subnet_ids.2540967096:                       "" => "subnet-07ed00cc615e4af9b"
  vpc_options.0.subnet_ids.340751494:                        "" => "subnet-0f99ee831127e4ea0"
  vpc_options.0.subnet_ids.932693878:                        "" => "subnet-0f8c727ebb4a1d0b4"
  vpc_options.0.vpc_id:                                      "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* module.elasticsearch.aws_elasticsearch_domain.default: 1 error(s) occurred:

* aws_elasticsearch_domain.default: ValidationException: You must choose an even number of data nodes for a two Availability Zone deployment
	status code: 400, request id: a9675a4c-4500-11e9-9ac8-072b7d046e84
```

**Comment by dornera** [comment] 2019-03-12 20:13
@jhenry82 I don't think this was merged. Above your comment, it appears it was added to the 2.3.0 milestone.

**Comment by jhenry82** [comment] 2019-03-13 01:35
I thought the implication was that it would be resolved by this PR, which was merged 28 days ago and is tagged in 1.58: https://github.com/terraform-providers/terraform-provider-aws/pull/7511. But apparently I am missing something :) Guess that just laid the groundwork for this issue to be worked.

**Comment by LaurenceChau** [comment] 2019-03-13 03:07
vpc_options.#:                                           "" => "1"
  vpc_options.0.availability_zones.#:                      "" => "<computed>"
  vpc_options.0.security_group_ids.#:                      "" => "1"
  vpc_options.0.security_group_ids.34337178:               "" => "sg-0e882c0c8a0d7342f"
  vpc_options.0.subnet_ids.#:                              "" => "3"
  vpc_options.0.subnet_ids.116119174:                      "" => "subnet-0ac696415210775c1"
  vpc_options.0.subnet_ids.219527426:                      "" => "subnet-0f4e5bf1fd67f9475"
  vpc_options.0.subnet_ids.3452613960:                     "" => "subnet-05c05f65046e97152"
  vpc_options.0.vpc_id:                                    "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* aws_elasticsearch_domain.es: 1 error(s) occurred:

* aws_elasticsearch_domain.es: ValidationException: You must specify exactly

manually build this plugin but still get the error

**Comment by dornera** [comment] 2019-03-13 10:28
> 
> 
> I thought the implication was that it would be resolved by this PR, which was merged 28 days ago and is tagged in 1.58: #7511. But apparently I am missing something :) Guess that just laid the groundwork for this issue to be worked.

It requires an update to aws-sdk-go which is what was merged.

**Comment by jtran-sigsci** [comment] 2019-03-20 17:00
Although the provider has updated its version of aws-sdk-go ( > 1.16.30) , the problem is that terraform 0.11.13 still is using an older version aws-sdk-go (1.14.31).   The only tag of terraform that uses a version we need for this elasticsearch three zone support is 'v0.12.0-beta1'

**Comment by keety** [comment] 2019-03-29 18:53
@bflad  noticed  the release was removed from 2.3.0 milestone.
 Based on @jtran-sigsci  comment  is it safe to assume this would only be supported in version greater than  terraform 0.11.13 ?

**Comment by bflad** [comment] 2019-03-29 18:56
@keety Since Terraform 0.10, Terraform providers are no longer distributed as part of Terraform Core and have their own release cadence. Here are the [Terraform AWS Provider CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md) and the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) for reference. When this functionality is released in the Terraform AWS Provider, it can be used in any Terraform 0.10 or Terraform 0.11 environment.

**Comment by dnedev** [comment] 2019-03-29 19:37
Since milestone `2.4.0` bumped `aws-sdk-go` up to `v1.19.4` (https://github.com/terraform-providers/terraform-provider-aws/pull/8108), does that mean when using AWS Provider `2.4.0` we can use 3 AZs?

**Comment by jtran-sigsci** [comment] 2019-03-29 19:51
You can try it but my experience is that it still doesn't work for me.  Has anyone else gotten it to work?

**Comment by jhenry82** [comment] 2019-03-29 20:02
Just tried 2.4, same error.

**Comment by jtcressy** [comment] 2019-04-01 16:09
while `2.4.0` bumped `aws-sdk-go` to the newer version, it does not outright enable 3 AZ deployments. In my PR above, I'm enabling another parameter in `cluster_config` that specifies the number of AZ's to deploy. It's [WIP] so i'd like some input. :)
example:
```
cluster_config {
  ...
  zone_awareness_enabled = true
  zone_awareness_count     = 3
}
```

**Comment by dnedev** [comment] 2019-04-02 07:29
@jtcressy I think it is implied from the subnet count, if you deploy in a VPC at least. We set `aws_elasticsearch_domain. cluster_config. zone_awareness_enabled = true` and supply 3 distinc subnets

**Comment by jtcressy** [comment] 2019-04-02 14:38
Yes, it works already if you are deploying in a VPC. However I have a use case which requires a public ES endpoint, and as such we can't rely on subnet allocation to imply an availability zone count.

**Comment by MrBagheera** [comment] 2019-04-04 10:57
For what it is worth: we have submitted an issue to AWS support as to what request format for 3-AZ cluster should and got following reply:
> I have checked the Cloudtrail shared by you. In order to have 3 Avaialbility zone to work we need to pass the following config parameter in order to it worked and accept 3 subnet:
>
```
ZoneAwarenessConfig={AvailabilityZoneCount=3}
```
> The AWS Elasticsearch will accept 3 subnet when the above parameter is set to 3 else it will fail.
>
> Further, the other configuration done by you are valid changes. Also I would like to inform you that the support for 3 Availability zone has already been added to AWS Go SDK as part of Release v1.16.30. For more information on AWS GO SDK release : https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v11630-2019-02-07

**Comment by Orlamh** [comment] 2019-04-17 19:36
> Yes, it works already if you are deploying in a VPC. However I have a use case which requires a public ES endpoint, and as such we can't rely on subnet allocation to imply an availability zone count.

I still can't get to work in VPC mode.  
Terraform v0.11.3
+ provider.aws v2.6.0

cluster_config.0.zone_awareness_enabled:          "" => "true"
vpc_options.0.subnet_ids.#:                       "" => "3"

What am I missing?

**Comment by dimisjim** [comment] 2019-05-08 15:40
@Orlamh Doesn't work with public endpoint as well

**Comment by jaiwardhan** [comment] 2019-06-19 07:27
Yeah, this still doesn't work with 3AZ or more. Neither it takes dynamically based on the length of subnets passed. Looks like that the suggestion for `zone_awareness_count` is also not added yet.
Keep on getting this.
```
..invalid or unknown key: zone_awareness_count
```

**Comment by yashwanthkalva** [comment] 2019-06-19 09:52
Is there any way out ? Not able to use terraform to create an elastic search cluster on AWS in 3-AZs ?

Any update or inputs will be useful ?

**Comment by ZoidBB** [comment] 2019-06-28 20:31
My project definitely needs this ASAP

**Comment by BrianMusson** [comment] 2019-07-02 03:58
Experienced this just now, would appreciate this to work across 3 AZs.

**Comment by truonghongphuoc** [comment] 2019-07-03 08:29
Got same issue today, hope can create ES domain in 3 AZs soon.

**Comment by VidhushiniSrinivasan16** [comment] 2019-07-12 23:30
Got the same issue today. Any updates?

**Comment by Moulick** [comment] 2019-07-14 14:02
Damn, how long is this gonna take?

**Comment by bflad** [comment] 2019-07-17 23:33
Hi folks 👋 @jtcressy did some great work to get the implementation started and we are currently verifying a finished implementation here: #9398 

Barring any major issues, we are hoping to get the new configuration out with this or next week's release of the Terraform AWS Provider. This issue will automatically close when the functionality has been merged, hopefully soon. 😄

**Closed** 2019-07-18 16:52 UTC
Labels: enhancement, service/elasticsearch

**Comment by bflad** [comment] 2019-07-18 16:57
Hi again 😄 

Support for this functionality has been merged for the `aws_elastisearch_domain` resource and will release with version 2.20.0 of the Terraform AWS Provider, later today. The configuration to enable zone awareness with three availability zones looks like the following:

```hcl
# Example implementation - only showing relevant new configuration
resource "aws_elasticsearch_domain" "example" {
  # ... other configuration ...

  cluster_config {
    # ... other configuration ...
    zone_awareness_enabled = true

    zone_awareness_config {
      availability_zone_count = 3
    }
  }
}
```

See also the [Amazon Elasticsearch Development Guide](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains.html#es-managedomains-multiaz) for additional recommendations and considerations with this functionality. 🎉
