### ISSUE TITLE
Error creating CodeBuild project: InvalidInputException

### ISSUE THREAD

**Issue by LennyCastaneda** [terraform-providers/terraform-provider-aws#11742] opened 2020-01-23 22:20 UTC
The issue is when I run the Terraform configuration module below, whichis used for an AMI pipeline, it get this error. (see screen shot below).

When the variable inputs are all within the acceptable restrictions, no spaces, small character count and only underscores.

the only way to remiedate this issue is to simply rerun "terraform apply" and the error is gone and the configuration is fully deployed.

Thinking this maybe a bug because it makes no sense why it would error out the first time but the second time it successfully competes.

<img width="769" alt="Error_Creating_Codebuild_Project" src="https://user-images.githubusercontent.com/9893446/73028793-e1a51700-3dfb-11ea-8c6c-772e9eb08a26.PNG">

resource "aws_codebuild_project" "container" {
  name          = join("", ["${var.ami_repo_name}", "-build"])
  description   = join("", ["Build for ", "${var.ami_repo_name}", " repository"])
  build_timeout = "180"
  service_role  = aws_iam_role.codebuild_service_role.arn
	badge_enabled	= false

  artifacts {
    type = "NO_ARTIFACTS"
  }

  cache {
    type     = "NO_CACHE"
  }

  environment {
    compute_type                = "BUILD_GENERAL1_SMALL"
    image                       = "aws/codebuild/amazonlinux2-x86_64-standard:2.0"
    type                        = "LINUX_CONTAINER"
    image_pull_credentials_type = "CODEBUILD"
  }

  logs_config {
    cloudwatch_logs {
			status			= "ENABLED"
      group_name 	= ""
      stream_name = ""
    }

    s3_logs {
      status = "DISABLED"
    }
  }

  source {
    type            = "S3"
    location        = join("/",["${var.ami_repo_bucket_name}","${var.ami_repo_name}", "master.zip"])
  }

	secondary_sources {
    type            	= "S3"
		source_identifier = "ami_scripts"
    location        	= join("/",["${var.ami_scripts_repo_bucket_name}","${var.ami_scripts_repo_name}", "master.zip"])
  }

  vpc_config {
    vpc_id = var.vpc_id

    subnets = [
      "${var.private_subnet_ids[0]}",
      "${var.private_subnet_ids[1]}",
    ]

    security_group_ids = [
      aws_security_group.codebuild_packer.id
    ]
  }

  tags = {
    Environment = "Prod"
		Terraform		= "True"
  }
}

**Comment by AzySir** [comment] 2020-01-24 04:58
Also having the same issue!

**Comment by bflad** [comment] 2020-01-24 12:55
Hi @LennyCastaneda 👋 Thank you for reporting this issue and sorry you are running into trouble. This is due to a regression in version 2.45.0 of the Terraform AWS Provider (https://github.com/terraform-providers/terraform-provider-aws/issues/11682) and was resolved in [Terraform AWS Provider version 2.46.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2460-january-23-2020), which was released January 23rd. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading. 👍

**Closed by bflad** 2020-01-24 12:55 UTC
Labels: regression, service/codebuild

**Comment by LennyCastaneda** [comment] 2020-01-24 20:24
Wow that was fasts! Thanks @bflad ... I'll get that provider upgraded.

**Comment by AzySir** [comment] 2020-01-27 05:01
Hey @LennyCastaneda how did you go? DId it work when you updated the provider?

**Comment by LennyCastaneda** [comment] 2020-01-28 15:58
Hi @AzySir it worked well. The “InvalidInputException” error did not occur. I just updated all my root modules with 2.46 and all good to go now. Thanks again for putting that patch.

**Comment by LennyCastaneda** [comment] 2020-01-30 00:47
Hey @AzySir I did notice something strange after the update though....I'll create a new issue ticket but it was when I did a plan Terraform attempted to recreate resources that already exists despite no changes to my TF code.

**Comment by LennyCastaneda** [comment] 2020-01-30 00:55
https://github.com/terraform-providers/terraform-provider-aws/issues/11807
