### ISSUE TITLE
AWS CodeArtifact Support

### ISSUE THREAD

**Issue by vibhuyadav** [terraform-providers/terraform-provider-aws#13720] opened 2020-06-11 17:52 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Add new AWS CodeArtifact as terraform resource

### New or Affected Resource(s)

New Resource
* aws_codeartifact

### Potential Terraform Configuration

```hcl
resource "aws_codeartifact" "foo" {

}
```

### References
https://aws.amazon.com/about-aws/whats-new/2020/06/introducing-aws-codeartifact-a-fully-managed-software-artifact-repository-service/

**Comment by ewbankkit** [comment] 2020-06-11 19:44
@vibhuyadav Thanks for raising this issue.
I'm going to close it as a duplicate of #13714. Please add any comments to that issue.

**Closed by ewbankkit** 2020-06-11 19:44 UTC
Labels: enhancement, needs-triage
