### ISSUE TITLE
aws_ecs_task_definition: diffs didn't match during apply

### ISSUE THREAD

**Issue by s-maj** [terraform-providers/terraform-provider-aws#4693] opened 2018-05-29 20:35 UTC
### Terraform Version
Terraform Version: 0.11.7
provider.aws  version: 1.20

### Affected Resource(s)

* aws_ecs_task_definition

### Terraform Configuration Files

First:
```hcl
resource "aws_ecs_task_definition" "service" {
  family                = "service"
  container_definitions = "${file("task.json")}"
  task_role_arn = "arn:aws:iam::123445789001:role/ecs-task-platform-s3-acccess"
}
```

Second:
```hcl
resource "aws_ecs_task_definition" "service" {
  family                = "service"
  container_definitions = "${file("task.json")}"
  task_role_arn = ""
}
```

task.json:
```json
[{
	"name": "first",
	"image": "service-first",
	"cpu": 10,
	"memory": 512,
	"essential": true,
	"portMappings": [{
		"containerPort": 80,
		"hostPort": 80
	}]
}]
```

### Panic Output

```
* aws_ecs_task_definition.service: aws_ecs_task_definition.service: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.7
    Resource ID: aws_ecs_task_definition.service
    Mismatch reason: attribute mismatch: task_role_arn
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"network_mode":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "arn":*terraform.ResourceAttrDiff{Old:"arn:aws:ecs:eu-west-1:123445789001:task-definition/service:7", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "task_role_arn":*terraform.ResourceAttrDiff{Old:"arn:aws:iam::123445789001:role/ecs-task-platform-s3-acccess", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "container_definitions":*terraform.ResourceAttrDiff{Old:"[{\"cpu\":10,\"environment\":[],\"essential\":true,\"image\":\"service-first\",\"memory\":512,\"mountPoints\":[],\"name\":\"first\",\"portMappings\":[{\"containerPort\":80,\"hostPort\":80,\"protocol\":\"tcp\"}],\"volumesFrom\":[]}]", New:"[{\"cpu\":10,\"essential\":true,\"image\":\"service-first\",\"memory\":512,\"name\":\"first\",\"portMappings\":[{\"containerPort\":80,\"hostPort\":80}]}]", NewComputed:false, NewRemoved:false, NewExtra:"[{\n\t\"name\": \"first\",\n\t\"image\": \"service-first\",\n\t\"cpu\": 10,\n\t\"memory\": 512,\n\t\"essential\": true,\n\t\"portMappings\": [{\n\t\t\"containerPort\": 80,\n\t\t\"hostPort\": 80\n\t}]\n}]\n", RequiresNew:false, Sensitive:false, Type:0x0}, "family":*terraform.ResourceAttrDiff{Old:"service", New:"service", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "revision":*terraform.ResourceAttrDiff{Old:"7", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"family":*terraform.ResourceAttrDiff{Old:"", New:"service", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "network_mode":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "arn":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "revision":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "container_definitions":*terraform.ResourceAttrDiff{Old:"", New:"[{\"cpu\":10,\"essential\":true,\"image\":\"service-first\",\"memory\":512,\"name\":\"first\",\"portMappings\":[{\"containerPort\":80,\"hostPort\":80}]}]", NewComputed:false, NewRemoved:false, NewExtra:"[{\n\t\"name\": \"first\",\n\t\"image\": \"service-first\",\n\t\"cpu\": 10,\n\t\"memory\": 512,\n\t\"essential\": true,\n\t\"portMappings\": [{\n\t\t\"containerPort\": 80,\n\t\t\"hostPort\": 80\n\t}]\n}]\n", RequiresNew:true, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.
```
### Expected Behavior

Create new aws_ecs_task_definition without IAM role.

### Actual Behavior

Diff mismatch

### Steps to Reproduce

1. Create aws_ecs_task_definition with task_role_arn
2. Change task_role_arn to empty string (see Terraform code labeled  as Second), then plan/apply

**Comment by bflad** [comment] 2018-05-30 12:52
Hmm this is interesting behavior because the attribute is `ForceNew: true`, so not sure why Terraform core cares about the attribute difference. 🤔  Let me poke around the upstream issues and see if I cannot find something similar.

**Comment by bflad** [comment] 2018-05-30 17:23
After further investigation, the diff behavior is pretty unexpected here, but this is likely not something to be fixed in the AWS provider itself oddly enough. It seems like Terraform core is somehow losing some context about the mismatched attribute during the destroy/create flow, but I am certainly not an expert in that area or point to a direct fix upstream. The folks working on Terraform core are already in the middle of a rewrite of diff logic code as part of the larger HCL update (slated for Terraform 0.12), so I'm tempted to backburner this until 0.12 is released and see if we can't reproduce it with the new diff logic. There's not likely to be any further code updates for 0.11.

**Comment by s-maj** [comment] 2018-05-31 08:19
No worries. Could you please tag this issue as 'waiting for response' and
I'll test again this and come back after 0.12 release.

**Comment by pecigonzalo** [comment] 2019-02-06 09:50
We are getting a similar situation with `Mismatch reason: attribute mismatch: cpu` when changing:
```
resource "aws_ecs_task_definition" "default" {
[...]
  memory = "256"
  cpu = "256"
}
```
to (disable cpu/mem limits): 
```
resource "aws_ecs_task_definition" "default" {
[...]
  memory = ""
  cpu = ""
}
```

--- 
Error: 
```
Terraform Version: 0.11.7
    Resource ID: aws_ecs_task_definition.default
    Mismatch reason: attribute mismatch: cpu
```
---
Im not sure if its related to the same issue, but before opening a new one, I thought to comment here.

After a rerun, the apply works just fine.

**Comment by MikaNikulin** [comment] 2019-02-21 09:51
I can confirm what pecigonzalo wrote above:

    Terraform Version: 0.11.11
    Resource ID: aws_ecs_task_definition.app
    Mismatch reason: attribute mismatch: cpu

Settings: CPU = some_value -> cpu = ""

**Comment by bflad** [comment] 2019-07-05 22:48
Hi folks 👋 Sorry you ran into this confusing error and thank you for reporting it. There have been a lot of relevant changes in the Terraform Core and Terraform AWS Provider codebases since this issue was originally reported so as a first step it might be best to try updating to recent versions of both and seeing if any of those updates may have resolved this issue.

Attempting to troubleshoot these types of errors is very difficult in Terraform 0.11 and earlier as those versions will report this problem (`diffs didn't match during apply` error) where a problematic configuration value exists or is referenced and not where the Terraform resource with the underlying problem actually exists. We typically will need much more information than the original error message suggests for filing the issue (e.g. the full Terraform configuration). There are also frequent issues in the Terraform 0.11 error reporting where the error message is due to behavior outside the control of the Terraform resources themselves (e.g. `lifecycle` configurations).

In Terraform 0.12 and later, the "value did not match" type of error can now be found with the newer `Provider produced inconsistent result after apply` error, which better reports the source of the problem so the provider maintainers and community can more easily work towards a fix of the issue. Other similar errors that fell previously into `diffs didn't match during apply` errors, but outside problems within the Terraform provider are also better diagnosed before being displayed.

Since the majority of the Terraform code path and reporting structure of these errors has changed between Terraform 0.11 and 0.12, along with the difficult triage process in Terraform 0.11 and earlier, the maintainers prefer to close these older issues to continue troubleshooting and fixing based on Terraform 0.12's error reporting instead. I apologize for this unsatisfying closure of this particular version of the issue.

That said, if the configuration does happen to reproduce the newer `Provider produced inconsistent result after apply` error in Terraform 0.12 (which requires Terraform AWS Provider version 2.7.0 or later), please do not hesitate to file a new issue and complete all of the information requested in the [Bug Report template](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/ISSUE_TEMPLATE/Bug_Report.md) so we can hopefully get the root cause for fixing the issue. Thanks again for this bug report and sorry about the additional steps for getting a potential fix implemented.

**Closed by bflad** 2019-07-05 22:48 UTC
Labels: bug, service/ecs, terraform-0.12, upstream-terraform
