### ISSUE TITLE
AWS EMR allows proxy information to be supplied via --additional-info parameter during EMR provisioning. Currently Terraform AWS provider doesn't provide options to pass proxy information.

### ISSUE THREAD

**Issue by kirupagaran** [terraform-providers/terraform-provider-aws#4549] opened 2018-05-16 07:29 UTC
AWS EMR supports passing of proxy information during EMR provisioning via **--additional-info** parameter. See below. 

`aws emr create-cluster --name "Test" --applications Name=Hive --release-label emr-5.9.0 --additional-info "{ 'instanceAwsClientConfiguration': { 'proxyPort': 8000, 'proxyHost': 'myproxy' }}"`

But passing proxy information to EMR during provisioning is not currently available in Terraform AWS provider. It would be great if this feature is available soon.

**Comment by bflad** [comment] 2018-05-18 02:42
Thanks for submitting this request. This looks like a duplicate of #3158. In order to consolidate discussion and effort, let's track this in the earlier issue.

**Closed by bflad** 2018-05-18 02:42 UTC
Labels: enhancement, service/emr
