### ISSUE TITLE
Invalid JSON in container_definition doesn't cause fatal error

### ISSUE THREAD

**Issue by Stretch96** [terraform-providers/terraform-provider-aws#3748] opened 2018-03-12 18:16 UTC
### Terraform Version
Terraform v0.11.3
+ provider.aws v1.10.0
+ provider.template v1.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_ecs_task_definition

### Terraform Configuration Files
```hcl
data "template_file" "example_task" {
  template = "${file('example_task.json')}"
}

resource "aws_ecs_task_definition" "example_task" {
  container_definitions    = "${data.template_file.example_task.rendered}"
  requires_compatibilities = ["EC2"]
  network_mode             = "bridge"
  cpu                      = "256"
  memory                   = "512"
  execution_role_arn       = "${aws_iam_role.execution_role.arn}"
  task_role_arn            = "${aws_iam_role.task_role.arn}"
}
```

example_task.json
```
[
  {
    "name": "a_name",
    "image": "an_image:latest",
    "memory": 512,
    "networkMode": "bridge",
    "logConfiguration": {
      "logDriver": "awslogs",
      "options": {
        "awslogs-group": "a_group",
        "awslogs-region": "eu-west-1",
        "awslogs-stream-prefix": "a_stream_prefix"
      }
    },
    "environment": [
      {
         "name": "MESS_UP_JSON_AFTER_THIS",
         "value": "Going to mess up json ..."
      }
      {
        "name": "MISSED_THE_COMMA",
        "value": "Missed the comma, causing invalid json"
      }
    ]
  }
]
```

### Debug Output
This is only seen if TF_LOG is set to Debug
```
2018/03/12 17:48:48 [ERROR]: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: [ECS Task Definition container_definitions is invalid: Error decoding JSON: invalid character '{' after array element]
```
The only error that was displayed, was when a subsequent resource tried to reference it:
```
Error: Error running plan: 1 error(s) occurred:

* module.ecs.aws_ecs_service.a_service: 1 error(s) occurred:

* module.ecs.aws_ecs_service.a_service: Resource 'aws_ecs_task_definition.example_task' not found for variable 'aws_ecs_task_definition.example_task.arn'
```

### Expected Behavior
Terraform should have stopped and notified about invalid JSON in container_definitions

### Actual Behavior
Terraform continued without notifying that the resource had not been created

**Comment by ryanschneider** [comment] 2018-03-26 22:03
FWIW this does *not* seem to be the case using slightly newer versions:

```
Terraform v0.11.5
+ provider.aws v1.12.0
+ provider.template v1.0.0
```

I now see an error like this during `terraform plan`:

```
* module.my_module.aws_ecs_task_definition.my_ecs_task: ECS Task Definition container_definitions is invalid: Error decoding JSON: invalid character ',' looking for beginning of value
```

However, now the issue is that the invalid JSON never seems to be emitted, even with `TF_LOG=TRACE`, so it's very hard to find where exactly I missed a comma.

**Comment by Stretch96** [comment] 2018-05-02 21:32
@vancluever 

I have been able to reproduce this error, by supplying an invalid task definition:

```
[
  {
    "name": "a_name",
    "image": "an_image:latest",
    "memory": 512,
    "command": "I should be an array of strings, not a single string"
    "logConfiguration": {
      "logDriver": "json-file"
    }
  }
]
```

This then produces the error:

`* module.ecs.aws_ecs_service.a_service: Resource 'aws_ecs_task_definition.example_task' not found for variable 'aws_ecs_task_definition.example_task.arn'`

This could be related to the issue https://github.com/hashicorp/terraform/issues/3319

So, it's not actually a Invalid JSON and doesn't present an error until it tries to create the task definition.
It seems when the error occurs during  task definition creation, that error is ignored and tries to create the service, then the error is produced that the service can't be created (Because the task hasn't been created)

The aws error about invalid JSON does present itself, if you comment out the service and run a plan/apply:

```
module.ecs.aws_ecs_task_definition.example_task: ECS Task Definition container_definitions is invalid: Error decoding JSON: invalid character 's' after object key:value pair
```

**Comment by bflad** [comment] 2018-06-15 15:09
Hi folks! 👋 Sorry for the unexpected behavior here.

It turns out this is likely an issue upstream in Terraform core, rather than anything to do with the AWS provider specifically. This scenario basically occurs anytime we implement a resource attribute with a `ValidateFunc` and then that resource is then referenced by another resource. Terraform core, when the first resource is failing that validation, is preferring to return the invalid resource reference message instead of the resource validation error.

I'm going to close this issue out as we have a few upstream tracking issues relating to this:
* https://github.com/hashicorp/terraform/issues/18129
* https://github.com/hashicorp/terraform/issues/16332
* https://github.com/hashicorp/terraform/issues/14333

I would suggest commenting on and upvoting those for the latest updates on this. 👍

**Closed by bflad** 2018-06-15 15:09 UTC
Labels: bug, service/ecs, upstream-terraform
