### ISSUE TITLE
Unexpected behavior when deleting VPC subnet

### ISSUE THREAD

**Issue by mrubin** [terraform-providers/terraform-provider-aws#4487] opened 2018-05-09 01:30 UTC
I was trying to reduce the number of AZs I'm using and ran into an unexpected behavior when deleting a subnet.

First of all, Terraform did not try to update the resources which use that subnet (to no longer use that subnet) and only then delete the subnet. It tried to immediately delete the subnet. Because that subnet had active ENIs in it, it cannot be deleted. In the AWS console, you see: "The following subnets contain one or more network interfaces, and cannot be deleted until those network interfaces have been deleted." However, Terraform was trying to delete the subnet and looks like it would have failed after 20 minutes. I would have expected:

1) If any resources are using the subnet which is being deleted, update those resources first.
2) If a subnet is being deleted, but it has active ENIs, display an appropriate error and exit, instead of waiting for the operation to time out.

```
Terraform v0.11.7
+ provider.aws v1.14.1
```

**Comment by bflad** [comment] 2018-05-11 22:31
Hi @mrubin 👋  Sorry you ran into unexpected behavior here.

> If any resources are using the subnet which is being deleted, update those resources first.

Terraform is designed to singularly manage each physical resource from an API and its CRUD operations for that physical resource. This philosophy means that each resource should not attempt to handle other physical resources except in extremely rare situations where required due to the amount of complexity, maintainability, and other unexpected behavior this might introduce.

In this particular case, its by Terraform's design that it is up to the operator to reconfigure the upstream resources (by updating the resources in those subnets) to allow the deletion configuration to converge. Generally, this is easiest to achieve within Terraform by directly referencing the relevant resource/data source (e.g. `${aws_subnet.example.id}`) where Terraform will error on `terraform plan` or `terraform apply` about missing references if you remove the `aws_subnet` resource/data source from the configuration.

> If a subnet is being deleted, but it has active ENIs, display an appropriate error and exit, instead of waiting for the operation to time out.

Here is the logic in question:

https://github.com/terraform-providers/terraform-provider-aws/blob/0b9dcb95a6559e55c045577cb5cb1c1ebf27c498/aws/resource_aws_subnet.go#L294-L323

This logic is in place for two reasons:
* Some APIs (such as deleting an ELB) will return immediately with success, but leave ENIs active for an additional few minutes. I have personally observed this for up to 5 minutes after the fact.
* [EC2 is an eventually consistent service](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#eventual-consistency)

Generally speaking, we believe its better to provide the expected behavior of a subnet deleting when it can after a few minutes, rather than just failing for valid deletions when it would be successful after a short time. Unfortunately the timeout of 10 minutes is pretty much required in this case and we have no insight into whether it will eventually succeed or not. If you don't like this behavior, we can make the timeout configurable.

---

Please let me know if this makes sense. Thanks!

**Comment by mildwonkey** [comment] 2018-06-21 19:48
Hi! since there hasn't been a response in awhile, I'm going to close this out, but if you are still experiencing this, feel free to reply below and we can open this back up and get it taken care of. Thanks!

**Closed by mildwonkey** 2018-06-21 19:48 UTC
Labels: question, service/ec2, waiting-response
