### ISSUE TITLE
Ability to toggle 'Log AWS KMS Events' in Cloudtrail

### ISSUE THREAD

**Issue by AliHill** [terraform-providers/terraform-provider-aws#11710] opened 2020-01-22 14:41 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be useful to be able to toggle the 'Log AWS KMS Events' feature in Terraform to enable us to reduce Cloudtrail costs.

Just now the only option in Terraform appears to be 'include_management_events' which toggles both the 'Read/Write Events' and the 'Log AWS KMS Events'. There is no way to differentiate between these two options.

More details about this functionality can be found here: https://aws.amazon.com/blogs/aws-cost-management/launch-controlling-aws-cloudtrail-costs-using-aws-kms-event-filtering/

### New or Affected Resource(s)

* aws_cloudtrail

### References

https://aws.amazon.com/blogs/aws-cost-management/launch-controlling-aws-cloudtrail-costs-using-aws-kms-event-filtering/ 

* #0000

**Comment by DrFaust92** [comment] 2020-01-22 16:53
Duplicate of #11448

**Comment by bflad** [comment] 2020-06-25 15:19
Closing as a duplicate of #11448. Please 👍  upvote and subscribe to that issue for further updates.

**Closed by bflad** 2020-06-25 15:19 UTC
Labels: enhancement, needs-triage, service/cloudtrail
