### ISSUE TITLE
aws_elasticache_replication_group and tags

### ISSUE THREAD

**Issue by CyrilDevOps** [terraform-providers/terraform-provider-aws#9002] opened 2019-06-14 17:33 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14
+ provider.aws v2.15.0
+ provider.template v0.1.1

### Affected Resource(s)

* aws_elasticache_replication_group

### Terraform Configuration Files

my terraform create a aws_elasticache_replication_group (3 nodes redis cluster) with some tags. It went ok.
However when I have to change the tags, terraform plan show tag change on the aws_elasticache_replication_group, apply change the terraform state, but did nothing on the real redis nodes in AWS.
When I do a plan again, terraform doesn't see that the resources in AWS have different tags than what is in the tfstate, and report nothing to change.

### Expected Behavior

I expect the plan to read correctly the tags of the redis nodes corresponding to the aws_elasticache_replication_group in aws to find if they need to be corrected.
I exepect the apply to change the tags of all redis nodes corresponding to the aws_elasticache_replication_group.

### Actual Behavior

plan doesn't read the real tags in aws ( aws_elasticache_replication_group object in terraform create multiple redis node in aws).
apply doesn't change the tags in aws.

### Steps to Reproduce

Create a basic redis aws_elasticache_replication_group with some tags,
then try to change the tags in terraform and check the result in aws,
and change the tags in aws and check the plan return by terraform.

### Important Factoids

aws_elasticache_replication_group in terraform create multiple redis nodes (master/replica/shards...) in AWS, each of those nodes have their own tags.

### References

* #0000

**Comment by CyrilDevOps** [comment] 2019-06-14 17:37
I will add that aws elasticache modify-replication-group doesn't support tag, neither that aws elasticache describe-replication-group.
You have to 'play' with the tag on node directly with aws elasticache add-tags-to-resource, list-tags-for-resource and remove-tags-from-resource.

**Comment by CyrilDevOps** [comment] 2019-06-14 18:38
After looking at some of my redis, it seems that the tag applied at creation of a redis are only applied to the first shard in a cluster redis, the other shards nodes aren't tagged at all.
It is another bug that need to be fixed.

**Comment by nywilken** [comment] 2019-06-17 20:12
Hi @CyrilDevOps sorry that you are running into trouble with your cache group, and thank you for reporting this issue. This looks like a duplicate of #1615 and #5366 -- the Elasticache API and Terraform treat the underlying Elasticache clusters as separate resources compared to the top level replication group. 

I am going to close this issue and ask that you up-vote/track the related issues so that we can work to get them prioritized. If you think this issue is different from those that have already been reported. Please comment with an accompanying configuration and I will gladly reopen.

**Closed by nywilken** 2019-06-17 20:12 UTC
Labels: service/elasticache

**Comment by CyrilDevOps** [comment] 2019-06-17 20:19
Thanks. I miss those 2 open issues.
