### ISSUE TITLE
Error: Provider produced inconsistent final plan in aws_ecs_task_definition

### ISSUE THREAD

**Issue by rilutham** [terraform-providers/terraform-provider-aws#15044] opened 2020-09-05 05:00 UTC
## Terraform CLI and Terraform AWS Provider Version

- Terraform v0.13.2
- AWS v3.5.0

### Affected Resource(s)

* aws_ecs_task_definition

### Terraform Configuration Files

```hcl
resource "aws_ecs_task_definition" "my-service" {
  family             = "${module.my-service.service_app}"
  cpu                = 1024
  memory             = 1024
  execution_role_arn = "${data.aws_iam_role.task.arn}"
  container_definitions = templatefile(
    "${path.module}/task_templates/my-service.json",
    {
      environment = "${local.environment}"
      name        = "${module.my-service.service_app}"
      image       = "1232332323.dkr.ecr.ap-southeast-1.amazonaws.com/platform/my-service:latest"
      param_order_auth_password                = "${aws_ssm_parameter.order_auth_password.arn}"
      param_order_auth_username                = "${aws_ssm_parameter.order_auth_username.arn}"
      param_order_service_url                   = "${aws_ssm_parameter.order_service_url.arn}"
    }
  )

  placement_constraints {
    type       = "memberOf"
    expression = "attribute:ecs.instance-type =~ c5.*"
  }
}
```

### Expected Behavior

Apply process working properly.

### Actual Behavior

There is an error message as is follow:
```
Error: Provider produced inconsistent final plan

When expanding the plan for aws_ecs_task_definition.my-service to
include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" changed the planned action from
CreateThenDelete to DeleteThenCreate.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I just updated from terraform `0.12.28` to `0.13.2`

**Comment by bflad** [comment] 2020-09-08 12:56
Hi @rilutham 👋  Thank you for reporting this and sorry you ran into trouble here. There is indeed some sort of bug within Terraform, but oddly enough it is outside of the Terraform AWS Provider's control since Terraform core is wholly what handles `create_before_destroy` behaviors. We would love to fix the underlying issue though and could use some help trying to reproduce what you are seeing.

Can you please share a little more of your configuration setup here (redacting anything as necessary)? Having a full configuration that can reproduce the issue will go a long way in helping resolve this. Thanks. 😄

**Comment by alekhrycaiko** [comment] 2020-09-08 14:31
I've recently had this crop up, but, I'm on a much earlier version of AWS Provider (2.40) and have just upgraded to Terraform 0.13.2. 

Like @bflad mentioned it sounds like this is an issue with Terraform core.

The behaviour that triggered this error for myself was updating a module that generates a task definition on my system. After providing an updated command value input for a `template_file` resource, this error occurred.

**Comment by rilutham** [comment] 2020-09-14 02:58
Thank you @bflad for the explanation. I think @jbardin already create PR to fix these issues.

**Comment by bflad** [comment] 2020-09-14 12:54
A potential fix for this has been merged upstream in Terraform core and will release in Terraform 0.14 (I imagine it will be backported for release for Terraform 0.13.3). If there are still issues after those releases for this specific `changed the planned action from CreateThenDelete to DeleteThenCreate` error, please file a new issue upstream. 👍

**Closed by bflad** 2020-09-14 12:54 UTC
Labels: bug, service/ecs, upstream-terraform
