### ISSUE TITLE
Support for Lambda Layers

### ISSUE THREAD

**Issue by jonathan-kosgei** [terraform-providers/terraform-provider-aws#6660] opened 2018-11-30 11:42 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Lambda layers allow you to remove libraries, bins and other dependencies from your deployment package, place them in a layer and make them available to your function via the layer. Each function can use up to 5 layers. The total unzipped size of the function and all layers can't exceed the unzipped deployment package size limit of 250 MB.

### New or Affected Resource(s)

* aws_lambda_function
* aws_lambda_layer

### Potential Terraform Configuration

```hcl
resource "aws_lambda_layer" "test_lambda_layer" {
  layer_name  = "my_layer"
  description    = "My layer"
  license_info  = "MIT"
  s3_bucket     = "my_bucket"
  s3_key          = "layer.zip"
  compatible_runtimes = "[python3.6, python3.7]" 
}
```

### References

https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html

**Comment by bflad** [comment] 2018-11-30 12:05
Hi @jonathan-kosgei 👋 Thanks for submitting this. This appears to be a duplicate of the previous #6651 so to consolidate discussions and efforts, I'm going to close this issue in preference of the existing issue. 👍

**Closed by bflad** 2018-11-30 12:05 UTC
