### ISSUE TITLE
Create ACM resource specifying Cert and Key content.

### ISSUE THREAD

**Issue by rorybrowne** [terraform-providers/terraform-provider-aws#4689] opened 2018-05-29 17:32 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please allow for the specifying of a certificate in ACM by specifying the content of the Cert, Private Key and CA Chain.

### New or Affected Resource(s)

* aws_acm_certificate

### Potential Terraform Configuration

```hcl

resource "aws_acm_certificate" "the_cert" {
  domain_name = "www.example.com"
  
  certificate_body = "----BEGIN CERTIFICATE ----\n........----END CERTIFICATE -----"
  private_key = "----BEGIN PRIVATE KEY ----\n........----END PRIVATE KEY -----"
  ca_chain = "whatever...."
}
```

Ultimately we'd like to be able to use ACM from a terraform perspective the same way as we'd use aws_iam_server_certificate.

I'd also want to be able to specify the values inline, so as to be able to generate the certificates with another terraform resource, and not have to import it ahead of time.

### References

* #0000

**Comment by bflad** [comment] 2018-05-30 12:22
Thanks for this feature request, @rorybrowne! It looks like a duplicate of the earlier #3560. In an effort to consolidate discussion and efforts we'll close this issue in preference of the earlier issue. 👍

**Closed by bflad** 2018-05-30 12:22 UTC
Labels: enhancement, service/acm
