### ISSUE TITLE
Destroying aws_db_instance doesn't wait until it has completely finished

### ISSUE THREAD

**Issue by gvasquez95** [terraform-providers/terraform-provider-aws#1571] opened 2017-09-01 17:33 UTC
### Terraform Version
Terraform v0.10.2

### Affected Resource(s)
aws_db_instance
aws_db_subnet_group

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_db_parameter_group" "mysql-sonar" {
  name   = "mysql-sonar"
  family = "mysql5.6"

  parameter {
    name  = "max_allowed_packet"
    value = "268435456"
  }
}

data "aws_vpc" "devops" {
  tags {
    Name = "DevOps"
  }
}

data "aws_subnet_ids" "devops-subnet" {
  vpc_id = "${data.aws_vpc.devops.id}"
}

resource "aws_db_subnet_group" "sonarqube" {
  name       = "sonarqube"
  subnet_ids = ["subnet-456", "subnet-123"]

  tags {
    Name = "Sonar subnet group"
  }
}

resource "aws_db_instance" "sonarqube" {
  allocated_storage         = 5
  storage_type              = "gp2"
  engine                    = "mysql"
  engine_version            = "5.6.27"
  instance_class            = "db.t2.micro"
  name                      = "sonar"
  username                  = "root"
  password                  = "mypass"
  parameter_group_name      = "mysql-sonar"
  publicly_accessible       = "true"
  identifier                = "sonarqube"
  final_snapshot_identifier = "sonarqube"
  skip_final_snapshot       = "true"
  backup_window             = "05:00-06:00"
  backup_retention_period   = "7"
  availability_zone         = "us-east-1b"
  multi_az                  = "false"
  db_subnet_group_name      = "${aws_db_subnet_group.sonarqube.id}"
}

```

### Expected Behavior
Terraform should have waited longer for the db instance to be terminated before trying to delete the db_subnet_group

### Steps to Reproduce
terraform destroy
aws_db_parameter_group.mysql-sonar: Refreshing state... (ID: mysql-sonar)
aws_db_subnet_group.sonarqube: Refreshing state... (ID: sonarqube)
data.aws_vpc.devops: Refreshing state...
data.aws_subnet_ids.devops-subnet: Refreshing state...
aws_db_instance.sonarqube: Refreshing state... (ID: sonarqube)

The Terraform destroy plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning.
Resources shown in red will be destroyed.

  - data.aws_subnet_ids.devops-subnet

  - aws_db_instance.sonarqube

  - aws_db_parameter_group.mysql-sonar

  - aws_db_subnet_group.sonarqube

  - data.aws_vpc.devops

Do you really want to destroy?
  Terraform will delete all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

aws_db_instance.sonarqube: Destroying... (ID: sonarqube)
data.aws_subnet_ids.devops-subnet: Destroying... (ID: vpc-d399aeaa)
aws_db_parameter_group.mysql-sonar: Destroying... (ID: mysql-sonar)
data.aws_subnet_ids.devops-subnet: Destruction complete
data.aws_vpc.devops: Destroying... (ID: vpc-d399aeaa)
data.aws_vpc.devops: Destruction complete
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 10s elapsed)
aws_db_parameter_group.mysql-sonar: Still destroying... (ID: mysql-sonar, 10s elapsed)
aws_db_parameter_group.mysql-sonar: Still destroying... (ID: mysql-sonar, 20s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 20s elapsed)
aws_db_parameter_group.mysql-sonar: Still destroying... (ID: mysql-sonar, 30s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 30s elapsed)
aws_db_parameter_group.mysql-sonar: Still destroying... (ID: mysql-sonar, 40s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 40s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 50s elapsed)
aws_db_parameter_group.mysql-sonar: Still destroying... (ID: mysql-sonar, 50s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 1m0s elapsed)
aws_db_parameter_group.mysql-sonar: Still destroying... (ID: mysql-sonar, 1m0s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 1m10s elapsed)
aws_db_parameter_group.mysql-sonar: Still destroying... (ID: mysql-sonar, 1m10s elapsed)
aws_db_parameter_group.mysql-sonar: Still destroying... (ID: mysql-sonar, 1m20s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 1m20s elapsed)
aws_db_parameter_group.mysql-sonar: Still destroying... (ID: mysql-sonar, 1m30s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 1m30s elapsed)
aws_db_parameter_group.mysql-sonar: Still destroying... (ID: mysql-sonar, 1m40s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 1m40s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 1m50s elapsed)
aws_db_parameter_group.mysql-sonar: Still destroying... (ID: mysql-sonar, 1m50s elapsed)
aws_db_parameter_group.mysql-sonar: Still destroying... (ID: mysql-sonar, 2m0s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 2m0s elapsed)
aws_db_parameter_group.mysql-sonar: Still destroying... (ID: mysql-sonar, 2m10s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 2m10s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 2m20s elapsed)
aws_db_parameter_group.mysql-sonar: Still destroying... (ID: mysql-sonar, 2m20s elapsed)
aws_db_parameter_group.mysql-sonar: Still destroying... (ID: mysql-sonar, 2m30s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 2m30s elapsed)
aws_db_parameter_group.mysql-sonar: Still destroying... (ID: mysql-sonar, 2m40s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 2m40s elapsed)
aws_db_parameter_group.mysql-sonar: Still destroying... (ID: mysql-sonar, 2m50s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 2m50s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 3m0s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 3m10s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 3m20s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 3m30s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 3m40s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 3m50s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 4m0s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 4m10s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 4m20s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 4m30s elapsed)
aws_db_instance.sonarqube: Still destroying... (ID: sonarqube, 4m40s elapsed)
aws_db_instance.sonarqube: Destruction complete
aws_db_subnet_group.sonarqube: Destroying... (ID: sonarqube)
aws_db_subnet_group.sonarqube: Destruction complete
Error applying plan:

1 error(s) occurred:

* aws_db_parameter_group.mysql-sonar (destroy): 1 error(s) occurred:

* aws_db_parameter_group.mysql-sonar: InvalidDBParameterGroupState: One or more database instances are still members of this parameter group mysql-sonar, so the group cannot be deleted
	status code: 400, request id: 65f93c67-8f39-11e7-8a92-17ee39c8ffc9

**Comment by matthewfischer** [comment] 2017-11-06 03:19
I have the same issue but you should correct the bug text above because the failure is in to delete the parameter group (aws_db_parameter_group), not the subnet group.

**Comment by matthewfischer** [comment] 2017-11-06 03:34
Here is a more minimal failure case that does not require a subnet.

`resource "aws_db_parameter_group" "mysql-parameters" {
    name = "mysql-parameters"
    family = "mysql5.6"
    description = "MySQL parameter group"

    parameter {
      name = "max_connections"
      value = "256"
   }
}

resource "aws_db_instance" "mysql" {
    allocated_storage    = 20
    engine               = "mysql"
    engine_version       = "5.6.37"
    instance_class       = "db.t2.small"
    name                 = "foo"
    username             = "foo"
    password             = "foobar123"
    parameter_group_name = "mysql-parameters"
    multi_az             = false
    storage_type         = "gp2"
    skip_final_snapshot = true
}`


terraform destroy -force
...
...
aws_db_parameter_group.mysql-parameters: Still destroying... (ID: mysql-parameters, 1m30s elapsed)
aws_db_parameter_group.mysql-parameters: Still destroying... (ID: mysql-parameters, 1m40s elapsed)
aws_db_instance.mysql: Still destroying... (ID: terraform-20171106032237276700000001, 1m40s elapsed)
aws_db_parameter_group.mysql-parameters: Still destroying... (ID: mysql-parameters, 1m50s elapsed)
aws_db_instance.mysql: Still destroying... (ID: terraform-20171106032237276700000001, 1m50s elapsed)
aws_db_parameter_group.mysql-parameters: Still destroying... (ID: mysql-parameters, 2m0s elapsed)
aws_db_instance.mysql: Still destroying... (ID: terraform-20171106032237276700000001, 2m0s elapsed)
aws_db_parameter_group.mysql-parameters: Still destroying... (ID: mysql-parameters, 2m10s elapsed)
aws_db_instance.mysql: Still destroying... (ID: terraform-20171106032237276700000001, 2m10s elapsed)
aws_db_parameter_group.mysql-parameters: Still destroying... (ID: mysql-parameters, 2m20s elapsed)
aws_db_instance.mysql: Still destroying... (ID: terraform-20171106032237276700000001, 2m20s elapsed)
aws_db_parameter_group.mysql-parameters: Still destroying... (ID: mysql-parameters, 2m30s elapsed)
aws_db_instance.mysql: Still destroying... (ID: terraform-20171106032237276700000001, 2m30s elapsed)
aws_db_parameter_group.mysql-parameters: Still destroying... (ID: mysql-parameters, 2m40s elapsed)
aws_db_instance.mysql: Still destroying... (ID: terraform-20171106032237276700000001, 2m40s elapsed)
aws_db_parameter_group.mysql-parameters: Still destroying... (ID: mysql-parameters, 2m50s elapsed)
aws_db_instance.mysql: Still destroying... (ID: terraform-20171106032237276700000001, 2m50s elapsed)
aws_db_instance.mysql: Still destroying... (ID: terraform-20171106032237276700000001, 3m0s elapsed)
aws_db_instance.mysql: Still destroying... (ID: terraform-20171106032237276700000001, 3m10s elapsed)
aws_db_instance.mysql: Still destroying... (ID: terraform-20171106032237276700000001, 3m20s elapsed)
aws_db_instance.mysql: Still destroying... (ID: terraform-20171106032237276700000001, 3m30s elapsed)
aws_db_instance.mysql: Still destroying... (ID: terraform-20171106032237276700000001, 3m40s elapsed)
aws_db_instance.mysql: Still destroying... (ID: terraform-20171106032237276700000001, 3m50s elapsed)
aws_db_instance.mysql: Destruction complete after 3m59s

Error: Error applying plan:

1 error(s) occurred:

* aws_db_parameter_group.mysql-parameters (destroy): 1 error(s) occurred:

* aws_db_parameter_group.mysql-parameters: InvalidDBParameterGroupState: One or more database instances are still members of this parameter group mysql-parameters, so the group cannot be deleted
	status code: 400, request id: 07b9afc7-5db9-453a-a344-cc8b5d0eee9e

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by egarbi** [comment] 2018-09-13 14:19
@gvasquez-waypoint  Can you please edit this issue and all reference to `aws_db_subnet_group` should be replaced for `aws_db_parameter_group` since the issue is with parameters and not with subnet. You made a typo there

**Comment by bflad** [comment] 2020-07-07 03:50
Hi folks 👋  The above recommendations by @tomelliff are correct in this situation. You need to tell Terraform the proper ordering of resources by using attributes references or explicitly via `depends_on`. Since Terraform and the Terraform AWS Provider are acting as expected in this situation and the fix can be done via configuration, I'm going to close this issue.

**Closed by bflad** 2020-07-07 03:50 UTC
Labels: bug, service/rds
