### ISSUE TITLE
Please add support for default values in Cloudwatch Metric Filters

### ISSUE THREAD

**Issue by hazmeister** [terraform-providers/terraform-provider-aws#1483] opened 2017-08-23 09:35 UTC
### Terraform Version
Terraform v0.9.5

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_cloudwatch_log_metric_filter

### Important Factoids
The [terraform docs](https://www.terraform.io/docs/providers/aws/r/cloudwatch_log_metric_filter.html) don't list **default value** as a property.  This hidden behind the **show advanced metric settings** in the AWS web interface.  This allows for metrics to record a 0 value in the absence of the event, instead of a null value. 
![image](https://user-images.githubusercontent.com/11080542/29609234-6f39ebb6-87ee-11e7-91ae-e072fe718ee0.png)

![image](https://user-images.githubusercontent.com/11080542/29609194-52278b50-87ee-11e7-8468-8ad8085963bb.png)

**Comment by stack72** [comment] 2017-09-03 18:32
Duplicate of #1563 - fixed via #1578

**Comment by bflad** [comment] 2018-01-22 18:49
This was previously released in [terraform-provider-aws version 1.2.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#120-october-31-2017) and has been available in all releases since. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Closed by bflad** 2018-01-22 18:49 UTC
Labels: enhancement, service/cloudwatchlogs
