### ISSUE TITLE
aws_iam_instance_profile returnin "non existent" attribute "role

### ISSUE THREAD

**Issue by dfduarte** [terraform-providers/terraform-provider-aws#6428] opened 2018-11-11 03:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by bflad** [comment] 2018-11-12 14:38
This looks to be an empty duplicate of #6429 so closing in preference of that issue. 😄

**Closed by bflad** 2018-11-12 14:38 UTC
