### ISSUE TITLE
Crash during aws_lb_target_group import

### ISSUE THREAD

**Issue by szczad** [terraform-providers/terraform-provider-aws#2245] opened 2017-11-10 07:59 UTC
### Terraform Version
* Terraform v0.10.8
* provider.aws: 1.2

### Affected Resource(s)
- aws_lb_target_group

### Terraform Configuration Files
https://drive.google.com/file/d/1eed8P0Qt20fO_mRqxy6FilNOjullMRJ7/view?usp=sharing

### Debug Output
https://drive.google.com/file/d/17hEfMFCXJNwfpMC48yOOVNtkCbBkYHdG/view?usp=sharing

### Panic Output
https://drive.google.com/file/d/13aoT1Ca2XwDOBGNFaHCoRUuTH4uwt1cR/view?usp=sharing

### Expected Behavior
Given resource should import its state smoothly

### Actual Behavior
Terraform crashes with crash log not doin anything

### Steps to Reproduce
1. `terraform import aws_lb_target_group.<resource> <ARN> `

### Important Factoids
Trying to import "network" type load balancer with TCP target group

**Comment by roman-vynar** [comment] 2017-11-13 13:38
I have got the same but on the creation step.
The problem is aws_lb_target_group resource expects either HTTP or HTTPS for network balancer which is a bug :( TCP should be there too.
```
Error: module.vpc.aws_lb_target_group.foo: "protocol" must be either "HTTP" or "HTTPS"
```

**Comment by roman-vynar** [comment] 2017-11-13 14:05
So it turns out a network lb feature is completely unusable with terraform as you can't create TCP target group.

**Comment by radeksimko** [comment] 2017-11-14 09:41
Clipping out the relevant part of the crash log:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x194eed1]

goroutine 14 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.flattenAwsLbTargetGroupResource(0xc420242380, 0x209a300, 0xc420090480, 0xc42037c3f0, 0x0, 0x7f8869124de8)
	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_lb_target_group.go:491 +0x391
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsLbTargetGroupRead(0xc420242380, 0x209a300, 0xc420090480, 0x0, 0x3b0d980)
	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_lb_target_group.go:257 +0x28b
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc42043b500, 0xc4208d80a0, 0x209a300, 0xc420090480, 0xc420450590, 0xc4202d9a01, 0x80000485772)
	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:321 +0x199
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc4202d6770, 0xc4208d8050, 0xc4208d80a0, 0x7f886917d000, 0x0, 0x18)
	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x9a
github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc4202d2680, 0xc42046cba0, 0xc42046cd50, 0x0, 0x0)
	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
reflect.Value.call(0xc42047e060, 0xc4202e87b0, 0x13, 0x23e9987, 0x4, 0xc4202d9f20, 0x3, 0x3, 0x403a23, 0xc4204c2e00, ...)
	/usr/local/go/src/reflect/value.go:434 +0x906
reflect.Value.Call(0xc42047e060, 0xc4202e87b0, 0x13, 0xc4202a2f20, 0x3, 0x3, 0xc4202a2f20, 0xc4202a2f28, 0xc420603780)
	/usr/local/go/src/reflect/value.go:302 +0xa4
net/rpc.(*service).call(0xc4202c2900, 0xc42045e0a0, 0xc4202ee7b8, 0xc4203b4580, 0xc4202d3240, 0x1cda3c0, 0xc42046cba0, 0x16, 0x1cda400, 0xc42046cd50, ...)
	/usr/local/go/src/net/rpc/server.go:381 +0x142
created by net/rpc.(*Server).ServeCodec
	/usr/local/go/src/net/rpc/server.go:475 +0x36b
```

**Comment by catsby** [comment] 2017-11-15 15:58
Hey @szczad thanks for the report, I'm looking into this now. I believe it's resolved with https://github.com/terraform-providers/terraform-provider-aws/pull/2251 ; in that change we only set `path` for Application type load balancers, avoiding the nil pointer dereference. I'm trying to reproduce though to confirm, and I'm unable to decrypt the config zip you sent, what key did you use to encrypt it with? 

Thanks!

**Comment by catsby** [comment] 2017-11-15 16:35
I've verified `aws_lb_listener`, `aws_lb_target_group`, and `aws_lb` can all be imported after #2251, so I'm going to close this issue now. Thanks!

**Closed by catsby** 2017-11-15 16:35 UTC
Labels: bug, crash

**Comment by szczad** [comment] 2017-11-16 13:17
@catsby Verified. I've built the plugin from master. Works like a charm right now. 

PS: the key used here was taken from https://www.hashicorp.com/security - imported manually from gpg server with ID 51852D87348FFC4C

**Comment by catsby** [comment] 2017-11-16 18:28
Ah yeah, that one 😄 I didn't have it installed, but I have since done so and verified I could decrypt your config, thanks again!
