### ISSUE TITLE
Assume Role via .aws/config profiles does not work

### ISSUE THREAD

**Issue by h3lo** [terraform-providers/terraform-provider-aws#11429] opened 2019-12-27 18:41 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

`Terraform v0.11.14`
Note that moving to `v0.12.x` is not feasible for our organization at this time.

AWS Provider is set to version `2.43.0`.

### Affected Resource(s)

* provider itself

### Terraform Configuration Files

```hcl
provider "aws" {
  version = "2.43.0"
  region  = "us-east-1"
  profile = "acct1"
}

provider "aws" {
  version = "2.43.0"
  region  = "us-east-1"
  alias   = "acct2_east"
  profile = "acct2"

terraform {
  backend "s3" {
    encrypt = true
    bucket  = "someS3bucket"
    key     = "path/to/state.tfstate"
    profile = "acct1"
    region  = "us-east-1"
  }
}
```
In my .aws/config:
```hcl
[default]
region = us-east-1

[profile acct1]
role_arn = arn:aws:iam::<ACCT1>:role/rolename
credential_source = Ec2InstanceMetadata

[profile acct2]
role_arn = arn:aws:iam::<ACCT2>:role/rolename
source_profile = acct1

```
### Debug Output

```hcl
# terraform0.11.14 plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.terraform_remote_state.network: Refreshing state...
aws_iam_role.*****: Refreshing state... (ID: *****)
aws_security_group.*****: Refreshing state... (ID: sg-*****)
data.aws_route53_zone.*****: Refreshing state...
aws_iam_role_policy_attachment.*****: Refreshing state... (ID: *****-*****)
aws_iam_instance_profile.*****: Refreshing state... (ID: *****)
aws_iam_role_policy_attachment.*****: Refreshing state... (ID: *****-*****)
aws_iam_role_policy.*****: Refreshing state... (ID: *****)
aws_security_group_rule.*****: Refreshing state... (ID: sgrule-*****)
aws_security_group_rule.*****: Refreshing state... (ID: sgrule-*****)
aws_security_group_rule.*****: Refreshing state... (ID: sgrule-*****)
aws_security_group_rule.*****: Refreshing state... (ID: sgrule-*****)
aws_instance.*****: Refreshing state... (ID: i-*****)
aws_route53_record.*****: Refreshing state... (ID: *****)
aws_route53_record.*****: Refreshing state... (ID: *****)
aws_route53_record.*****: Refreshing state... (ID: *****)

Error: Error refreshing state: 1 error occurred:
	* aws_route53_record.*****: 1 error occurred:
	* aws_route53_record.*****: aws_route53_record.*****: AccessDenied: User: arn:aws:sts::*****:assumed-role/*****/i-***** is not authorized to access this resource
	status code: 403, request id: *****

```
The role arn in the error is the arn of acct1 when it should be acct2 (as set in the aws config).

I also tried setting `AWS_SDK_LOAD_CONFIG=1` but again, the behavior was identical.

### Expected Behavior
Plan / Apply succeeds 

### Actual Behavior
TF tries to use the alias'd provider with the main acct instead of the second one.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids
Running aws cli commands on either acct1 or acct2 on this instance works without issue, so the roles and trust relationships are set up properly. If I add a block in the provider for the role assumption, it works, but this is unacceptable because then the TF cannot be run by a user with different roles. I need to be able to abstract this in AWS config profiles so the TF code is generic.

In addition, I tried setting the role assume stuff in the credentials file instead, but the behavior was identical. AWS CLI worked fine either way for both accounts, TF fails to properly assume the role for the provider.

### References
This issue seems very similar, but was closed without resolution. The patch that claims to fix it very much does NOT fix role assumption via aws config file profiles. https://github.com/terraform-providers/terraform-provider-aws/issues/1184

Please let me know if I should add any other specific details.

**Comment by pcantea** [comment] 2020-02-12 23:33
+1 also running into this. It seems to not work when using the EC2 instance metadata.

Terraform 0.12.20
provider version 2.48

**Comment by lapkritinis** [comment] 2020-02-21 07:46
+1
its not exactly same - in my case, I want to use multiple providers for setting up vpc peering between accounts. I want to achieve it, by using "profile" property in aws provider, but it gets ignored (always gets picked "default" instead what is specified). Obviously I cannot use env variable AWS_PROFILE, because I need multiple profiles, not one.

**Comment by rehevkor5** [comment] 2020-02-21 16:16
This might be a duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/11429

**Comment by joeaawad** [comment] 2020-06-05 06:24
@h3lo one work around idea until this gets fixed is to have the profiles use a variable for the profile name with acct1 and acct2 as the defaults. If you do that, the terraform code can be generic and if someone who doesn't have the same profiles wants to run it on their own machine, they just need to pass in the profile they want to use as an additional variable. 

One gotcha with that workaround is that you can't use a variable in the terraform backend block. You could get around this by having a generic terraform state access role that everyone/every automated process that runs terraform has access to and has saved under a consistent profile name. 

For the overall issue you're running into, have you checked if that only occurs when using `Ec2InstanceMetadata` as the `credential_source`? I've used that same sort of process where one profile uses a source_profile of another profile many times before in terraform 12 without issue but not in combination with the `Ec2InstanceMetadata` credential_source. It looks to me like @rehevkor5's comment about this being a duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/5018 is the real issue.

**Comment by h3lo** [comment] 2020-06-13 23:40
I already use a single account to own all the state files (sort of a master account), so the backend is okay. In my case, I the role on the instance has access to the s3 bucket with the backends so no role needs to be assumed. This leaves the TF backend clean (no hard coded profile or role assumed).

The issue persists if I remove the `Ec2InstanceMetadata` as the `credential_source`.

**Closed** 2020-07-13 14:01 UTC
Labels: bug, provider

**Comment by bflad** [comment] 2020-07-13 14:19
Hi folks 👋  Version 3.0 of the Terraform AWS Provider will include a few authentication changes that should help in this case. Similar enhancements and fixes were applied to the Terraform S3 Backend (part of Terraform CLI) in version 0.13.0-beta2.

The Terraform AWS Provider major version update will release in the next two weeks or so. Please follow the [v3.0.0 milestone](https://github.com/terraform-providers/terraform-provider-aws/milestone/70) for tracking the progress of that release. If you are still having trouble after updating when its released, please file a new issue. Thanks!
