### ISSUE TITLE
iam_instance_profile not updating roles

### ISSUE THREAD

**Issue by salliewalecka** [terraform-providers/terraform-provider-aws#1270] opened 2017-07-27 21:00 UTC
### Terraform Version
v0.9.11

### Affected Resource(s)
iam_instance_profile

### Terraform Configuration Files
```hcl

resource "aws_iam_instance_profile" "instance-profile" {
  name = "test-eb-instance-profile"
  role = "${aws_iam_role.test-role.name}"
}

```

### Debug Output
* 2017-07-27 18:25:22.125 +0000 UTC () : The instance profile test-eb-instance-profile associated with the environment has no role. Please attach a role to the instance profile.
* 2017-07-27 18:25:22.254 +0000 UTC () : Failed to launch environment.

### Expected Behavior
When using role attribute, the instance profile should have a role. e.g.
```
{
    "InstanceProfileId": "***********", 
    "Roles": [
        {
            "AssumeRolePolicyDocument": {
                "Version": "2012-10-17", 
                "Statement": [
                    {
                        "Action": "sts:AssumeRole", 
                        "Principal": {
                            "Service": "ec2.amazonaws.com"
                        }, 
                        "Effect": "Allow", 
                        "Sid": ""
                    }
                ]
            }, 
            "RoleId": "***********", 
            "CreateDate": "2017-07-27T16:47:16Z", 
            "RoleName": "test-eb-instance-role", 
            "Path": "/", 
            "Arn": "arn:aws:iam::***********:role/test-eb-instance-role"
        }
    ], 
    "CreateDate": "2017-07-27T14:32:58Z", 
    "InstanceProfileName": "test-eb-instance-profile", 
    "Path": "/", 
    "Arn": "arn:aws:iam::***********:instance-profile/test-eb-instance-profile"
}

```

### Actual Behavior
When using role attribute, the instance profile had an empty array.
```
{
    "InstanceProfileId": "************", 
    "Roles": [], 
    "CreateDate": "2017-07-27T14:32:58Z", 
    "InstanceProfileName": "test-eb-instance-profile", 
    "Path": "/", 
    "Arn": "arn:aws:iam::1*********"
} 
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create an iam_instance_profile with roles
1. Terraform apply
1. Change iam_instance_profile to role (because roles is deprecated)
1. Terraform apply
2. See error: The instance profile ______ associated with the environment has no role. Please attach a role to the instance profile.

### Workaround
Go back to using roles even though it is deprecated.  
```
resource "aws_iam_instance_profile" "instance-profile" {
  name = "test-eb-instance-profile"
  roles = ["${aws_iam_role.instance-role.name}"]
}
```

**Comment by peterromfeldhk** [comment] 2017-09-11 06:41
same with Terraform v0.10.2 
thanks for the workaround!

**Comment by redbaron** [comment] 2018-03-21 18:02
Happens with terraform-provider-aws 0.10 too. Thanks for workaround!

**Comment by charsyam** [comment] 2019-02-18 01:28
Happens with Terraform v0.11.7, provider.aws v1.17.0 too.
Thanks for workaround!

**Comment by ryndaniels** [comment] 2019-11-20 13:56
Hi @salliewalecka - Thanks for taking the time to submit this issue. I had a look at this with the most recent versions of Terraform and the AWS Provider (0.12.13 and 2.38.0 respectively, at the moment) and was unable to reproduce this behavior - changing from `roles` to `role` worked as expected without error. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md). 🙂

**Closed by ryndaniels** 2019-11-20 13:56 UTC
Labels: bug, service/iam

**Comment by heytherepeter** [comment] 2019-12-19 20:08
Thanks for the work-around!! I've been stuck on this problem all day.

```
terraform -v                         
Terraform v0.12.17
+ provider.aws v2.31.0
+ provider.template v2.1.2
```
