### ISSUE TITLE
Unable to Create KMS Grant for External CMK

### ISSUE THREAD

**Issue by brandonstevens** [terraform-providers/terraform-provider-aws#4141] opened 2018-04-10 14:08 UTC
We currently use external KMS CMKs for EBS encryption including AMIs. The recent service-linked role change with Auto Scaling Groups requires us to create a KMS grant for the service-linked role. We are following the instructions for Case 2 on https://forums.aws.amazon.com/thread.jspa?threadID=277523. Note that for Step 4, the grant is created in the ASG account and references an external CMK. We're able to create the grant using the AWS CLI, but run into an input validation error with Terraform.

### Terraform Version
```
Terraform v0.11.6
+ provider.aws v1.14.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_kms_grant

### Terraform Configuration Files
```hcl
resource "aws_kms_grant" "main" {
  name              = "test"
  key_id            = "arn:aws:kms:us-west-2:999999999999:key/12345678-abcd-1234-abcd-1234567890ab"
  grantee_principal = "arn:aws:iam::111111111111:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling"

  operations = [
    "Encrypt",
    "Decrypt",
    "ReEncryptFrom",
    "ReEncryptTo",
    "GenerateDataKey",
    "GenerateDataKeyWithoutPlaintext",
    "DescribeKey",
    "CreateGrant",
  ]
}
```

### Expected Behavior
The grant is created.

### Actual Behavior
```
Error: Error refreshing state: 1 error(s) occurred:

* aws_kms_grant.main: 1 error(s) occurred:

* aws_kms_grant.main: aws_kms_grant.main: unexpected format of ID ("arn:aws:kms:us-west-2:999999999999:key/12345678-abcd-1234-abcd-1234567890ab:03702bb961f64eb71472f88ffab76e9863c2931171a7d01c98505b451875eec2"), expected KeyID:GrantID
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Important Factoids
- KMS CMK is in AWS Account 9999999999 
- Service-linked Role (as well as ASG/AMI/etc) are in AWS Account 11111111111

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-641

**Comment by bflad** [comment] 2018-04-10 14:24
Does it work if you create/import the resource with key ID just being the part after `key/` in the ARN you currently have in the `key_id` field?

**Comment by brandonstevens** [comment] 2018-04-10 14:39
Good idea. The plan generates successfully, but apply fails with the AWS API returns NotFoundException since AWS assumes that the CMK exists in the current account. In my case, the CMK is in a different account.

```
Error: Error applying plan:

1 error(s) occurred:

* aws_kms_grant.main: 1 error(s) occurred:

* aws_kms_grant.main: NotFoundException: Key 'arn:aws:kms:us-west-2:11111111111:key/12345678-abcd-1234-abcd-1234567890ab' does not exist
	status code: 400, request id: 9ed62782-3ccc-11e8-a480-df5512930820
```

**Comment by brandonstevens** [comment] 2018-04-10 16:12
Here's some code that reproduces the issue: https://github.com/brandonstevens/asg-cross-account-kms-grant-issue

**Comment by njeirath** [comment] 2018-04-11 22:15
I ran into the same issue yesterday.  Interestingly enough, it appears that running `terraform apply` will actually cause the grant to be created despite the error (was confirmed using the aws CLI to list grants) but any subsequent attempts to `plan` or `apply` fail with the above error.  These commands continue to fail even if the `aws_kms_grant` resource is removed from the module.  To get back to a state where I could run `plan` or `apply` I had to remove the state using `terraform state rm` command.

I'm not at all familiar with the internals of Terraform and how the state files work/are structured but my best guess is that the create grant works but something gets corrupted when writing to the state file causing all subsequent calls to fail.  In any case, hope this helps.

**Comment by brandonstevens** [comment] 2018-04-11 22:27
A colleague and I were able to do some more testing and were able to track the issue down to _decodeKmsGrantId_ which fails to break apart the internal ID when an ARN is used. When new grant is added, the TF code sticks `key_id`:`grant` into the internal ID field after it's created, but errors out when it's read and decoded. Seems like a pretty straightforward fix that we can provide soon.

**Comment by pintbrewer** [comment] 2018-04-20 13:34
I am having the exact same issue. CMK is in a separate account from my autoscale group which requires the grant for the new service linked roles. I would love to see the fix for this soon, since I have a deadline from Amazon to get this implemented.

**Closed** 2018-06-21 02:20 UTC
Labels: service/kms

**Comment by bflad** [comment] 2018-06-25 11:48
This has been released in [version 1.24.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1240-june-21-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by rafaelmagu** [comment] 2019-06-06 04:41
This still fails for me in provider 2.4 and I am at a loss as to why.

**Comment by rafaelmagu** [comment] 2019-06-06 04:49
I have basically the same setup as referenced by @brandonstevens [here](https://github.com/terraform-providers/terraform-provider-aws/issues/4141#issuecomment-380158894). I can manually launch AMIs encrypted with an external CMK but ASG fails to launch them because there is no grant created.

How do I even test that the ASG can find the key?

**Comment by rafaelmagu** [comment] 2019-06-06 21:46
Need a night of sleep to figure this out: trying to create the grant in a different region from the key won't work. PEBKAC.

**Comment by mrg2k8** [comment] 2019-06-27 06:51
I was following the instructions [here](https://forums.aws.amazon.com/thread.jspa?threadID=277523) and got a ```aws_kms_grant.asg-kms: error listing KMS Grants: AccessDeniedException``` error, which I solved by adding the ```kms:ListGrants``` action on the KMS key permissions.
