### ISSUE TITLE
[version 3.0.0] unsupported attribute network_interface_id on aws_instance resource

### ISSUE THREAD

**Issue by kdubmartins** [terraform-providers/terraform-provider-aws#14431] opened 2020-07-31 14:51 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_instance

### Expected Behavior

`terraform apply` should work as usual

### Actual Behavior

```Error: Invalid resource instance data in state

  on ../../../modules/instance/main.tf line 61:
  61: resource "aws_instance" "instance_no_ebs" {

Instance
module.nomad_servers.module.nomad_server_instances.module.instance.aws_instance.instance_no_ebs[1]
data could not be decoded from the state: unsupported attribute
"network_interface_id".
```

### Steps to Reproduce

1. `terraform init` to download latest provider version (3.0.0)
1. `terraform apply`

### Important Factoids

- error is not presented during `plan`, only `apply`
- reverting to version 2.70.0 of the provider fixes the issue,

**Comment by kdubmartins** [comment] 2020-07-31 17:02
Most definitely caused by https://github.com/terraform-providers/terraform-provider-aws/pull/14001/commits/3586a1a9b5ed6f121a64f022c22b405476f44d24#diff-28aade55afa0cda57279a9d35d523488. 

The error had already been bypassed on plan because the attribute is used in an output which I wrapped in a `try()` function, Therefore it could be planned successfully but not applied, when terraform tries to retrieve the attribute from the state.

**Comment by jameshounshell** [comment] 2020-07-31 17:40
We see a very similar problem, that actually breaks in the `plan` stage. This affects `placement_strategy` for ECS service which is now I believe `ordered_placement_strategy`. We probably could bypass by destroying and redeploying the infra but it would be nice to not have to.

```
terraform validate
Success! The configuration is valid.

terraform plan -var-file=terraform.tfvars -var-file=chariot-nxo.tfvars -var env=qa -var region=us-east-1

Error: Invalid resource instance data in state

  on .terraform/modules/ecs_app_chariot_runtime/ecs_service/main.tf line 28:
  28: resource "aws_ecs_service" "service" {

Instance module.ecs_app_chariot_runtime.aws_ecs_service.service data could not
be decoded from the state: unsupported attribute "placement_strategy".

make: *** [plan] Error 1
```

**Comment by bflad** [comment] 2020-07-31 18:24
Hi folks 👋  Thank you for reporting this issue and apologies for the frustrating behavior. Something is certainly amiss with the physical removal of the attributes from the provider schema, but usually Terraform core handles these just fine.

It would be very helpful if you all could provide the following information, so we can start troubleshooting this:

* Terraform CLI version
* Steps (e.g. commands ran, including upgrading the Terraform AWS Provider) that led to this error
* Snippet of Terraform configuration associated with the resource reporting the error
* A [Gist](https://gist.github.com) with [trace logging enabled](https://www.terraform.io/docs/internals/debugging.html) so we can further troubleshoot. If you are worried about any sensitive data, it can be encrypted with the [HashiCorp GPG Key](https://keybase.io/hashicorp) or redacted as necessary.

Hopefully with those outlined, we can figure out root cause. [Relevant Terraform core logic triggering the error](https://github.com/hashicorp/terraform/blob/0e5651560b8e74cbbfddc0a188887c490d3ae4d5/terraform/evaluate.go#L710-L721).

**Comment by Starttoaster** [comment] 2020-08-01 17:07
- TF CLI 0.12.29, using the hashicorp/terraform:light image in docker hub
- `terraform validate` or `terraform apply`
- Having an output is what led to this error for me:

```
output "network_interface_id" {
  description = "ID of the network interface that was created with the instance."
  value       = aws_instance.<module_name>.network_interface_id
}
```

**Comment by kdubmartins** [comment] 2020-08-02 19:03
In my case it's also because of an output.

**Comment by kimor79** [comment] 2020-08-03 22:29
I have more info in #14458 but noting here for compactness. In my case `plan` fails because my existing state was generated with 2.70.0 and has _removed_ attributes listed:
```
    {
      "module": "module.my-module",
      "mode": "data",
      "type": "aws_region",
      "name": "main",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"].my-module",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "current": null,
            "description": "US East (N. Virginia)",
            "endpoint": "ec2.us-east-1.amazonaws.com",
            "id": "us-east-1",
            "name": "us-east-1"
          }
        }
      ]
    },
```

`current` was removed from the aws_region datasource in 3.0.0

**Comment by mimozell** [comment] 2020-08-04 13:51
Issue is happening to me as well when going from aws provider version 2.70.0 to 3.0.0

- Version: Terraform v0.13.0-rc1, provider registry.terraform.io/hashicorp/aws v3.0.0
- Action: `terraform apply` or `terraform destroy`
- Resource:
```
resource aws_route53_zone external {
  name = var.domain-name
  comment = "${var.environment}-external-zone"

  tags = {
    Environment = var.environment
  }
}
```
- Error: Instance module.dns.aws_route53_zone.external data could not be decoded fromthe state: unsupported attribute "vpc_id"

**Comment by bflad** [comment] 2020-08-05 19:07
Please note that I have filed a bug report upstream with Terraform core, where this error is being generated: https://github.com/hashicorp/terraform/issues/25752

**Comment by RayOei** [comment] 2020-08-11 10:46
Just updated to v0.13 and the `terraform **plan**` fails.

Terraform v0.13.0
+ provider registry.terraform.io/-/aws v3.1.0
+ provider registry.terraform.io/hashicorp/aws v3.1.0

Commands used:
```
terraform 0.13update (added new required_providers)
terraform init
terraform plan
```

Failure (multiple times for the same aws_instance resource):
```
Error: Invalid resource instance data in state

  on main.tf line 313:
 313: resource "aws_instance" "instance" {

Instance aws_instance.instance data could not be decoded from the state:
unsupported attribute "network_interface_id".
```

Code snippet:
```
resource "aws_instance" "instance" {
  ami           = var.amis[format("%s_%s_%s_%s", var.ami_name, var.region, var.ubu_version, var.ebs_size)]
  instance_type = var.instance_type

  vpc_security_group_ids = [
    aws_security_group.ssh.id,
    aws_security_group.http.id,
    aws_security_group.openvpn.id,
  ]

  subnet_id = aws_subnet.default.id

  key_name = var.use_existingKey ? var.fixed_key_name : aws_key_pair.auth[0].id

  volume_tags = {
    Name = format("%s-ws_%s-ami_%s", var.basename, terraform.workspace, var.ami_name)
  }

  tags = {
    Name = format("%s-ws_%s-ami_%s", var.basename, terraform.workspace, var.ami_name)
  }
}
```

**Comment by bflad** [comment] 2020-08-12 15:34
Hi folks 👋  A fix for this particular Terraform state handling issue was merged upstream in the Terraform CLI code and will release with Terraform CLI version 0.13.1 in the coming days.

If you happen to have a reproducible case of this issue with only Terraform CLI 0.12.x, please [create a new bug report issue in the hashicorp/terraform repository](https://github.com/hashicorp/terraform/issues/new?labels=bug%2C+new&template=bug_report.md) with all the template details and the teams will triage further. Thanks.

**Closed by bflad** 2020-08-12 15:34 UTC
Labels: bug, service/ec2, service/ecs, upstream-terraform

**Comment by andresvia** [comment] 2020-08-24 19:51
Is there a workaround meanwhile?

> Hi folks 👋 A fix for this particular Terraform state handling issue was merged upstream in the Terraform CLI code and will release with Terraform CLI version 0.13.1 in the coming days.
> 
> If you happen to have a reproducible case of this issue with only Terraform CLI 0.12.x, please [create a new bug report issue in the hashicorp/terraform repository](https://github.com/hashicorp/terraform/issues/new?labels=bug%2C+new&template=bug_report.md) with all the template details and the teams will triage further. Thanks.

**Comment by dinvlad** [comment] 2020-08-24 19:58
@andresvia alas, you have to manually edit the state file to exclude the deprecated attributes for now, I think. That worked for us at least.

**Comment by dinvlad** [comment] 2020-08-24 19:59
More specifically, as described here: https://github.com/hashicorp/terraform/issues/25752#issuecomment-672217777
