### ISSUE TITLE
aws_elasticache_replication_group should support empty auth_token

### ISSUE THREAD

**Issue by rverma-nikiai** [terraform-providers/terraform-provider-aws#8789] opened 2019-05-28 09:49 UTC
Empty auth_token represents no auth. This is broken in the latest release.
Tested with terraform `0.11.13`

**Comment by bflad** [comment] 2019-05-28 15:40
Hi @rverma-nikiai 👋 Can you please provide all the details of the [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md) issue template? These details are required to properly troubleshoot issues or implement features. In this case, having the relevant Terraform versions/configuration, expected behavior, and actual behavior will help the maintainers and community appropriately triage. Thanks.

**Comment by bflad** [comment] 2019-07-24 02:45
It's been a long time since we heard from you here so we're going to close this out. If you're still having this problem, please feel free to open a new issue and complete all of the information requested in the Bug Report or Feature Request template. Thanks.

**Closed by bflad** 2019-07-24 02:45 UTC
Labels: needs-triage, service/elasticache, waiting-response
