### ISSUE TITLE
resource_aws_codedeploy_deployment_group.go - Ec2TagSet option not available

### ISSUE THREAD

**Issue by xriu** [terraform-providers/terraform-provider-aws#2930] opened 2018-01-10 20:12 UTC
### Terraform Version
Terraform v0.11.1 - provider.aws v1.6.0

### Affected Resource(s)
- aws_codedeploy_deployment_group

### Terraform Configuration Files
```
resource "aws_codedeploy_deployment_group" "example" {
  app_name              = "${aws_codedeploy_app.example.name}"
  deployment_group_name = "example-group"
  service_role_arn      = "${aws_iam_role.example.arn}"

"ec2TagSet": { 
         "ec2TagSetList": [ 
            [ 
               { 
                  "Key": "KEY_AND_VALUE",
                  "Type": "Name",
                  "Value": "AppVersion-ABC"
               }
            ],
            [ 
               { 
                  "Key": "KEY_AND_VALUE",
                  "Type": "Region",
                  "Value": "North"
               }
            ],
         ]
      },
}
```

### Expected Behavior
ec2_tag_set option to enable multiple tag support

### Actual Behavior
ec2_tag_set option not defined in **resource_aws_codedeploy_deployment_group.go** but defined in codedeploy API ( https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_codedeploy_deployment_group.go ) 

### References
Official documentation
https://docs.aws.amazon.com/codedeploy/latest/userguide/instances-tagging.html?icmpid=docs_acd_console

CodeDeploy API
https://github.com/terraform-providers/terraform-provider-aws/blob/master/vendor/github.com/aws/aws-sdk-go/service/codedeploy/api.go

Resource CodeDeploy
https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_codedeploy_deployment_group.go

**Comment by Haegin** [comment] 2018-04-10 19:38
Looks like this is a dupe of #2073.

**Comment by bflad** [comment] 2018-04-25 22:32
The `ec2_tag_set` argument has been added to the `aws_codedeploy_deployment_group` attribute via #4324 and will release with v1.17.0 of the AWS provider, likely in a week.

**Closed by bflad** 2018-04-25 22:32 UTC
Labels: enhancement, service/codedeploy
