### ISSUE TITLE
aws_elastic_beanstalk_environment data source

### ISSUE THREAD

**Issue by xlz-jgoutin** [terraform-providers/terraform-provider-aws#11533] opened 2020-01-09 09:36 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, `aws_elastic_beanstalk_environment` exists only as a Terraform resource.

The suggestion is to have also a data source with the same attributes as the resource. This can be used to retrieve attributes from an Elastic Beanstalk environment (endpoint URL, load balancers, instances, SQS queues, ...) to easily use them with other Terraform resources.

### New or Affected Resource(s)

* aws_elastic_beanstalk_environment (data source)

### Potential Terraform Configuration

```hcl
data "aws_elastic_beanstalk_environment" "env" {
  # Get environment by name or ID
  name = "env-name"
}

output "env_endpoint_url" {
  # Use attribute
  value = data.aws_elastic_beanstalk_environment.env.endpoint_url
}
```

### References

* https://www.terraform.io/docs/providers/aws/r/elastic_beanstalk_environment.html

**Comment by bflad** [comment] 2020-01-09 15:02
Hi @xlz-jgoutin 👋 Thank you for submitting this. This appears to be a duplicate of #2051, so to consolidate discussions and efforts I'm going to close this issue in preference of the earlier one. Please upvote and follow that issue for further updates. 👍

**Closed by bflad** 2020-01-09 15:02 UTC
Labels: enhancement, needs-triage, service/elasticbeanstalk
