### ISSUE TITLE
Add multicast support  to EC2 Transit Gateway

### ISSUE THREAD

**Issue by bardielle** [terraform-providers/terraform-provider-aws#13101] opened 2020-04-30 07:09 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
We should add an argument 'multicast_support' to the EC2 transit gateway. This allows the ability to create transit gateway multicast domain on AWS 

### New or Affected Resource(s)

*aws_transit_gateway - https://www.terraform.io/docs/providers/aws/r/ec2_transit_gateway.html

### Potential Terraform Configuration

resource "aws_ec2_transit_gateway" "tg" {
  description = "example"
  multicast_support = "enable"
}

**Comment by DrFaust92** [comment] 2020-04-30 15:08
duplicate of #11120 and addressed by #11474

**Closed** 2020-05-03 09:17 UTC
Labels: enhancement, needs-triage, service/ec2
