### ISSUE TITLE
problem with 2.63 release affecting terraform-aws-modules/terraform-aws-autoscaling

### ISSUE THREAD

**Issue by mescbs** [terraform-providers/terraform-provider-aws#13514] opened 2020-05-27 15:10 UTC
We are noticing a problem introduced with 2.63 provider version effecting the autoscaling tags of commonly used registry module https://github.com/terraform-aws-modules/terraform-aws-autoscaling.

There appears to be some change that alphabetizes the list of tags of the list of tags. The result is that the modules will never apply cleanly due to the order of the list of maps keeps changing.

This might be more of a problem with the module and should be addressed there. But I wanted to let someone know. For now I have my aws provider pinned to 2.62.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by bflad** [comment] 2020-05-27 15:58
Hi @mescbs 👋 Thank you for reporting this and sorry you ran into trouble here. This appears to be a duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/13469 so to consolidate discussions and efforts, I'm going to close this issue in preference of the earlier one. Please follow/upvote that issue for updates.

**Closed by bflad** 2020-05-27 15:58 UTC
Labels: needs-triage
